### ISSUE TITLE
多态的特点

### ISSUE THREAD

**Issue by dengyongqiang** [Snailclimb/JavaGuide#1011]
在Java 面向对象，面向对象三大特征，关于多态中提到：对象类型不可变，引用类型可变。此处应该为对象类型可变，引用类型不可变。引用类型指的是接口，对象类型指的是接口的实现，一个接口可以有不同的实现

**Comment by Snailclimb** [comment]
> 在Java 面向对象，面向对象三大特征，关于多态中提到：对象类型不可变，引用类型可变。此处应该为对象类型可变，引用类型不可变。引用类型指的是接口，对象类型指的是接口的实现，一个接口可以有不同的实现

理解的没问题。👍 但是，这里的引用类型并非值得是接口，对象类型也不是接口的实现。引用变量指向的是举例的实例对象。

**Comment by Snailclimb** [comment]
> 对象类型不可变，引用类型可变

原文中我已经把比较迷惑性的表达删除了，保留了多态  4 个比较重要的特点。

![image](https://user-images.githubusercontent.com/29880145/100823228-cc266200-348e-11eb-9bf9-1ebc4e6daa6d.png)
