### ISSUE TITLE
哥哥，ArrayList扩容机制文章链接失效了

### ISSUE THREAD

**Issue by mikeygithub** [Snailclimb/JavaGuide#1019]
https://snailclimb.gitee.io/javaguide/#/docs/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98

**Comment by Snailclimb** [comment]
木有呀 哥们


| |
寇爽
|
|
koushuangbwcx@163.com
|
签名由网易邮箱大师定制


在2020年12月7日 21:51，麦奇<notifications@github.com> 写道：

https://snailclimb.gitee.io/javaguide/#/docs/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98

**Comment by mikeygithub** [comment]
好吧是因为我这边github的原因，抱歉～＼（≧▽≦）／～
