### ISSUE TITLE
虚拟存储器和虚拟内存应该是同一个概念，只是英语术语Virtual Memory的不同翻译

### ISSUE THREAD

**Issue by Lamzigit** [Snailclimb/JavaGuide#1022]
操作系统里虚拟存储器和虚拟内存应该是同一个概念，只是英语翻译的不同（Virtual Memory），因为memory可以翻译为存储器或内存。笔记里把它们区分为两个概念有点误导

**Comment by Snailclimb** [comment]
> 只是英语翻译的不同（Virtual Memory）

已修正！👍
