### ISSUE TITLE
勘误：集合介绍的章节RandomAccess单词拼写错误

### ISSUE THREAD

**Issue by lixian13149999** [Snailclimb/JavaGuide#1032]
[docs/java/collection/Java集合框架常见面试题.md](https://github.com/Snailclimb/JavaGuide/blob/18a4deac91fc9a80488536b120660fc4cbb7d094/docs/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.md) L141
[docs/essential-content-for-interview/PreparingForInterview/美团面试常见问题总结.md](https://github.com/Snailclimb/JavaGuide/blob/43d6b2e9a0e00c36e368671c29c88fa4d3931d04/docs/essential-content-for-interview/PreparingForInterview/%E7%BE%8E%E5%9B%A2%E9%9D%A2%E8%AF%95%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%80%BB%E7%BB%93.md) L496
原词应该为 RandomAccess 写成了 RamdomAccess

**Comment by Snailclimb** [comment]
> RandomAccess



> [docs/java/collection/Java集合框架常见面试题.md](https://github.com/Snailclimb/JavaGuide/blob/18a4deac91fc9a80488536b120660fc4cbb7d094/docs/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.md) L141
> [docs/essential-content-for-interview/PreparingForInterview/美团面试常见问题总结.md](https://github.com/Snailclimb/JavaGuide/blob/43d6b2e9a0e00c36e368671c29c88fa4d3931d04/docs/essential-content-for-interview/PreparingForInterview/%E7%BE%8E%E5%9B%A2%E9%9D%A2%E8%AF%95%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%80%BB%E7%BB%93.md) L496
> 原词应该为 RandomAccess 写成了 RamdomAccess

已修复~感谢指出~👍
