### ISSUE TITLE
全自动软件开发平台

### ISSUE THREAD

**Issue by webproblem** [Snailclimb/JavaGuide#1039]
全自动软件开发平台，实现java后端可视化开发，测试，部署 
欢迎试用：
https://feisuanyz.com/marketing/?sc=C0001&cc=5fc6395c6ae31b0008742b83

**Comment by Snailclimb** [comment]
> 全自动软件开发平台，实现java后端可视化开发，测试，部署
> 欢迎试用：
> https://feisuanyz.com/marketing/?sc=C0001&cc=5fc6395c6ae31b0008742b83
 
首页有广告位 1.5k一个月，童叟无欺~来一个不？

**Comment by Snailclimb** [comment]
åå
