### ISSUE TITLE
我能把你这些文章转载到我的微信公众号么

### ISSUE THREAD

**Issue by lyunclesam** [Snailclimb/JavaGuide#104]
我能把你这些文章转载到我的微信公众号和[我的博客https://www.ydstudio.net/](https://www.ydstudio.net/)上么？虽然我暂时还没有申请公众号

**Comment by Snailclimb** [comment]
你也可以直接从我的公众号转载啊 ID：Java_Guide

**Comment by lyunclesam** [comment]
> 你也可以直接从我的公众号转载啊 ID：Java_Guide
好的，谢谢，我会写上文章来源的
