### ISSUE TITLE
Spring事务总结小问题

### ISSUE THREAD

**Issue by CoderiGenius** [Snailclimb/JavaGuide#1040]
Hi Snailclimb,
![image.png](https://i.loli.net/2020/12/26/J4lPaFZgWk3vXdG.png)
https://github.com/Snailclimb/JavaGuide/blob/master/docs/system-design/framework/spring/Spring%E4%BA%8B%E5%8A%A1%E6%80%BB%E7%BB%93.md 
这里您的意思是不是应该是bMethod2()回滚不会影响bMethod()和aMethod()？

**Comment by Snailclimb** [comment]
> Hi Snailclimb,
> ![image.png](https://camo.githubusercontent.com/700704c75e1dba21bc2ad845b0179eafdef40db88f01a0d06b08e6b08e9c27cd/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31322f32362f4a346c5061465a67576b33765864472e706e67)
> https://github.com/Snailclimb/JavaGuide/blob/master/docs/system-design/framework/spring/Spring%E4%BA%8B%E5%8A%A1%E6%80%BB%E7%BB%93.md
> 这里您的意思是不是应该是bMethod2()回滚不会影响bMethod()和aMethod()？

是的。这里笔误了👍
