### ISSUE TITLE
JavaGuide/docs/java/basis/代理模式详解.md

### ISSUE THREAD

**Issue by hong6666** [Snailclimb/JavaGuide#1042]
[ref:代理模式详解](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/basis/%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F%E8%AF%A6%E8%A7%A3.md)
举个例子：**你的找了一小红来帮你问话**，小红就看作是代理我的代理对象，代理的行为（方法）是问话。

加黑的地方有误

**Comment by Snailclimb** [comment]
> [ref:代理模式详解](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/basis/%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F%E8%AF%A6%E8%A7%A3.md)
> 举个例子：**你的找了一小红来帮你问话**，小红就看作是代理我的代理对象，代理的行为（方法）是问话。
> 
> 加黑的地方有误

![image](https://user-images.githubusercontent.com/29880145/103265122-ccf7d880-49e7-11eb-8421-1c0d5e042613.png)
zh
