### ISSUE TITLE
最长公共前缀解法有疑问

### ISSUE THREAD

**Issue by simplelist** [Snailclimb/JavaGuide#1044]
按照 KMP算法中的对于[前缀的定义](http://www.ruanyifeng.com/blog/2013/05/Knuth%E2%80%93Morris%E2%80%93Pratt_algorithm.html):

>   "前缀"指除了最后一个字符以外，一个字符串的全部头部组合；"后缀"指除了第一个字符以外，一个字符串的全部尾部组合。

这到[算法题的解法](https://snailclimb.gitee.io/javaguide/#/docs/dataStructures-algorithms/%E5%87%A0%E9%81%93%E5%B8%B8%E8%A7%81%E7%9A%84%E5%AD%90%E7%AC%A6%E4%B8%B2%E7%AE%97%E6%B3%95%E9%A2%98?id=_3-%e6%9c%80%e9%95%bf%e5%85%ac%e5%85%b1%e5%89%8d%e7%bc%80)中,
未考虑输入完全相同字符串的情况, 
即: 输入完全相同字符串,得到的答案是这个字符串, 问题要求的是前缀,因此这里略微有点点疑惑.

非常感谢这份学习指导资料.

**Comment by Snailclimb** [comment]
> 按照 KMP算法中的对于[前缀的定义](http://www.ruanyifeng.com/blog/2013/05/Knuth%E2%80%93Morris%E2%80%93Pratt_algorithm.html):
> 
> > "前缀"指除了最后一个字符以外，一个字符串的全部头部组合；"后缀"指除了第一个字符以外，一个字符串的全部尾部组合。
> 
> 这到[算法题的解法](https://snailclimb.gitee.io/javaguide/#/docs/dataStructures-algorithms/%E5%87%A0%E9%81%93%E5%B8%B8%E8%A7%81%E7%9A%84%E5%AD%90%E7%AC%A6%E4%B8%B2%E7%AE%97%E6%B3%95%E9%A2%98?id=_3-%e6%9c%80%e9%95%bf%e5%85%ac%e5%85%b1%e5%89%8d%e7%bc%80)中,
> 未考虑输入完全相同字符串的情况,
> 即: 输入完全相同字符串,得到的答案是这个字符串, 问题要求的是前缀,因此这里略微有点点疑惑.
> 
> 非常感谢这份学习指导资料.

这里的最大公共前缀我理解的是：多个相同的字符串的最长公共前缀就是它们自己。
