### ISSUE TITLE
设计模式我也在总结可以一起维护吗？

### ISSUE THREAD

**Issue by zhanglijun1217** [Snailclimb/JavaGuide#105]
现在写了策略和观察者模式:
https://zhanglijun1217.github.io/blog/2018/12/24/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E2%80%94%E2%80%94%E8%A7%82%E5%AF%9F%E8%80%85%E6%A8%A1%E5%BC%8F-md/

https://zhanglijun1217.github.io/blog/2018/08/02/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E2%80%94%E2%80%94%E7%AD%96%E7%95%A5%E6%A8%A1%E5%BC%8F/

**Comment by Snailclimb** [comment]
嗯嗯 没问题  老哥可以提PR啊

**Comment by zhanglijun1217** [comment]
> 嗯嗯 没问题 老哥可以提PR啊

ojbk，刚才提了一个观察者模式的PR~
