### ISSUE TITLE
这个图的继承关系貌似有点问题

### ISSUE THREAD

**Issue by ZLBer** [Snailclimb/JavaGuide#1053]
`Deque`是直接继承自`Queue`的，也就说`Queue`可以由`ArrayDeque`实现，`Queue q= new ArrayDeque()`，在图上好像看不出这层关系。    
还有就是 是`Deque` 而不是`Dequeue` ，拼写错误。   
   
![image](https://user-images.githubusercontent.com/20033804/103995052-dac11100-51d2-11eb-9ec7-d12b00826e62.png)

**Comment by Snailclimb** [comment]
这张图片描述的更准确点。
![image](https://user-images.githubusercontent.com/29880145/104090802-0bc54280-52b4-11eb-8a9f-3168c85983a5.png)
