### ISSUE TITLE
枚举 讲解的好像有问题

### ISSUE THREAD

**Issue by rymuscle** [Snailclimb/JavaGuide#1054]
https://snailclimb.gitee.io/javaguide/#/docs/java/basis/%E7%94%A8%E5%A5%BDJava%E4%B8%AD%E7%9A%84%E6%9E%9A%E4%B8%BE%E7%9C%9F%E7%9A%84%E6%B2%A1%E6%9C%89%E9%82%A3%E4%B9%88%E7%AE%80%E5%8D%95?id=_3%e4%bd%bf%e7%94%a8-%e6%af%94%e8%be%83%e6%9e%9a%e4%b8%be%e7%b1%bb%e5%9e%8b

”两个不同枚举类型进行比较，使用equal方法比较结果确定为true“  这句表述不对吧  经过测试，是false的

**Comment by Snailclimb** [comment]
![image](https://user-images.githubusercontent.com/29880145/104320398-3d8d1200-551d-11eb-853e-49911af01f34.png)
已修复 感谢吃出！
