### ISSUE TITLE
JavaGuide面试突击版v4.0 中 2.1.10 String，StringBuffer，StringBuilder 中的小错误

### ISSUE THREAD

**Issue by Ma-Yuyao** [Snailclimb/JavaGuide#1055]
在Java 9之后，AbstractStringBuilder 同样使用 byte[] 数组存储，如图。

![image](https://user-images.githubusercontent.com/69780852/104318763-d4a49a80-551a-11eb-8895-322fc2443c32.png)

**Comment by Snailclimb** [comment]
> AbstractStringBuilder

感谢指出。已经完善。
