### ISSUE TITLE
突击版4.0找到的问题

### ISSUE THREAD

**Issue by xlkit456852** [Snailclimb/JavaGuide#1056]
2.2.4：链接失效
2.2.8.1、2.2.8.2：图片好像缺失了
2.2.11：JDK1.8 的 ConcurrentHashMap的图解缺失了

**Comment by Snailclimb** [comment]
> 链接失效

在线版已经修复了，感谢老哥👍https://snailclimb.gitee.io/javaguide-interview/#/
