### ISSUE TITLE
非聚集索引不一定有回表操作的举例出错

### ISSUE THREAD

**Issue by xlndql** [Snailclimb/JavaGuide#1060]
原文：“
非聚集索引不一定回表查询。

试想一种情况，用户准备使用SQL查询用户名，而用户名字段正好建立了索引。

 SELECT name FROM table WHERE username='guang19';
”
这里的name和username应该是同一字段吧，都是name或者username

**Comment by Snailclimb** [comment]
> 原文：“
> 非聚集索引不一定回表查询。
> 
> 试想一种情况，用户准备使用SQL查询用户名，而用户名字段正好建立了索引。
> 
> SELECT name FROM table WHERE username='guang19';
> ”
> 这里的name和username应该是同一字段吧，都是name或者username

感谢指出，已经修改。
