### ISSUE TITLE
AQS 一章 CountDownLatch 的疑问

### ISSUE THREAD

**Issue by sleepingraven** [Snailclimb/JavaGuide#1061]
第4节说「当调用await方法的时候，如果state不为0，就代表仍然有线程没有调用countDown方法，那么就把已经调用过countDown的线程都放入阻塞队列Park,并自旋CAS判断state == 0，直至最后一个线程调用了countDown，使得state == 0，于是阻塞的线程便判断成功，全部往下执行。」。我觉得是当调用 await 方法时，尝试获取共享锁（判断 state 是否是 0），若获取失败，会加入阻塞队列。最后一个 countDown 后会释放锁，同时唤醒 Park 队列中阻塞的第一个线程，而一个线程被唤醒后，会继续唤醒下一个阻塞的线程。

另外，不一定一个线程 countDown 一次，一个线程是可以 countDown 多次的。

**Comment by Snailclimb** [comment]
![image](https://user-images.githubusercontent.com/29880145/104910842-e7104f80-59c4-11eb-80e3-88ace2bde776.png)
感谢指出，已经修改。
