### ISSUE TITLE
Spring 章节 5.2

### ISSUE THREAD

**Issue by songor** [Snailclimb/JavaGuide#1062]
原文：
对这个对象的非静态成员变量的写操作会存在线程安全问题
疑问：
这里为什么要特指非静态成员变量？对静态成员变量的写操作同样存在线程安全问题

**Comment by Snailclimb** [comment]
> 原文：
> 对这个对象的非静态成员变量的写操作会存在线程安全问题
> 疑问：
> 这里为什么要特指非静态成员变量？对静态成员变量的写操作同样存在线程安全问题

感谢指出！已经修改。
