### ISSUE TITLE
为什么把中华石杉的笔记删了，感觉那部分写的很好，可以补充回来吗？

### ISSUE THREAD

**Issue by TheMrCoder** [Snailclimb/JavaGuide#1067]
为什么把中华石杉的笔记删了，感觉那部分写的很好，可以补充回来吗？

**Comment by Snailclimb** [comment]
> 为什么把中华石杉的笔记删了，感觉那部分写的很好，可以补充回来吗？

貌似之前就没有中华石杉的笔，这个仓库的99%的文章都是我的原创。
