### ISSUE TITLE
JavaGuide 网络 4.1.2 中文字重复

### ISSUE THREAD

**Issue by gofromzero** [Snailclimb/JavaGuide#1069]
### 停止等待ARQ协议
2) 出现差错情况（超时重传）:
停止等待协议中超时重传是指只要超过一段时间仍然没有收到确认，就重传前面发送过的分组（认为刚才发送过的分组丢失了）。因此每发送完一个分组需要设置一个超时计时器，其重传时间应比数据在分组传输的平均往返时间更长一些。这种自动重传方式常称为 自动重传请求 ARQ 。另外在停止等待协议中若收到重复分组，就丢弃该分组，但同时还要发送确认。连续 ARQ 协议 可提高信道利用率。发送维持一个发送窗口，凡位于发送窗口内的分组可连续发送出去，而不需要等待对方确认。接收方一般采用累积确认，对按序到达的最后一个分组发送确认，表明到这个分组位置的所有分组都已经正确收到了。

从 连续ARQ协议 到最后 部分文字
该部分和下方连续ARQ协议介绍重复，是否有问题

**Comment by Snailclimb** [comment]
> ## 网络
> ### 停止等待ARQ协议
> 1. 出现差错情况（超时重传）:
>    停止等待协议中超时重传是指只要超过一段时间仍然没有收到确认，就重传前面发送过的分组（认为刚才发送过的分组丢失了）。因此每发送完一个分组需要设置一个超时计时器，其重传时间应比数据在分组传输的平均往返时间更长一些。这种自动重传方式常称为 自动重传请求 ARQ 。另外在停止等待协议中若收到重复分组，就丢弃该分组，但同时还要发送确认。连续 ARQ 协议 可提高信道利用率。发送维持一个发送窗口，凡位于发送窗口内的分组可连续发送出去，而不需要等待对方确认。接收方一般采用累积确认，对按序到达的最后一个分组发送确认，表明到这个分组位置的所有分组都已经正确收到了。
> 
> 从 连续ARQ协议 到最后 部分文字
> 该部分和下方连续ARQ协议介绍重复，是否有问题

貌似不太一样。
