### ISSUE TITLE
JavaGuide中面试/工作必备！3种常用的缓存读写策略中的错误

### ISSUE THREAD

**Issue by JasonLe** [Snailclimb/JavaGuide#1073]
在面试/工作必备！3种常用的缓存读写策略中，Read/Write Through Pattern（读写穿透）的第一张图片有错误，应该是cache 中存在，则先更新 cache，然后 cache 服务自己更新 DB（同步更新 cache 和 DB），而图片第2步文字是cache 中存在，则先更新 DB

**Comment by Snailclimb** [comment]
> 在面试/工作必备！3种常用的缓存读写策略中，Read/Write Through Pattern（读写穿透）的第一张图片有错误，应该是cache 中存在，则先更新 cache，然后 cache 服务自己更新 DB（同步更新 cache 和 DB），而图片第2步文字是cache 中存在，则先更新 DB

是的！感谢指出！👍
