### ISSUE TITLE
讲写优雅代码那段，是个啥鸡儿玩意啊

### ISSUE THREAD

**Issue by HackerCJC** [Snailclimb/JavaGuide#1085]

**Comment by Snailclimb** [comment]
> _No description provided._

麻烦你好好学习，学好语文再说话！fuck! you

**Comment by HackerCJC** [comment]
这种垃圾还好意思出来丢人现眼




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snailclimb/JavaGuide"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月13日(星期六) 上午9:25
收件人:&nbsp;"Snailclimb/JavaGuide"<JavaGuide@noreply.github.com&gt;;
抄送:&nbsp;"代码如风"<914665619@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Snailclimb/JavaGuide] 讲写优雅代码那段，是个啥鸡儿玩意啊 (#1085)





  
No description provided.
  
麻烦你好好学习，学好语文再说话！fuck! you

**Comment by HackerCJC** [comment]
舔个脸写些个没水平的东西，往上凑字数，还怕别人鄙视，心理还这么脆弱，真够弱鸡的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snailclimb/JavaGuide"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月13日(星期六) 上午9:25
收件人:&nbsp;"Snailclimb/JavaGuide"<JavaGuide@noreply.github.com&gt;;
抄送:&nbsp;"代码如风"<914665619@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Snailclimb/JavaGuide] 讲写优雅代码那段，是个啥鸡儿玩意啊 (#1085)





  
No description provided.
  
麻烦你好好学习，学好语文再说话！fuck! you

**Comment by Snailclimb** [comment]
> 舔个脸写些个没水平的东西，往上凑字数，还怕别人鄙视，心理还这么脆弱，真够弱鸡的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Snailclimb/JavaGuide" <notifications@github.com&gt;; 发送时间:&nbsp;2021年2月13日(星期六) 上午9:25 收件人:&nbsp;"Snailclimb/JavaGuide"<JavaGuide@noreply.github.com&gt;; 抄送:&nbsp;"代码如风"<914665619@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Snailclimb/JavaGuide] 讲写优雅代码那段，是个啥鸡儿玩意啊 (#1085) No description provided. 麻烦你好好学习，学好语文再说话！fuck! you — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

gdx！哈哈哈哈！加油，努力学习。
