### ISSUE TITLE
关于“ThreadLocal关键字解析”这一节的问题

### ISSUE THREAD

**Issue by 10ca1h0st** [Snailclimb/JavaGuide#1086]
[这篇文章，在回答第一个问题“GC之后key是否为null”时，新建了一个ThreadLocalDemo类，当模拟不使用GC时，输出有两行，为：](https://snailclimb.gitee.io/javaguide/#/docs/java/multi-thread/%E4%B8%87%E5%AD%97%E8%AF%A6%E8%A7%A3ThreadLocal%E5%85%B3%E9%94%AE%E5%AD%97?id=gc-%e4%b9%8b%e5%90%8ekey%e6%98%af%e5%90%a6%e4%b8%banull%ef%bc%9f)
```
弱引用key:java.lang.ThreadLocal@433619b6,值:abc
弱引用key:java.lang.ThreadLocal@418a15e3,值:java.lang.ref.SoftReference@bf97a12
```
**请问为什么会输出两行，不是应该只有一个Entry，就是值为abc的Entry吗？
请问第二行代表了什么？为什么线程的ThreadLocalMap中会有一个Entry，键为一个ThreadLocal，值为一个软引用。**

**Comment by StackInk** [comment]
你Debug看一下就可以了，有一些线程初始化的值是通过ThreadLocal存的。

**Comment by suncqujsj** [comment]
谁能详细讲下吗？

**Comment by suncqujsj** [comment]
您的邮件已经收到，我会在上网第一时间看到您的来信，谢谢您的关心。
