### ISSUE TITLE
关于 redis rdb 和 aof 的问题

### ISSUE THREAD

**Issue by xiaoheng1** [Snailclimb/JavaGuide#1088]
请教下，如果在 redis 刚启动的时候，没有开启 aof，只使用 rdb 持久化数据。然后在中途的时候，开发 aof，这时候如果 redis 宕机，那么使用 aof 恢复的化，我的理解是数据应该是不全的吧？

**Comment by Snailclimb** [comment]
> 请教下，如果在 redis 刚启动的时候，没有开启 aof，只使用 rdb 持久化数据。然后在中途的时候，开发 aof，这时候如果 redis 宕机，那么使用 aof 恢复的化，我的理解是数据应该是不全的吧？

一般默认都是重启之后配置才生效。
