### ISSUE TITLE
Java基础知识中的重载概念存在歧义

### ISSUE THREAD

**Issue by Feiyst** [Snailclimb/JavaGuide#1090]
**_2.1.8. 重载和重写的区别_** 中的重载概念存在歧义
![image](https://user-images.githubusercontent.com/28942130/108628345-5f22d700-7495-11eb-9dc2-671980aa8e6f.png)

阿里巴巴《码出高效》一书中，对重载有一段这样的描述：
> 父类的公有实例方法与子类的公有实例方法可以存在重载关系。不管继承关系如何复杂，重载在编译时可以根据规则知道调用哪种目标方法。

我在本地写了demo，发现编译能通过且能正常执行，以下为示例代码：
OverloadingParent.java
```java
/**
 * 父类
 */
public class OverloadingParent {

    /**
     * 获取个人信息
     *
     * @param name   姓名
     * @param age    年龄
     * @param weight 体重
     * @return 个人信息
     */
    public String getPersonInfo(String name, Integer age, Double weight) {
        return  "Parent{ Name = " + name + ", age = " + age + ", weight = " + weight + "}";
    }
}
```

OverloadingSon.java
```java
/**
 * 子类
 */
public class OverloadingSon extends OverloadingParent {

    /**
     * 获取个人信息
     *
     * @param name 姓名
     * @param age  年龄
     * @return 个人信息
     */
    public String getPersonInfo(String name, Integer age) {
        return "Son{ Name = " + name + ", age = " + age + "}";
    }

    /**
     * 获取个人信息
     *
     * @param name   姓名
     * @param age    年龄
     * @param weight 体重
     * @param height 身高
     * @return 个人信息
     */
    public String getPersonInfo(String name, Integer age, Double weight, Integer height) {
        return "Son{ Name = " + name + ", age = " + age + ", weight = " + weight + ", height = " + height + "}";
    }

    public static void main(String[] args) {
        OverloadingSon overloadingSon = new OverloadingSon();
        System.out.println(overloadingSon.getPersonInfo("rose.li", 24));
        System.out.println(overloadingSon.getPersonInfo("jack.lin", 25, 56.5d));
        System.out.println(overloadingSon.getPersonInfo("polo.wei", 26, 50.1d, 175));
    }
}
```

运行结果如下：
![image](https://user-images.githubusercontent.com/28942130/108628549-9cd42f80-7496-11eb-99fb-0e5570ff44ce.png)

**Comment by yusiwen** [comment]
Overloading一般指同一类中的方法。因为子类`OverloadingSon`继承父类，所以这个父类版本的`getPersonInfo(String name, Integer age, Double weight)`也可以理解是在子类里的，故而说“在同一类”里也没太大问题。这里强调同一类，估计是不想和Overriding混淆吧。

**Comment by Snailclimb** [comment]
> Overloading一般指同一类中的方法。因为子类`OverloadingSon`继承父类，所以这个父类版本的`getPersonInfo(String name, Integer age, Double weight)`也可以理解是在子类里的，故而说“在同一类”里也没太大问题。这里强调同一类，估计是不想和Overriding混淆吧。
> 
> 请参考官方文档里的描述：
> 
> ![image](https://user-images.githubusercontent.com/3704932/108649286-00db1000-74f8-11eb-958f-1cebdfae9be3.png)
> 
> [8.4.9 Overloading](https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.4.9)
> 
> 处于严谨的考虑，建议把“同一类”加个注释，类似于官方的括号里的说明

感谢！👍已加：
![image](https://user-images.githubusercontent.com/29880145/108712289-863ede80-7551-11eb-99b0-bc1cd2da1466.png)
