### ISSUE TITLE
JDK 动态代理只能只能代理实现了接口的类

### ISSUE THREAD

**Issue by zhenyiLiang** [Snailclimb/JavaGuide#1091]
这么说好像不太对，JDK 动态代理可以代理实现接口的类，也可以直接代理接口，接口不一定要有实现类

**Comment by Snailclimb** [comment]
> 这么说好像不太对，JDK 动态代理可以代理实现接口的类，也可以直接代理接口，接口不一定要有实现类

确实可以的！学到了！感谢。
