### ISSUE TITLE
关于“Java 内存区域详解”中的元空间

### ISSUE THREAD

**Issue by XShiMing** [Snailclimb/JavaGuide#1096]
在我的其他搜索结果中，元空间虽然和直接内存都属于本地内存，但是不属于直接内存。可否解答一下哪个是正确答案
Java内存区域详解中：![image](https://user-images.githubusercontent.com/49108467/108968687-0bde9d80-76bc-11eb-8489-bbf19ea596a3.png)
其他文章中：
![image](https://user-images.githubusercontent.com/49108467/108968850-447e7700-76bc-11eb-8a1e-94a50e660311.png)
![image](https://user-images.githubusercontent.com/49108467/108968898-56601a00-76bc-11eb-81c3-13fbfaba2d25.png)

**Comment by Snailclimb** [comment]
> 元空间

我理解的是本地内存应该是包括了直接内存和元空间所使用的堆外内存。

**Comment by XShiMing** [comment]
> > 元空间
> 
> 我理解的是本地内存应该是包括了直接内存和元空间所使用的堆外内存。

我也是这么理解的，但是在您的[Java 内存区域详解](https://snailclimb.gitee.io/javaguide/#/docs/java/jvm/Java%E5%86%85%E5%AD%98%E5%8C%BA%E5%9F%9F?id=java-%e5%86%85%e5%ad%98%e5%8c%ba%e5%9f%9f%e8%af%a6%e8%a7%a3)文中写的是**元空间使用的是直接内存**。
例如概述图
![image](https://user-images.githubusercontent.com/49108467/109119428-a2c05e00-777f-11eb-9fb5-587339e08ebd.png)
和[为什么要将永久代 (PermGen) 替换为元空间 (MetaSpace) 呢?](https://snailclimb.gitee.io/javaguide/#/docs/java/jvm/Java%E5%86%85%E5%AD%98%E5%8C%BA%E5%9F%9F?id=_253-%e4%b8%ba%e4%bb%80%e4%b9%88%e8%a6%81%e5%b0%86%e6%b0%b8%e4%b9%85%e4%bb%a3-permgen-%e6%9b%bf%e6%8d%a2%e4%b8%ba%e5%85%83%e7%a9%ba%e9%97%b4-metaspace-%e5%91%a2)
![image](https://user-images.githubusercontent.com/49108467/109119491-bbc90f00-777f-11eb-9ecc-c3005a8052de.png)

**Comment by Snailclimb** [comment]
> > > 元空间
> > 
> > 
> > 我理解的是本地内存应该是包括了直接内存和元空间所使用的堆外内存。
> 
> 我也是这么理解的，但是在您的[Java 内存区域详解](https://snailclimb.gitee.io/javaguide/#/docs/java/jvm/Java%E5%86%85%E5%AD%98%E5%8C%BA%E5%9F%9F?id=java-%e5%86%85%e5%ad%98%e5%8c%ba%e5%9f%9f%e8%af%a6%e8%a7%a3)文中写的是**元空间使用的是直接内存**。
> 例如概述图
> ![image](https://user-images.githubusercontent.com/49108467/109119428-a2c05e00-777f-11eb-9fb5-587339e08ebd.png)
> 和[为什么要将永久代 (PermGen) 替换为元空间 (MetaSpace) 呢?](https://snailclimb.gitee.io/javaguide/#/docs/java/jvm/Java%E5%86%85%E5%AD%98%E5%8C%BA%E5%9F%9F?id=_253-%e4%b8%ba%e4%bb%80%e4%b9%88%e8%a6%81%e5%b0%86%e6%b0%b8%e4%b9%85%e4%bb%a3-permgen-%e6%9b%bf%e6%8d%a2%e4%b8%ba%e5%85%83%e7%a9%ba%e9%97%b4-metaspace-%e5%91%a2)
> ![image](https://user-images.githubusercontent.com/49108467/109119491-bbc90f00-777f-11eb-9ecc-c3005a8052de.png)

👍老哥太有心了
![](https://oscimg.oschina.net/oscnet/up-cd8ac705f6f004c01e0a1312f1599430ba5.png)

**Comment by XShiMing** [comment]
想进大厂，只有用心学才能弥补以前耍过的那么多年了
