### ISSUE TITLE
能不能补充下spring cloud的面试题

### ISSUE THREAD

**Issue by larryluk** [Snailclimb/JavaGuide#1099]
面试准备的时候发现少了这玩意

**Comment by Snailclimb** [comment]
> 面试准备的时候发现少了这玩意

已经设置为待认领的状态，期待有小伙伴可以认领。

**Comment by Snailclimb** [comment]
> 面试准备的时候发现少了这玩意

可以看看这个：https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzU3MDAzNDg1MA==&action=getalbum&album_id=2042874937312346114&scene=126#wechat_redirect

![image](https://user-images.githubusercontent.com/29880145/148156037-70436f99-18d6-49a4-ba92-9c896d96f7fa.png)
