### ISSUE TITLE
有关redis常见数据结构及使用场景分析中添加bitmap有关内容

### ISSUE THREAD

**Issue by codingLemonzz** [Snailclimb/JavaGuide#1107]
你好，guide哥，看了你的java面经中关于redis的部分之后，感觉在第6小节介绍redis常见数据结构及应用场景中可以添加bitmap的有关介绍及应用场景（比如用户签到，统计活跃用户之类的），因为感觉面试的时候问的也挺多的（作为string类型的扩展？）。

**Comment by Snailclimb** [comment]
> 你好，guide哥，看了你的java面经中关于redis的部分之后，感觉在第6小节介绍redis常见数据结构及应用场景中可以添加bitmap的有关介绍及应用场景（比如用户签到，统计活跃用户之类的），因为感觉面试的时候问的也挺多的（作为string类型的扩展？）。

非常感谢这个建议！这个确实在面试中以及实际开发中都很重要。希望有小伙伴能够认领这个任务！我最近在忙着完善其他的内容。

**Comment by Snailclimb** [comment]
- [x] 已完成

**Comment by AKAeminem** [comment]
谢谢你的资源




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snailclimb/JavaGuide"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月8日(星期一) 晚上8:00
收件人:&nbsp;"Snailclimb/JavaGuide"<JavaGuide@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Snailclimb/JavaGuide] 有关redis常见数据结构及使用场景分析中添加bitmap有关内容 (#1107)





  
 已完成

**Comment by Snailclimb** [comment]
> 谢谢你的资源
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Snailclimb/JavaGuide" <notifications@github.com&gt;; 发送时间:&nbsp;2021年3月8日(星期一) 晚上8:00 收件人:&nbsp;"Snailclimb/JavaGuide"<JavaGuide@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [Snailclimb/JavaGuide] 有关redis常见数据结构及使用场景分析中添加bitmap有关内容 (#1107) 已完成 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

不客气的！持续完善中！
