### ISSUE TITLE
打印<<java guide面试突击版>>

### ISSUE THREAD

**Issue by kilakila-heart** [Snailclimb/JavaGuide#1112]
楼主好，我想打印出<<java guide面试突击版>>，所以想把pdf的字体调粗，调大一点，但是pdf不太方便编辑，楼主能不能释放一个打印版本的pdf呢，方便大家脱离网络，脱离电脑查看，同时也保护国人的眼睛，这边谢谢您啦～～～

**Comment by Snailclimb** [comment]
打印版这个我不太了解哈。

**Comment by kilakila-heart** [comment]
其实就是能否出一个 字体加粗加大版的PDF呢～～～

**Comment by Snailclimb** [comment]
> 其实就是能否出一个 字体加粗加大版的PDF呢～～～

可以的。下一版安排！
