### ISSUE TITLE
期待增加es相关

### ISSUE THREAD

**Issue by qyaaaa** [Snailclimb/JavaGuide#1118]

**Comment by Snailclimb** [comment]
在路上了~~~

**Comment by Snailclimb** [comment]
> _No description provided._

https://javaguide.cn/database/elasticsearch/elasticsearch-questions-01.html

![image](https://github.com/Snailclimb/JavaGuide/assets/29880145/d83d453f-3b6d-49a7-9720-b1f1fee8fb20)
