### ISSUE TITLE
数据库索引有错误

### ISSUE THREAD

**Issue by njuzhm** [Snailclimb/JavaGuide#1128]
数据库索引提到作者是8.0.x版本，联合索引给每个字段加索引。此处是不正确的。

show index中显示的三行记录是指同一个索引的三个列，可以看到Key_name是同一个，不同的是Seq_in_index和Column_name
给出的执行计划中type为index，在MySQL官方文档中index的解释为

> The index join type is the same as ALL, except that the index tree is scanned.

index和全表扫描一样，只是扫描的是索引。一般认为range及以上才是用到了索引

此外该SQL中在不同字段使用or，即使有索引也是无法使用的是没有办法用到索引的

建议该段直接删除，已提交Pull request

**Comment by Snailclimb** [comment]
> 数据库索引提到作者是8.0.x版本，联合索引给每个字段加索引。此处是不正确的。
> 
> show index中显示的三行记录是指同一个索引的三个列，可以看到Key_name是同一个，不同的是Seq_in_index和Column_name
> 给出的执行计划中type为index，在MySQL官方文档中index的解释为
> 
> > The index join type is the same as ALL, except that the index tree is scanned.
> 
> index和全表扫描一样，只是扫描的是索引。一般认为range及以上才是用到了索引
> 
> 此外该SQL中在不同字段使用or，即使有索引也是无法使用的是没有办法用到索引的
> 
> 建议该段直接删除，已提交Pull request

感谢指出！👍
