### ISSUE TITLE
这里是否有歧义

### ISSUE THREAD

**Issue by zhangshuge** [Snailclimb/JavaGuide#1140]
发布订阅模型（Pub-Sub） 使用主题（Topic） 作为消息通信载体，类似于广播模式；发布者发布一条消息，该消息通过主题传递给所有的订阅者，**_在一条消息广播之后才订阅的用户则是收不到该条消息的_**。

最后这一句，是否不包括beging这种情况，即使是后注册的consumer也可以通过beging从头开始消费啊。

**Comment by Snailclimb** [comment]
> 发布订阅模型（Pub-Sub）

的确是可以从头开始消费的，消费端自己设置即可。

**Comment by Snailclimb** [comment]
> > 发布订阅模型（Pub-Sub）
> 
> 的确是可以从头开始消费的，消费端自己设置即可。

其实

> 发布订阅模型（Pub-Sub） 使用主题（Topic） 作为消息通信载体，类似于广播模式；发布者发布一条消息，该消息通过主题传递给所有的订阅者，**_在一条消息广播之后才订阅的用户则是收不到该条消息的_**。
> 
> 最后这一句，是否不包括beging这种情况，即使是后注册的consumer也可以通过beging从头开始消费啊。

我感觉也没有歧义吧！你看这句话的描述，并没有提高从头开始消费的场景。没有订阅的的确收不到消息。

![](https://user-images.githubusercontent.com/29880145/114270144-5a15e900-9a3d-11eb-8ca9-a6a7a4a0bbc9.png)
