### ISSUE TITLE
可能是把Java内存区域讲的最清楚的一篇文章.md =>String 类和常量池 => intern 方法的介绍

### ISSUE THREAD

**Issue by whoKnowsss** [Snailclimb/JavaGuide#1160]
> JavaGuide/Java相关/可能是把Java内存区域讲的最清楚的一篇文章.md

+ 四 重点补充内容
    + String 类和常量池
           + 2 String 类型的常量池比较特殊。它的主要使用方法有两种：

这里关于String.intern()的说明应该分版本讨论，在JDK1.6之前，这样说是没问题的，在JDK1.7及之后，String.intern()方法的API已经改变，举个demo：
```
public class StringIntern {
    public static void main(String[] args) {
        String s1 = new String("1") + new String("1");
        s1.intern();
        String s2 = "11";
        System.out.println(s1 == s2);
    }
}

```
![image](https://user-images.githubusercontent.com/17433658/114734966-4e952b80-9d77-11eb-9cef-3a4784b30bf2.png)

**这里返回的结果是True**

分析:
1. 对s1调用intern的时候，因为常量池没有对应的字面量，所以在常量池保存了一个指向s1的引用
2. 接下来的s2会先去常量池里找，找到对应引用，故指向堆里的s1
3. 故 s1==s2 为true

**Comment by Snailclimb** [comment]
> > JavaGuide/Java相关/可能是把Java内存区域讲的最清楚的一篇文章.md
> 
> * 四 重点补充内容
>   
>   * String 类和常量池
>     + 2 String 类型的常量池比较特殊。它的主要使用方法有两种：
> 
> 这里关于String.intern()的说明应该分版本讨论，在JDK1.6之前，这样说是没问题的，在JDK1.7及之后，String.intern()方法的API已经改变，举个demo：
> 
> ```
> public class StringIntern {
>     public static void main(String[] args) {
>         String s1 = new String("1") + new String("1");
>         s1.intern();
>         String s2 = "11";
>         System.out.println(s1 == s2);
>     }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/17433658/114734966-4e952b80-9d77-11eb-9cef-3a4784b30bf2.png)
> 
> **这里返回的结果是True**
> 
> 分析:
> 
> 1. 对s1调用intern的时候，因为常量池没有对应的字面量，所以在常量池保存了一个指向s1的引用
> 2. 接下来的s2会先去常量池里找，找到对应引用，故指向堆里的s1
> 3. 故 s1==s2 为true

已经修复了！感谢你👍
