### ISSUE TITLE
死锁的避免和预防有区别

### ISSUE THREAD

**Issue by closess** [Snailclimb/JavaGuide#1167]
**更正——预防死锁和避免死锁是有区别的！**

🔗：[源地址：如何避免死锁？](https://snailclimb.gitee.io/javaguide/#/docs/java/multi-thread/2020%E6%9C%80%E6%96%B0Java%E5%B9%B6%E5%8F%91%E5%9F%BA%E7%A1%80%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98%E6%80%BB%E7%BB%93?id=_82-%e5%a6%82%e4%bd%95%e9%81%bf%e5%85%8d%e7%ba%bf%e7%a8%8b%e6%ad%bb%e9%94%81)

**避免死锁**：实质是系统进行资源分配时，如何使其进入安全状态。
**安全状态**：指的是系统能够按照某种进行推进顺序（P1、P2、P3.....Pn）来为每个进程分配所需资源，直到满足每个进程对资源的最大需求，使每个进程都可顺利完成。称<P1、P2、P3.....Pn>序列为安全序列

**如何预防死锁？** 破坏死锁的产生的必要条件：
1. 破坏请求和保持条件。规定进程在开始时运行之前，必须一次性地申请其在整个运行过程中所需的全部资源。缺点是一次性分配会造成资源浪费，进程执行延迟。
2. 破环‘不剥夺’条件。规定当一个保持了某些不可被抢占资源的进程，提出新的资源请求时而不能得到啊满足时，它必须释放已经保持的所有资源。缺点是反复的申请和释放资源，增加了系统的开销。这种方式只适用于主存和处理器资源。
3. 破坏循环等待条件。规定对系统所有资源类型进行线性排序，并赋予不同的序号，规定每个进程必须按照序号递增的顺序请求资源。

**Comment by Snailclimb** [comment]
> **避免死锁**：实质是系统进行资源分配时，如何使其进入安全状态。
> **安全状态**：指的是系统能够按照某种进行推进顺序（P1、P2、P3.....Pn）来为每个进程分配所需资源，直到满足每个进程对资源的最大需求，使每个进程都可顺利完成。称<P1、P2、P3.....Pn>序列为安全序列

感谢指出！已经修正👍
