### ISSUE TITLE
关于LinkedList删除元素时间复杂度勘误

### ISSUE THREAD

**Issue by NaivePerdant** [Snailclimb/JavaGuide#1180]
**勘误位置：**
Java容器
1. Java 容器常见问题总结 (必看 )
1. 剖析面试最常见问题之 Java 集合框架
  1.2. Collection 子接口之 List
    1.2.2. Arraylist 与 LinkedList 区别?

**勘误内容：**
`LinkedList`删除元素时，无论是`remove(Object o)`还是`remove(int index)`都是需要先找到第一个符合条件的要删除的元素，这个过程需要遍历链表，所以时间复杂度应该为`O(n)`

**Comment by Snailclimb** [comment]
> **勘误位置：**
> Java容器
> 
> 1. Java 容器常见问题总结 (必看 )
> 2. 剖析面试最常见问题之 Java 集合框架
>    1.2. Collection 子接口之 List
>    1.2.2. Arraylist 与 LinkedList 区别?
> 
> **勘误内容：**
> `LinkedList`删除元素时，无论是`remove(Object o)`还是`remove(int index)`都是需要先找到第一个符合条件的要删除的元素，这个过程需要遍历链表，所以时间复杂度应该为`O(n)`

Java 容器常见问题总结 (必看 )这里的描述貌似没有问题。

![image](https://user-images.githubusercontent.com/29880145/116798506-aaef9d80-ab22-11eb-801b-bc7487a511a5.png)

**Comment by NaivePerdant** [comment]
谢谢guide老师的邮件回复，这里我认为是有争议的。原因如下：

1. 这里说的删除元素与add(E e)对应的我理解的是remove(E e)，这种 删除方式确实是需要遍历到第一个符合条件的元素的位置才开始删除的。所以应该是O(n)，源码如下(java9)：

2. 如果这里的删除元素指的是removeFirst() 和 removeLast() 确实是 O(1)，源代码如下(java9)：



3. 还是希望可以写清楚一点，避免造成我这样新手的误解。
最后再次表示感谢，谢谢guide老师给我提供的宝贵学习资料！祝你一切顺利，前程似锦！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snailclimb/JavaGuide"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月2日(星期天) 上午8:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Snailclimb/JavaGuide] 关于LinkedList删除元素时间复杂度勘误 (#1180)





  
勘误位置：
 Java容器
  
Java 容器常见问题总结 (必看 )
 
剖析面试最常见问题之 Java 集合框架
 1.2. Collection 子接口之 List
 1.2.2. Arraylist 与 LinkedList 区别?
  
勘误内容：
 LinkedList删除元素时，无论是remove(Object o)还是remove(int index)都是需要先找到第一个符合条件的要删除的元素，这个过程需要遍历链表，所以时间复杂度应该为O(n)
  
Java 容器常见问题总结 (必看 )这里的描述貌似没有问题。

**Comment by Snailclimb** [comment]
> 谢谢guide老师的邮件回复，这里我认为是有争议的。原因如下： 1. 这里说的删除元素与add(E e)对应的我理解的是remove(E e)，这种 删除方式确实是需要遍历到第一个符合条件的元素的位置才开始删除的。所以应该是O(n)，源码如下(java9)： ![image](https://user-images.githubusercontent.com/44255391/116798943-25bab780-ab27-11eb-9279-15991926e65f.png) 2. 如果这里的删除元素指的是removeFirst() 和 removeLast() 确实是 O(1)，源代码如下(java9)： ![image](https://user-images.githubusercontent.com/44255391/116798945-2b180200-ab27-11eb-9ce8-9913e0874604.png) 3. 还是希望可以写清楚一点，避免造成我这样新手的误解。 最后再次表示感谢，谢谢guide老师给我提供的宝贵学习资料！祝你一切顺利，前程似锦！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Snailclimb/JavaGuide" ***@***.***&gt;; 发送时间:&nbsp;2021年5月2日(星期天) 上午8:45 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Snailclimb/JavaGuide] 关于LinkedList删除元素时间复杂度勘误 (#1180) 勘误位置： Java容器 Java 容器常见问题总结 (必看 ) 剖析面试最常见问题之 Java 集合框架 1.2. Collection 子接口之 List 1.2.2. Arraylist 与 LinkedList 区别? 勘误内容： LinkedList删除元素时，无论是remove(Object o)还是remove(int index)都是需要先找到第一个符合条件的要删除的元素，这个过程需要遍历链表，所以时间复杂度应该为O(n) Java 容器常见问题总结 (必看 )这里的描述貌似没有问题。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

👍

**Comment by Snailclimb** [comment]
> 谢谢guide老师的邮件回复，这里我认为是有争议的。原因如下： 1. 这里说的删除元素与add(E e)对应的我理解的是remove(E e)，这种 删除方式确实是需要遍历到第一个符合条件的元素的位置才开始删除的。所以应该是O(n)，源码如下(java9)： ![image](https://user-images.githubusercontent.com/44255391/116798943-25bab780-ab27-11eb-9279-15991926e65f.png) 2. 如果这里的删除元素指的是removeFirst() 和 removeLast() 确实是 O(1)，源代码如下(java9)： ![image](https://user-images.githubusercontent.com/44255391/116798945-2b180200-ab27-11eb-9ce8-9913e0874604.png) 3. 还是希望可以写清楚一点，避免造成我这样新手的误解。 最后再次表示感谢，谢谢guide老师给我提供的宝贵学习资料！祝你一切顺利，前程似锦！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Snailclimb/JavaGuide" ***@***.***&gt;; 发送时间:&nbsp;2021年5月2日(星期天) 上午8:45 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Snailclimb/JavaGuide] 关于LinkedList删除元素时间复杂度勘误 (#1180) 勘误位置： Java容器 Java 容器常见问题总结 (必看 ) 剖析面试最常见问题之 Java 集合框架 1.2. Collection 子接口之 List 1.2.2. Arraylist 与 LinkedList 区别? 勘误内容： LinkedList删除元素时，无论是remove(Object o)还是remove(int index)都是需要先找到第一个符合条件的要删除的元素，这个过程需要遍历链表，所以时间复杂度应该为O(n) Java 容器常见问题总结 (必看 )这里的描述貌似没有问题。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

已经修复，这样描述会不会好点呢？
![image](https://user-images.githubusercontent.com/29880145/116883805-957c8f80-ac58-11eb-9fed-4d3057edff1e.png)
