### ISSUE TITLE
关于 ThreadLocal 在调用 set()、get()、remove() 方法的时候，会清理掉 key 为 null 的记录

### ISSUE THREAD

**Issue by xiaod-dev** [Snailclimb/JavaGuide#1190]
>  ThreadLocalMap 实现中已经考虑了这种情况，在调用 set()、get()、remove() 方法的时候，**会清理掉 key 为 null 的记录**。使用完 ThreadLocal方法后 最好手动调用remove()方法

看了一下源码，并没有找到这部分的逻辑，原文也只是贴了Entry的代码，不够说服性。
```java
    static class Entry extends WeakReference<ThreadLocal<?>> {
            /** The value associated with this ThreadLocal. */
            Object value;

            Entry(ThreadLocal<?> k, Object v) {
                super(k);
                value = v;
            }
        } 
```
还望请教一下清理的代码的位置。并建议在原文贴上清理的源码片段。

**Comment by 1725636955** [comment]
> > ThreadLocalMap 实现中已经考虑了这种情况，在调用 set()、get()、remove() 方法的时候，**会清理掉 key 为 null 的记录**。使用完 ThreadLocal方法后 最好手动调用remove()方法
> 
> 看了一下源码，并没有找到这部分的逻辑，原文也只是贴了Entry的代码，不够说服性。
> 
> ```java
>     static class Entry extends WeakReference<ThreadLocal<?>> {
>             /** The value associated with this ThreadLocal. */
>             Object value;
> 
>             Entry(ThreadLocal<?> k, Object v) {
>                 super(k);
>                 value = v;
>             }
>         } 
> ```
> 
> 还望请教一下清理的代码的位置。并建议在原文贴上清理的源码片段。
java.lang.ThreadLocal.ThreadLocalMap#expungeStaleEntry方法会清除key为null的记录


java.lang.ThreadLocal#set调用java.lang.ThreadLocal.ThreadLocalMap#set中调用java.lang.ThreadLocal.ThreadLocalMap#cleanSomeSlots方法清除key为null的
![image](https://user-images.githubusercontent.com/43667484/118837383-535d7a00-b8f7-11eb-934d-61986c822eb8.png)

java.lang.ThreadLocal#remove方法调用java.lang.ThreadLocal.ThreadLocalMap#remove，中调用expungeStaleEntry清除
![image](https://user-images.githubusercontent.com/43667484/118837706-acc5a900-b8f7-11eb-84b2-cfbaca34ee19.png)

java.lang.ThreadLocal#get调用java.lang.ThreadLocal.ThreadLocalMap#getEntry中如果无法快速命中存的值，则调用java.lang.ThreadLocal.ThreadLocalMap#getEntryAfterMiss方法，里面调用了java.lang.ThreadLocal.ThreadLocalMap#expungeStaleEntry方法清除

**Comment by xiaod-dev** [comment]
@1725636955  感谢大兄弟回复，已找到清理部分的代码。
