### ISSUE TITLE
JavaGuide/docs/java/basis/代理模式详解.md

### ISSUE THREAD

**Issue by labi-xiaoxin** [Snailclimb/JavaGuide#1192]
cglib案例在jdk1.7使用cglib3.3.0会提示：
`Caused by: net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null`

当修改cglib版本为3.2.0代码便成功执行

**Comment by Snailclimb** [comment]
> 当修改cglib版本为3.2.0代码便成功执
