### ISSUE TITLE
关于ArrayList中的Arrays.copy()中的建议

### ISSUE THREAD

**Issue by jtMook** [Snailclimb/JavaGuide#1193]
建议可以把Arrays.copy()和System.arraycopy()的源码附上去
是关于ArrayList的文章[入口](https://snailclimb.gitee.io/javaguide/#/docs/java/collection/ArrayList%E6%BA%90%E7%A0%81+%E6%89%A9%E5%AE%B9%E6%9C%BA%E5%88%B6%E5%88%86%E6%9E%90?id=_322-%e5%86%8d%e6%9d%a5%e7%9c%8b%e7%9c%8b-ensurecapacityinternal-%e6%96%b9%e6%b3%95)
**Arrays.copyOf()**
```
public static int[] copyOf(int[] original, int newLength) {
        //newLength 要返回的副本的长度
        int[] copy = new int[newLength];
        System.arraycopy(original, 0, copy, 0,
                         Math.min(original.length, newLength));
        return copy;
    }




```
**System.arraycopy()**
```
public static native void arraycopy(Object src,  int  srcPos,
                                    Object dest, int destPos,
                                    int length);
```

**Comment by Snailclimb** [comment]
> 建议可以把Arrays.copy()和System.arraycopy()的源码附上去
> 是关于ArrayList的文章[入口](https://snailclimb.gitee.io/javaguide/#/docs/java/collection/ArrayList%E6%BA%90%E7%A0%81+%E6%89%A9%E5%AE%B9%E6%9C%BA%E5%88%B6%E5%88%86%E6%9E%90?id=_322-%e5%86%8d%e6%9d%a5%e7%9c%8b%e7%9c%8b-ensurecapacityinternal-%e6%96%b9%e6%b3%95)
> **Arrays.copyOf()**
> 
> ```
> public static int[] copyOf(int[] original, int newLength) {
>         //newLength 要返回的副本的长度
>         int[] copy = new int[newLength];
>         System.arraycopy(original, 0, copy, 0,
>                          Math.min(original.length, newLength));
>         return copy;
>     }
> ```
> 
> **System.arraycopy()**
> 
> ```
> public static native void arraycopy(Object src,  int  srcPos,
>                                     Object dest, int destPos,
>                                     int length);
> ```

已经处理：https://github.com/Snailclimb/JavaGuide/commit/86b2ddf14e29df2d110ec62adcd7dcbaadb2b839
