### ISSUE TITLE
typo: ArrayList源码+扩容机制分析.md

### ISSUE THREAD

**Issue by lewisbyte** [Snailclimb/JavaGuide#1194]
[ArrayList源码+扩容机制分析.md](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/collection/ArrayList%E6%BA%90%E7%A0%81+%E6%89%A9%E5%AE%B9%E6%9C%BA%E5%88%B6%E5%88%86%E6%9E%90.md)
的 `使用ensureCapacity方法前：1773` 应该修改为  `使用ensureCapacity方法后：1773`

**Comment by Snailclimb** [comment]
👍
