### ISSUE TITLE
Java 容器常见问题总结  好像看不了哦

### ISSUE THREAD

**Issue by waper97** [Snailclimb/JavaGuide#1197]
Java 容器常见问题总结  好像看不了哦

**Comment by Snailclimb** [comment]
> Java 容器常见问题总结 好像看不了哦

貌似可以吧~https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.md
