### ISSUE TITLE
Linux目录的操作命令ll命令和ls命令关系解释有误

### ISSUE THREAD

**Issue by debugjoker** [Snailclimb/JavaGuide#120]
在后端程序员必备的Linux基础知识.md文件4.2节中描述如下：
> ```ls或者ll```（ll是ls -l的别名，ll命令可以看到该目录下的所有目录和文件的详细信息）：查看目录信息
实际上查看.bashrc里面的定义可以知道
![TIM截图20190115155015.png](https://i.loli.net/2019/01/15/5c3d90c94ea38.png)
```ll``` 命令实际上是  ```ls -alF```

**Comment by Snailclimb** [comment]
实际上 ll 就是 ls -l 的别名。详情可以参考这篇文章 https://www.linuxidc.com/Linux/2018-07/153131.htmhttps://www.linuxidc.com/Linux/2018-07/153131.htm

**Comment by debugjoker** [comment]
> 实际上 ll 就是 ls -l 的别名。详情可以参考这篇文章 https://www.linuxidc.com/Linux/2018-07/153131.htmhttps://www.linuxidc.com/Linux/2018-07/153131.htm

ll是可以看到隐藏文件的 ls -l是看不到隐藏文件的

![微信截图_20190116205758.png](https://i.loli.net/2019/01/16/5c3f2a7325fcc.png)

type ll 可以看到

![微信截图_20190116210531.png](https://i.loli.net/2019/01/16/5c3f2c2ca73ef.png)

**Comment by Snailclimb** [comment]
之前确实没注意过这个问题，不知道是不是我俩的Linux版本不同的原因呢?感谢老哥提醒！

鸟哥的Linux私房菜P253
![](http://my-blog-to-use.oss-cn-beijing.aliyuncs.com/19-1-17/87559480.jpg)
我自己的centos7.0系统
![](http://my-blog-to-use.oss-cn-beijing.aliyuncs.com/19-1-17/22919257.jpg)

**Comment by debugjoker** [comment]
我的是ubuntu的，原来两个预设的别名不一样。十分感谢！！

**Comment by Snailclimb** [comment]
不客气 感谢老哥指出这个问题！
