### ISSUE TITLE
“整型包装类值的比较”小节中的解释错误

### ISSUE THREAD

**Issue by mjhxy** [Snailclimb/JavaGuide#1200]
现有描述“当使用自动装箱方式创建一个Integer对象时，当数值在-128 ~127时，会将创建的 Integer 对象缓存起来，当下次再出现该数值时，直接从缓存中取出对应的Integer对象。所以上述代码中，x和y引用的是相同的Integer对象。”

正确解释大概为“IntegerCache为Integer类的缓存类，默认缓存了-128~127的Integer值，如遇到[-128,127]范围的值需要转换为Integer时会直接从IntegerCache中获取”

博客参考：https://blog.csdn.net/cockroach02/article/details/88857551  https://blog.csdn.net/moakun/article/details/80165177

问题页面地址：https://snailclimb.gitee.io/javaguide/#/docs/java/basis/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86%E7%96%91%E9%9A%BE%E7%82%B9

![image](https://user-images.githubusercontent.com/48780291/119014902-0054f700-b9cb-11eb-90eb-182ad0cfc610.png)

**Comment by Snailclimb** [comment]
> 当使用自动装箱方式创建一个Integer对象时

![image](https://user-images.githubusercontent.com/29880145/119261247-223bbd00-bc09-11eb-887d-3dc1b76123c3.png)
