### ISSUE TITLE
Hashtable的组成描述笔误

### ISSUE THREAD

**Issue by mjhxy** [Snailclimb/JavaGuide#1201]
原内容：“Hashtable： 数组+链表组成的，数组是 HashMap 的主体，链表则是主要为了解决哈希冲突而存在的”

内容地址：https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.md

此处的“数组是 HashMap 的主体”是不是应该是“数组是 HashTable 的主体”

![image](https://user-images.githubusercontent.com/48780291/119074138-1392b180-ba21-11eb-956c-e267f163a1e7.png)

**Comment by Snailclimb** [comment]
> 原内容：“Hashtable： 数组+链表组成的，数组是 HashMap 的主体，链表则是主要为了解决哈希冲突而存在的”
> 
> 内容地址：https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.md
> 
> 此处的“数组是 HashMap 的主体”是不是应该是“数组是 HashTable 的主体”
> 
> ![image](https://user-images.githubusercontent.com/48780291/119074138-1392b180-ba21-11eb-956c-e267f163a1e7.png)

嗯嗯 👍
