### ISSUE TITLE
有没有一个综合性的练手项目提供啊？

### ISSUE THREAD

**Issue by zychen2016** [Snailclimb/JavaGuide#121]

**Comment by Snailclimb** [comment]
你可以加我微信：bwcx9393，我可以给你提供一些不错的练手项目。注意备注来自Github

**Comment by lzx2005** [comment]
[https://github.com/xtTech/app-version](https://github.com/xtTech/app-version) 

LZ，我这里有个完整的基于Spring Boot + Vue 实现的Java项目，可以参考一下哈~

**Comment by sanwancoder** [comment]
https://github.com/macrozheng/mall.git  相当值得学习 推荐一下
