### ISSUE TITLE
关于GC的Minor GC的空间分配担保

### ISSUE THREAD

**Issue by ZHBlue5** [Snailclimb/JavaGuide#1210]
在《深入理解Java虚拟机》，在内存分配和回收策略=》新增空间分配担保
-  在发生Minor GC之前，虚拟机必须检查老年代最大可用的连续空间是否大于新生代所有对象总空间，若允许，则Minor GC是安全；
- 否则老年代的连续空间大于此GC新生代对象总大小或者历次晋升的平均大小，就会进行Minor GC，否则进行Full GC
- JDK 6 Update 24的规则

**Comment by Snailclimb** [comment]
![image](https://user-images.githubusercontent.com/29880145/125059325-c73d2700-e0dd-11eb-9d8e-284c5e316e88.png)
![image](https://user-images.githubusercontent.com/29880145/125059367-d328e900-e0dd-11eb-87e2-4f03879586ad.png)
