### ISSUE TITLE
错别字修正

### ISSUE THREAD

**Issue by guotao1415** [Snailclimb/JavaGuide#1213]
JavaGuide/docs/dataStructures-algorithms/data-structure/线性数据结构.md

2.4. 数组 vs 链表
数组支持随机访问，而链表不支持。
数组使用的是连续内存空间对 CPU 的缓存机制友好，链表则相反。
数组的大小固定，而链表则天然支持动态扩容。如果声明的数组过小，需要另外申请一个更大的内存空间存放数组元素，然后将原数组拷贝进去，这个操作是比较耗时的！

**Comment by TommyMerlin** [comment]
已修改错别字并提交 PR。

**Comment by TommyMerlin** [comment]
已通过 PR，可 close issue。
