### ISSUE TITLE
错别字修正

### ISSUE THREAD

**Issue by guotao1415** [Snailclimb/JavaGuide#1215]
JavaGuide/docs/dataStructures-algorithms/几道常见的子符串算法题.md
->
JavaGuide/docs/dataStructures-algorithms/几道常见的字符串算法题.md

**Comment by TommyMerlin** [comment]
已经修改完毕，可 close。

**Comment by Snailclimb** [comment]
> JavaGuide/docs/dataStructures-algorithms/几道常见的子符串算法题.md
> ->
> JavaGuide/docs/dataStructures-algorithms/几道常见的字符串算法题.md

感谢各位！爱了爱了😊
