### ISSUE TITLE
线程的生命周期和状态

### ISSUE THREAD

**Issue by Belo-betty** [Snailclimb/JavaGuide#1219]
guide哥，您好，请教个问题。
链接：https://snailclimb.gitee.io/javaguide/#/docs/java/multi-thread/2020%E6%9C%80%E6%96%B0Java%E5%B9%B6%E5%8F%91%E5%9F%BA%E7%A1%80%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98%E6%80%BB%E7%BB%93?id=6-%e8%af%b4%e8%af%b4%e7%ba%bf%e7%a8%8b%e7%9a%84%e7%94%9f%e5%91%bd%e5%91%a8%e6%9c%9f%e5%92%8c%e7%8a%b6%e6%80%81
图片：https://i0.wp.com/howtodoinjava.com/wp-content/uploads/2016/04/RUNNABLE-VS-RUNNING.png?w=526&ssl=1

Ready + Running （操作系统）-> Runnable（JVM）
请问是“就绪”加“运行中”统称“运行”
还是“就绪”加“运行”统称“运行中”
个人感觉前者才是对的，但是你和书都写的是后者。是笔误还是我理解错了

**Comment by z-soulx** [comment]
用户角度 运行：用户态已经交给内核，让它运行。对于应用来说已经提交运行了。

就绪+运行中： 是内核的角度，得到时间片的就是运行中，没得到的就是就绪。

**Comment by VinterHe** [comment]
其实就是字面意思就好，runnable，有运行能力的
