### ISSUE TITLE
snailclimb.gitee.io的文档可以同步Github的更新吗？

### ISSUE THREAD

**Issue by 2293736867** [Snailclimb/JavaGuide#1222]
https://snailclimb.gitee.io/javaguide/#/ 的文档好像很久没更新过的样子。

**Comment by Snailclimb** [comment]
> https://snailclimb.gitee.io/javaguide/#/ 的文档好像很久没更新过的样子。

嗯嗯 我大概一周同步一次。刚刚又同步了一下。
