### ISSUE TITLE
关于类加载过程

### ISSUE THREAD

**Issue by ddmcc** [Snailclimb/JavaGuide#1224]
[原文描述：](https://snailclimb.gitee.io/javaguide/#/docs/java/jvm/%E7%B1%BB%E5%8A%A0%E8%BD%BD%E8%BF%87%E7%A8%8B?id=%e5%8a%a0%e8%bd%bd)

类加载过程的第一步，主要完成下面 3 件事情：

...

...

**加载阶段和连接阶段的部分内容是交叉进行的，加载阶段尚未结束，连接阶段可能就已经开始了**。

看了[jvm规范5.4](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-5.html#jvms-5.4)描述的是：

`This specification allows an implementation flexibility as to when linking activities (and, because of recursion, loading) take place, provided that all of the following properties are maintained:`

`A class or interface is completely loaded before it is linked.`

`A class or interface is completely verified and prepared before it is initialized.`

 @`其它...`

1，类或接口在链接之前已完全加载
2，类或接口在初始化之前是完全验证和准备好的

所以原文是不是描述错了？

**Comment by Snailclimb** [comment]
> jvm规范5.4

为支持运行时绑定，解析过程在某些情况下可在初始化之后再开始，除解析过程外的其他加载过程必须按照如图顺序开始。

refer:周志明老师的[《深入理解Java虚拟机（第3版）》](https://book.douban.com/subject/34907497/) 
![image](https://user-images.githubusercontent.com/29880145/120951872-6f2ca100-c77c-11eb-8a46-e0450231347a.png)
