### ISSUE TITLE
万字详解ThreadLocal关键字问题

### ISSUE THREAD

**Issue by shwangshoudao** [Snailclimb/JavaGuide#1237]
这篇文章中的关于ThreadLocalMap结局hash冲突的地方顺序是不是有点乱，z这个地方怎么第三步第四步来回转
![image](https://user-images.githubusercontent.com/53508777/121287117-9073c580-c913-11eb-8c91-f9c4c1c95f09.png)

**Comment by Snailclimb** [comment]
> 这篇文章中的关于ThreadLocalMap结局hash冲突的地方顺序是不是有点乱，z这个地方怎么第三步第四步来回转
> ![image](https://user-images.githubusercontent.com/53508777/121287117-9073c580-c913-11eb-8c91-f9c4c1c95f09.png)

两种不同的情况，针对的是第三步是否找到相同key值的Entry数据~
