### ISSUE TITLE
关于静态代码块执行时机的问题

### ISSUE THREAD

**Issue by wulnm** [Snailclimb/JavaGuide#1245]
在[Java常见关键字总结](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/basis/Java%E5%B8%B8%E8%A7%81%E5%85%B3%E9%94%AE%E5%AD%97%E6%80%BB%E7%BB%93.md#static%E9%9D%99%E6%80%81%E4%BB%A3%E7%A0%81%E5%9D%97%E4%B8%8E%E9%9D%9E%E9%9D%99%E6%80%81%E4%BB%A3%E7%A0%81%E5%9D%97%E6%9E%84%E9%80%A0%E4%BB%A3%E7%A0%81%E5%9D%97)中, 有如下说明:
>🐛 修正（参见： issue #677） ：静态代码块可能在第一次new的时候执行，但不一定只在第一次new的时候执行。比如通过 Class.forName("ClassDemo")创建 Class 对象的时候也会执行。

这句话有歧义, 我第一次看到的时候认为是static有可能会执行两次, 即"不一定只在第一次new的时候执行"我理解为"在new的时候执行static块后, 可能还会再执行一次static块".

当然通过代码验证以及查看issue后明白是指 "可以通过new或者Class.forName来执行static".
代码验证如下:
```java
public void staticExecTimeTest(){
        try {
            Thread.sleep(2000);
            Class.forName("yourClassName");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

所以也是觉得消除歧义可能对于不熟悉的人更加友好.

**Comment by Snailclimb** [comment]
> 可以通过new或者Class.forName来执行static

已经修正~
![image](https://user-images.githubusercontent.com/29880145/121910722-a9d89f80-cd61-11eb-950a-aedd13e542b1.png)
