### ISSUE TITLE
jdk1.8，HashMap源码，HashMap扩容条件描述不准确

### ISSUE THREAD

**Issue by 1725636955** [Snailclimb/JavaGuide#1246]
原文：[HashMap 简介](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/collection/HashMap(JDK1.8)%E6%BA%90%E7%A0%81%2B%E5%BA%95%E5%B1%82%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E5%88%86%E6%9E%90.md#hashmap-%E7%AE%80%E4%BB%8B)

![image](https://user-images.githubusercontent.com/43667484/121869342-8814f380-cd34-11eb-8873-b289541c56d6.png)

链表长度大于阈值（默认为 8）且 HashMap 数组长度超过 64。

问题：不止是大于和超过 还有等于
建议修改为：链表长度大于或等于阈值（默认为 8）  HashMap 数组长度大于或等于 64。
提了一个pr #1247 

判断链表长度代码
java.util.HashMap#putVal，643行。循环的次数 >= 8（因为从零开始循环，所以判断的时候8-1了），符合这个条件调用判断是否树化方法
![image](https://user-images.githubusercontent.com/43667484/121865865-ffe11f00-cd30-11eb-8bc9-91ccb4460f3b.png)

判断table数组长度代码
java.util.HashMap#treeifyBin，995行，如果table.length < 64则进行table扩容，否则大于等于64时进行树化
![image](https://user-images.githubusercontent.com/43667484/121866595-a7f6e800-cd31-11eb-86d0-9c0b39aa8f7b.png)

**Comment by Snailclimb** [comment]
> 原文：[HashMap 简介](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/collection/HashMap(JDK1.8)%E6%BA%90%E7%A0%81%2B%E5%BA%95%E5%B1%82%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E5%88%86%E6%9E%90.md#hashmap-%E7%AE%80%E4%BB%8B)
> 
> ![image](https://user-images.githubusercontent.com/43667484/121869342-8814f380-cd34-11eb-8873-b289541c56d6.png)
> 
> 链表长度大于阈值（默认为 8）且 HashMap 数组长度超过 64。
> 
> 问题：不止是大于和超过 还有等于
> 建议修改为：链表长度大于或等于阈值（默认为 8） HashMap 数组长度大于或等于 64。
> 提了一个pr #1247
> 
> 判断链表长度代码
> java.util.HashMap#putVal，643行。循环的次数 >= 8（因为从零开始循环，所以判断的时候8-1了），符合这个条件调用判断是否树化方法
> ![image](https://user-images.githubusercontent.com/43667484/121865865-ffe11f00-cd30-11eb-8bc9-91ccb4460f3b.png)
> 
> 判断table数组长度代码
> java.util.HashMap#treeifyBin，995行，如果table.length < 64则进行table扩容，否则大于等于64时进行树化
> ![image](https://user-images.githubusercontent.com/43667484/121866595-a7f6e800-cd31-11eb-86d0-9c0b39aa8f7b.png)



> 原文：[HashMap 简介](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/collection/HashMap(JDK1.8)%E6%BA%90%E7%A0%81%2B%E5%BA%95%E5%B1%82%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E5%88%86%E6%9E%90.md#hashmap-%E7%AE%80%E4%BB%8B)
> 
> ![image](https://user-images.githubusercontent.com/43667484/121869342-8814f380-cd34-11eb-8873-b289541c56d6.png)
> 
> 链表长度大于阈值（默认为 8）且 HashMap 数组长度超过 64。
> 
> 问题：不止是大于和超过 还有等于
> 建议修改为：链表长度大于或等于阈值（默认为 8） HashMap 数组长度大于或等于 64。
> 提了一个pr #1247
> 
> 判断链表长度代码
> java.util.HashMap#putVal，643行。循环的次数 >= 8（因为从零开始循环，所以判断的时候8-1了），符合这个条件调用判断是否树化方法
> ![image](https://user-images.githubusercontent.com/43667484/121865865-ffe11f00-cd30-11eb-8bc9-91ccb4460f3b.png)
> 
> 判断table数组长度代码
> java.util.HashMap#treeifyBin，995行，如果table.length < 64则进行table扩容，否则大于等于64时进行树化
> ![image](https://user-images.githubusercontent.com/43667484/121866595-a7f6e800-cd31-11eb-86d0-9c0b39aa8f7b.png)

这里忘记同步更新了~感谢指出👍

![image](https://user-images.githubusercontent.com/29880145/121913152-b6f68e00-cd63-11eb-9877-a6e0df5709d4.png)
