### ISSUE TITLE
配图错误

### ISSUE THREAD

**Issue by TommyMerlin** [Snailclimb/JavaGuide#1249]
### 错误配图1：  
![image](https://user-images.githubusercontent.com/32566324/121988814-9b27d200-cdcd-11eb-98ff-3bf995c946e9.png)  
### 错误配图2：  
![image](https://user-images.githubusercontent.com/32566324/121988851-a844c100-cdcd-11eb-8485-fe6a323b1426.png)
### 错误配图1：  
![image](https://user-images.githubusercontent.com/32566324/122002417-480d4980-cde4-11eb-9ee3-9215c043ed62.png)

**Comment by Snailclimb** [comment]
> ## 1.目标文件：`/docs/tools/Github技巧.md`
> ### 错误配图1：
> ![image](https://user-images.githubusercontent.com/32566324/121988814-9b27d200-cdcd-11eb-98ff-3bf995c946e9.png)
> 
> ### 错误配图2：
> ![image](https://user-images.githubusercontent.com/32566324/121988851-a844c100-cdcd-11eb-8485-fe6a323b1426.png)
> 
> ## 2.目标文件：`/docs/tools/Docker.md.md`
> ### 错误配图1：
> ![image](https://user-images.githubusercontent.com/32566324/122002417-480d4980-cde4-11eb-9ee3-9215c043ed62.png)

感谢指出！已经修改👍
