### ISSUE TITLE
一个潜在问题或疑问

### ISSUE THREAD

**Issue by intSpark** [Snailclimb/JavaGuide#125]
请教一个疑问，关于‘基础知识->18. 成员变量与局部变量的区别有那些’中提到的一点：局部变量是在方法中定义的变量或是方法的参数...局部变量存在于栈内存....
局部变量存在于栈内存这个说法我个人觉得是有疑问的。
线程方法栈中的栈帧大小是不可变的，如果方法中包含一个集合类型的变量则其运行时占用内存的大小在编译时完全无法确定。因此，我的理解是简单类型的局部变量可以直接栈上分配；对象类型栈上只持有指向HEAP的reference。

**Comment by intSpark** [comment]
另外有问题的说法：成员变量如果没有被赋初值，则会自动以类型的默认值而赋值....而局部变量则不会自动赋值。
下面是一个反例：
public void method1() {
		boolean[] someBools = new boolean[3];
		boolean aBool;
		//System.out.println(aBool);    <----编译无法通过，因为aBool没有赋初值
		for (boolean b : someBools) {
			System.out.println(b);   <----输出全为false
		}
	}
someBools是方法的局部变量，但它是被自动赋初值了的。因为它是堆上分配的，堆上对象在分配了内存之后会有一次内存清零的动作，因此有初始值。

**Comment by xia1299** [comment]
> 另外有问题的说法：成员变量如果没有被赋初值，则会自动以类型的默认值而赋值....而局部变量则不会自动赋值。
> 下面是一个反例：
> public void method1() {
> boolean[] someBools = new boolean[3];
> boolean aBool;
> //System.out.println(aBool); <----编译无法通过，因为aBool没有赋初值
> for (boolean b : someBools) {
> System.out.println(b); <----输出全为false
> }
> }
> someBools是方法的局部变量，但它是被自动赋初值了的。因为它是堆上分配的，堆上对象在分配了内存之后会有一次内存清零的动作，因此有初始值。

 “boolean[] someBools = new boolean[3];“”这句话就是赋值操作了吧。未赋值的应该就是声明 boolean[] someBools;

**Comment by xia1299** [comment]
> 请教一个疑问，关于‘基础知识->18. 成员变量与局部变量的区别有那些’中提到的一点：局部变量是在方法中定义的变量或是方法的参数...局部变量存在于栈内存....
> 局部变量存在于栈内存这个说法我个人觉得是有疑问的。
> 线程方法栈中的栈帧大小是不可变的，如果方法中包含一个集合类型的变量则其运行时占用内存的大小在编译时完全无法确定。因此，我的理解是简单类型的局部变量可以直接栈上分配；对象类型栈上只持有指向HEAP的reference。

这个我的理解是，对于集合类型，他的引用是局部变量，是位于栈内存的

**Comment by xia1299** [comment]
我觉得我们似乎是有点模糊 变量 和 对象这两个概念。我觉得变量实际存放的应该是内存地址，并且告诉编译器这个位置存放的是什么，而对象则是基本类型或者类的实例，也就是存值的地方。赋值操作，就是在对应的内存（栈、堆内存）中分配空间，并进行初始化，最后把对应的内存地址存放到变量。因此对于局部变量，是需要进行赋值操作的，因为不会自动的赋初值。

**Comment by yuechuanx** [comment]
Java方法堆栈（栈帧）中存在一个内存区域叫局部变量表，用来保存Java方法内部所声明的局部变量以及入参（存放入参是因为Java是值传递，引用是内存地址的值）。
在编译阶段，编译器能准确计算出Java方法的局部变量空间（可以理解为索引表，基础数据类型可直接存储在表中，对象类型存放引用）。
在运行期JVM为Java方法中的局部变量分配堆栈空间，而不用为入参额外分配空间，入参的堆栈空间由调用方完成分配。

Reference：
《揭秘Java虚拟机—JVM设计原理与实现》第7章
