### ISSUE TITLE
JVM线程状态

### ISSUE THREAD

**Issue by DeShun-1024** [Snailclimb/JavaGuide#1255]
![image](https://user-images.githubusercontent.com/19798975/122939506-41fc0780-d3a6-11eb-8b94-d46ba82fab1e.png)

图中标注的是不是说反了？

线程状态Running与Ready状态是操作系统中的线程状态，是JVM屏蔽这两种状态，统一使用Runnable状态。Runnable状态是JVM特有的。

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/19798975/122939506-41fc0780-d3a6-11eb-8b94-d46ba82fab1e.png)
> 
> 图中标注的是不是说反了？
> 
> 线程状态Running与Ready状态是操作系统中的线程状态，是JVM屏蔽这两种状态，统一使用Runnable状态。Runnable状态是JVM特有的。

已经完善描述~

![image](https://user-images.githubusercontent.com/29880145/123101795-fb221680-d466-11eb-8cda-55d463ed179f.png)
