### ISSUE TITLE
对多线程文章中，单核和多核中多线程作用，以及上下文切换描述进行修改

### ISSUE THREAD

**Issue by VinterHe** [Snailclimb/JavaGuide#1256]

**Comment by VinterHe** [comment]
- **单核时代**： 在单核时代多线程主要是为了提高单进程利用CPU和IO系统的效率。 当我们请求IO的时候，如果java进程中只有一个线程，此线程被IO阻塞则整个进程被阻塞。CPU和IO设备只有一个在运行，那么可以简单地说系统整体效率只有50%。当使用多线程的时候，一个线程被IO阻塞，其他线程还可以继续使用CPU。从而提高了java进程利用系统资源的整体效率。

注意：此种情况是指的计算机只有一个CPU核心，并且假设只运行了一个java进程的情况，多进程的时候，操作系统会调度不同进程占用CPU，也不会存在浪费CPU的问题，只不过是因为大型项目中，作为服务器运行的机器中一般不会运行太多无关进程，所以才可作此假设。

- **多核时代**: 多核时代多线程主要是为了提高进程利用多核CPU的能力。举个例子：假如我们要计算一个复杂的任务，我们只用一个线程的话，不论系统有几个CPU核心，都只会有一个 CPU 核心被利用到。而创建多个线程，这些线程可以被映射到底层多个CPU上执行，在任务中的多个线程没有资源竞争的情况下，任务执行的效率会有显著性的提高，约等于（单核时执行时间/CPU核心数）。

**Comment by VinterHe** [comment]
线程在执行过程中会有自己的运行条件和状态（也称上下文），比如上文所说到过的程序计数器，栈信息等。当出现如下情况的时候，线程会从占用CPU状态中退出。
- 主动让出CPU，比如调用了sleep(),wait()等。
- 时间片用完，因为操作系统要防止一个线程或者进程长时间占用CPU导致其他线程或者进程饿死。
- 调用了阻塞类型的系统中断，比如请求IO，线程被阻塞。
- 被终止或结束运行

这其中前三种都会发生线程切换，线程切换意味着需要保存当前线程的上下文，留待线程下次占用CPU的时候恢复现场。并加载下一个将要占用CPU的线程上下文。这就是所谓的上下文切换。

上下文切换是现代操作系统的基本功能，因其每次需要保存信息恢复信息，这将会占用CPU，内存等系统资源进行处理，也就意味着效率会有一定损耗，如果频繁切换就会造成整体效率低下。

**Comment by VinterHe** [comment]
## 7. 什么是上下文切换?
线程在执行过程中会有自己的运行条件和状态（也称上下文），比如上文所说到过的程序计数器，栈信息等。当出现如下情况的时候，线程会从占用CPU状态中退出。
- 主动让出CPU，比如调用了sleep(),wait()等。
- 时间片用完，因为操作系统要防止一个线程或者进程长时间占用CPU导致其他线程或者进程饿死。
- 调用了阻塞类型的系统中断，比如请求IO，线程被阻塞。
- 被终止或结束运行

这其中前三种都会发生线程切换，线程切换意味着需要保存当前线程的上下文，留待线程下次占用CPU的时候恢复现场。并加载下一个将要占用CPU的线程上下文。这就是所谓的上下文切换。

上下文切换是现代操作系统的基本功能，因其每次需要保存信息恢复信息，这将会占用CPU，内存等系统资源进行处理，也就意味着效率会有一定损耗，如果频繁切换就会造成整体效率低下。

**Comment by Snailclimb** [comment]
> ## 7. 什么是上下文切换?
> 线程在执行过程中会有自己的运行条件和状态（也称上下文），比如上文所说到过的程序计数器，栈信息等。当出现如下情况的时候，线程会从占用CPU状态中退出。
> 
> * 主动让出CPU，比如调用了sleep(),wait()等。
> * 时间片用完，因为操作系统要防止一个线程或者进程长时间占用CPU导致其他线程或者进程饿死。
> * 调用了阻塞类型的系统中断，比如请求IO，线程被阻塞。
> * 被终止或结束运行
> 
> 这其中前三种都会发生线程切换，线程切换意味着需要保存当前线程的上下文，留待线程下次占用CPU的时候恢复现场。并加载下一个将要占用CPU的线程上下文。这就是所谓的上下文切换。
> 
> 上下文切换是现代操作系统的基本功能，因其每次需要保存信息恢复信息，这将会占用CPU，内存等系统资源进行处理，也就意味着效率会有一定损耗，如果频繁切换就会造成整体效率低下。

感谢 @VinterHe  的帮忙完善！非常感谢！💐
