### ISSUE TITLE
Kafka常见面试题总结 发布-订阅模型 图错了

### ISSUE THREAD

**Issue by yxudong** [Snailclimb/JavaGuide#1266]
Kafka常见面试题总结.md 中发布-订阅模型那里

> 发布-订阅模型主要是为了解决队列模型存在的问题。

下面的图中，仍然标着队列模型，而不是发布-订阅模型

https://camo.githubusercontent.com/365a3daadb2f440c2b20db8a47a147ec0ead6be82652c6b924ae7e81b2c4d130/68747470733a2f2f6d792d626c6f672d746f2d7573652e6f73732d636e2d6265696a696e672e616c6979756e63732e636f6d2f323031392d31312f25453525423925424625453625393225414425453625413825413125453525394525384232313331322e706e67

**Comment by Snailclimb** [comment]
> Kafka常见面试题总结.md 中发布-订阅模型那里
> 
> > 发布-订阅模型主要是为了解决队列模型存在的问题。
> 
> 下面的图中，仍然标着队列模型，而不是发布-订阅模型
> 
> https://camo.githubusercontent.com/365a3daadb2f440c2b20db8a47a147ec0ead6be82652c6b924ae7e81b2c4d130/68747470733a2f2f6d792d626c6f672d746f2d7573652e6f73732d636e2d6265696a696e672e616c6979756e63732e636f6d2f323031392d31312f25453525423925424625453625393225414425453625413825413125453525394525384232313331322e706e67

感谢指出，已经处理：https://github.com/Snailclimb/JavaGuide/commit/450df55ce018b4008d743c213adfb43154f06bf7
