### ISSUE TITLE
v4.0-JavaGuide面试突击版.pdf 阅读“Arraylist 与 LinkedList 区别”时发现的小问题

### ISSUE THREAD

**Issue by NeroArc** [Snailclimb/JavaGuide#1269]
PDF中方法名出现缺失。而网页中则正常都有。不知道7月更新的版本中是否已修复
![image](https://user-images.githubusercontent.com/49861997/124731848-33385780-df45-11eb-812c-33021a05ceff.png)
![image](https://user-images.githubusercontent.com/49861997/124732045-67137d00-df45-11eb-9460-6ceb0affb773.png)

**Comment by Snailclimb** [comment]
> PDF中方法名出现缺失。而网页中则正常都有。不知道7月更新的版本中是否已修复
> ![image](https://user-images.githubusercontent.com/49861997/124731848-33385780-df45-11eb-812c-33021a05ceff.png)
> ![image](https://user-images.githubusercontent.com/49861997/124732045-67137d00-df45-11eb-9460-6ceb0affb773.png)

👍
