### ISSUE TITLE
增加MVCC相关内容

### ISSUE THREAD

**Issue by ddmcc** [Snailclimb/JavaGuide#1271]
看了下数据库这块内容好像没有mvcc的，希望能补充一下

- innodb对MVCC的实现
- 在RC、RR级别下的区别

如果这部分内容是还没有且可以的话，我可以尝试一下...

**Comment by Snailclimb** [comment]
> 看了下数据库这块内容好像没有mvcc的，希望能补充一下
> 
> * innodb对MVCC的实现
> * 在RC、RR级别下的区别
> 
> 如果这部分内容是还没有且可以的话，我可以尝试一下...

![image](https://user-images.githubusercontent.com/29880145/125478892-898baa5f-87ba-4a84-9b6b-fe2305afb64c.png)

👍你可以就innodb对MVCC的实现这个主题写一篇文章，有兴趣尝试下不？

**Comment by ddmcc** [comment]
> > 看了下数据库这块内容好像没有mvcc的，希望能补充一下
> > 
> > * innodb对MVCC的实现
> > * 在RC、RR级别下的区别
> > 
> > 如果这部分内容是还没有且可以的话，我可以尝试一下...
> 
> ![image](https://user-images.githubusercontent.com/29880145/125478892-898baa5f-87ba-4a84-9b6b-fe2305afb64c.png)
> 
> 👍你可以就innodb对MVCC的实现这个主题写一篇文章，有兴趣尝试下不？

嗯，可以尝试下。我认领了～

**Comment by Snailclimb** [comment]
> > > 看了下数据库这块内容好像没有mvcc的，希望能补充一下
> > > 
> > > * innodb对MVCC的实现
> > > * 在RC、RR级别下的区别
> > > 
> > > 如果这部分内容是还没有且可以的话，我可以尝试一下...
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/29880145/125478892-898baa5f-87ba-4a84-9b6b-fe2305afb64c.png)
> > 👍你可以就innodb对MVCC的实现这个主题写一篇文章，有兴趣尝试下不？
> 
> 嗯，可以尝试下。我认领了～

赞赞赞！这几天搬家都没回复老哥，不好意思啊~

**Comment by ddmcc** [comment]
> > > > 看了下数据库这块内容好像没有mvcc的，希望能补充一下
> > > > 
> > > > * innodb对MVCC的实现
> > > > * 在RC、RR级别下的区别
> > > > 
> > > > 如果这部分内容是还没有且可以的话，我可以尝试一下...
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/29880145/125478892-898baa5f-87ba-4a84-9b6b-fe2305afb64c.png)
> > > 👍你可以就innodb对MVCC的实现这个主题写一篇文章，有兴趣尝试下不？
> > 
> > 
> > 嗯，可以尝试下。我认领了～
> 
> 赞赞赞！这几天搬家都没回复老哥，不好意思啊~

哈哈，多谢Guide哥～
