### ISSUE TITLE
redis篇里面许多图片都失效了

### ISSUE THREAD

**Issue by Strong-bb** [Snailclimb/JavaGuide#1276]
希望能够及时补充一下 感谢🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏

**Comment by Strong-bb** [comment]
可以修改下hosts文件 加入如下内容 就能显示了

``# GitHub Start
140.82.113.4       github.com
140.82.114.20      gist.github.com

151.101.184.133    assets-cdn.github.com
151.101.184.133    raw.githubusercontent.com
151.101.184.133    gist.githubusercontent.com
151.101.184.133    cloud.githubusercontent.com
151.101.184.133    camo.githubusercontent.com
151.101.184.133    avatars0.githubusercontent.com
199.232.68.133     avatars0.githubusercontent.com
199.232.28.133     avatars1.githubusercontent.com
151.101.184.133    avatars1.githubusercontent.com
151.101.184.133    avatars2.githubusercontent.com
199.232.28.133     avatars2.githubusercontent.com
151.101.184.133    avatars3.githubusercontent.com
199.232.68.133     avatars3.githubusercontent.com
151.101.184.133    avatars4.githubusercontent.com
199.232.68.133     avatars4.githubusercontent.com
151.101.184.133    avatars5.githubusercontent.com
199.232.68.133     avatars5.githubusercontent.com
151.101.184.133    avatars6.githubusercontent.com
199.232.68.133     avatars6.githubusercontent.com
151.101.184.133    avatars7.githubusercontent.com
199.232.68.133     avatars7.githubusercontent.com
151.101.184.133    avatars8.githubusercontent.com
199.232.68.133     avatars8.githubusercontent.com

# GitHub End`

`

**Comment by yagamilighttuski** [comment]
k

lumpm


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月14日(周三) 中午11:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Snailclimb/JavaGuide] redis篇里面许多图片都失效了 (#1276)




 
希望能够及时补充一下 感谢
 
&mdash;
