### ISSUE TITLE
项目推荐 【📚JVM底层原理解析】

### ISSUE THREAD

**Issue by shaoxiongdu** [Snailclimb/JavaGuide#1283]
- 项目地址：https://github.com/shaoxiongdu/JVMStudy

- 类别：Java

- 项目后续更新计划： 正在持续更新！

- 项目描述：
  - JVM 底层原理解析 + 面试的知识点整理
  - 可以让大家理解到JVM底层是如何运行的，类加载机制，以及执行引擎的内部底层原理

- 推荐理由：有详细的图示和文档说明  并且标出了参考的官方规范地址便于查证

- 截图：
- ![image-20210720213009479](https://gitee.com/ShaoxiongDu/imageBed/raw/master//images/image-20210720213009479.png)
- ![image-20210720213047701](https://gitee.com/ShaoxiongDu/imageBed/raw/master//images/image-20210720213047701.png)
- ![image-20210720213112938](https://gitee.com/ShaoxiongDu/imageBed/raw/master//images/image-20210720213112938.png)

**Comment by Snailclimb** [comment]
> * https://github.com/shaoxiongdu/JVMStudy

赞 有些章节内容好像还没写完呢

**Comment by shaoxiongdu** [comment]
目前正在更新 🔹
