### ISSUE TITLE
【项目自荐】: ❤️基于Springboot个人博客

### ISSUE THREAD

**Issue by shaoxiongdu** [Snailclimb/JavaGuide#1284]
## 一个基于SpringBoot的简洁优雅的个人博客

- 项目地址：https://github.com/shaoxiongdu/blog
- 在线演示地址: http://blog.shaoxiongdu.cn

- ![image-20210721105046249](https://gitee.com/ShaoxiongDu/imageBed/raw/master//images/image-20210721105046249.png)
- ![image-20210721105128027](https://gitee.com/ShaoxiongDu/imageBed/raw/master//images/image-20210721105128027.png)
-

**Comment by Snailclimb** [comment]
> ## 一个基于SpringBoot的简洁优雅的个人博客
> * 项目地址：https://github.com/shaoxiongdu/blog
> * 在线演示地址: http://www.shaoxiongdu.cn
> * ![image-20210721105046249](https://camo.githubusercontent.com/a00b1bb1ceb47a934c23c5f03d980dc25aff32e45af0481b01e922439892da6d/68747470733a2f2f67697465652e636f6d2f5368616f78696f6e6744752f696d6167654265642f7261772f6d61737465722f2f696d616765732f696d6167652d32303231303732313130353034363234392e706e67)
> * ![image-20210721105128027](https://camo.githubusercontent.com/5c3016eccf6509180b3d8e9f1512d4ab674f6c1b5a20d08933c380a2d952cc3c/68747470733a2f2f67697465652e636f6d2f5368616f78696f6e6744752f696d6167654265642f7261772f6d61737465722f2f696d616765732f696d6167652d32303231303732313130353132383032372e706e67)

项目预览好像挂掉了

**Comment by shaoxiongdu** [comment]
> > ## 一个基于SpringBoot的简洁优雅的个人博客
> > 
> > * 项目地址：https://github.com/shaoxiongdu/blog
> > * 在线演示地址: http://www.shaoxiongdu.cn
> > * ![image-20210721105046249](https://camo.githubusercontent.com/a00b1bb1ceb47a934c23c5f03d980dc25aff32e45af0481b01e922439892da6d/68747470733a2f2f67697465652e636f6d2f5368616f78696f6e6744752f696d6167654265642f7261772f6d61737465722f2f696d616765732f696d6167652d32303231303732313130353034363234392e706e67)
> > * ![image-20210721105128027](https://camo.githubusercontent.com/5c3016eccf6509180b3d8e9f1512d4ab674f6c1b5a20d08933c380a2d952cc3c/68747470733a2f2f67697465652e636f6d2f5368616f78696f6e6744752f696d6167654265642f7261772f6d61737465722f2f696d616765732f696d6167652d32303231303732313130353132383032372e706e67)
> 
> 项目预览好像挂掉了

抱歉  忘记配置DNS解析了   现在可以了 🛩️
