### ISSUE TITLE
Github技巧.md 一些拼写问题

### ISSUE THREAD

**Issue by anaer** [Snailclimb/JavaGuide#1287]
![image](https://user-images.githubusercontent.com/4637100/126732895-ed5e93c3-2523-4a4e-88f3-0deb7ef55f30.png)
![image](https://user-images.githubusercontent.com/4637100/126732932-3b93f281-3d3a-43fb-8a02-4f9c6cdd944c.png)
![image](https://user-images.githubusercontent.com/4637100/126732977-62c799ef-9a4b-4355-b2c7-8f440a7237b4.png)

**Comment by Snailclimb** [comment]
感谢，已经修正！👍
