### ISSUE TITLE
关于Zookeeper的CAP问题

### ISSUE THREAD

**Issue by Vector6662** [Snailclimb/JavaGuide#1288]
在[CAP理论](https://github.com/Snailclimb/JavaGuide/blob/master/docs/system-design/distributed-system/CAP%E7%90%86%E8%AE%BA.md)中提到Zookeeper：

> ZooKeeper 保证的是 CP。 任何时刻对 ZooKeeper 的读请求都能得到一致性的结果，...

严格来说，似乎Zookeeper并不能保证CP，它对读请求只保证高可用性，并不保证每次读取返回的都是最新的数据，即不保证线性一致性。但是对于写请求是线性一致的，牺牲了部分可用性。
虽然Zookee也采用了一些手段来弥补读请求的一致性缺陷，比如同步操作，但是这并不推荐，因为这是一个耗费leader时间的操作。

观点来源于MIT6.824课程Lecture 8，中文版本可参考[这里](https://mit-public-courses-cn-translatio.gitbook.io/mit6-824/lecture-08-zookeeper/8.5)。

> 学生提问：那么Zookeeper究竟是不是线性一致呢？
Robert教授：我认为Zookeeper不是线性一致的，但是又不是完全的非线性一致。首先，所有客户端发送的请求以一个特定的序列执行，所以，某种意义上来说，所有的写请求是线性一致的。同时，每一个客户端的所有请求或许也可以认为是线性一致的。尽管我不是很确定，Zookeeper的一致性保证的第二条可以理解为，单个客户端的请求是线性一致的。

**Comment by Snailclimb** [comment]
> ZooKeeper

嗯嗯 stackoverflow 上面也有一个类似的回答：https://stackoverflow.com/a/44845275
