### ISSUE TITLE
关于图数据结构中的勘误

### ISSUE THREAD

**Issue by lzhaoyang** [Snailclimb/JavaGuide#1289]
![image](https://user-images.githubusercontent.com/14249262/126863880-fa15ba8a-e98c-43c9-ada0-17c197c1c0da.png)
这里应该是图的结构关系是随机的吧，希望大佬修改一下

**Comment by Snailclimb** [comment]
已近修改哈~感谢指出👍 这种小问题建议直接PR哈！
