### ISSUE TITLE
MySQL 基础 持久性 英语拼写出错

### ISSUE THREAD

**Issue by dddrecall** [Snailclimb/JavaGuide#1291]
![image](https://user-images.githubusercontent.com/8815759/126892516-cf0964e9-1c75-4232-9e0c-68f0a7a6aea7.png)

**Durabilily**
**Durability**

https://github.com/Snailclimb/JavaGuide/blob/master/docs/database/MySQL.md

**Comment by kaka2634** [comment]
是的，你没看错 :thumbsup:

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/8815759/126892516-cf0964e9-1c75-4232-9e0c-68f0a7a6aea7.png)
> 
> **Durabilily**
> **Durability**
> 
> https://github.com/Snailclimb/JavaGuide/blob/master/docs/database/MySQL.md

感谢👍 这种小问题的话，下次可以直接提交PR哈
