### ISSUE TITLE
关于线程池ThreadPoolExcutor

### ISSUE THREAD

**Issue by 727729853** [Snailclimb/JavaGuide#1301]
![image](https://user-images.githubusercontent.com/60378045/127742114-6132771e-6bb4-486a-b2dc-764d3eec8b3b.png)

问题：文中提到每次执行5个任务，只有这5个任务都执行完毕后，才会执行后5个。

实际：通过测试发现，实际上并不是这样的。每当有任务执行完毕，就会执行下一个了。
![image](https://user-images.githubusercontent.com/60378045/127742150-abd3a8c7-d5c8-4a30-b51d-fbe74a7de901.png)

**Comment by kaka2634** [comment]
同看到这一段，从文中的测试结果来看，是这5个任务执行完了，后面的5个才被执行，应该碰巧是线程调度的时机不同刚好形成这样测试结果。

实际上确实跟你表述的一样，只要有线程运行结束退出，等待队列中的线程就会立刻补上，但还是保持同时运行5个线程。

我想文中提出的思考应该是为什么每次同时运行最多是5个线程，而不是设置的最大10个线程。这块可以再明确一下，不然确实会让人有误解。

**Comment by Snailclimb** [comment]
> java线程池学习总结 - 4.2 线程池原理分析

感谢老哥！节省了我不少事👍
