### ISSUE TITLE
关于redis的aof持久化

### ISSUE THREAD

**Issue by sunseeker0011** [Snailclimb/JavaGuide#1302]
原文：
开启 AOF 持久化后每执行一条会更改 Redis 中的数据的命令，Redis 就会将该命令写入硬盘中的 AOF 文件。AOF 文件的保存位置和 RDB 文件的位置相同，都是通过 dir 参数设置的，默认的文件名是 appendonly.aof。

在 Redis 的配置文件中存在三种不同的 AOF 持久化方式，它们分别是：

appendfsync always    #每次有数据修改发生时都会写入AOF文件,这样会严重降低Redis的速度
appendfsync everysec  #每秒钟同步一次，显示地将多个写命令同步到硬盘
appendfsync no        #让操作系统决定何时进行同步
---------------------------------------------------------------------------
个人愚见是redis先将命令写入缓存中，然后根据以下三种策略，刷新到磁盘上面

**Comment by Snailclimb** [comment]
> 原文：
> 开启 AOF 持久化后每执行一条会更改 Redis 中的数据的命令，Redis 就会将该命令写入硬盘中的 AOF 文件。AOF 文件的保存位置和 RDB 文件的位置相同，都是通过 dir 参数设置的，默认的文件名是 appendonly.aof。
> 
> 在 Redis 的配置文件中存在三种不同的 AOF 持久化方式，它们分别是：
> 
> ## appendfsync always #每次有数据修改发生时都会写入AOF文件,这样会严重降低Redis的速度
> appendfsync everysec #每秒钟同步一次，显示地将多个写命令同步到硬盘
> appendfsync no #让操作系统决定何时进行同步
> 个人愚见是redis先将命令写入缓存中，然后根据以下三种策略，刷新到磁盘上面

对的！我这块描述有点欠缺准确性。正确的表达应该是:

开启 AOF 持久化后每执行一条会更改 Redis 中的数据的命令，Redis 就会将该命令写入到内存缓存 `server.aof_buf` 中，然后再根据 `appendfsync` 配置来决定何时将其同步到硬盘中的 AOF 文件。

AOF 文件的保存位置和 RDB 文件的位置相同，都是通过 dir 参数设置的，默认的文件名是 `appendonly.aof`。
