### ISSUE TITLE
补充静态方法

### ISSUE THREAD

**Issue by curiositer** [Snailclimb/JavaGuide#1304]
在以下的部分，参照first head java p277，添加一点自己的理解（加粗部分）。

### 静态方法和实例方法有何不同？
在外部调用静态方法时，可以使用"类名.方法名"的方式，也可以使用"对象名.方法名"的方式 **（实际都是第一种方法，而且编译器也会提示不建议用实例化的对象来访问静态方法）**。而实例方法只有后面这种方式。也就是说，调用静态方法可以无需创建对象。

静态方法在访问本类的成员时，只允许访问静态成员（即静态成员变量和静态方法），而不允许访问实例成员变量和实例方法 **（静态方法实际通过类名来调用，无法引用到该类的任何实例变量，也不会知道用哪个实例变量值）**；实例方法则无此限制。

**Comment by Snailclimb** [comment]
> 在以下的部分，参照first head java p277，添加一点自己的理解（加粗部分）。
> 
> ### 静态方法和实例方法有何不同？
> 在外部调用静态方法时，可以使用"类名.方法名"的方式，也可以使用"对象名.方法名"的方式 **（实际都是第一种方法，而且编译器也会提示不建议用实例化的对象来访问静态方法）**。而实例方法只有后面这种方式。也就是说，调用静态方法可以无需创建对象。
> 
> 静态方法在访问本类的成员时，只允许访问静态成员（即静态成员变量和静态方法），而不允许访问实例成员变量和实例方法 **（静态方法实际通过类名来调用，无法引用到该类的任何实例变量，也不会知道用哪个实例变量值）**；实例方法则无此限制。

感谢补充!已经完善~
