### ISSUE TITLE
令牌桶算法：描述与图不一致

### ISSUE THREAD

**Issue by chenxiangzZ** [Snailclimb/JavaGuide#1313]
![image](https://user-images.githubusercontent.com/30611183/128805005-e0ac1791-ac81-4762-aa9e-46b74e27124a.png)
令牌桶中按速率加入的是请求还是令牌啊

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/30611183/128805005-e0ac1791-ac81-4762-aa9e-46b74e27124a.png)
> 令牌桶中按速率加入的是请求还是令牌啊
请求在被处理之前需要拿到一个令牌，请求处理完毕之后将这个令牌丢弃（删除）。
我们根据限流大小，按照一定的速率往桶里添加令牌。
