### ISSUE TITLE
Java容器常见问题 补充 Queue 部分

### ISSUE THREAD

**Issue by kaka2634** [Snailclimb/JavaGuide#1317]
最近在学习Java集合，看到 [Java集合框架常见面试题.md](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.md) 里面只针对List, Set, Map 进行讲解，在图中有提到Queue，但后序并没有相应的介绍。

如果需要增加这部分内容，我想认领这个部分，利用周末时间总结一下，目前的想做的改动包括：
1. 修改[Java 概览](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.md#111-java-%E9%9B%86%E5%90%88%E6%A6%82%E8%A7%88)中的图片，增加Map 部分示意图

2. 增加子章节Collection子接口之Queue 
    - Queue 与 Deque 的区别
    - LinkedList 与 ArrayDeque 的区别
    - 说一说 PriorityQueue 

看看有什么其他建议？

**Comment by Snailclimb** [comment]
> 最近在学习Java集合，看到 [Java集合框架常见面试题.md](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.md) 里面只针对List, Set, Map 进行讲解，在图中有提到Queue，但后序并没有相应的介绍。
> 
> 如果需要增加这部分内容，我想认领这个部分，利用周末时间总结一下，目前的想做的改动包括：
> 
> 1. 修改[Java 概览](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.md#111-java-%E9%9B%86%E5%90%88%E6%A6%82%E8%A7%88)中的图片，增加Map 部分示意图
> 2. 增加子章节Collection子接口之Queue
>    
>    * Queue 与 Deque 的区别
>    * LinkedList 与 ArrayDeque 的区别
>    * 说一说 PriorityQueue
> 
> 看看有什么其他建议？

嗯嗯，非常不错啊! BlockingQueue和ConcurrentLinkedQueue不用介绍了，我在并发容器那一节有提到。
