### ISSUE TITLE
关于JavaGuide/docs/java/basis/代理模式详解.md

### ISSUE THREAD

**Issue by zzzfwd** [Snailclimb/JavaGuide#1319]
![image](https://user-images.githubusercontent.com/48471795/129131889-ac99d623-296d-4662-a109-e8c9b356817a.png)
这里的参数o应该是指代理对象吧

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/48471795/129131889-ac99d623-296d-4662-a109-e8c9b356817a.png)
> 这里的参数o应该是指代理对象吧

嗯嗯  这里应该是代理对象
