### ISSUE TITLE
redis章节补充

### ISSUE THREAD

**Issue by sophie0909** [Snailclimb/JavaGuide#1366]
redis章节缺少，redis持久化策略，内存淘汰策略，主从复制原理，redis集群。缓存穿透，缓存雪崩，缓存击穿等的说明

**Comment by anaer** [comment]
https://github.com/Snailclimb/JavaGuide/blob/master/docs/database/Redis/redis-all.md

**Comment by Snailclimb** [comment]
> redis章节缺少，redis持久化策略，内存淘汰策略，主从复制原理，redis集群。缓存穿透，缓存雪崩，缓存击穿等的说明
https://github.com/Snailclimb/JavaGuide/blob/master/docs/database/Redis/redis-all.md
![image](https://user-images.githubusercontent.com/29880145/132353936-865de23a-34c0-4352-aaac-7d68a8ab5fa1.png)
