### ISSUE TITLE
Java基础知识 (Oracle JDK 和 OpenJDK 的对比)修改

### ISSUE THREAD

**Issue by schrodog** [Snailclimb/JavaGuide#138]
由於OracleJDK 已經要收費， OpenJDK 將成為很多公司首選， "OpenJDK不太受欢迎" 將不再正確。 請更新對比

**Comment by zxj5470** [comment]
> 顶级公司正在使用Oracle JDK，例如Android Studio，Minecraft和IntelliJ IDEA开发工具，其中Open JDK不太受欢迎；

还有一个问题（ IntelliJ IDEA 的 JRE 用的是 Jetbrains 自己魔改的 OpenJDK

**Comment by Snailclimb** [comment]
感谢 已经更正！
