### ISSUE TITLE
关于数据库ACID特性中的一致性（Consistency）的疑问

### ISSUE THREAD

**Issue by Qiwenlii** [Snailclimb/JavaGuide#1382]
在Mysql这篇总结中（https://github.com/Snailclimb/JavaGuide/blob/master/docs/database/mysql/MySQL总结.md ）
提到了一致性的定义为：一致性（Consistency）： 执行事务前后，数据保持一致，例如转账业务中，无论事务是否成功，转账者和收款人的总额应该是不变的；
但是通过我查阅的资料以及学校老师的讲解，应为：It satisfies the integrity constraints on the database at the transaction's boundaries， 我的理解为，向数据库写入的任何数据都应该满足数据库的完整性约束； 这与数据是否保持一致是无关的。

**Comment by gengxiz** [comment]
我理解是像质量守恒定律那样，在一个环境内，能量的转移，但整体来看没有增减

**Comment by JavaJike** [comment]
> 我理解是像质量守恒定律那样，在一个环境内，能量的转移，但整体来看没有增减

理解很到位
