### ISSUE TITLE
完全二叉树的图示错误

### ISSUE THREAD

**Issue by 2293736867** [Snailclimb/JavaGuide#1391]
链接在[此处](https://snailclimb.gitee.io/javaguide/#/docs/cs-basics/data-structure/%E6%A0%91)。

![](https://img-blog.csdnimg.cn/303e01840f6d471e82438d6bb41146ec.png)

如果是完全二叉树的话，8应该是3的右孩子。

**Comment by Snailclimb** [comment]
> 链接在[此处](https://snailclimb.gitee.io/javaguide/#/docs/cs-basics/data-structure/%E6%A0%91)。
> 
> ![](https://camo.githubusercontent.com/5292af16acb8c036f446ffc4c61aff087265f854800cf8238bd7c8b7683b3a8d/68747470733a2f2f696d672d626c6f672e6373646e696d672e636e2f33303365303138343066366434373165383234333864366262343131343665632e706e67)
> 
> 如果是完全二叉树的话，8应该是3的右孩子。

感谢指出👍
