### ISSUE TITLE
Kafka面试题总结中有关partition的部分

### ISSUE THREAD

**Issue by workingonescape** [Snailclimb/JavaGuide#1408]
![image-20210920230959243](https://gitee.com/workingonescape/typora_images/raw/master/image-20210920230959243.png)

**Kafka 只能为我们保证 Partition(分区) 中的消息有序，而不能保证 Topic(主题) 中的 Partition(分区) 的有序。** 这句话语句不通，而且容易让人迷惑，建议修改为，**Kafka 只能保证单个 Partition(分区) 中的消息是有序的，这个是通过offset来实现的。**

**Comment by Snailclimb** [comment]
> Kafka 只能为我们保证 Partition(分区)

已完善👍
