### ISSUE TITLE
容器篇中对于HashMap遍历方式的说明存在部分错误

### ISSUE THREAD

**Issue by houtaroy** [Snailclimb/JavaGuide#1411]
[1.5.8. HashMap 有哪几种常见的遍历方式?](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.md#158-hashmap-%E6%9C%89%E5%93%AA%E5%87%A0%E7%A7%8D%E5%B8%B8%E8%A7%81%E7%9A%84%E9%81%8D%E5%8E%86%E6%96%B9%E5%BC%8F)

此处引用公众号文章中, 对于parallelStream遍历方式的性能分析有误

先说结论, 存在阻塞时parallelStream性能最高, 非阻塞时parallelStream性能最低

当遍历不存在阻塞时, parallelStream的性能是最低的:

```
Benchmark               Mode  Cnt     Score      Error  Units
Test.entrySet           avgt    5   288.651 ±   10.536  ns/op
Test.keySet             avgt    5   584.594 ±   21.431  ns/op
Test.lambda             avgt    5   221.791 ±   10.198  ns/op
Test.parallelStream     avgt    5  6919.163 ± 1116.139  ns/op
```

加入阻塞代码`Thread.sleep(10)`后, parallelStream的性能才是最高的:

```
Benchmark               Mode  Cnt           Score          Error  Units
Test.entrySet           avgt    5  1554828440.000 ± 23657748.653  ns/op
Test.keySet             avgt    5  1550612500.000 ±  6474562.858  ns/op
Test.lambda             avgt    5  1551065180.000 ± 19164407.426  ns/op
Test.parallelStream     avgt    5   186345456.667 ±  3210435.590  ns/op
```

**Comment by Ahaola** [comment]
good
