### ISSUE TITLE
MySQL章节大表优化中使用MySQL本身的缓存不太认可

### ISSUE THREAD

**Issue by liverrrr** [Snailclimb/JavaGuide#143]
如果我理解没错的话，使用MySQL本身的缓存会存在缓存失效的问题。只要修改了表，这张表的缓存就会失效，在大量读的场景下，这个失效问题比较严重，而且MySQL8.0版本已经取消MySQL的缓存模块了。

**Comment by ming-jock** [comment]
是的，只要一有update动作，那么缓存就会被清空，8.0里面这个功能已经被去掉了

**Comment by Snailclimb** [comment]
已经更正！感谢！
