### ISSUE TITLE
StringBuffer，StringBuilder 中的描述问题

### ISSUE THREAD

**Issue by debugjoker** [Snailclimb/JavaGuide#1434]
原文如下：
> 补充（来自[issue 675](https://github.com/Snailclimb/JavaGuide/issues/675)）：在 Java 9 之后，String 、`StringBuilder` 与 `StringBuffer` 的实现改用 byte 数组存储字符串 `private final byte[] value`

源码中的变量是改用了byte数组，但是不是final修饰的啊，写错了吧这里
```java
    /**
     * The value is used for character storage.
     */
    byte[] value;

    /**
     * The id of the encoding used to encode the bytes in {@code value}.
     */
    byte coder;

    /**
     * The count is the number of characters used.
     */
    int count;

    private static final byte[] EMPTYVALUE = new byte[0];
```

**Comment by ckxxm** [comment]
> 这描述的有歧义，建议改成下面这样
> 
> > String 、StringBuilder 与 StringBuffer 的底层实现均改用 byte 数组存储字符串
> 
> 只有String底层是final修饰，StringBuilder 与 StringBuffer 没有，容易歧义

博主对String的描述应该是默认基于1.8版本的，毕竟现在绝大多数企业商用的是这个版本，此处可以标注说明一下版本。至于对JDK 9中的变化，issuer 可以单独补充特性进行说明。

**Comment by Snailclimb** [comment]
> 原文如下：
> 
> > 补充（来自[issue 675](https://github.com/Snailclimb/JavaGuide/issues/675)）：在 Java 9 之后，String 、`StringBuilder` 与 `StringBuffer` 的实现改用 byte 数组存储字符串 `private final byte[] value`
> 
> 源码中的变量是改用了byte数组，但是不是final修饰的啊，写错了吧这里
> 
> ```java
>     /**
>      * The value is used for character storage.
>      */
>     byte[] value;
> 
>     /**
>      * The id of the encoding used to encode the bytes in {@code value}.
>      */
>     byte coder;
> 
>     /**
>      * The count is the number of characters used.
>      */
>     int count;
> 
>     private static final byte[] EMPTYVALUE = new byte[0];
> ```

已经修复👍
