### ISSUE TITLE
JVM垃圾回收这一章中的标记-复制算法

### ISSUE THREAD

**Issue by xjlgod** [Snailclimb/JavaGuide#1438]
标记-复制算法其实应该是复制算法，它并没有标记这一过程，这样是否会误导读者

**Comment by Snailclimb** [comment]
> 标记-复制算法其实应该是复制算法，它并没有标记这一过程，这样是否会误导读者


![](https://user-images.githubusercontent.com/29880145/141952067-aeac4d6f-3c3c-47ff-a76e-2e6fcb5d82ae.png)
