### ISSUE TITLE
CAP理论中的对AP实现的讲解问题

### ISSUE THREAD

**Issue by xjlgod** [Snailclimb/JavaGuide#1442]
原文为：

为啥不可能选择 CA 架构呢？ 举个例子：若系统出现“分区”，系统中的某个节点在进行写操作。为了保证 C， 必须要禁止其他节点的读写操作，这就和 A 发生冲突了。如果为了保证 A，其他节点的读写操作正常的话，那就和 C 发生冲突了。

guide哥的参考文献中的原文为

如果选择了CA而放弃了P，若发生分区现象，为了保证C，系统需要禁止写入，此时就与A发生冲突，如果是为了保证A，则会出现正常的分区可以写入数据，有故障的分区不能写入数据，则与C就冲突了。因此分布式系统理论上不可能选择CA架构，而必须选择CP或AP架构。

我觉得guide哥的参考文献的说的才是对的，是这样吗？

**Comment by Snailclimb** [comment]
> 为啥不可能选择 CA 架构呢？

表达的意思是一样的。
