### ISSUE TITLE
谢希仁老师的《计算机网络》内容总结.md， typo 较多

### ISSUE THREAD

**Issue by acflameking** [Snailclimb/JavaGuide#1443]
本篇总结只能说错别字有点多了，第一遍看下去简直令人反感，根本没有读下去的愿望，当然我能体会作者维护的艰难，其中我对一些显而易见的错误进行了更改，稍后提交 PR，同时这篇文章我觉得作者有必要再精致精致🧐。

**Comment by acflameking** [comment]
改动较多，同时对一些语句不通顺的地方做了修改，Guide哥可以检查一下

**Comment by Snailclimb** [comment]
> 本篇总结只能说错别字有点多了，第一遍看下去简直令人反感，根本没有读下去的愿望，当然我能体会作者维护的艰难，其中我对一些显而易见的错误进行了更改，稍后提交 PR，同时这篇文章我觉得作者有必要再精致精致🧐。

看到啦！太感谢了👍

**Comment by Snailclimb** [comment]
> 改动较多，同时对一些语句不通顺的地方做了修改，Guide哥可以检查一下

嗯嗯 这还是我大学那会对着书总结的，期待你的继续完善👍
