### ISSUE TITLE
java内存区域4.1节里面举例有误

### ISSUE THREAD

**Issue by climbL** [Snailclimb/JavaGuide#1445]
``` java
final String str1 = "str";
final String str2 = getStr();
String c = "str" + "str2";// 常量池中的对象（此处应该是"str"+"ing"，不过可以意会: D）
String d = str1 + str2; // **常量池中的对象**    —— 此处应该是堆上创建新的对象
System.out.println(c == d);// false
public static String getStr() {
      return "ing";
}
```

测试类：
``` java
public class Main1 {
    public static void main(String[] args) {
        final String str1 = "hello";
        final String str2 = getStr();
        String d = str1 + str2;
    }

    public static String getStr() {
        return "world";
    }
}
```

对应的二进制文件：
![image](https://user-images.githubusercontent.com/50400133/141082832-be152eaf-8f50-4c33-b462-95f437f61227.png)
可以看到二进制文件中使用StringBuilder调用append()，然后调用toString()。

**Comment by Snailclimb** [comment]
> ```java
>  d
> ```



> ```java
> final String str1 = "str";
> final String str2 = getStr();
> String c = "str" + "str2";// 常量池中的对象（此处应该是"str"+"ing"，不过可以意会: D）
> String d = str1 + str2; // **常量池中的对象**    —— 此处应该是堆上创建新的对象
> System.out.println(c == d);// false
> public static String getStr() {
>       return "ing";
> }
> ```
> 
> 测试类：
> 
> ```java
> public class Main1 {
>     public static void main(String[] args) {
>         final String str1 = "hello";
>         final String str2 = getStr();
>         String d = str1 + str2;
>     }
> 
>     public static String getStr() {
>         return "world";
>     }
> }
> ```
> 
> 对应的二进制文件： ![image](https://user-images.githubusercontent.com/50400133/141082832-be152eaf-8f50-4c33-b462-95f437f61227.png) 可以看到二进制文件中使用StringBuilder调用append()，然后调用toString()。

感谢指出！这里笔误了，抱歉。
