### ISSUE TITLE
Requesting a English Translated integration

### ISSUE THREAD

**Issue by FahimFBA** [Snailclimb/JavaGuide#1453]
Hello, your project can be a great asset globally if you could add a translation to English. As a student of Computer Science and Engineering background, I am hyped for this project repository of yours, but, sadly, there is not any translated part in English. Therefore, I am unable to go through this.

Please let me know whether you have any plan of adding English translation or not in the upcoming days.

**Comment by Snailclimb** [comment]
> 您好，如果您可以添加英语翻译，您的项目可以成为全球的重要资产。作为一名计算机科学与工程背景的学生，我对你的这个项目存储库大肆宣传，但遗憾的是，没有任何英文翻译部分。因此，我无法通过这个。
> 
> 请让我知道您是否有计划在未来几天内添加英文翻译。

Hello, the project is still in constant improvement and improvement, and we will consider translation when it is stable in the future. Thank you very much for your suggestion 👍 open source without borders, I hope we can receive the goods

**Comment by xingxing-prog** [comment]
Hello, your project will be an important asset if you add the English version. As an computer and engineer student, I would like to broadcast your project and its huge storage. Unfortunately, there is no English translation. Therefore, I can't get access to it. 

Please tell me whether you are going to add English version in few days.

**Comment by haro0san** [comment]
hellow
