### ISSUE TITLE
/cs-basics/data-structure/图 中 无权图和带权图下面的配图问题

### ISSUE THREAD

**Issue by Aaron-Ge** [Snailclimb/JavaGuide#1454]
![image](https://user-images.githubusercontent.com/22882546/142588972-5e5c7358-1615-4515-8aa1-a92342d0e9d8.png)
这英文说的是无向图和有向图,这图是有向图吗?

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/22882546/142588972-5e5c7358-1615-4515-8aa1-a92342d0e9d8.png) 这英文说的是无向图和有向图,这图是有向图吗?

感谢指出👍 已经更正。
![image](https://user-images.githubusercontent.com/29880145/143253229-40438cc8-8113-43dd-bb86-be10c000aa7f.png)
