### ISSUE TITLE
一处链接失效（通过源码一步一步分析 ArrayList 扩容机制）

### ISSUE THREAD

**Issue by wx98** [Snailclimb/JavaGuide#1457]
## 问题：
我在浏览到[java集合框架基础知识&面试题总结/#说一说-arraylist-的扩容机制吧](https://javaguide.cn/java/collection/java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86&%E9%9D%A2%E8%AF%95%E9%A2%98%E6%80%BB%E7%BB%93/#%E8%AF%B4%E4%B8%80%E8%AF%B4-arraylist-%E7%9A%84%E6%89%A9%E5%AE%B9%E6%9C%BA%E5%88%B6%E5%90%A7)时，发现此处有如下链接
>[通过源码一步一步分析 ArrayList 扩容机制](https://snailclimb.gitee.io/javaguide/#/docs/java/collection/ArrayList%E6%BA%90%E7%A0%81+%E6%89%A9%E5%AE%B9%E6%9C%BA%E5%88%B6%E5%88%86%E6%9E%90)
>
>![image](https://user-images.githubusercontent.com/33981111/142798659-2f55e998-fb50-4c91-bb57-1dec7fe21393.png)

访问后发现此链接文章已失效
>![image](https://user-images.githubusercontent.com/33981111/142798945-682b11df-652c-4ded-b808-7e5bb57e4f01.png)

## 建议:
在阅读失效链接网站[https://snailclimb.gitee.io/javaguide/#/](https://snailclimb.gitee.io/javaguide/#/)后，我发现文章[《ArrayList 源码+扩容机制分析 》](https://snailclimb.gitee.io/javaguide/#/docs/java/collection/arraylist-source-code)中内容与失效内容契合。      
故，我认为此处应改为
>`https://snailclimb.gitee.io/javaguide/#/docs/java/collection/arraylist-source-code?id=_2-arraylist-核心源码解读`
>```text
>https://snailclimb.gitee.io/javaguide/#/docs/java/collection/arraylist-source-code?id=_2-arraylist-%e6%a0%b8%e5%bf%83%e6%ba%90%e7%a0%81%e8%a7%a3%e8%af%bb
>```
>修改后链接：
>[通过源码一步一步分析 ArrayList 扩容机制](https://snailclimb.gitee.io/javaguide/#/docs/java/collection/arraylist-source-code?id=_2-arraylist-%e6%a0%b8%e5%bf%83%e6%ba%90%e7%a0%81%e8%a7%a3%e8%af%bb)

**Comment by Snailclimb** [comment]
> ## 问题：
> 我在浏览到[java集合框架基础知识&面试题总结/#说一说-arraylist-的扩容机制吧](https://javaguide.cn/java/collection/java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86&%E9%9D%A2%E8%AF%95%E9%A2%98%E6%80%BB%E7%BB%93/#%E8%AF%B4%E4%B8%80%E8%AF%B4-arraylist-%E7%9A%84%E6%89%A9%E5%AE%B9%E6%9C%BA%E5%88%B6%E5%90%A7)时，发现此处有如下链接
> 
> > [通过源码一步一步分析 ArrayList 扩容机制](https://snailclimb.gitee.io/javaguide/#/docs/java/collection/ArrayList%E6%BA%90%E7%A0%81+%E6%89%A9%E5%AE%B9%E6%9C%BA%E5%88%B6%E5%88%86%E6%9E%90)
> > ![image](https://user-images.githubusercontent.com/33981111/142798659-2f55e998-fb50-4c91-bb57-1dec7fe21393.png)
> 
> 访问后发现此链接文章已失效
> 
> > ![image](https://user-images.githubusercontent.com/33981111/142798945-682b11df-652c-4ded-b808-7e5bb57e4f01.png)
> 
> ## 建议:
> 在阅读失效链接网站https://snailclimb.gitee.io/javaguide/#/后，我发现文章[《ArrayList 源码+扩容机制分析 》](https://snailclimb.gitee.io/javaguide/#/docs/java/collection/arraylist-source-code)中内容与失效内容契合。 故，我认为此处应改为
> 
> > `https://snailclimb.gitee.io/javaguide/#/docs/java/collection/arraylist-source-code?id=_2-arraylist-核心源码解读`
> > ```
> > https://snailclimb.gitee.io/javaguide/#/docs/java/collection/arraylist-source-code?id=_2-arraylist-%e6%a0%b8%e5%bf%83%e6%ba%90%e7%a0%81%e8%a7%a3%e8%af%bb
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 修改后链接：
> > [通过源码一步一步分析 ArrayList 扩容机制](https://snailclimb.gitee.io/javaguide/#/docs/java/collection/arraylist-source-code?id=_2-arraylist-%e6%a0%b8%e5%bf%83%e6%ba%90%e7%a0%81%e8%a7%a3%e8%af%bb)

感谢👍已经合并您的pr~
