### ISSUE TITLE
面试突击markdown版本

### ISSUE THREAD

**Issue by cqboyone** [Snailclimb/JavaGuide#1459]
请问有markdown版本吗？pdf不好做标注和复制。

**Comment by Snailclimb** [comment]
> 请问有markdown版本吗？pdf不好做标注和复制。

直接把仓库克隆到本地，然后用 Typora 打开就可以啦！
![image](https://user-images.githubusercontent.com/29880145/143037343-969f746f-de46-4747-88c2-0b52cf907bc4.png)
