### ISSUE TITLE
接口和抽象类的区别是什么

### ISSUE THREAD

**Issue by raoyh** [Snailclimb/JavaGuide#146]
在JDK8中，接口也可以定义静态方法，可以直接用接口名调用。实现类和实现是不可以调用的。
如果同时实现两个接口，接口中定义了一样的默认方法，必须重写，不然会报错

**Comment by Snailclimb** [comment]
感谢您的回答！

**Comment by lanmeiniu** [comment]
关于抽象类
JDK 1.8以前，抽象类的方法默认访问权限为protected
JDK 1.8时，抽象类的方法默认访问权限变为default
关于接口
JDK 1.8以前，接口中的方法必须是public的
JDK 1.8时，接口中的方法可以是public的，也可以是default的
JDK 1.9时，接口中的方法可以是private的

**Comment by powerLeePlus** [comment]
jdk1.8后，接口方法可以有方法体，需要用default或static修饰。实现类无需重新。当然default方法重写也是可以的。如果一个类实现多个接口，多个接口有相同default方法，则子类必须重写该方法

**Comment by kalsp** [comment]
> 在JDK8中，接口也可以定义静态方法，可以直接用接口名调用。实现类和实现是不可以调用的。
> 如果同时实现两个接口，接口中定义了一样的默认方法，必须重写，不然会报错

实现接口的方法不重写肯定报错啊！！这无关乎有没有一样的方法，本就必须重写，谁能告诉上面到底想表达啥意思啊，如果两个同名方法返回值不同，这个就不是重写能解决的问题吧

**Comment by WangZhen-Ddm** [comment]
请问，在jdk1.8中
`public class HashMap<K,V> extends AbstractMap<K,V>
    implements Map<K,V>, Cloneable, Serializable`
HashMap继承了AbstractMap这一抽象类并实现了Map<>接口，为何其中的代码都未加@Override进行重写

**Comment by wangpeipei90** [comment]
@override 是annotation，貌似不是必须的

**Comment by chengweng** [comment]
> 
> 
> 请问，在jdk1.8中
> `public class HashMap<K,V> extends AbstractMap<K,V> implements Map<K,V>, Cloneable, Serializable`
> HashMap继承了AbstractMap这一抽象类并实现了Map<>接口，为何其中的代码都未加@override进行重写

看下@override它的源码
![图片](https://user-images.githubusercontent.com/26996504/80331414-98d98000-887a-11ea-87fd-c3a60cda60f9.png)
是SOURCE级别

**Comment by WangZhen-Ddm** [comment]
> > 请问，在jdk1.8中
> > `public class HashMap<K,V> extends AbstractMap<K,V> implements Map<K,V>, Cloneable, Serializable`
> > HashMap继承了AbstractMap这一抽象类并实现了Map<>接口，为何其中的代码都未加@override进行重写
> 
> 看下@override它的源码
> ![图片](https://user-images.githubusercontent.com/26996504/80331414-98d98000-887a-11ea-87fd-c3a60cda60f9.png)
> 是SOURCE级别

source级别的注解可以选择不加吗，class和runtime级别的注解是必须的吗

**Comment by Amuao** [comment]
> > > 请问，在jdk1.8中
> > > `public class HashMap<K,V> extends AbstractMap<K,V> implements Map<K,V>, Cloneable, Serializable`
> > > HashMap继承了AbstractMap这一抽象类并实现了Map<>接口，为何其中的代码都未加@override进行重写
> > 
> > 
> > 看下@override它的源码
> > ![图片](https://user-images.githubusercontent.com/26996504/80331414-98d98000-887a-11ea-87fd-c3a60cda60f9.png)
> > 是SOURCE级别
> 
> source级别的注解可以选择不加吗，class和runtime级别的注解是必须的吗

java的注解出现在Jdk1.5，而集合框架早在Jdk1.2就出现了，我觉得就是懒得加 专门去加这玩意干啥

**Comment by ryuhi** [comment]
> 
看下RetentionPolicy的源码
public enum RetentionPolicy {
    /**
     * Annotations are to be discarded by the compiler.
     */
    SOURCE,

注释是这样说的Annotations are to be discarded by the compiler.
意思是，SOURCE级别的注解会被compiler扔掉，也就是说编译后的代码里肯定是没有这个的。
至于@Override，为什么现在阿里规范里要求大家写，是因为这样在代码编译的时候，可以强制编译器去检查你的代码是不是符合Override的标准，把问题在编译期就抛出
