### ISSUE TITLE
"从ReentrantLock的实现看AQS的原理及应用"部分

### ISSUE THREAD

**Issue by nnniuzy** [Snailclimb/JavaGuide#1461]
在2.2节中非公平锁的示意图中，如果“CAS修改共享资源State成功”的话，应该不是获取锁失败吧。

**Comment by zjxjwxk** [comment]
我有同样的问题，不过这个图应该出自美团技术团队博客，我发给他们公众号了。
“2.2AQS重要方法与ReentrantLock的关联” 中的第一张流程图中右下方的 “(AQS)CAS修改共享资源State成功” 判断箭头引出的 “是” 和 “否” 是不是搞反了？而且如果是 “是” ，是不是应该连线到左上方的 “(AQS)setExclusiveOwnerThread” 呢？（这是我看JDK 1.8 中ReentrantLock 的实现得出的）

**Comment by KaKinWong** [comment]
> 我有同样的问题，不过这个图应该出自美团技术团队博客，我发给他们公众号了。 “2.2AQS重要方法与ReentrantLock的关联” 中的第一张流程图中右下方的 “(AQS)CAS修改共享资源State成功” 判断箭头引出的 “是” 和 “否” 是不是搞反了？而且如果是 “是” ，是不是应该连线到左上方的 “(AQS)setExclusiveOwnerThread” 呢？（这是我看JDK 1.8 中ReentrantLock 的实现得出的）

我读到此处的时候，结合Java 8 的源码看也有相同的疑问。请问你反馈给美团技术的公众号后，有得到回复吗？

**Comment by Snailclimb** [comment]
嗯嗯 这篇当时看着写的不错，就转载了一下。

![image](https://user-images.githubusercontent.com/29880145/147739033-5f2ab3f2-ea48-4841-b452-3ce9183b7c77.png)
