### ISSUE TITLE
文章内容中连接失效，《JavaGuide面试突击版》

### ISSUE THREAD

**Issue by z-ak-z** [Snailclimb/JavaGuide#1464]
文章内容中连接失效，《JavaGuide面试突击版》
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/69227310/143725375-8e9d4bed-83f7-4475-9f87-3d07e1d9d562.png">

**Comment by Snailclimb** [comment]
> 文章内容中连接失效，《JavaGuide面试突击版》 <img alt="image" width="1432" src="https://user-images.githubusercontent.com/69227310/143725375-8e9d4bed-83f7-4475-9f87-3d07e1d9d562.png">

感谢👍
