### ISSUE TITLE
一千行MySQL学习笔记中 SHOW DATABASES[ LIKE 'PATTERN'] 命令

### ISSUE THREAD

**Issue by Aaron-Ge** [Snailclimb/JavaGuide#1471]
一千行MySQL学习笔记中 SHOW DATABASES[ LIKE 'PATTERN'] 命令,我的版本是5.7.36,这样使用会报错,
我这边可以使用这样的命令 SHOW DATABASES like '%company_frame'

**Comment by Aaron-Ge** [comment]
下方的 SHOW TABLES[ LIKE 'pattern'] 我这边也是不行的

**Comment by Snailclimb** [comment]
> %

不要加外面的[ ]就可以，这个外面的 [ ] 只是文章格式哈。。。 

![image](https://user-images.githubusercontent.com/29880145/148153671-f047ff2d-552e-4363-832e-89c85c75cc09.png)
