### ISSUE TITLE
https://javaguide.cn/ js文件404，侧边栏无法展开

### ISSUE THREAD

**Issue by orange-random** [Snailclimb/JavaGuide#1472]
![image](https://user-images.githubusercontent.com/44739276/145358251-4fb099f8-489e-4cdd-be36-a32428aa1a15.png)

**Comment by sunshineonly1314** [comment]
尊敬的先生/女士，Dear Sir or Madam,您发给我的信件已经收到，我将尽快回复。Thanks for your e-mail. I will reply to you as soon as possible.孙斌Mr pierre &nbs

**Comment by zaizailong** [comment]
这是来自QQ邮箱的假期自动回复邮件。您的邮件已收到噢、我会立即查看的~    辛苦了哟~

**Comment by 937327493** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Alex-LPDeng** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/44739276/145358251-4fb099f8-489e-4cdd-be36-a32428aa1a15.png)

已经修复了，清楚一下浏览器缓存。
