### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by ItDage** [Snailclimb/JavaGuide#1474]
<img width="848" alt="image" src="https://user-images.githubusercontent.com/30619789/145679700-967ae05c-ed50-4648-b6d0-99a1c6ad2433.png">
System.out.println("aa==bb");// true

**Comment by Snailclimb** [comment]
> <img alt="image" width="848" src="https://user-images.githubusercontent.com/30619789/145679700-967ae05c-ed50-4648-b6d0-99a1c6ad2433.png">
> 
> System.out.println("aa==bb");// true

这不是代码错误哈~只是为了演示这个知识点，IDEA 会提示字符串的毕竟不要用 “==”。
