### ISSUE TITLE
https://javaguide.cn/database/mysql/mysql-logs/      配图文字错误

### ISSUE THREAD

**Issue by Aaron-Ge** [Snailclimb/JavaGuide#1475]
![03](https://user-images.githubusercontent.com/22882546/145783664-1ebd7903-d3c1-4651-a0db-81723cb485f1.png)
第四步,buffer少了r

**Comment by Aaron-Ge** [comment]
![4fa9039762db36efd4c15b6a5125432](https://user-images.githubusercontent.com/22882546/145807509-1cbb40b5-ea9c-41fa-bd00-ad0a72e18179.png)
下方复用了里面图片的 也存在勘误

**Comment by Snailclimb** [comment]
感谢指出👍
