### ISSUE TITLE
JavaGuide面试突击v4.0版本多态的解释可能有误

### ISSUE THREAD

**Issue by pengber** [Snailclimb/JavaGuide#1476]
多态是同一个行为具有多个不同表现形式或形态的能力(这个没有同意定义), 关键是分为运行时多态和编译时多态, 运行时多态的体现是在程序运行时确定使用哪一个函数, 比如将子类对象赋值给父类对象, 然后调用某个方法, 而编译时多态是在编译时确定使用哪一个函数, 体现为重载, 在编译时根据参数和返回值类型确定使用哪个函数.

**Comment by pengber** [comment]
JavaGuide面试突击版本V4版本中是这样描述多态的"所谓多态就是指程序中定义的引⽤变量所指向的具体类型和通过该引⽤变量发出的⽅法调⽤在编 程时并不确定，⽽是在程序运⾏期间才确定，即⼀个引⽤变量到底会指向哪个类的实例对象，该 引⽤变量发出的⽅法调⽤到底是哪个类中实现的⽅法，必须在由程序运⾏期间才能决定。", 不知道是否更新呢

**Comment by Snailclimb** [comment]
> 多态是同一个行为具有多个不同表现形式或形态的能力(这个没有同意定义), 关键是分为运行时多态和编译时多态, 运行时多态的体现是在程序运行时确定使用哪一个函数, 比如将子类对象赋值给父类对象, 然后调用某个方法, 而编译时多态是在编译时确定使用哪一个函数, 体现为重载, 在编译时根据参数和返回值类型确定使用哪个函数.

忘记这部分内容是不是已经修改了，我这边关于多态显示的内容是：
![image](https://user-images.githubusercontent.com/29880145/148153267-895b88b9-0cf7-4268-912b-d3d4b6a4905b.png)
