### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by Auoy** [Snailclimb/JavaGuide#1477]
容器 - 源码分析 - ArrayList源码&扩容机制分析一文中第3.1节第一个代码块第39行，“if ((size = elementData.length) != 0) {” 中，应为 “size - elementData.length”

**Comment by Snailclimb** [comment]
> size = elementData.length

可以去看下源码哈！
![image](https://user-images.githubusercontent.com/29880145/146384326-7e5e1841-741d-485a-956b-c2b0900c3fcc.png)

**Comment by Auoy** [comment]
不好意思，我的问题，感谢回复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Guide哥 ***@***.***&gt;
发送时间: 2021年12月16日 21:52
收件人: Snailclimb/JavaGuide ***@***.***&gt;
抄送: Auoy ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Snailclimb/JavaGuide] 代码错误 (Issue #1477)





  
size = elementData.length
  
可以去看下源码哈！
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Snailclimb** [comment]
> 不好意思，我的问题，感谢回复 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Guide哥 ***@***.***&gt; 发送时间: 2021年12月16日 21:52 收件人: Snailclimb/JavaGuide ***@***.***&gt; 抄送: Auoy ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [Snailclimb/JavaGuide] 代码错误 (Issue #1477) size = elementData.length 可以去看下源码哈！ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

没事的！多多交流👍
