### ISSUE TITLE
讨论-关于联合索引优化建议

### ISSUE THREAD

**Issue by jocodepeasant** [Snailclimb/JavaGuide#1478]
https://javaguide.cn/database/mysql/mysql-high-performance-optimization-specification-recommendations/#_4-%E5%B8%B8%E8%A7%81%E7%B4%A2%E5%BC%95%E5%88%97%E5%BB%BA%E8%AE%AE
![1639489442(1)](https://user-images.githubusercontent.com/54167433/146009775-4143db3b-5f5e-4cdc-aa94-e8b142dad768.png)
guide哥，联合索引的非叶子节点应该包含所有的索引项？那么把字段长度小的索引放左边应该没办法增加一页的数据量吧？

**Comment by wywl99** [comment]
联合索引的非叶子节点是所有的索引项和页号组成的，字段长度小的放左边应该是没办法增加一页的记录条数
