### ISSUE TITLE
关于HashMap底层源码分析--PutVal()流程图的建议

### ISSUE THREAD

**Issue by liangcanxin** [Snailclimb/JavaGuide#1482]
是这样的，最近在加固Java基础的学习，首先很感谢guide哥的这份学习指南，但是我发现以下链接位置
https://javaguide.cn/java/collection/hashmap-source-code/#put-%E6%96%B9%E6%B3%95
的流程图可以换一下说辞会更好理解
对应位置有值-->key存在，是直接覆盖；否....

其实这里我觉得换个说辞：
对应位置有值-->是否存在哈希冲突，不存在，覆盖原value；存在冲突，进行链式处理，个人感觉会好一点理解吧（当然仅个人看法）

**Comment by Tttttttttt59** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Snailclimb** [comment]
> https://javaguide.cn/java/collection/hashmap-source-code/#put-%E6%96%B9%E6%B3%95

不错的建议👍
