### ISSUE TITLE
JAD反编译可以替换为JADX

### ISSUE THREAD

**Issue by pruidong** [Snailclimb/JavaGuide#1483]
https://javaguide.cn/java/tips/jad/

JAD反编译内容可以替换为JADX,这个库一直在维护.

https://github.com/skylot/jadx

**Comment by Snailclimb** [comment]
> https://javaguide.cn/java/tips/jad/
> 
> JAD反编译内容可以替换为JADX,这个库一直在维护.
> 
> https://github.com/skylot/jadx

jadx 的已经在写了，写完了就同步过去。👍
