### ISSUE TITLE
jdk18版本删除了 finalize 方法

### ISSUE THREAD

**Issue by 1725636955** [Snailclimb/JavaGuide#1485]
参考官网地址：https://openjdk.java.net/jeps/421
文中建议指出 finalize 方法的最终结果 和 适用范围

![image](https://user-images.githubusercontent.com/43667484/147095545-e0194ad2-fabf-4180-a2b9-eb5d2072d776.png)

**Comment by Snailclimb** [comment]
> 参考官网地址：https://openjdk.java.net/jeps/421 文中建议指出 finalize 方法的最终结果 和 适用范围
> 
> ![image](https://user-images.githubusercontent.com/43667484/147095545-e0194ad2-fabf-4180-a2b9-eb5d2072d776.png)

好的，感谢指出，我去看看👍
