### ISSUE TITLE
算法-几道常见的字符串算法题-2.替换空格

### ISSUE THREAD

**Issue by ruansheng8** [Snailclimb/JavaGuide#1486]
原文: 
剑指offer：请实现一个函数，将一个字符串中的每个空格替换成“%20”。例如，当字符串为We Are Happy.则经过替换之后的字符串为We%20Are%20Happy。
里面用到了API: str.toString().replaceAll("\\s", "%20");
如果是替换固定的字符(空格属于固定字符) , 则使用replace(" ","%20")性能更高,replaceAll属于正则表达式替换,性能并不高

**Comment by Snailclimb** [comment]
> 原文: 剑指offer：请实现一个函数，将一个字符串中的每个空格替换成“%20”。例如，当字符串为We Are Happy.则经过替换之后的字符串为We%20Are%20Happy。 里面用到了API: str.toString().replaceAll("\s", "%20"); 如果是替换固定的字符(空格属于固定字符) , 则使用replace(" ","%20")性能更高,replaceAll属于正则表达式替换,性能并不高

👍

**Comment by Snailclimb** [comment]
> 原文: 剑指offer：请实现一个函数，将一个字符串中的每个空格替换成“%20”。例如，当字符串为We Are Happy.则经过替换之后的字符串为We%20Are%20Happy。 里面用到了API: str.toString().replaceAll("\s", "%20"); 如果是替换固定的字符(空格属于固定字符) , 则使用replace(" ","%20")性能更高,replaceAll属于正则表达式替换,性能并不高

已经修改了哈
