### ISSUE TITLE
AQS模板方法模式重写的应该是钩子方法而不是模板方法

### ISSUE THREAD

**Issue by ZhengLin-Li** [Snailclimb/JavaGuide#1487]
在[6.2. AQS 原理分析](https://javaguide.cn/java/concurrent/java%E5%B9%B6%E5%8F%91%E8%BF%9B%E9%98%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98%E6%80%BB%E7%BB%93/#_6-1-aqs-%E4%BB%8B%E7%BB%8D)中，写道

> AQS 使用了模板方法模式，自定义同步器时需要重写下面几个 AQS 提供的模板方法

这里有误，一般模板方法都加上 final 关键词，不能被重写，**重写的应该是钩子方法而不是模板方法**

**Comment by Snailclimb** [comment]
> 在[6.2. AQS 原理分析](https://javaguide.cn/java/concurrent/java%E5%B9%B6%E5%8F%91%E8%BF%9B%E9%98%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98%E6%80%BB%E7%BB%93/#_6-1-aqs-%E4%BB%8B%E7%BB%8D)中，写道
> 
> > AQS 使用了模板方法模式，自定义同步器时需要重写下面几个 AQS 提供的模板方法
> 
> 这里有误，一般模板方法都加上 final 关键词，不能被重写，**重写的应该是钩子方法而不是模板方法**

抽象类中 final 修饰的方法无法被重写。

![](https://user-images.githubusercontent.com/29880145/147738753-f3ff5f56-c65e-4360-a0b6-cf15ad4580ed.png)

**Comment by ZhengLin-Li** [comment]
对, 模板方法一般加上final修饰无法被重写,, 所以重写的应该是钩子方法

**Comment by Snailclimb** [comment]
> 对, 模板方法一般加上final修饰无法被重写,, 所以重写的应该是钩子方法

感谢，已经修改完善：https://github.com/Snailclimb/JavaGuide/commit/274848094ebee89e4a0692b063590d2f96642ab0
