### ISSUE TITLE
反射模块：“注解的实现用到反射”？

### ISSUE THREAD

**Issue by W--7V** [Snailclimb/JavaGuide#1491]
![2JL%@@M6J~JDO$2RP{R@@77](https://user-images.githubusercontent.com/9429451/147680133-5ac785e8-d7b2-435a-9d0a-aebbddef52ec.png)
这里说注解的实现用到反射不太理解。我的理解中注解就是注解，只是在spring这类框架中用到了反射+注解来实现DI。麻烦指点一下。

**Comment by Snailclimb** [comment]
> ![2JL%@@M6J~JDO$2RP{R@@77](https://user-images.githubusercontent.com/9429451/147680133-5ac785e8-d7b2-435a-9d0a-aebbddef52ec.png) 这里说注解的实现用到反射不太理解。我的理解中注解就是注解，只是在spring这类框架中用到了反射+注解来实现DI。麻烦指点一下。

注解如果不被处理就和单纯的注释没啥区别，通常都是通过结合反射来处理的。

**Comment by Snailclimb** [comment]
> ![2JL%@@M6J~JDO$2RP{R@@77](https://user-images.githubusercontent.com/9429451/147680133-5ac785e8-d7b2-435a-9d0a-aebbddef52ec.png) 这里说注解的实现用到反射不太理解。我的理解中注解就是注解，只是在spring这类框架中用到了反射+注解来实现DI。麻烦指点一下。

![image](https://user-images.githubusercontent.com/29880145/148145626-a822ff96-4cde-4f63-8c2c-d4adaa7f48fa.png)

相关阅读：https://cloud.tencent.com/developer/article/1522675

**Comment by W--7V** [comment]
那是不是应该说DI是通过注解+反射实现的，而不是注解的实现用到了反射？
