### ISSUE TITLE
操作系统常见面试题&知识点总结.md的3.2段页描述有冲突

### ISSUE THREAD

**Issue by solojin** [Snailclimb/JavaGuide#1493]
段页空间大小描述有冲突
“段式管理”里说“每一段的空间又要比一页的空间小很多”，而“段页式管理机制”里说“段页式管理机制就是把主存先分成若干段，每个段又分成若干页”，那到底是段空间大，还是页空间大？

**Comment by Snailclimb** [comment]
> 段页空间大小描述有冲突 “段式管理”里说“每一段的空间又要比一页的空间小很多”，而“段页式管理机制”里说“段页式管理机制就是把主存先分成若干段，每个段又分成若干页”，那到底是段空间大，还是页空间大？

这段我已经删了，并不需要关注两者大小，我这里写的有问题。
