### ISSUE TITLE
【执行结果和预期不一致】4.3. 执行 execute()方法和 submit()方法的区别

### ISSUE THREAD

**Issue by hwj1** [Snailclimb/JavaGuide#1495]
该段提到 _**get(long timeout，TimeUnit unit)方法则会阻塞当前线程一段时间后立即返回，这时候有可能任务没有执行完。**_ 
执行下面一段代码会发现是抛异常, 立即返回是否描述不够准确?
```
ExecutorService executorService = Executors.newFixedThreadPool(3);

        Future<String> submit = executorService.submit(() -> {
            try {
                Thread.sleep(5000L);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            return "abc";
        });

        String s = submit.get(3, TimeUnit.SECONDS);
        System.out.println(s);
        executorService.shutdown();
```

**Comment by Snailclimb** [comment]
> ExecutorService executorService = Executors.newFixedThreadPool(3);
> 
>         Future<String> submit = executorService.submit(() -> {
>             try {
>                 Thread.sleep(5000L);
>             } catch (InterruptedException e) {
>                 e.printStackTrace();
>             }
>             return "abc";
>         });
> 
>         String s = submit.get(3, TimeUnit.SECONDS);
>         System.out.println(s);
>         executorService.shutdown();

抱歉，犯了一个常识性的错误，已经修改。

#### 4.3.2 `execute()` vs `submit()`

- `execute()`方法用于提交不需要返回值的任务，所以无法判断任务是否被线程池执行成功与否；
- `submit()`方法用于提交需要返回值的任务。线程池会返回一个 `Future` 类型的对象，通过这个 `Future` 对象可以判断任务是否执行成功，并且可以通过 `Future` 的 `get()`方法来获取返回值，`get()`方法会阻塞当前线程直到任务完成，而使用 `get（long timeout，TimeUnit unit）`方法的话，如果在 `timeout` 时间内任务还没有执行完，就会抛出 `java.util.concurrent.TimeoutException`。

这里只是为了演示使用，推荐使用 `ThreadPoolExecutor` 构造方法来创建线程池。

示例1：使用 `get() `方法获取返回值。

```java
ExecutorService executorService = Executors.newFixedThreadPool(3);

Future<String> submit = executorService.submit(() -> {
    try {
        Thread.sleep(5000L);
    } catch (InterruptedException e) {
        e.printStackTrace();
    }
    return "abc";
});

String s = submit.get();
System.out.println(s);
executorService.shutdown();
```

输出：

```
abc
```

示例2：使用 `get（long timeout，TimeUnit unit） `方法获取返回值。

```java
ExecutorService executorService = Executors.newFixedThreadPool(3);

Future<String> submit = executorService.submit(() -> {
    try {
        Thread.sleep(5000L);
    } catch (InterruptedException e) {
        e.printStackTrace();
    }
    return "abc";
});

String s = submit.get(3, TimeUnit.SECONDS);
System.out.println(s);
executorService.shutdown();
```

输出：

```
Exception in thread "main" java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
```
