### ISSUE TITLE
关于String.intern()描述运行时常量池是否有误

### ISSUE THREAD

**Issue by QianJinGuo** [Snailclimb/JavaGuide#1497]
guide中原文中描述：String.intern() 是一个 Native 方法，它的作用是：如果运行时常量池中已经包含一个等于此 String 对象内容的字符串，则返回常量池中该字符串的引用；如果没有，JDK1.7 之前...jdk1.7及之后...

正确描述应该为：如果字符串常量池中已经包含一个等于次String对象的字符串。
这里应该是字符串常量池，而非运行时常量池。

**Comment by Snailclimb** [comment]
> 运行时常量池

感谢指出，已经修复👍
