### ISSUE TITLE
方法重写这一块，对返回值描述修改未改全（第一次阅读容易留下错误印象）

### ISSUE THREAD

**Issue by CrystalWyz** [Snailclimb/JavaGuide#1499]
![image](https://user-images.githubusercontent.com/37053692/149607042-c658abf2-96f5-423b-9bfa-6fa58393a57c.png)
方法重写这一块，对返回值描述修改未改全（第一次阅读容易留下错误印象）

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/37053692/149607042-c658abf2-96f5-423b-9bfa-6fa58393a57c.png) 方法重写这一块，对返回值描述修改未改全（第一次阅读容易留下错误印象）

感谢👍 已经修改，在线网站会晚一些才能同步，Github已经同步更改。
![image](https://user-images.githubusercontent.com/29880145/150054441-47c828fc-b6de-400b-88b7-3a93266b49fb.png)
