### ISSUE TITLE
增加 Java 8 新特性講解 (Stream, Lambda, Optional)

### ISSUE THREAD

**Issue by schrodog** [Snailclimb/JavaGuide#150]
由於java8/java11 在互聯網公司內逐漸成為主流，關於Java 8 新特性的面試內容將越來越多，有必要新增相關內容。建議內容：Stream api, lambda expression, Optional, CompletableFuture, Supplier Consumer, 以及新Java fp 風格的寫法。

**Comment by Snailclimb** [comment]
嗯嗯 好的 感谢您的建议！

**Comment by niefy** [comment]
JDK1.8内存划分与之前版本略有不同，建议对[内存区域划分相关文章](https://github.com/Snailclimb/JavaGuide/blob/master/Java%E7%9B%B8%E5%85%B3/%E5%8F%AF%E8%83%BD%E6%98%AF%E6%8A%8AJava%E5%86%85%E5%AD%98%E5%8C%BA%E5%9F%9F%E8%AE%B2%E7%9A%84%E6%9C%80%E6%B8%85%E6%A5%9A%E7%9A%84%E4%B8%80%E7%AF%87%E6%96%87%E7%AB%A0.md)做更新
参考：https://blog.csdn.net/bruce128/article/details/79357870

**Comment by Snailclimb** [comment]
Java8新特性总结已经增加，对一些重要的特性的详解暂时还没有：[Java8新特性总结](https://github.com/Snailclimb/JavaGuide/blob/master/Java/What's%20New%20in%20JDK8/Java8Tutorial.md)
