### ISSUE TITLE
数据结构-树的深度概念问题

### ISSUE THREAD

**Issue by JinLong369** [Snailclimb/JavaGuide#1502]
1. 在 **数据结构-树** 章节，[**树**](https://github.com/Snailclimb/JavaGuide/blob/main/docs/cs-basics/data-structure/%E6%A0%91.md#%E6%A0%91) 标题下，提到节点深度的概念为：
> 根节点到该节点的路径所包含的边数。

该页面中的示例图如下：

![68747470733a2f2f6d792d626c6f672d746f2d7573652e6f73732d636e2d6265696a696e672e616c6979756e63732e636f6d2f323031392d362f2545342542412538432545352538462538392545362541302539312d322e706e67](https://user-images.githubusercontent.com/50287763/149925573-cf25d690-110e-4dae-a952-d7b0e0f5d647.png)

2. 在 **数据结构-树** 章节，[**二叉树的分类**](https://github.com/Snailclimb/JavaGuide/blob/main/docs/cs-basics/data-structure/%E6%A0%91.md#%E4%BA%8C%E5%8F%89%E6%A0%91%E7%9A%84%E5%88%86%E7%B1%BB) 标题下，提到：
> 深度为 k 的二叉树至多总共有 2^k-1 个节点。

这两处的概念有冲突。试想，若按第1点中提到的概念深度为1时，最多应该有3个节点。可代入第2点中的公式时，得出的结果却是最多只有1个节点。

在[树的百度百科](https://baike.baidu.com/item/%E6%A0%91/2699484#2)中，树深度概念如下：
> 定义一棵树的根结点层次为1，其他结点的层次是其父结点层次加1。一棵树中所有结点的层次的最大值称为这棵树的深度。

若是以此为基础，第2点的公式才能成立。

**Comment by Snailclimb** [comment]
> 1. 在 **数据结构-树** 章节，[**树**](https://github.com/Snailclimb/JavaGuide/blob/main/docs/cs-basics/data-structure/%E6%A0%91.md#%E6%A0%91) 标题下，提到节点深度的概念为：
> 
> > 根节点到该节点的路径所包含的边数。
> 
> 该页面中的示例图如下：
> 
> ![68747470733a2f2f6d792d626c6f672d746f2d7573652e6f73732d636e2d6265696a696e672e616c6979756e63732e636f6d2f323031392d362f2545342542412538432545352538462538392545362541302539312d322e706e67](https://user-images.githubusercontent.com/50287763/149925573-cf25d690-110e-4dae-a952-d7b0e0f5d647.png)
> 
> 2. 在 **数据结构-树** 章节，[**二叉树的分类**](https://github.com/Snailclimb/JavaGuide/blob/main/docs/cs-basics/data-structure/%E6%A0%91.md#%E4%BA%8C%E5%8F%89%E6%A0%91%E7%9A%84%E5%88%86%E7%B1%BB) 标题下，提到：
> 
> > 深度为 k 的二叉树至多总共有 2^k-1 个节点。
> 
> 这两处的概念有冲突。试想，若按第1点中提到的概念深度为1时，最多应该有3个节点。可代入第2点中的公式时，得出的结果却是最多只有1个节点。
> 
> 在[树的百度百科](https://baike.baidu.com/item/%E6%A0%91/2699484#2)中，树深度概念如下：
> 
> > 定义一棵树的根结点层次为1，其他结点的层次是其父结点层次加1。一棵树中所有结点的层次的最大值称为这棵树的深度。
> 
> 若是以此为基础，第2点的公式才能成立。

维基百科是这样描述深度的，我在外网搜了下，感觉这种描述更准确一些：
![image](https://user-images.githubusercontent.com/29880145/150058168-d910d872-3cf2-4f0e-95f5-0611c93305db.png)

我修改了你说的内容的描述：

> **二叉树** 的第 i 层至多拥有 `2^(i-1)` 个节点，深度为 k 的二叉树至多总共有 `2^(k+1)-1` 个节点（满二叉树的情况）。

关于树的深度和高度的定义可以看 stackoverflow 上的这个问题：[What is the difference between tree depth and height?](https://stackoverflow.com/questions/2603692/what-is-the-difference-between-tree-depth-and-height) 。
