### ISSUE TITLE
有关布隆过滤器hash函数的疑问

### ISSUE THREAD

**Issue by 15575432921** [Snailclimb/JavaGuide#1503]
为什么hash函数是写成这个样子的呢： Math.abs(seed * (cap - 1) & ((h = value.hashCode()) ^ (h >>> 16)));
这个值不会大于cap然后导致溢出范围吗

**Comment by 15575432921** [comment]
BitSet中数组大小会随需要增加（学艺不精了 。。。）

**Comment by Snailclimb** [comment]
> 为什么hash函数是写成这个样子的呢： Math.abs(seed * (cap - 1) & ((h = value.hashCode()) ^ (h >>> 16))); 这个值不会大于cap然后导致溢出范围吗

👍
