### ISSUE TITLE
关于加密的基本知识

### ISSUE THREAD

**Issue by LiWenGu** [Snailclimb/JavaGuide#152]
前几天有个朋友在面小米时（1-2年经验）被问了 http/https 区别，具体加密流程、算法等，正好之前看过《图解密码技术》里面有详细讲解到 SSL 这个知识点，所以想关于这个知识点提个 PR，放在**计算机网络与数据通道**目录里面可行么（其实我倾向于新建一个目录）？:grin:  
@Snailclimb

**Comment by Snailclimb** [comment]
嗯嗯 可以啊
