### ISSUE TITLE
关于编译型和解释型的一点疑问

### ISSUE THREAD

**Issue by reflyhight** [Snailclimb/JavaGuide#1526]
文中提到`一般情况下，编译语言的执行速度比较快，开发效率比较低`。
感觉开发效率很多时候决定于 语法设计的简洁性，跟是否是编译型没直接关系。
之前我是记得有一个说编译型语言和解释型语言的各自的优缺点，似乎没提到开发效率

**Comment by sotondolphin** [comment]
我觉得作者这么说的依据是因为编译型的语言很多时候需要繁琐的类型声明和重复的样板导致要写大量的代码，所以开发效率会减慢

**Comment by ENNRIaaa** [comment]
编译型语言一般都是强类型语言，相对于 JS、Python 这种解释型语言来说，实现同一个功能，编译型语言要写相对更多的代码。
