### ISSUE TITLE
在看spring事务与锁

### ISSUE THREAD

**Issue by lizhifeng100** [Snailclimb/JavaGuide#1529]
这两种有什么区别吗？事务中的隔离性由锁实现，不太分的清？望前辈指点，提供方向。

**Comment by hujesse83** [comment]
只能说你的issue 毫不相关

**Comment by Snailclimb** [comment]
> 这两种有什么区别吗？事务中的隔离性由锁实现，不太分的清？望前辈指点，提供方向。

事务的隔离性实现依靠锁，但不一定只通过锁来实现，还可以是其他机制比如MVCC机制。
