### ISSUE TITLE
需求：是否可以添加隐私模式

### ISSUE THREAD

**Issue by zengzuo613** [Snailclimb/JavaGuide#1535]
# 需求
添加隐藏模式，支持页面隐藏header和aside，避免让boss和同事看到我们再看面试资料

# 效果
![image](https://user-images.githubusercontent.com/76633368/153984060-37f8fc37-8713-4551-b379-75c31722f872.png)

# 如果
如果隐藏header、aside后，页面能自动调整布局，减少空白面积，更好

**Comment by Snailclimb** [comment]
> # 需求
> 添加隐藏模式，支持页面隐藏header和aside，避免让boss和同事看到我们再看面试资料
> 
> # 效果
> ![image](https://user-images.githubusercontent.com/76633368/153984060-37f8fc37-8713-4551-b379-75c31722f872.png)
> 
> # 如果
> 如果隐藏header、aside后，页面能自动调整布局，减少空白面积，更好

目前仅支持缩小屏幕后隐藏侧边栏，你的需求我会充分考虑的👍

![image](https://user-images.githubusercontent.com/29880145/154173191-b4a6ad06-1b70-4227-8fbd-dad9fdcbbc0a.png)

**Comment by NikoAoi** [comment]
> # 需求
> 添加隐藏模式，支持页面隐藏header和aside，避免让boss和同事看到我们再看面试资料
> 
> # 效果
> ![image](https://user-images.githubusercontent.com/76633368/153984060-37f8fc37-8713-4551-b379-75c31722f872.png)
> 
> # 如果
> 如果隐藏header、aside后，页面能自动调整布局，减少空白面积，更好

写了个油猴脚本，欢迎star：https://github.com/NikoAoi/SilentlyJavaGuide

**Comment by Snailclimb** [comment]
> > # 需求
> > 添加隐藏模式，支持页面隐藏header和aside，避免让boss和同事看到我们再看面试资料
> > # 效果
> > ![image](https://user-images.githubusercontent.com/76633368/153984060-37f8fc37-8713-4551-b379-75c31722f872.png)
> > # 如果
> > 如果隐藏header、aside后，页面能自动调整布局，减少空白面积，更好
> 
> 写了个油猴脚本专门用来隐藏JavaGuide的侧边栏和导航栏，欢迎star：https://github.com/NikoAoi/SilentlyJavaGuide

不错的👍
