### ISSUE TITLE
图片不匹配

### ISSUE THREAD

**Issue by szq2287745536** [Snailclimb/JavaGuide#154]
Java相关--->可能是把Java内存区域讲的最清楚的一篇文章.md   这一节中，第一张图片无内容。

**Comment by LiWenGu** [comment]
你说的是在“运行时数据区域”下面的第一张图么：  
![](https://camo.githubusercontent.com/7dbe84f3d6186c5f8e2836489ad1dae57f4b2f59/68747470733a2f2f757365722d676f6c642d63646e2e786974752e696f2f323031382f342f32372f313633303661333463643861343335343f773d35313326683d34303426663d706e6726733d313332303638)  
我这边可以看的到，图片地址为：https://camo.githubusercontent.com/7dbe84f3d6186c5f8e2836489ad1dae57f4b2f59/68747470733a2f2f757365722d676f6c642d63646e2e786974752e696f2f323031382f342f32372f313633303661333463643861343335343f773d35313326683d34303426663d706e6726733d313332303638

**Comment by szq2287745536** [comment]
您好，我这边点开您提供的链接是一张横条形的白色图片，图片上什么信息也没有啊。
