### ISSUE TITLE
这里的类对象是不是不准确，感觉是实例对象，类对象不是Class对象么

### ISSUE THREAD

**Issue by yuyang2030** [Snailclimb/JavaGuide#1544]
![image](https://user-images.githubusercontent.com/56267437/154483834-fb4261f6-a62c-4f8e-9661-4385d0ec9de1.png)

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/56267437/154483834-fb4261f6-a62c-4f8e-9661-4385d0ec9de1.png)

![image](https://user-images.githubusercontent.com/29880145/154687201-c9c769bc-95bd-492a-a8ab-66cc68d3777d.png)
