### ISSUE TITLE
并发事务带来哪些问题中不可重复读和幻读区别不严谨的

### ISSUE THREAD

**Issue by SummerWen107** [Snailclimb/JavaGuide#1566]
![image](https://user-images.githubusercontent.com/63193856/155090056-26ec3728-a0e9-4a74-9675-e1f634270e9a.png)
这里应该是说使用比如like语句时，多次查询获得的数据个数增多或减少，一条记录不能直观的说明幻读的问题

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/63193856/155090056-26ec3728-a0e9-4a74-9675-e1f634270e9a.png) 这里应该是说使用比如like语句时，多次查询获得的数据个数增多或减少，一条记录不能直观的说明幻读的问题

👍看到PR了
