### ISSUE TITLE
计算机网络->计算机网络常见面试题图片挂掉

### ISSUE THREAD

**Issue by hujesse83** [Snailclimb/JavaGuide#1571]
计算机网络->计算机网络常见面试题图片挂掉—>1.6 总结一下挂掉了一张图片

**Comment by Snailclimb** [comment]
> 计算机网络->计算机网络常见面试题图片挂掉—>1.6 总结一下挂掉了一张图片

好的 已经修改，这部分内容正在重构，在线版还没有同步。
