### ISSUE TITLE
Java基础->常见（上）->java关键字

### ISSUE THREAD

**Issue by Kongtiao88** [Snailclimb/JavaGuide#1572]
https://docs.oracle.com/javase/specs/jls/se7/html/jls-3.html#jls-3.9

**Comment by Kongtiao88** [comment]
true、false、null不在里面

**Comment by hujesse83** [comment]
i agree with you

**Comment by Snailclimb** [comment]
> true、false、null不在里面
是的 👍  https://docs.oracle.com/javase/tutorial/java/nutsandbolts/_keywords.html 已经修正
