### ISSUE TITLE
面试突击版，关于Error的catch问题

### ISSUE THREAD

**Issue by chengliangluo** [Snailclimb/JavaGuide#1577]
2.1.29中，讲到Error不可以catch，但我实验是可以catch的呀，语法上是允许的，只是通常不建议这么做吧？
![image](https://user-images.githubusercontent.com/41443654/155885934-d1369d47-11de-405c-9e28-098b0508be25.png)

**Comment by Snailclimb** [comment]
> 2.1.29中，讲到Error不可以catch，但我实验是可以catch的呀，语法上是允许的，只是通常不建议这么做吧？ ![image](https://user-images.githubusercontent.com/41443654/155885934-d1369d47-11de-405c-9e28-098b0508be25.png)

正常情况下，除非是你自己抛出 Error 捕获，否则，你的应用程序出现 Error 的时候，对应的 catch 代码是不会被执行的。
