### ISSUE TITLE
希望加入elasticSerch 搜索引擎相关技术栈

### ISSUE THREAD

**Issue by bailuWX** [Snailclimb/JavaGuide#1581]
缺少 es搜索引擎先关技术栈，对于看重数据库能力的相关公司可能有面试压力。。

**Comment by Snailclimb** [comment]
> 缺少 es搜索引擎先关技术栈，对于看重数据库能力的相关公司可能有面试压力。。

已经在进行中了。

**Comment by Snailclimb** [comment]
忘记还有这个 issue，年初已经加了，过年的时候抽空写的。不过，这篇目前只有星球能看，后续会考虑是否开源出来：https://javaguide.cn/database/elasticsearch/elasticsearch-questions-01.html 。
