### ISSUE TITLE
数据库基础知识-drop、delete 与 truncate 区别？“delete from 表名 where 列名=值，删除某一列的数据”有误，应该是删除某一行

### ISSUE THREAD

**Issue by BigBlueBaby** [Snailclimb/JavaGuide#1585]
https://javaguide.cn/database/basis.html#drop%E3%80%81delete-%E4%B8%8E-truncate-%E5%8C%BA%E5%88%AB

**Comment by ily666666** [comment]
同意

**Comment by Snailclimb** [comment]
> https://javaguide.cn/database/basis.html#drop%E3%80%81delete-%E4%B8%8E-truncate-%E5%8C%BA%E5%88%AB

已修改，感谢指出👍

**Comment by BigBlueBaby** [comment]
> > https://javaguide.cn/database/basis.html#drop%E3%80%81delete-%E4%B8%8E-truncate-%E5%8C%BA%E5%88%AB
> 
> 已修改，感谢指出👍

是我这边的问题吗？网站看着还是原来错误的

**Comment by Snailclimb** [comment]
> > > https://javaguide.cn/database/basis.html#drop%E3%80%81delete-%E4%B8%8E-truncate-%E5%8C%BA%E5%88%AB
> > 
> > 
> > 已修改，感谢指出👍
> 
> 是我这边的问题吗？网站看着还是原来错误的

网站这边一般是周末进行部署更改哈，Github 项目里的已经更新完善了。
