### ISSUE TITLE
关于 "try里面的return 和 finally的return"

### ISSUE THREAD

**Issue by yydzxz** [Snailclimb/JavaGuide#1588]
![image](https://user-images.githubusercontent.com/13087806/156195598-028fec42-1ade-47b7-87e8-576ff08e275a.png)
try里面的return是会执行的，只不过最终的返回值由finally里面的return决定
![image](https://user-images.githubusercontent.com/13087806/156196101-50b71841-5e8a-4d22-9dc9-d7c76365460f.png)

**Comment by yydzxz** [comment]
有相关的issue https://github.com/Snailclimb/JavaGuide/issues/190

**Comment by hujesse83** [comment]
try 只是调用了print方法. 等价于
`int res = print("我是try块里面的");
return res;`

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/13087806/156195598-028fec42-1ade-47b7-87e8-576ff08e275a.png) try里面的return是会执行的，只不过最终的返回值由finally里面的return决定 ![image](https://user-images.githubusercontent.com/13087806/156196101-50b71841-5e8a-4d22-9dc9-d7c76365460f.png)

感谢指出，我之前的描述确实不严谨，已经修改👍

![image](https://user-images.githubusercontent.com/29880145/156524894-a2528550-f6a2-4d64-8bc0-32f25c82d1b8.png)
