### ISSUE TITLE
纠错：关于 Spring事务总结-事务属性详解-propagation.PROPAGATION_NESTED

### ISSUE THREAD

**Issue by 1autodidact** [Snailclimb/JavaGuide#1600]
文中描述 ：如果当前存在事务，则创建一个事务作为当前事务的嵌套事务来运行；如果当前没有事务，则该取值等价于TransactionDefinition.PROPAGATION_REQUIRED。也就是说：

在外部方法未开启事务的情况下Propagation.NESTED和Propagation.REQUIRED作用相同，修饰的内部方法都会新开启自己的事务，且开启的事务相互独立，互不干扰。
如果外部方法开启事务的话，Propagation.NESTED修饰的内部方法属于外部事务的子事务，外部主事务回滚的话，子事务也会回滚，而内部子事务可以单独回滚而不影响外部主事务和其他子事务。
这里还是简单举个例子：

`**如果 aMethod() 回滚的话，bMethod()和bMethod2()都要回滚，而bMethod()回滚的话，并不会造成 aMethod() 和bMethod()2回滚**`。
实际测试bMethod() 回滚 ，aMethod() 也会回滚

测试代码
```
 @Transactional
    public void createUser() {
        User user = new User();
        user.setName("invokeUserService");
        user.setAge(333);
        userMapper.insert(user);
        this.insertData();
    }

    @Transactional(propagation = Propagation.NESTED)
    public void insertData() {
        int a = 1/0 ;
         User user = new User();
         user.setName("inser");
         user.setAge(2222);
        userMapper.insert(user);


@SpringBootTest
public class TransactionalTest {
    @Autowired
    UserService userService;
    @Autowired
    UserInvokeService userInvokeService;
    @Test
    public void testTransaction() {
        userService.createUser();
    }
}
    }
```

**Comment by Snailclimb** [comment]
> 文中描述 ：如果当前存在事务，则创建一个事务作为当前事务的嵌套事务来运行；如果当前没有事务，则该取值等价于TransactionDefinition.PROPAGATION_REQUIRED。也就是说：
> 
> 在外部方法未开启事务的情况下Propagation.NESTED和Propagation.REQUIRED作用相同，修饰的内部方法都会新开启自己的事务，且开启的事务相互独立，互不干扰。 如果外部方法开启事务的话，Propagation.NESTED修饰的内部方法属于外部事务的子事务，外部主事务回滚的话，子事务也会回滚，而内部子事务可以单独回滚而不影响外部主事务和其他子事务。 这里还是简单举个例子：
> 
> `**如果 aMethod() 回滚的话，bMethod()和bMethod2()都要回滚，而bMethod()回滚的话，并不会造成 aMethod() 和bMethod()2回滚**`。 实际测试bMethod() 回滚 ，aMethod() 也会回滚
> 
> 测试代码
> 
> ```
>  @Transactional
>     public void createUser() {
>         User user = new User();
>         user.setName("invokeUserService");
>         user.setAge(333);
>         userMapper.insert(user);
>         this.insertData();
>     }
> 
>     @Transactional(propagation = Propagation.NESTED)
>     public void insertData() {
>         int a = 1/0 ;
>          User user = new User();
>          user.setName("inser");
>          user.setAge(2222);
>         userMapper.insert(user);
> 
> 
> @SpringBootTest
> public class TransactionalTest {
>     @Autowired
>     UserService userService;
>     @Autowired
>     UserInvokeService userInvokeService;
>     @Test
>     public void testTransaction() {
>         userService.createUser();
>     }
> }
>     }
> ```



> 

感谢指出，确认没问题了之后，可以提交一个PR修改一下哈~感谢

**Comment by 1autodidact** [comment]
@Snailclimb guide 哥 已经提pr了喔，关注下

**Comment by Snailclimb** [comment]
> @Snailclimb guide 哥 已经提pr了喔，关注下

好的👍
