### ISSUE TITLE
纠错：Raft算法 -> 拜占庭将军 -> 内容：信使可能会被暗示 应为 信使可能会被暗杀

### ISSUE THREAD

**Issue by CrystalWyz** [Snailclimb/JavaGuide#1601]
![image](https://user-images.githubusercontent.com/37053692/157063072-a5d09924-5453-4588-9118-a33d83375f58.png)

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/37053692/157063072-a5d09924-5453-4588-9118-a33d83375f58.png)

已修改。
