### ISSUE TITLE
纠错：HTTP vs HTTPS（应用层）

### ISSUE THREAD

**Issue by Feyl** [Snailclimb/JavaGuide#1602]
[HTTP vs HTTPS（应用层）](https://javaguide.cn/cs-basics/network/http&https.html#ssl-tls-%E7%9A%84%E5%B7%A5%E4%BD%9C%E5%8E%9F%E7%90%86)
**SSL/TLS 的工作原理** 部分的 **数字签名** 小节中：
> S 信任 CA，CA 是知道 S 公钥的，**S 向 CA 颁发证书**。并附上 CA 私钥对消息摘要的加密签名。

应改为 “**CA 向 S 颁发证书**”。

**Comment by Snailclimb** [comment]
> CA 向 S 颁发证书

感谢指出，已修改👍
