### ISSUE TITLE
突击版v3里面spring boot部分欠缺

### ISSUE THREAD

**Issue by CONTINUE12** [Snailclimb/JavaGuide#1609]
想问下Guide哥，突击版v3里面spring、mybatis框架后直接就是spring cloud部分了，请问是否有整理spring boot部分，或者有无相关知识点链接推荐

**Comment by Snailclimb** [comment]
> 想问下Guide哥，突击版v3里面spring、mybatis框架后直接就是spring cloud部分了，请问是否有整理spring boot部分，或者有无相关知识点链接推荐

这部分内容放到了星球里了。
