### ISSUE TITLE
Wrong description in your blog 《Java多线程学习（一）Java多线程入门》

### ISSUE THREAD

**Issue by isudox** [Snailclimb/JavaGuide#161]
[Java多线程学习（一）Java多线程入门#1.2 何为进程](https://blog.csdn.net/qq_34337272/article/details/79640870#12__20)
It should be "进程" in line of "我们就可以清楚看到 window 当前运行的线程", not "线程".

**Comment by Snailclimb** [comment]
已经修改！感谢！
