### ISSUE TITLE
MySQL索引文章中一个似乎笔误的地方

### ISSUE THREAD

**Issue by hhmy27** [Snailclimb/JavaGuide#1612]
[https://github.com/Snailclimb/JavaGuide/blob/main/docs/database/mysql/mysql-index.md](url) 中非聚集索引下面的表述

> MYISAM 引擎的表的.MYI 文件包含了表的索引， 该表的索引(B+树)的每个叶子非叶子节点存储索引， 叶子节点存储索引和索引对应数据的指针，指向.MYD 文件的数据。
非聚集索引的叶子节点并不一定存放数据的指针， 因为二级索引的叶子节点就存放的是主键，根据主键再回表查数据。

什么叫**该表的索引(B+树)的每个叶子非叶子节点存储索引**？
这地方是不是打错了

**Comment by Snailclimb** [comment]
> MYISAM 引擎的表的.MYI 文件包含了表的索引

已经基础了这部分内容哈~
