### ISSUE TITLE
【关于JVM调优的一些方面】这一章中的4.1 最后手动执行一次 FullGC 的代码无法支撑后面的结论

### ISSUE THREAD

**Issue by djl19921205** [Snailclimb/JavaGuide#1623]
“此时我们手动执行了一次fullgc，此时total memory的内存空间又变回5.5M了，此时又是把申请的内存释放掉的结果。” 
使用的代码是
System.gc();
System.out.println("Xmx=" + Runtime.getRuntime().maxMemory() / 1024.0 / 1024 + "M");    //系统的最大空间
System.out.println("free mem=" + Runtime.getRuntime().freeMemory() / 1024.0 / 1024 + "M");  //系统的空闲空间
System.out.println("total mem=" + Runtime.getRuntime().totalMemory() / 1024.0 / 1024 + "M");  //当前可用的总空间
这样并不能说明申请了的内存了。
本机运行的话，还是15M

**Comment by Snailclimb** [comment]
> “此时我们手动执行了一次fullgc，此时total memory的内存空间又变回5.5M了，此时又是把申请的内存释放掉的结果。” 使用的代码是 System.gc(); System.out.println("Xmx=" + Runtime.getRuntime().maxMemory() / 1024.0 / 1024 + "M"); //系统的最大空间 System.out.println("free mem=" + Runtime.getRuntime().freeMemory() / 1024.0 / 1024 + "M"); //系统的空闲空间 System.out.println("total mem=" + Runtime.getRuntime().totalMemory() / 1024.0 / 1024 + "M"); //当前可用的总空间 这样并不能说明申请了的内存了。 本机运行的话，还是15M

说明一下你的 jdk 版本，最好带上运行的截图哈~

**Comment by djl19921205** [comment]
（1）jdk 版本：1.8.0_281；
&nbsp;(2) 设置的VM参数：-Xmx20m -Xms5m -XX:+PrintGCDetails；
&nbsp;(3)代码如下：

(4) 运行结果如下：







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snailclimb/JavaGuide"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月16日(星期三) 上午9:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Snailclimb/JavaGuide] 【关于JVM调优的一些方面】这一章中的4.1 最后手动执行一次 FullGC 的代码无法支撑后面的结论 (Issue #1623)





  
“此时我们手动执行了一次fullgc，此时total memory的内存空间又变回5.5M了，此时又是把申请的内存释放掉的结果。” 使用的代码是 System.gc(); System.out.println("Xmx=" + Runtime.getRuntime().maxMemory() / 1024.0 / 1024 + "M"); //系统的最大空间 System.out.println("free mem=" + Runtime.getRuntime().freeMemory() / 1024.0 / 1024 + "M"); //系统的空闲空间 System.out.println("total mem=" + Runtime.getRuntime().totalMemory() / 1024.0 / 1024 + "M"); //当前可用的总空间 这样并不能说明申请了的内存了。 本机运行的话，还是15M
  
说明一下你的 jdk 版本，最好带上运行的截图哈~
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lwmfjc** [comment]
你们好，我也是这个问题，gc之后total mem=16.0M
