### ISSUE TITLE
计算机网络 - HTTPS - SSL/TLS 的工作原理 - 数字签名

### ISSUE THREAD

**Issue by Kongtiao88** [Snailclimb/JavaGuide#1628]
原文：注意，验证身份的证书一定是由 CA 的公钥进行签名，而不能由发送者自己来签名。
疑问：工作原理这块我看的有点绕，不是很明白，但是感觉这里验证身份的证书应该是由CA的私钥来进行签名的，不知道这样对不对，求大佬指正。

**Comment by Snailclimb** [comment]
> 原文：注意，验证身份的证书一定是由 CA 的公钥进行签名，而不能由发送者自己来签名。 疑问：工作原理这块我看的有点绕，不是很明白，但是感觉这里验证身份的证书应该是由CA的私钥来进行签名的，不知道这样对不对，求大佬指正。

对于数字签名，我这里讲的比较简单，如果你没有搞清楚的话，强烈推荐你看看[数字签名及数字证书原理](https://www.bilibili.com/video/BV18N411X7ty/)这个视频，这是我看过最清晰的讲解。

![](https://guide-blog-images.oss-cn-shenzhen.aliyuncs.com/github/javaguide/image-20220321121814946.png)
