### ISSUE TITLE
首页部分链接404

### ISSUE THREAD

**Issue by a-fly-fly-bird** [Snailclimb/JavaGuide#1629]
<img width="656" alt="截屏2022-03-20 17 37 02" src="https://user-images.githubusercontent.com/70647529/159156534-5d279e3d-c956-47e6-b1c7-4243eafc4fc6.png">

<img width="1245" alt="截屏2022-03-20 17 37 10" src="https://user-images.githubusercontent.com/70647529/159156538-e206bd6f-08c5-4f3e-93e4-e148d1636869.png">

**Comment by Snailclimb** [comment]
> <img alt="截屏2022-03-20 17 37 02" width="656" src="https://user-images.githubusercontent.com/70647529/159156534-5d279e3d-c956-47e6-b1c7-4243eafc4fc6.png">
> 
> <img alt="截屏2022-03-20 17 37 10" width="1245" src="https://user-images.githubusercontent.com/70647529/159156538-e206bd6f-08c5-4f3e-93e4-e148d1636869.png">

感谢指出，已经修复👍
