### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by maxwellens** [Snailclimb/JavaGuide#163]
AQS 原理
在面试中被问到并发知识的时候，大多都会被问到“请你说一下自己对于AQS原理的理解”。下面给大家一个示例供大家参加，面试不是背题，大家一定要**假如**自己的思想，即使加入不了自己的思想也要保证自己能够通俗的讲出来而不是背出来。
假如->加入

**Comment by Snailclimb** [comment]
好的 感谢！
