### ISSUE TITLE
【suggestion】关于并行和并发的解释。

### ISSUE THREAD

**Issue by zzzzail** [Snailclimb/JavaGuide#1632]
原文：
- **并发：** 同一时间段，多个任务都在执行 (单位时间内不一定同时执行)；
- **并行：** 单位时间内，多个任务同时执行。

建议：
- **并发**：两个及两个以上的作业在同一**时间段**内执行。
- **并行**：两个及两个以上的作业在同一**时刻**执行。

我觉得在并行的解释中，用同一时刻更精确。

**Comment by zzzzail** [comment]
https://github.com/Snailclimb/JavaGuide/blob/4d09f56304b7ca3f1ea741e6d2bdcd517c864066/docs/java/concurrent/java-concurrent-questions-01.md?plain=1#L95-L96

**Comment by Snailclimb** [comment]
> * **并发**：两个及两个以上的作业在同一**时间段**内执行。
> * **并行**：两个及两个以上的作业在同一**时刻**执行。

很不错的建议，已经同步👍
