### ISSUE TITLE
基本数据类型存放位置

### ISSUE THREAD

**Issue by wecgwm** [Snailclimb/JavaGuide#1634]
[Java 中的几种基本数据类型了解么？](https://javaguide.cn/java/basis/java-basic-questions-01.html#%E5%9F%BA%E6%9C%AC%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B)
这一节写到
> 基本数据类型直接存放在 Java 虚拟机栈中的局部变量表中  

应该是局部基本数据类型，才会被保存于局部变量表中。

**Comment by Snailclimb** [comment]
> 

感谢指出，这里确实写的不是很准备，已做修改👍

![image](https://user-images.githubusercontent.com/29880145/159645013-0b9549a7-1ffa-4818-ba3f-34a2cddaad48.png)
