### ISSUE TITLE
Redis目录大小写冲突

### ISSUE THREAD

**Issue by luanrz** [Snailclimb/JavaGuide#1636]
[database](https://github.com/Snailclimb/JavaGuide/tree/main/docs/database)目录下存在两个大小写不同的Redis目录，导致在非Linux系统下拉取的时候报错，我看里面的内容差不多，建议删除冗余的那个Redis目录

**Comment by Snailclimb** [comment]
> [database](https://github.com/Snailclimb/JavaGuide/tree/main/docs/database)目录下存在两个大小写不同的Redis目录，导致在非Linux系统下拉取的时候报错，我看里面的内容差不多，建议删除冗余的那个Redis目录

已修复，感谢指出。主要我本地没有这个问题，很奇怪，一直没有人提出。
