### ISSUE TITLE
jvm参数重复

### ISSUE THREAD

**Issue by cl7106786** [Snailclimb/JavaGuide#1638]
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/4155491/159601818-39bb8ac9-38cf-4f0d-8874-42680b4fff1f.png">

**Comment by zzzzail** [comment]
@cl7106786 提交一下 PR 作者直接会通过的

**Comment by cl7106786** [comment]
收到

**Comment by Snailclimb** [comment]
> <img alt="image" width="1035" src="https://user-images.githubusercontent.com/4155491/159601818-39bb8ac9-38cf-4f0d-8874-42680b4fff1f.png">

感谢指出👍
