### ISSUE TITLE
整形->整型

### ISSUE THREAD

**Issue by maxwellens** [Snailclimb/JavaGuide#164]
4.2 JUC 包中的原子类是哪4类?
基本类型

使用原子的方式更新基本类型

AtomicInteger：**整形**原子类
AtomicLong：长整型原子类
AtomicBoolean ：布尔型原子类
数组类型

使用原子的方式更新数组里的某个元素

AtomicIntegerArray：**整形**数组原子类
AtomicLongArray：长整形数组原子类
AtomicReferenceArray ：引用类型数组原子类
引用类型

AtomicReference：引用类型原子类
**AtomicStampedRerence**：原子更新引用类型里的字段原子类
AtomicMarkableReference ：原子更新带有标记位的引用类型
对象的属性修改类型
---------------------------------------
修改：
AtomicStampedRerence->AtomicStampedReference
整形->整型

**Comment by Snailclimb** [comment]
好的 感谢！
