### ISSUE TITLE
Java新特性分组中是否可以补全16~18的新特性？

### ISSUE THREAD

**Issue by MrXionGe** [Snailclimb/JavaGuide#1644]
### JDK16新特性参考：
https://www.oschina.net/news/133354/jdk-16-ga
https://openjdk.java.net/projects/jdk/16/

### JDK17新特性参考：
https://www.oschina.net/news/160291/jdk-17-lts-ga
https://openjdk.java.net/projects/jdk/17/

### JDK18新特性参考：
https://www.oschina.net/news/187796/jdk-18-ga
https://openjdk.java.net/projects/jdk/18/

**Comment by Snailclimb** [comment]
> ### JDK16新特性参考：
> https://www.oschina.net/news/133354/jdk-16-ga https://openjdk.java.net/projects/jdk/16/
> 
> ### JDK17新特性参考：
> https://www.oschina.net/news/160291/jdk-17-lts-ga https://openjdk.java.net/projects/jdk/17/
> 
> ### JDK18新特性参考：
> https://www.oschina.net/news/187796/jdk-18-ga https://openjdk.java.net/projects/jdk/18/

目前有此打算！感谢你的分享👍

**Comment by Snailclimb** [comment]
> ### JDK16新特性参考：
> https://www.oschina.net/news/133354/jdk-16-ga https://openjdk.java.net/projects/jdk/16/
> 
> ### JDK17新特性参考：
> https://www.oschina.net/news/160291/jdk-17-lts-ga https://openjdk.java.net/projects/jdk/17/
> 
> ### JDK18新特性参考：
> https://www.oschina.net/news/187796/jdk-18-ga https://openjdk.java.net/projects/jdk/18/

已经补全 JDK16 ~JDK19 的新特性：

JDK16 新特性：https://javaguide.cn/java/new-features/java16.html
JDK17 新特性：https://javaguide.cn/java/new-features/java17.html
JDK18 新特性：https://javaguide.cn/java/new-features/java18.html
JDK19 新特性：https://javaguide.cn/java/new-features/java19.html
