### ISSUE TITLE
内存分配其中一种方式为什么叫指针碰撞

### ISSUE THREAD

**Issue by lingkai1** [Snailclimb/JavaGuide#1666]
JVM新对象做内存分配的两种方式其中一种指针碰撞，为什么不叫指针偏移呢？ 
看上去更像是偏移，没有碰撞的过程。

**Comment by Snailclimb** [comment]
> JVM新对象做内存分配的两种方式其中一种指针碰撞，为什么不叫指针偏移呢？ 看上去更像是偏移，没有碰撞的过程。

看一下参考一下这个：[指针碰撞、空闲列表、TLAB是什么关系？ - 干货满满张哈希的回答 - 知乎](https://www.zhihu.com/question/476948066/answer/2036463259)

**Comment by lingkai1** [comment]
***@***.***已成功抓取您发送的数据包！
