### ISSUE TITLE
字符串常量池和String对象的创建

### ISSUE THREAD

**Issue by 1127426159** [Snailclimb/JavaGuide#1681]
![image](https://user-images.githubusercontent.com/35327252/162475129-7594bb31-03e8-4fd2-9f2a-07b1b25950a3.png)
这里的代码的编译结果如下图，无论是第一次使用”ab“还是第二次使用”ab“编译得到的字节码都是相同的，都是从字符串常量池中载入对象，然后赋值给变量。不应该说是第一次使用的使用放入常量池，第二次从常量池中取，应该是两次都是从常量池中取。
![image](https://user-images.githubusercontent.com/35327252/162475776-9d980714-5a4d-400b-bd5e-af3e55759e6e.png)
还有下图这里的对象会创建几个的问题
![image](https://user-images.githubusercontent.com/35327252/162475992-6b79c09e-0bb6-4c28-8bb3-50cc475de96a.png)
我觉得这个在执行到创建的这行代码的时候应该是创建一个，字符串常量池中的变量应该是在类载入的时候就被创建了，在执行到这里的时候应该直接引用就行了，这个代码对应的字节码如下图，也是由IDC直接加载。
![image](https://user-images.githubusercontent.com/35327252/162478362-320d45f4-5924-4bca-bee1-9b9238446df2.png)

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/35327252/162475129-7594bb31-03e8-4fd2-9f2a-07b1b25950a3.png) 这里的代码的编译结果如下图，无论是第一次使用”ab“还是第二次使用”ab“编译得到的字节码都是相同的，都是从字符串常量池中载入对象，然后赋值给变量。不应该说是第一次使用的使用放入常量池，第二次从常量池中取，应该是两次都是从常量池中取。 ![image](https://user-images.githubusercontent.com/35327252/162475776-9d980714-5a4d-400b-bd5e-af3e55759e6e.png) 还有下图这里的对象会创建几个的问题 ![image](https://user-images.githubusercontent.com/35327252/162475992-6b79c09e-0bb6-4c28-8bb3-50cc475de96a.png) 我觉得这个在执行到创建的这行代码的时候应该是创建一个，字符串常量池中的变量应该是在类载入的时候就被创建了，在执行到这里的时候应该直接引用就行了，这个代码对应的字节码如下图，也是由IDC直接加载。 ![image](https://user-images.githubusercontent.com/35327252/162478362-320d45f4-5924-4bca-bee1-9b9238446df2.png)

确实，这部分内容我貌似理解错了，写的也有一点问题。我尽快完善修改！

**Comment by Phukety** [comment]
您好Guide哥，我看您的文档中写的：使用new String方式创建字符串，如果常量池中没有，那么会先在常量池中创建一个新的。但我也在很多地方看到过说不会在常量池中创建，只会在堆中创建对象（https://www.zhihu.com/question/36908414/answer/1182187223）。这到底是要创建还是不创建呢？

**Comment by Snailclimb** [comment]
·

> ![image](https://user-images.githubusercontent.com/35327252/162475129-7594bb31-03e8-4fd2-9f2a-07b1b25950a3.png) 这里的代码的编译结果如下图，无论是第一次使用”ab“还是第二次使用”ab“编译得到的字节码都是相同的，都是从字符串常量池中载入对象，然后赋值给变量。不应该说是第一次使用的使用放入常量池，第二次从常量池中取，应该是两次都是从常量池中取。 ![image](https://user-images.githubusercontent.com/35327252/162475776-9d980714-5a4d-400b-bd5e-af3e55759e6e.png) 还有下图这里的对象会创建几个的问题 ![image](https://user-images.githubusercontent.com/35327252/162475992-6b79c09e-0bb6-4c28-8bb3-50cc475de96a.png) 我觉得这个在执行到创建的这行代码的时候应该是创建一个，字符串常量池中的变量应该是在类载入的时候就被创建了，在执行到这里的时候应该直接引用就行了，这个代码对应的字节码如下图，也是由IDC直接加载。 ![image](https://user-images.githubusercontent.com/35327252/162478362-320d45f4-5924-4bca-bee1-9b9238446df2.png)



> 您好Guide哥，我看您的文档中写的：使用new String方式创建字符串，如果常量池中没有，那么会先在常量池中创建一个新的。但我也在很多地方看到过说不会在常量池中创建，只会在堆中创建对象（ https://www.zhihu.com/question/36908414/answer/1182187223 ）。这到底是要创建还是不创建呢？

这部分内容我正在修改，字符串常量池保存的是对象引用，我之前理解错了。

**Comment by Snailclimb** [comment]
@Phukety @1127426159 已经修正了字符串常量池相关概念的描述，感谢二位指出👍

https://github.com/Snailclimb/JavaGuide/blob/main/docs/java/basis/java-basic-questions-02.md#%E5%AD%97%E7%AC%A6%E4%B8%B2%E5%B8%B8%E9%87%8F%E6%B1%A0%E7%9A%84%E4%BD%9C%E7%94%A8%E4%BA%86%E8%A7%A3%E5%90%97
