### ISSUE TITLE
包装类的常量池这个表述是否正确？

### ISSUE THREAD

**Issue by 1127426159** [Snailclimb/JavaGuide#1690]
![image](https://user-images.githubusercontent.com/35327252/163222419-57ca4815-5da0-4aec-a8f8-da79bdafcc8e.png)
如下图，Integer包装类缓存的创建代码
![image](https://user-images.githubusercontent.com/35327252/163222869-56acbdf8-0fa5-4e4f-8aae-23ef2977a566.png)
在IntegerCache中，使用的是一个Integer数组cache来作为包装类的缓存，在IntegerCache加载的时候static中的初始化代码被执行，在这个初始化的代码中，可以看到是直接new了[low,high]范围的Integer对象，并将引用放在了cache数组对应的位置中。代码中new出来的对象的存储空间应该是jvm的堆空间，而不应该在JVM的常量池中，用常量池这个表达有歧义，叫包装类的缓存应该更合适。

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/35327252/163222419-57ca4815-5da0-4aec-a8f8-da79bdafcc8e.png) 如下图，Integer包装类缓存的创建代码 ![image](https://user-images.githubusercontent.com/35327252/163222869-56acbdf8-0fa5-4e4f-8aae-23ef2977a566.png) 在IntegerCache中，使用的是一个Integer数组cache来作为包装类的缓存，在IntegerCache加载的时候static中的初始化代码被执行，在这个初始化的代码中，可以看到是直接new了[low,high]范围的Integer对象，并将引用放在了cache数组对应的位置中。代码中new出来的对象的存储空间应该是jvm的堆空间，而不应该在JVM的常量池中，用常量池这个表达有歧义，叫包装类的缓存应该更合适。

嗯嗯，这里可以改为包装类型的缓存机制，常量池这个描述很容易让人误解。
