### ISSUE TITLE
ArrayQueue貌似不是Queue接口的实现类

### ISSUE THREAD

**Issue by cgengwei** [Snailclimb/JavaGuide#1694]
ArrayQueue貌似不是Queue接口的实现类

markdown页面
https://github.com/Snailclimb/JavaGuide/edit/main/docs/java/collection/java-collection-questions-01.md

**Comment by Snailclimb** [comment]
> ArrayQueue貌似不是Queue接口的实现类
> 
> markdown页面 https://github.com/Snailclimb/JavaGuide/edit/main/docs/java/collection/java-collection-questions-01.md

![image](https://user-images.githubusercontent.com/29880145/163589555-cb51327a-4ec2-4a75-ab9d-2abb3ffb105d.png)
![Uploading image.png…]()
