### ISSUE TITLE
描述错误

### ISSUE THREAD

**Issue by youaremywind** [Snailclimb/JavaGuide#1695]
![image](https://user-images.githubusercontent.com/18423358/163665203-b69feaf8-f079-42ce-9601-3c283dc8116b.png)
应该是 // s1 和 s4 指向的是堆中相同的对象
https://javaguide.cn/java/basis/java-basic-questions-02.html#string

**Comment by Snailclimb** [comment]
> https://javaguide.cn/java/basis/java-basic-questions-02.html#string

笔误了，感谢指出👍
