### ISSUE TITLE
关于字符串拼接用“+” 还是 StringBuilder?

### ISSUE THREAD

**Issue by luckyboy520** [Snailclimb/JavaGuide#1699]
有一个疑问，就是在for循环使用+号，看字节码只是new了一次stringbuilder对象吧，下面都是用的同一个对象吧，描述是否有误呢
![image](https://user-images.githubusercontent.com/27756246/164479777-9aa76926-b266-454d-bba7-d6ed86a436aa.png)

![image](https://user-images.githubusercontent.com/27756246/164479978-7c172024-f8c2-42e7-995d-e837ea8fc198.png)

**Comment by Snailclimb** [comment]
> 有一个疑问，就是在for循环使用+号，看字节码只是new了一次stringbuilder对象吧，下面都是用的同一个对象吧，描述是否有误呢 ![image](https://user-images.githubusercontent.com/27756246/164479777-9aa76926-b266-454d-bba7-d6ed86a436aa.png)
>





> 有一个疑问，就是在for循环使用+号，看字节码只是new了一次stringbuilder对象吧，下面都是用的同一个对象吧，描述是否有误呢 ![image](https://user-images.githubusercontent.com/27756246/164479777-9aa76926-b266-454d-bba7-d6ed86a436aa.png)
> 
> ![image](https://user-images.githubusercontent.com/27756246/164479978-7c172024-f8c2-42e7-995d-e837ea8fc198.png)

确实字节码上显示的是这样的。IDEA 的提示是说这样使用会复制整个字符串，不如直接使用 `StringBuilder`。

![image](https://user-images.githubusercontent.com/29880145/164637440-d47b5cb6-9a82-4c8d-9712-055713ce7a08.png)

**Comment by Snailclimb** [comment]
@luckyboy520  刚刚回顾了一下字节码相关的知识，我发现这里的new是在循环中，因此，的确是会创建多个 `StringBuilder` 对象的。

**Comment by luckyboy520** [comment]
好的，了解了。感谢大佬回答

**Comment by luckyboy520** [comment]
> @luckyboy520  刚刚回顾了一下字节码相关的知识，我发现这里的new是在循环中，因此，的确是会创建多个 `StringBuilder` 对象的。

好的清楚了，感谢大佬解答
