### ISSUE TITLE
【建议】

### ISSUE THREAD

**Issue by mxm-j** [Snailclimb/JavaGuide#1700]
事务传播行为知识点加上一张图表方便对比，图片来源csdn
![image](https://user-images.githubusercontent.com/41312095/164578294-2bb4b99f-7d48-44bd-8ed6-ab214de4d1d8.png)

**Comment by Snailclimb** [comment]
> 事务传播行为知识点加上一张图表方便对比，图片来源csdn ![image](https://user-images.githubusercontent.com/41312095/164578294-2bb4b99f-7d48-44bd-8ed6-ab214de4d1d8.png)

感谢建议👍
