### ISSUE TITLE
[新功能] 是否可以新建一个关于开源实习的板块？

### ISSUE THREAD

**Issue by erdengk** [Snailclimb/JavaGuide#1706]
我是一名爱好开源的普通研究生。我注意到有很多同学因为导师项目、课程学习压力（本科生这类问题较多）、疫情原因，无法直接去线下实习。
随着疫情原因，有越来越多的线上开源实习被更多公司认可（谷歌的GSoC、中科院的暑期之夏）。这种开源实习基本上全程线上，适合因为各种原因无法参加线下实习的朋友。而这种实习难度也有高有低，上到为Apache 的各种顶级项目提升项目性能，下到为社区编写新功能。这种实习好处在于，只有贡献的足够多，基本上是稳的，而不像线下的实习，可能说没就没。

我想写一个帖子来详细介绍这些活动，我觉得作为一个程序员为开源社区做出一些贡献是一件好事。

**Comment by Snailclimb** [comment]
> 我是一名爱好开源的普通研究生。我注意到有很多同学因为导师项目、课程学习压力（本科生这类问题较多）、疫情原因，无法直接去线下实习。 随着疫情原因，有越来越多的线上开源实习被更多公司认可（谷歌的GSoC、中科院的暑期之夏）。这种开源实习基本上全程线上，适合因为各种原因无法参加线下实习的朋友。而这种实习难度也有高有低，上到为Apache 的各种顶级项目提升项目性能，下到为社区编写新功能。这种实习好处在于，只有贡献的足够多，基本上是稳的，而不像线下的实习，可能说没就没。
> 
> 我想写一个帖子来详细介绍这些活动，我觉得作为一个程序员为开源社区做出一些贡献是一件好事。

我看行，像国内的开源之夏就挺不错的，值得被更多同学知道！期待你的文章👍

**Comment by erdengk** [comment]
嗯嗯，谢谢guide哥的认可，我先开始着手文章的编写。写好后我应该提交到哪个板块下呢？

**Comment by Snailclimb** [comment]
> 嗯嗯，谢谢guide哥的认可，我先开始着手文章的编写。写好后我应该提交到哪个板块下呢？

要不先投稿到我的公众号？

**Comment by Snailclimb** [comment]
> 嗯嗯，谢谢guide哥的认可，我先开始着手文章的编写。写好后我应该提交到哪个板块下呢？

我的邮箱 koushuangbwcx@163.com ，可以先发到这里。

**Comment by erdengk** [comment]
> > 嗯嗯，谢谢guide哥的认可，我先开始着手文章的编写。写好后我应该提交到哪个板块下呢？
> 
> 要不先投稿到我的公众号？

好的。

**Comment by erdengk** [comment]
> > 嗯嗯，谢谢guide哥的认可，我先开始着手文章的编写。写好后我应该提交到哪个板块下呢？
> 
> 我的邮箱 [koushuangbwcx@163.com](mailto:koushuangbwcx@163.com) ，可以先发到这里。

嗯嗯，我会备注是GitHub关于这个issue的。
