### ISSUE TITLE
关于"Java"->"基础"->''面试题总结(下)"一文中的异常的勘误建议

### ISSUE THREAD

**Issue by 0212Infinity** [Snailclimb/JavaGuide#1707]
这里使用 throws 会不会更合适点
![image](https://user-images.githubusercontent.com/49862950/165197751-96d0216d-37bd-440c-8f7f-46fd9f0a0967.png)

**Comment by Snailclimb** [comment]
> 这里使用 throws 会不会更合适点 ![image](https://user-images.githubusercontent.com/49862950/165197751-96d0216d-37bd-440c-8f7f-46fd9f0a0967.png)

确实，这里应该是 throws 更加准确。
