### ISSUE TITLE
教程中提供的“Linux 命令大全”网址已无法访问

### ISSUE THREAD

**Issue by ljtjerry** [Snailclimb/JavaGuide#1710]
在这个文件中：Snailclimb/JavaGuide/blob/main/docs/cs-basics/operating-system/linux-intro.md
“4. Linux 基本命令”这一章节
下面只是给出了一些比较常用的命令。推荐一个 Linux 命令快查网站，非常不错，大家如果遗忘某些命令或者对某些命令不理解都可以在这里得到解决。

Linux 命令大全：http://man.linuxde.net/

“http://man.linuxde.net/”这个网址，访问时浏览器提示“man.linuxde.net 未发送任何数据。ERR_EMPTY_RESPONSE”
确认过梯子已开并正常工作中。

系统版本：	macOS 11.1
内核版本：	Darwin 20.2.0
浏览器：谷歌Chrome，版本 100.0.4896.127（正式版本） (x86_64)

**Comment by Snailclimb** [comment]
> http://man.linuxde.net/

感谢支持，http://man.linuxde.net/ 这个网站应该没有在维护了，故我换了一个搜索 Linux 命令的网站。

原文已修改：

推荐一个 Linux 命令快查网站，非常不错，大家如果遗忘某些命令或者对某些命令不理解都可以在这里得到解决。Linux 命令在线速查手册：https://www.w3xue.com/manual/linux/ 。

另外，[shell.how](https://www.shell.how/) 这个网站可以用来解释常见命令的意思，对你学习 Linux 基本命令以及其他常用命令（如 Git、NPM）。
