### ISSUE TITLE
对fail-fast机制的详细说明

### ISSUE THREAD

**Issue by Polaris799** [Snailclimb/JavaGuide#1712]
[Java集合使用注意事项总结](https://javaguide.cn/java/collection/java-collection-precautions-for-use.html#%E9%9B%86%E5%90%88%E9%81%8D%E5%8E%86)这一节的集合遍历部分可以结合源码解释为什么在foreach循环里进行add/remove操作会抛出CMException
参考博客地址[什么是fail-fast](https://www.cnblogs.com/54chensongxia/p/12470446.html)
ps：这是我第一次使用issues，如果出现问题和错误请多包涵

**Comment by Snailclimb** [comment]
> Java集合使用注意事项总结

不错的建议👍
