### ISSUE TITLE
Java基础-反射机制详解-获得Class对象的四种方式遇到的问题

### ISSUE THREAD

**Issue by walkkong** [Snailclimb/JavaGuide#1716]
![image](https://user-images.githubusercontent.com/55477781/166176578-11687637-a72b-4c93-aec1-476093bacf03.png)

直接这样运行会报错的，loadClass 不是类方法。没办法使用类名直接调用，改成这样可以运行：
```java
            Class clazz = ClassLoader.getSystemClassLoader().loadClass("Student");
```

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/55477781/166176578-11687637-a72b-4c93-aec1-476093bacf03.png)
> 
> 直接这样运行会报错的，loadClass 不是类方法。没办法使用类名直接调用，改成这样可以运行：
> 
> ```java
>             Class clazz = ClassLoader.getSystemClassLoader().loadClass("Student");
> ```

感谢指出👍
