### ISSUE TITLE
JAVA基础-重要知识点中的Java 代理模式详解有错？

### ISSUE THREAD

**Issue by MrDecadent** [Snailclimb/JavaGuide#1718]
在第一章代理模式中
文字中写的代理是小红，但是图片中的代理是在小绿下方
![捕获](https://user-images.githubusercontent.com/82100995/166475657-377e5680-5321-414a-b241-00cc3de08ab6.PNG)

**Comment by Snailclimb** [comment]
> 在第一章代理模式中 文字中写的代理是小红，但是图片中的代理是在小绿下方 ![捕获](https://user-images.githubusercontent.com/82100995/166475657-377e5680-5321-414a-b241-00cc3de08ab6.PNG)

哈哈哈 细致👍 我这里简单修改了一下描述。

![image](https://user-images.githubusercontent.com/29880145/167081435-22885d3b-8f5a-47ae-8129-e5037d492d57.png)
