### ISSUE TITLE
一个编号问题

### ISSUE THREAD

**Issue by 337245354** [Snailclimb/JavaGuide#1724]
java并发编程（进阶）有两个1.3 ， 分别是 ： 
1.3. 构造方法可以使用 synchronized 关键字修饰么？
1.3. 讲一下 synchronized 关键字的底层原理
![屏幕快照 2022-05-11 下午5 04 11](https://user-images.githubusercontent.com/35426702/167812743-3db33e02-d6f6-4c46-a21f-1f220eac4554.png)

**Comment by Snailclimb** [comment]
> java并发编程（进阶）有两个1.3 ， 分别是 ： 1.3. 构造方法可以使用 synchronized 关键字修饰么？ 1.3. 讲一下 synchronized 关键字的底层原理 ![屏幕快照 2022-05-11 下午5 04 11](https://user-images.githubusercontent.com/35426702/167812743-3db33e02-d6f6-4c46-a21f-1f220eac4554.png)

👍
