### ISSUE TITLE
网页文字格式有点混乱

### ISSUE THREAD

**Issue by Tenderness-Miao** [Snailclimb/JavaGuide#1729]
https://javaguide.cn/java/basis/java-basic-questions-01.html#%E4%BB%80%E4%B9%88%E6%98%AF%E5%8F%AF%E5%8F%98%E9%95%BF%E5%8F%82%E6%95%B0
文字排版不利于阅读代码，请确认修改

![image](https://user-images.githubusercontent.com/13068041/168509859-b56d5966-0d53-46d4-b2fa-d9d7e6afaccb.png)

**Comment by Snailclimb** [comment]
> https://javaguide.cn/java/basis/java-basic-questions-01.html#%E4%BB%80%E4%B9%88%E6%98%AF%E5%8F%AF%E5%8F%98%E9%95%BF%E5%8F%82%E6%95%B0 文字排版不利于阅读代码，请确认修改
> 
> ![image](https://user-images.githubusercontent.com/13068041/168509859-b56d5966-0d53-46d4-b2fa-d9d7e6afaccb.png)

奇怪了，我试了几个浏览器都出现不了你这里的问题。。。

![image](https://user-images.githubusercontent.com/29880145/168595591-c3a56e26-220c-4386-8fc5-5286adb5217a.png)

**Comment by Tenderness-Miao** [comment]
> > https://javaguide.cn/java/basis/java-basic-questions-01.html#%E4%BB%80%E4%B9%88%E6%98%AF%E5%8F%AF%E5%8F%98%E9%95%BF%E5%8F%82%E6%95%B0 文字排版不利于阅读代码，请确认修改
> > ![image](https://user-images.githubusercontent.com/13068041/168509859-b56d5966-0d53-46d4-b2fa-d9d7e6afaccb.png)
> 
> 奇怪了，我试了几个浏览器都出现不了你这里的问题。。。
> 
> ![image](https://user-images.githubusercontent.com/29880145/168595591-c3a56e26-220c-4386-8fc5-5286adb5217a.png)

那就奇怪了，昨天看的时候除了这一页是这样，其他的都正常。

今天全都正常了

**Comment by Snailclimb** [comment]
> > > https://javaguide.cn/java/basis/java-basic-questions-01.html#%E4%BB%80%E4%B9%88%E6%98%AF%E5%8F%AF%E5%8F%98%E9%95%BF%E5%8F%82%E6%95%B0 文字排版不利于阅读代码，请确认修改
> > > ![image](https://user-images.githubusercontent.com/13068041/168509859-b56d5966-0d53-46d4-b2fa-d9d7e6afaccb.png)
> > 
> > 
> > 奇怪了，我试了几个浏览器都出现不了你这里的问题。。。
> > ![image](https://user-images.githubusercontent.com/29880145/168595591-c3a56e26-220c-4386-8fc5-5286adb5217a.png)
> 
> 那就奇怪了，昨天看的时候除了这一页是这样，其他的都正常。
> 
> 今天全都正常了

我大概知道什么问题了，URL 链接错误，缺少 `.html` 后缀。
![image](https://user-images.githubusercontent.com/29880145/168991302-2127def8-5502-484a-9c23-bc0e7e10c1d3.png)
