### ISSUE TITLE
cglib动态代理,发现一处小错误

### ISSUE THREAD

**Issue by yangjiawen-621** [Snailclimb/JavaGuide#1746]
![image](https://user-images.githubusercontent.com/61310700/173782383-9700e655-6268-4e94-8c0a-c5f9ca017574.png)

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/61310700/173782383-9700e655-6268-4e94-8c0a-c5f9ca017574.png)

是的，已修改👍
