### ISSUE TITLE
Kafka知识点面试总结架构图问题

### ISSUE THREAD

**Issue by shusheng007** [Snailclimb/JavaGuide#1748]
我看那个kafka架构图上面两个consumer同时消费同一个partition，这块是不是不对呀？
我记得每个partition最多只能由一个consumer消费，而一个consumer可以同时消费多个partition。

<img width="655" alt="image" src="https://user-images.githubusercontent.com/10703676/174198730-866dfd3b-5ba6-47e4-845c-81f1d6656820.png">

**Comment by Snailclimb** [comment]
忘记同步到网上上了，这个图片后来改了。我等下同步一下。感谢👍
