### ISSUE TITLE
在重写时返回类型必须完全与被重写方法的返回类型相同

### ISSUE THREAD

**Issue by stdwal** [Snailclimb/JavaGuide#175]
在Java基础知识回顾中关于重写和重载中的叙述“重载返回值范围小于等于父类”不当
在重写时返回类型必须完全与被重写方法的返回类型相同
否则会产生返回类型不兼容导致无法覆盖的错误

**Comment by baitaobox** [comment]
不是吧，自己写个Demo试试看就知道了，
“重载返回值范围小于等于父类”是正确的
