### ISSUE TITLE
关于String的intern方法

### ISSUE THREAD

**Issue by wuzimian** [Snailclimb/JavaGuide#1754]
![image](https://user-images.githubusercontent.com/10112588/175472969-46bbaa00-30a9-4c8c-8468-d760db0b9faf.png)

![F42488EB-5DB0-4021-8BFA-2E87EC1D8F4E](https://user-images.githubusercontent.com/10112588/175473063-1f396fdc-8748-467f-b436-edd567c0d6ee.png)

关于intern方法，这里的描述是不是有些小问题？intern是去看pool里面有没有equals（相等）的字符串，而不是看对象的引用是否已经存在。

也可能是我理解有误，狗头。

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/10112588/175472969-46bbaa00-30a9-4c8c-8468-d760db0b9faf.png)
> 
> ![F42488EB-5DB0-4021-8BFA-2E87EC1D8F4E](https://user-images.githubusercontent.com/10112588/175473063-1f396fdc-8748-467f-b436-edd567c0d6ee.png)
> 
> 关于intern方法，这里的描述是不是有些小问题？intern是去看pool里面有没有equals（相等）的字符串，而不是看对象的引用是否已经存在。
> 
> 也可能是我理解有误，狗头。

嗯嗯 ，这里的意思就是相等了就相当于保存了对应字符串的引用。
