### ISSUE TITLE
redis 常用的3种读写策略中旁路缓存模式

### ISSUE THREAD

**Issue by cat3306** [Snailclimb/JavaGuide#1757]
https://github.com/Snailclimb/JavaGuide/blob/main/docs/database/redis/3-commonly-used-cache-read-and-write-strategies.md
我有个地方没有搞懂，服务有数据要更新，更新了DB，为什么到缓存这里就删除了，到缓存这儿不也是更新吗，还望解答

关于数据一致性，我的一个想法哈：有数据要更新，可以利用数据库事务保持数据一致性。
数据更新先起一个事务，更新数据库，再更新缓存，如果更新缓存有什么问题，事务直接回滚，如果更新成功，事务提交。

**Comment by Snailclimb** [comment]
> https://github.com/Snailclimb/JavaGuide/blob/main/docs/database/redis/3-commonly-used-cache-read-and-write-strategies.md

Cache Aside Pattern（旁路缓存模式）的写是这样的步骤。
