### ISSUE TITLE
为什么javaguide.cn中的图总是消失？

### ISSUE THREAD

**Issue by SuperDongdongYan** [Snailclimb/JavaGuide#1758]
请问是因为图床不稳定吗？ 可否修复一下，尤其是关于虚拟机相关的，没图真的痛苦

**Comment by Snailclimb** [comment]
> 请问是因为图床不稳定吗？ 可否修复一下，尤其是关于虚拟机相关的，没图真的痛苦

你说的是网站上的还是Github上的？
