### ISSUE TITLE
HTTP状态码建议

### ISSUE THREAD

**Issue by ChenSheng6869** [Snailclimb/JavaGuide#1767]
把HTTP状态码归为4大类
| 状态码 | 类型 | 含义 |
|  :----: |  :----: | :----: |
| 2XX | 成功状态码 | 正常完成处理请求 |
| 3XX | 重定向 | 进行附加操作完成请求 |
|4XX|客户端错误|无法处理请求|
|5XX|服务器错误|处理请求出错|

**Comment by Snailclimb** [comment]
> 

<img width="751" alt="image" src="https://user-images.githubusercontent.com/29880145/177892221-27f76de8-1d3b-443c-86e6-2a8c3749ab30.png">

**Comment by Snailclimb** [comment]
> 把HTTP状态码归为4大类
> 
> 状态码	类型	含义
> 2XX	成功状态码	正常完成处理请求
> 3XX	重定向	进行附加操作完成请求
> 4XX	客户端错误	无法处理请求
> 5XX	服务器错误	处理请求出错

新的一篇文章中会有这一张图。
