### ISSUE TITLE
对象的访问定位，目前主流的访问方式有：使用句柄、直接指针。  

### ISSUE THREAD

**Issue by qiujunlin** [Snailclimb/JavaGuide#1769]
[对象的访问定位](https://javaguide.cn/java/jvm/memory-area.html#%E5%AF%B9%E8%B1%A1%E7%9A%84%E8%AE%BF%E9%97%AE%E5%AE%9A%E4%BD%8D)
建议补充下面： 对于我们目前主要虚拟机HotSpot而言，它是使用第二种方式(直接指针访问)进行对象访问的。

**Comment by Snailclimb** [comment]
> 虚拟机HotSpot

HotSpot 虚拟机主要使用的第二种方式(直接指针访问)来进行对象访问。

![image](https://user-images.githubusercontent.com/29880145/178141449-2040624a-8cf8-4339-ba60-9d502c91f684.png)
