### ISSUE TITLE
万字解析 ThreadLocal 关键字这篇文章的 <ThreadLocalMap.get()详解>部分,移位过后的循环查找表述有歧义

### ISSUE THREAD

**Issue by JQ1013** [Snailclimb/JavaGuide#1776]
![image](https://user-images.githubusercontent.com/26687870/180645248-963cd31d-0a55-4f4e-9506-33a6d0dfb2a1.png)
index 6,7的数据都会前移，此时继续往后迭代，到index = 6的时候即找到了key值相等的Entry数据
这里6 7 的数据往前移后,还是继续从5开始迭代,这句话容易让人以为从6开始迭代

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/26687870/180645248-963cd31d-0a55-4f4e-9506-33a6d0dfb2a1.png) index 6,7的数据都会前移，此时继续往后迭代，到index = 6的时候即找到了key值相等的Entry数据 这里6 7 的数据往前移后,还是继续从5开始迭代,这句话容易让人以为从6开始迭代

完善后的表述如下：
![image](https://user-images.githubusercontent.com/29880145/180735551-e584c5d9-0b15-4a0b-a2bb-1aff91b3440c.png)
