### ISSUE TITLE
completableFuture.get() 阻塞问题

### ISSUE THREAD

**Issue by zhangsunsuochang1** [Snailclimb/JavaGuide#1777]
你好，在原文中说 completableFuture.get() 并不会阻塞，但是经查阅get方法好像是阻塞的，请解释一下呢？

**Comment by Snailclimb** [comment]
> 你好，在原文中说 completableFuture.get() 并不会阻塞，但是经查阅get方法好像是阻塞的，请解释一下呢？

我当时想表达的是这里的 CompletableFuture 已经完成运算了。我把这部分描述修改一下吧。
