### ISSUE TITLE
关于volatile关键字不具有原子性操作的例子

### ISSUE THREAD

**Issue by SchafferJ** [Snailclimb/JavaGuide#178]
在[Java多线程学习（三）volatile关键字](https://blog.csdn.net/qq_34337272/article/details/79680771)这篇文章中对volatile关键字不具有原子操作的例子并不能说明volatile不具有原子性，打印结果会出现非99（例子中的74）是由于该线程执行到打印行的时候其他线程还处于循环中，所以加synchronized关键字不过是让线程执行到打印行的时候其他线程无法拿到锁进入循环，原子性**不等于**同步。

**Comment by Silverados** [comment]
同意。正如你说的：打印结果会出现非99（例子中的74）是由于该线程执行到打印行的时候其他线程还处于循环中，其他线程对static的变量count进行了修改，而volatile会立即将值刷新到内存，这时候打印的就不是99。这无法证实作者的论点。

**Comment by Snailclimb** [comment]
目前正在利用业余时间重构多线程知识，感谢楼上两位指出！

**Comment by maxwellens** [comment]
补充一点关于volatile和原子性的关系。32位虚拟机下，long和double的取值和赋值操作不是原子操作（会分成两条指令），但是如果volatile修饰long和double变量，可以保证变量的取值和赋值操作具有原子性。

**Comment by yuechuanx** [comment]
《Java核心技术卷一》14.5.8节对volatile的说明：volatile 变量不提供原子性
![image](https://user-images.githubusercontent.com/19339293/54619972-69b1e600-4aa0-11e9-8142-0c61f61402cd.png)

**Comment by faaronzheng** [comment]
count=i是原子操作么？count=1才是原子操作吧

**Comment by faaronzheng** [comment]
public class Run {
    public static void main(String[] args) {
        int a=0;
        int b=1;
        a=b;
    }
}

Code:
      stack=1, locals=3, args_size=1
         0: iconst_0
         1: istore_1
         2: iconst_1
         3: istore_2
         4: iload_2
         5: istore_1
         6: return

**Comment by yunshuipiao** [comment]
> 目前正在利用业余时间重构多线程知识，感谢楼上两位指出！

我最近面试遇到多线程也答的不好，多学习

**Comment by Xiaoyang-Zhu** [comment]
还有一个问题，就是在 [synchronized关键字里面的](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Multithread/JavaConcurrencyAdvancedCommonInterviewQuestions.md) 单例模式的代码中，解释到 uniqueInstance “使用 volatile 可以禁止 JVM 的指令重排，保证在多线程环境下也能正常运行“，但是代码里 new Singleton() 本身就被 synchronized修释了，也就是说，不会被多线程同时执行。所以，我认为这里的解释应是， 使用 volatile 可以保证 变量 uniqueInstance的可见性 （一个线程更新后，另一个线程会马上知道内容变了），而不是顺序性（JVM指令重排）。

**Comment by sanwancoder** [comment]
> > 目前正在利用业余时间重构多线程知识，感谢楼上两位指出！
> 
> 我最近面试遇到多线程也答的不好，多学习

https://github.com/sanwancoder/mashibing_concurrent.git  希望对你有帮助
