### ISSUE TITLE
关于 ArrayList 源码阅读部分，ensureCapacity 调用前后速度的问题

### ISSUE THREAD

**Issue by walkkong** [Snailclimb/JavaGuide#1785]
[文章链接](https://javaguide.cn/java/collection/arraylist-source-code.html#_3-3-system-arraycopy-%E5%92%8C-arrays-copyof-%E6%96%B9%E6%B3%95)

您在文中提到，ArrayList 的 ensureCapacity 在增加大量元素时，调用会让速度更快。但是在我用您的测试例子，发现用后速度反而更慢。

用前：300ms 左右

用后：3000 ms 左右

我的 Java 基础环境是 jdk1.8。

**Comment by Snailclimb** [comment]
> 

我运行的结果还是两者差距不是很大。

![image](https://user-images.githubusercontent.com/29880145/183314512-c11f2534-98af-409f-b0b1-9663c127d278.png)
