### ISSUE TITLE
文件名包含： win系统无法clone

### ISSUE THREAD

**Issue by PolarBears-DontEat-IceCream** [Snailclimb/JavaGuide#1794]
(https://github.com/Snailclimb/JavaGuide/tree/main/docs/system-design/security/images/design-of-authority-system)/design-of-authority-system:role-and-user-management.png
您好，刚更新的这个文件名能否修改下，win系统下不了：的文件名。

**Comment by Snailclimb** [comment]
> (https://github.com/Snailclimb/JavaGuide/tree/main/docs/system-design/security/images/design-of-authority-system)/design-of-authority-system:role-and-user-management.png 您好，刚更新的这个文件名能否修改下，win系统下不了：的文件名。

好的
