### ISSUE TITLE
作者你好，有个文件在windows下无法下载，能麻烦看下

### ISSUE THREAD

**Issue by SmallSayBye** [Snailclimb/JavaGuide#1804]
![image](https://user-images.githubusercontent.com/11520064/185883849-8e397979-ca16-4e33-aa3c-74d7a9ff2576.png)

路径为：docs/system-design/security/images/design-of-authority-system/design-of-authority-system:role-and-user-management.png
因为windows下路径不能存在 ":"  .所以在windows下克隆时，会报错。谢谢啦

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/11520064/185883849-8e397979-ca16-4e33-aa3c-74d7a9ff2576.png)
> 
> 路径为：docs/system-design/security/images/design-of-authority-system/design-of-authority-system:role-and-user-management.png 因为windows下路径不能存在 ":" .所以在windows下克隆时，会报错。谢谢啦

已经修正了这个图片问的文件名，你重新拉取试试。

**Comment by SmallSayBye** [comment]
好的，非常感谢~

**Comment by Snailclimb** [comment]
> 好的，非常感谢~

不客气的，小事！
