### ISSUE TITLE
请问你的java guide网站是怎么弄的，我也想弄一个自己的guide

### ISSUE THREAD

**Issue by yangzhanlong** [Snailclimb/JavaGuide#1814]

**Comment by Snailclimb** [comment]
好问题！

项目介绍文章里有写哈：https://javaguide.cn/javaguide/intro.html

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/29880145/188316664-dcab66a3-52d8-4a60-bbbb-0adb440126f9.png">

**Comment by yangzhanlong** [comment]
感觉挺复杂的，那是要自己搭建一个服务器吗？

**Comment by Snailclimb** [comment]
> 感觉挺复杂的，那是要自己搭建一个服务器吗？

不需要的，可以直接用Github 或者 Gitee 的 PAGES 服务，免费的。

**Comment by yangzhanlong** [comment]
> 

没有学过vue，这个还要学vue，太难了

**Comment by Snailclimb** [comment]
> > 
> 
> 没有学过vue，这个还要学vue，太难了

不用学vue，就跟着傻瓜教程，一步一步来就行了。

**Comment by yangzhanlong** [comment]
搞了一周我终于部署起来了，但是 我的链接是 xxx.github.io，我看你的不是啊，这个要怎么搞啊？

**Comment by yangzhanlong** [comment]
还有就是，我在预览的时候，icon是显示出来的，但是部署之后，icon不见了

**Comment by yangzhanlong** [comment]
大佬，有个问题困扰我好久了，为什么我这个无法展开的？  我在本地是可以展开，一部署到github page，就展开不了了

<img width="291" alt="image" src="https://user-images.githubusercontent.com/6387629/190956945-7d6b97a7-6a2a-4230-b4f1-2fb71a844d61.png">
