### ISSUE TITLE
JVM章节关于“堆空间基本结构”的描述存在问题。

### ISSUE THREAD

**Issue by RowanLiu97** [Snailclimb/JavaGuide#1817]
![image](https://user-images.githubusercontent.com/50400387/188532852-4660e08e-c727-4aba-a384-cb6899f54415.png)
堆内存中应该是不包含永久代的吧？

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/50400387/188532852-4660e08e-c727-4aba-a384-cb6899f54415.png) 堆内存中应该是不包含永久代的吧？

方法区的Class信息,又称为永久代,是否属于Java堆？：https://www.zhihu.com/question/49044988
