### ISSUE TITLE
计算机基础的Https介绍章节中“对该公钥采用散列技术生成一个摘要”疑似有误

### ISSUE THREAD

**Issue by EscapeReality846089495** [Snailclimb/JavaGuide#1820]
经过查阅，Https的消息摘要应该是整份证书散列后得到的，而非仅公钥散列得到，此句描述有误
![image](https://user-images.githubusercontent.com/46855992/189021396-3fc083a8-83a5-4d63-adf4-b6ce52c20c03.png)

**Comment by Snailclimb** [comment]
> 经过查阅，Https的消息摘要应该是整份证书散列后得到的，而非仅公钥散列得到，此句描述有误 ![image](https://user-images.githubusercontent.com/46855992/189021396-3fc083a8-83a5-4d63-adf4-b6ce52c20c03.png)

个人觉得这个使用公钥描述就足够了，主要验证对比就是这个公钥。
