### ISSUE TITLE
Redis常见面试总结（上）中  Redis6.0 之前为什么不使用多线程？部分存在描述错误

### ISSUE THREAD

**Issue by RowanLiu97** [Snailclimb/JavaGuide#1822]
![image](https://user-images.githubusercontent.com/50400387/189076685-b8176775-ed2b-4644-998d-5722e453b3ff.png)
经查阅资料，FLUSHALL ASYNC（清空所有数据库的所有 key，不仅仅是当前 select 的数据库）、FLUSHDB ASYNC（清空当前 select 数据库中的所有 key）
参考资料地址：https://www.redis.com.cn/commands/flushall.html

**Comment by Snailclimb** [comment]
> 清空当前 select 数据库中的所有 key

感谢支持，已经修复，网站会晚点重新部署同步。
