### ISSUE TITLE
关于kafka的asks=all的描述好像有点不准确

### ISSUE THREAD

**Issue by NAME005** [Snailclimb/JavaGuide#1832]
https://kafka.apache.org/documentation/#brokerconfigs
acks=all This means the leader will wait for the full set of in-sync replicas to acknowledge the record. This guarantees that the record will not be lost as long as at least one in-sync replica remains alive. This is the strongest available guarantee. This is equivalent to the acks=-1 setting.

acks=all应该是所有ISR列表的副本到消息之后算成功发送，不需要所有副本都接收。

**Comment by Snailclimb** [comment]
> 所有ISR列表的副本

已经修改，感谢指出错误。
