### ISSUE TITLE
Java SPI 机制详解文章里有个错别字

### ISSUE THREAD

**Issue by chenzijia12300** [Snailclimb/JavaGuide#1833]
![image](https://user-images.githubusercontent.com/48479242/192553733-3e360ca3-27e6-40e4-a55a-0fc17e8c6ae6.png)
“过个”应该是“多个”把

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/48479242/192553733-3e360ca3-27e6-40e4-a55a-0fc17e8c6ae6.png) “过个”应该是“多个”把

感谢指出，已经修改。
