### ISSUE TITLE
slf4j 介绍容易引起误解

### ISSUE THREAD

**Issue by wecgwm** [Snailclimb/JavaGuide#1838]
[Java SPI 机制详解](https://javaguide.cn/java/basis/spi.html#%E5%AE%9E%E6%88%98%E6%BC%94%E7%A4%BA)下关于 slf4j 介绍是否容易产生误解？实际上 slf4j 与 spring 并没有什么关系

**Comment by Snailclimb** [comment]
#1837 感谢指出👍
