### ISSUE TITLE
JavaGuide/Java相关/synchronized.md 章节的内容说得不够具体

### ISSUE THREAD

**Issue by friends110110** [Snailclimb/JavaGuide#184]
1.偏向锁 是否指jvm 运行时消除锁同步，而 消除锁 是否 是jvm编译时 消除了锁？
2.自旋锁 空等待多长时间？ 自旋锁是否与轻量级锁 都用到了CAS的意思？

我觉得这章节 这些概念的介绍说得还是不够具体，不够细化

**Comment by Snailclimb** [comment]
这部分内容建议自己可以去查一下，详解的话也没有必要，比较晦涩难懂！

**Comment by friends110110** [comment]
@Snailclimb 就怕面试官会问得深，或许可以收集相关的资料放上去？
