### ISSUE TITLE
关于面试题总结"JMM（Java 内存模型）详解"一文的"从 CPU 缓存模型"小节图片一些个人个人不严谨的地方

### ISSUE THREAD

**Issue by shark-ctrl** [Snailclimb/JavaGuide#1848]
guide哥绘制的CPU Cache 示意图如图所示:
![image](https://user-images.githubusercontent.com/56210926/197372010-4e57a3fb-1cc3-46b6-8522-eec3307fe8e9.png)

参考网上文章，我认为CPU Cache应该分为3级:
1. L1 cache为CPU私有，相较于其他两种缓存更加接近CPU，访问速度差不多2-4个时钟周期。
2. L2 cache为CPU私有，访问速度差不多10-20个时钟周期。
3. L3 Cache，所有物理核共享，是最慢的一级，访问速度差不多20-60个时钟周期。

由上所述，我建议图片应该改为下面这个样子

![image](https://user-images.githubusercontent.com/56210926/197372160-43a4caf2-9e0d-4385-aec3-31900a745575.png)

详情可参阅:
1. https://zhuanlan.zhihu.com/p/370057417
2. 《深入理解高并发编程》 6.1.2 章节CPU多级缓存架构原理
![image](https://user-images.githubusercontent.com/56210926/197372259-465c636a-f2a2-4ec6-815d-43a5792bd93c.png)

**Comment by Snailclimb** [comment]
> guide哥绘制的CPU Cache 示意图如图所示: ![image](https://user-images.githubusercontent.com/56210926/197372010-4e57a3fb-1cc3-46b6-8522-eec3307fe8e9.png)
> 
> 参考网上文章，我认为CPU Cache应该分为3级:
> 
> 1. L1 cache为CPU私有，相较于其他两种缓存更加接近CPU，访问速度差不多2-4个时钟周期。
> 2. L2 cache为CPU私有，访问速度差不多10-20个时钟周期。
> 3. L3 Cache，所有物理核共享，是最慢的一级，访问速度差不多20-60个时钟周期。
> 
> 由上所述，我建议图片应该改为下面这个样子
> 
> ![image](https://user-images.githubusercontent.com/56210926/197372160-43a4caf2-9e0d-4385-aec3-31900a745575.png)
> 
> 详情可参阅:
> 
> 1. https://zhuanlan.zhihu.com/p/370057417
> 2. 《深入理解高并发编程》 6.1.2 章节CPU多级缓存架构原理
>    ![image](https://user-images.githubusercontent.com/56210926/197372259-465c636a-f2a2-4ec6-815d-43a5792bd93c.png)

感谢，我这块画的确实不准确，会尽快抽时间完善。

**Comment by Snailclimb** [comment]
> guide哥绘制的CPU Cache 示意图如图所示: ![image](https://user-images.githubusercontent.com/56210926/197372010-4e57a3fb-1cc3-46b6-8522-eec3307fe8e9.png)
> 
> 参考网上文章，我认为CPU Cache应该分为3级:
> 
> 1. L1 cache为CPU私有，相较于其他两种缓存更加接近CPU，访问速度差不多2-4个时钟周期。
> 2. L2 cache为CPU私有，访问速度差不多10-20个时钟周期。
> 3. L3 Cache，所有物理核共享，是最慢的一级，访问速度差不多20-60个时钟周期。
> 
> 由上所述，我建议图片应该改为下面这个样子
> 
> ![image](https://user-images.githubusercontent.com/56210926/197372160-43a4caf2-9e0d-4385-aec3-31900a745575.png)
> 
> 详情可参阅:
> 
> 1. https://zhuanlan.zhihu.com/p/370057417
> 2. 《深入理解高并发编程》 6.1.2 章节CPU多级缓存架构原理
>    ![image](https://user-images.githubusercontent.com/56210926/197372259-465c636a-f2a2-4ec6-815d-43a5792bd93c.png)

已修正。


![Uploading image.png…]()

**Comment by kindear** [comment]
good good
