### ISSUE TITLE
面试指南-Java-JVM-2.2中：XX:NewRatio=<int>代表老年代与新生代的比值

### ISSUE THREAD

**Issue by KylehsuXu** [Snailclimb/JavaGuide#1858]
### 在[链接](https://javaguide.cn/java/jvm/jvm-parameters-intro.html#_2-2-%E6%98%BE%E5%BC%8F%E6%96%B0%E7%94%9F%E4%BB%A3%E5%86%85%E5%AD%98-young-generation)中，
> 面试指南-Java-JVM-2.2：
- -XX:NewRatio=<int> 代表老年代与新生代的比值，而不是新生代与老年代的比值
- 可参考[oracle javase 13 docs](https://docs.oracle.com/en/java/javase/13/docs/specs/man/java.html)，也可以开启GC日志查看

**Comment by Snailclimb** [comment]
> 

已修正，感谢您👍

<img width="869" alt="image" src="https://user-images.githubusercontent.com/29880145/199212369-28fde419-d6a8-40e3-857b-7ed6a0d36d9b.png">

**Comment by maoliziCC** [comment]
您发的邮件，已收到 O(∩_∩)O~  我会尽快查看滴
