### ISSUE TITLE
Redis - Redis常见面试题总结(上) - 缓存数据的处理流程图不完整

### ISSUE THREAD

**Issue by liubobo1996** [Snailclimb/JavaGuide#1863]
![redis](https://user-images.githubusercontent.com/66815197/199499185-1860ed2b-03b0-477c-a7dc-4af958a50330.png)

**Comment by Snailclimb** [comment]
> ![redis](https://user-images.githubusercontent.com/66815197/199499185-1860ed2b-03b0-477c-a7dc-4af958a50330.png)

嗯嗯，处理流程和对应的缓存更新策略有关系，我把这个问题移除了哈。
