### ISSUE TITLE
String s = new String("abc"); 创建对象问题

### ISSUE THREAD

**Issue by BinchaoPeng** [Snailclimb/JavaGuide#1869]
对于这一部分，感觉描述比较模糊，过程不够具体，不然步骤复现。
**原文**：
```bash
1、如果字符串常量池中不存在字符串对象“abc”的引用，那么会在堆中创建 2 个字符串对象“abc”。
      堆中创建String对象，堆中创建字符串“abc”对象。
2、如果字符串常量池中已存在字符串对象“abc”的引用，则只会在堆中创建 1 个字符串对象“abc”。
```
**疑惑**：
按照1的说法，关键对象有：字符串对象的引用（在常量池中），String对象（new出来的），字符串“abc”对象，在字符串数据中，要这三者齐全才是正常的。 串起来就是：栈中的引用s指向堆里的String对象，String对象指向常量池的字符串对象引用，字符串对象引用最后指向堆里的字符串对象“abc”；
那么，在2中，就没有了String对象。难道不是常量池里有字符串对象“abc”的引用，它已经指向了“abc”，所以应该新建的String对象，去指向这个常量池的引用嘛？

**Comment by Snailclimb** [comment]
> ```shell
> 、如果字符串常量池中不存在字符串对象
> ```

原文中通过分析字节码来解释看着应该更清晰一些吧？

**Comment by BinchaoPeng** [comment]
> 我认为在常量池中有字符串对象“abc”的引用的情况下，`String s = new String("abc")`，应该是创建了一个String对象啊，这样String对象会指向常量池中的引用。
而，`String s = "abc"`,就不用创建String对象，是直接指向常量池的引用。、
我的疑惑点在这里

**Comment by BinchaoPeng** [comment]
也就是 `new String("abc")`其实由String对象和“abc”对象构成，这两个是区分开的
