### ISSUE TITLE
java语法糖详解-可能遇到的坑-增强 for 循环

### ISSUE THREAD

**Issue by alanleung2017** [Snailclimb/JavaGuide#1871]
这一小节的demo好像跟Iterator.remove() 没有任何关系

**Comment by Snailclimb** [comment]
> 这一小节的demo好像跟Iterator.remove() 没有任何关系

参考一下这里的介绍：https://javaguide.cn/java/collection/java-collection-precautions-for-use.html#%E9%9B%86%E5%90%88%E9%81%8D%E5%8E%86
