### ISSUE TITLE
图片大部分无法访问

### ISSUE THREAD

**Issue by RikudouPatrickstar** [Snailclimb/JavaGuide#1874]
网站上以 https://guide-blog-images.oss-cn-shenzhen.aliyuncs.com 开头的 url 和语雀的 url 都查看不了，在 github 页面中查看正常。可以把图片也放入项目中吗？本来以为下载到本地应该能看，结果链接都是指向那两个站点的。。。

**Comment by Snailclimb** [comment]
> 网站上以 https://guide-blog-images.oss-cn-shenzhen.aliyuncs.com 开头的 url 和语雀的 url 都查看不了，在 github 页面中查看正常。可以把图片也放入项目中吗？本来以为下载到本地应该能看，结果链接都是指向那两个站点的。。。

你刷新试试，我这边正常显示没问题的。

**Comment by RikudouPatrickstar** [comment]
清过缓存了，但网页上面还是加载不出来，chrome 和 firefox 都是。调试工具里面复制 URL 出来访问又可以，神奇。。🙈
