### ISSUE TITLE
永久代也属于堆内存吗？

### ISSUE THREAD

**Issue by 20170702102** [Snailclimb/JavaGuide#1875]
永久代是方法区的实现，他为什么会跟堆内存有关呢？
![image](https://user-images.githubusercontent.com/41622231/203003904-311ef3e9-a40e-4632-a125-b5981e5838af.png)

**Comment by Snailclimb** [comment]
> 永久代是方法区的实现，他为什么会跟堆内存有关呢？ ![image](https://user-images.githubusercontent.com/41622231/203003904-311ef3e9-a40e-4632-a125-b5981e5838af.png)

方法区属于是 JVM 运行时数据区域的一块逻辑区域，是各个线程共享的内存区域。《Java 虚拟机规范》只是规定了有方法区这么个概念和它的作用，方法区到底要如何实现那就是虚拟机自己要考虑的事情了。也就是说，在不同的虚拟机实现上，方法区的实现是不同的。

方法区和永久代以及元空间的关系很像 Java 中接口和类的关系，类实现了接口，这里的类就可以看作是永久代和元空间，接口可以看作是方法区，也就是说永久代以及元空间是 HotSpot 虚拟机对虚拟机规范中方法区的两种实现方式。并且，永久代是 JDK 1.8 之前的方法区实现，JDK 1.8 及以后方法区的实现变成了元空间。
