### ISSUE TITLE
幻读在可重复读级别下加锁无法完全解决幻读

### ISSUE THREAD

**Issue by tang-world** [Snailclimb/JavaGuide#1880]
原文中写的是，可以加上以下处理方法后可以防止在事务过程中，其他事务进行的新增和删除操作。
那么修改操作是无法防止的，所以说加上以下处理方法后，无法完全解决幻读问题，只能部分解决。

原文如下：
就比如 REPEATABLE-READ 在当前读情况下需要使用加锁读来保证不会出现幻读。

**Comment by 2firenut** [comment]
对，这块确实有问题

> 原文中写的是，可以加上以下处理方法后可以防止在事务过程中，其他事务进行的新增和删除操作。 那么修改操作是无法防止的，所以说加上以下处理方法后，无法完全解决幻读问题，只能部分解决。
> 
> 原文如下： 就比如 REPEATABLE-READ 在当前读情况下需要使用加锁读来保证不会出现幻读。

**Comment by Snailclimb** [comment]
> 就比如 REPEATABLE-READ

快照读下应该是解决了幻读的问题：https://heapdump.cn/article/4547714
