### ISSUE TITLE
为什么serialVersionUID会被序列化

### ISSUE THREAD

**Issue by LittleWhiteMouse9527** [Snailclimb/JavaGuide#1889]
private static final long serialVersionUID = 1L;

不是说static修饰的属性不会被序列化吗，是在序列化的时候做了什么操作吗

**Comment by Snailclimb** [comment]
> private static final long serialVersionUID = 1L;
> 
> 不是说static修饰的属性不会被序列化吗，是在序列化的时候做了什么操作吗

这篇文章里面有写哈：https://javaguide.cn/java/basis/serialization.html#jdk-%E8%87%AA%E5%B8%A6%E7%9A%84%E5%BA%8F%E5%88%97%E5%8C%96%E6%96%B9%E5%BC%8F

**serialVersionUID 有什么作用？**

序列化号 serialVersionUID 属于版本控制的作用。反序列化时，会检查 serialVersionUID 是否和当前类的 serialVersionUID 一致。如果 serialVersionUID 不一致则会抛出 InvalidClassException 异常。强烈推荐每个序列化类都手动指定其 serialVersionUID，如果不手动指定，那么编译器会动态生成默认的 serialVersionUID。

**serialVersionUID 不是被 static 变量修饰了吗？为什么还会被“序列化”？**

static 修饰的变量是静态变量，位于方法区，本身是不会被序列化的。 static 变量是属于类的而不是对象。你反序列之后，static 变量的值就像是默认赋予给了对象一样，看着就像是 static 变量被序列化，实际只是假象罢了。

**Comment by WuMiaoGao** [comment]
> > private static final long serialVersionUID = 1L;
> > 不是说static修饰的属性不会被序列化吗，是在序列化的时候做了什么操作吗
> 
> 这篇文章里面有写哈：https://javaguide.cn/java/basis/serialization.html#jdk-%E8%87%AA%E5%B8%A6%E7%9A%84%E5%BA%8F%E5%88%97%E5%8C%96%E6%96%B9%E5%BC%8F
> 
> **serialVersionUID 有什么作用？**
> 
> 序列化号 serialVersionUID 属于版本控制的作用。反序列化时，会检查 serialVersionUID 是否和当前类的 serialVersionUID 一致。如果 serialVersionUID 不一致则会抛出 InvalidClassException 异常。强烈推荐每个序列化类都手动指定其 serialVersionUID，如果不手动指定，那么编译器会动态生成默认的 serialVersionUID。
> 
> **serialVersionUID 不是被 static 变量修饰了吗？为什么还会被“序列化”？**
> 
> static 修饰的变量是静态变量，位于方法区，本身是不会被序列化的。 static 变量是属于类的而不是对象。你反序列之后，static 变量的值就像是默认赋予给了对象一样，看着就像是 static 变量被序列化，实际只是假象罢了。

反序列化时所比对的serialVersionUID是从字节流中读取的吧，那么字节流中存储的这个serialVersionUID不属于序列化吗？

**Comment by WuMiaoGao** [comment]
> > private static final long serialVersionUID = 1L;
> > 不是说static修饰的属性不会被序列化吗，是在序列化的时候做了什么操作吗
> 
> 这篇文章里面有写哈：https://javaguide.cn/java/basis/serialization.html#jdk-%E8%87%AA%E5%B8%A6%E7%9A%84%E5%BA%8F%E5%88%97%E5%8C%96%E6%96%B9%E5%BC%8F
> 
> **serialVersionUID 有什么作用？**
> 
> 序列化号 serialVersionUID 属于版本控制的作用。反序列化时，会检查 serialVersionUID 是否和当前类的 serialVersionUID 一致。如果 serialVersionUID 不一致则会抛出 InvalidClassException 异常。强烈推荐每个序列化类都手动指定其 serialVersionUID，如果不手动指定，那么编译器会动态生成默认的 serialVersionUID。
> 
> **serialVersionUID 不是被 static 变量修饰了吗？为什么还会被“序列化”？**
> 
> static 修饰的变量是静态变量，位于方法区，本身是不会被序列化的。 static 变量是属于类的而不是对象。你反序列之后，static 变量的值就像是默认赋予给了对象一样，看着就像是 static 变量被序列化，实际只是假象罢了。

反序列化时所比对的serialVersionUID是从字节流中读取的吧，那么字节流中存储的这个serialVersionUID不属于序列化吗？
