### ISSUE TITLE
【MyBatis常见面试题总结】中存在文档格式问题

### ISSUE THREAD

**Issue by MrXionGe** [Snailclimb/JavaGuide#1891]
#### 页面
![image](https://user-images.githubusercontent.com/23261935/210510499-8ec15f64-3e15-4521-b681-a5f959d2b2f6.png)
#### 链接
https://javaguide.cn/system-design/framework/mybatis/mybatis-interview.html#mybatis-%E9%83%BD%E6%9C%89%E5%93%AA%E4%BA%9B-executor-%E6%89%A7%E8%A1%8C%E5%99%A8-%E5%AE%83%E4%BB%AC%E4%B9%8B%E9%97%B4%E7%9A%84%E5%8C%BA%E5%88%AB%E6%98%AF%E4%BB%80%E4%B9%88
#### 问题
在介绍三种基本的Executor执行器时，BatchExecutor没有换行。

**Comment by Snailclimb** [comment]
> #### 页面
> ![image](https://user-images.githubusercontent.com/23261935/210510499-8ec15f64-3e15-4521-b681-a5f959d2b2f6.png)
> 
> #### 链接
> https://javaguide.cn/system-design/framework/mybatis/mybatis-interview.html#mybatis-%E9%83%BD%E6%9C%89%E5%93%AA%E4%BA%9B-executor-%E6%89%A7%E8%A1%8C%E5%99%A8-%E5%AE%83%E4%BB%AC%E4%B9%8B%E9%97%B4%E7%9A%84%E5%8C%BA%E5%88%AB%E6%98%AF%E4%BB%80%E4%B9%88
> 
> #### 问题
> 在介绍三种基本的Executor执行器时，BatchExecutor没有换行。

感谢指出，已经修改了，近期会重新部署一遍网站。
