### ISSUE TITLE
JMM缺少严谨的描述

### ISSUE THREAD

**Issue by jizhuozhi** [Snailclimb/JavaGuide#1899]
在任何语言中，包括C++，Go，Java等都有定义自己的内存模型，它们定义的内存模型都大同小异：解决在并发执行过程中，共享变量的修改在另一个线程中的可见性。

由于内存模型在C/C++提前被定义为内存布局，因此额外引入了memory_order(内存顺序)来表示并发执行过程中的执行和副作用的生效顺序，但是其本身和可见性是相同的。

https://en.cppreference.com/w/c/atomic/memory_order
https://en.cppreference.com/w/cpp/atomic/memory_order
https://go.dev/ref/mem
https://download.oracle.com/otn-pub/jcp/memory_model-1.0-pfd-spec-oth-JSpec/memory_model-1_0-pfd-spec.pdf

但是在jmm.md中用了大量的篇幅介绍体系结构相关知识，并没有明确表示定义内存模型的目标，应当对定义内存模型的目标进行严谨的表述

**Comment by Snailclimb** [comment]
> 在任何语言中，包括C++，Go，Java等都有定义自己的内存模型，它们定义的内存模型都大同小异：解决在并发执行过程中，共享变量的修改在另一个线程中的可见性。
> 
> 由于内存模型在C/C++提前被定义为内存布局，因此额外引入了memory_order(内存顺序)来表示并发执行过程中的执行和副作用的生效顺序，但是其本身和可见性是相同的。
> 
> https://en.cppreference.com/w/c/atomic/memory_order https://en.cppreference.com/w/cpp/atomic/memory_order https://go.dev/ref/mem https://download.oracle.com/otn-pub/jcp/memory_model-1.0-pfd-spec-oth-JSpec/memory_model-1_0-pfd-spec.pdf
> 
> 但是在jmm.md中用了大量的篇幅介绍体系结构相关知识，并没有明确表示定义内存模型的目标，应当对定义内存模型的目标进行严谨的表述

感谢，已经看到 PR了。
