### ISSUE TITLE
发现一个问题

### ISSUE THREAD

**Issue by pojozhang** [Snailclimb/JavaGuide#19]
https://github.com/Snailclimb/JavaGuide/blob/master/Java%E7%9B%B8%E5%85%B3/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md  
在第8点字符型常量和字符串常量的区别中，字符似乎是占2个字节的空间。

**Comment by debugjoker** [comment]
是的 char在Java中占两个字节

**Comment by HiAscend** [comment]
> 是的 char在Java中占两个字节

正确，补充如下，java编程思想第四版：2.2.2节
![image](https://user-images.githubusercontent.com/16573380/45525680-98f04d80-b806-11e8-8591-9e589f4263df.png)

**Comment by Snailclimb** [comment]
感谢各位提醒！非常感谢！
