### ISSUE TITLE
Java基础知识.md # 异常处理总结 建议添加

### ISSUE THREAD

**Issue by hades0525** [Snailclimb/JavaGuide#190]
如果try语句里有return，返回的是try语句块中变量值。 
详细执行过程如下：
a.如果有返回值，就把返回值保存到局部变量中；
b.执行jsr指令跳到finally语句里执行；
c.执行完finally语句后，返回之前保存在局部变量表里的值。
**如果try，finally语句里均有return，忽略try的return，而使用finally的return.

**Comment by Snailclimb** [comment]
感谢！已经添加！ @hades0525

**Comment by hashming** [comment]
可以理解为jvm在cpu中吗?

**Comment by QzP-QD** [comment]
感谢分享
