### ISSUE TITLE
书写小问题

### ISSUE THREAD

**Issue by ShouHuJiYi** [Snailclimb/JavaGuide#1908]
https://javaguide.cn/java/new-features/java9.html#%E6%A8%A1%E5%9D%97%E5%8C%96%E7%B3%BB%E7%BB%9F
这个地址上，下面这段代码中 com.·my.package.name to com.specific.package 应该是多了一个 ·
module my.module {
    //exports 公开指定包的所有公共成员
    exports com.my.package.name;
}

module my.module {
     //exports…to 限制访问的成员范围
    export com.·my.package.name to com.specific.package;
}
------
著作权归所有
原文链接：https://javaguide.cn/java/new-features/java9.html

**Comment by Snailclimb** [comment]
> com.·my.package.name to com.specific.package

对的，不小心打的一个点。
