### ISSUE TITLE
链表的删除插入的时间复杂度为O(n)吧，不是O(1)

### ISSUE THREAD

**Issue by chenjun-1201** [Snailclimb/JavaGuide#1914]

**Comment by Snailclimb** [comment]
> _No description provided._

**Comment by Snailclimb** [comment]
> _No description provided._

这里描述的比较详细，建议仔细看看：https://javaguide.cn/java/collection/java-collection-questions-01.html#collection-%E5%AD%90%E6%8E%A5%E5%8F%A3%E4%B9%8B-list

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/29880145/217468713-25f4e04b-16a2-4b14-b01a-22180da19770.png">
