### ISSUE TITLE
HTTP部分的勘误

### ISSUE THREAD

**Issue by RuiGao98** [Snailclimb/JavaGuide#1915]
![1675862233(1)](https://user-images.githubusercontent.com/52376684/217540816-575bdeab-2260-4adb-9065-6625c5b2d517.png)
HTTP是基于TCP还是UDP的？
HTTP3.0之前是基于TCP协议的，而HTTP3.0将弃用TCP，改用基于UDP的QUIC协议。
来源：https://zh.wikipedia.org/zh-tw/HTTP/3
https://datatracker.ietf.org/doc/rfc9114/

**Comment by Snailclimb** [comment]
> ![1675862233(1)](https://user-images.githubusercontent.com/52376684/217540816-575bdeab-2260-4adb-9065-6625c5b2d517.png) HTTP是基于TCP还是UDP的？ HTTP3.0之前是基于TCP协议的，而HTTP3.0将弃用TCP，改用基于UDP的QUIC协议。 来源：https://zh.wikipedia.org/zh-tw/HTTP/3 https://datatracker.ietf.org/doc/rfc9114/

感谢补充完善👍

**Comment by zhiyiYo** [comment]
> 另外，HTTP/2.0 需要经过经典的 TCP 三次握手过程（一般是 3 个 RTT）

这里有点疑惑，不应该是 1.5 个 RTT 吗

**Comment by Snailclimb** [comment]
> > 另外，HTTP/2.0 需要经过经典的 TCP 三次握手过程（一般是 3 个 RTT）
> 
> 这里有点疑惑，不应该是 1.5 个 RTT 吗

我描述的不太清楚，抱歉。

HTTP/2.0 需要经过经典的 TCP 三次握手过程（由于安全的 HTTP 连接建立还需要 TLS 握手，共需要大约 3 个 RTT）。由于 QUIC 协议的特性（TLS 1.3，TLS 1.3 除了支持 1 个 RTT 的握手，还支持 0 个 RTT 的握手）连接建立仅需 0-RTT 或者 1-RTT。这意味着 QUIC 在最佳情况下不需要任何的额外往返时间就可以建立新连接。

**Comment by zhiyiYo** [comment]
感谢解答
