### ISSUE TITLE
JVM垃圾回收详解中的一个错别字

### ISSUE THREAD

**Issue by w-40** [Snailclimb/JavaGuide#1918]
https://javaguide.cn/java/jvm/jvm-garbage-collection.html#g1-%E6%94%B6%E9%9B%86%E5%99%A8
空间整合：与 CMS 的“标记-清理”算法不同，G1 从整体来看是基于“标记-整理”算法实现的收集器；从局部上来看是基于“标记-复制”算法实现的。
这里的标记-清除算法打成了清理

**Comment by Snailclimb** [comment]
> https://javaguide.cn/java/jvm/jvm-garbage-collection.html#g1-%E6%94%B6%E9%9B%86%E5%99%A8 空间整合：与 CMS 的“标记-清理”算法不同，G1 从整体来看是基于“标记-整理”算法实现的收集器；从局部上来看是基于“标记-复制”算法实现的。 这里的标记-清除算法打成了清理

已修改统一，意思差不多。
