### ISSUE TITLE
关于survivor区满了之后，是否会触发GC

### ISSUE THREAD

**Issue by ronjod** [Snailclimb/JavaGuide#1919]
![image](https://user-images.githubusercontent.com/34700174/218288719-88173972-792f-486e-92f9-23ad3675a11e.png)
在大白话带你认识JVM的篇章中，3.3.7 Eden年轻代的介绍里，图片中描述survivor区存放满了之后，会触发minorgc，我查阅询问得出的结果是survivor区满了之后，并不会触发GC,每次minorgc的时候会对survivor区和eden区进行回收，存活的对象进入另一个survivor区，若Survivor区（S0或S1）放不下该对象，由于Survivor区满不会触发GC，故该对象会直接晋升到老年代中，想确认下是否有问题或我搞错了

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/34700174/218288719-88173972-792f-486e-92f9-23ad3675a11e.png) 在大白话带你认识JVM的篇章中，3.3.7 Eden年轻代的介绍里，图片中描述survivor区存放满了之后，会触发minorgc，我查阅询问得出的结果是survivor区满了之后，并不会触发GC,每次minorgc的时候会对survivor区和eden区进行回收，存活的对象进入另一个survivor区，若Survivor区（S0或S1）放不下该对象，由于Survivor区满不会触发GC，故该对象会直接晋升到老年代中，想确认下是否有问题或我搞错了

对的  S区满了不会 Minor GC，这里的描述存在问题，我会尽快修正。
