### ISSUE TITLE
关于引用传递的定义不准确

### ISSUE THREAD

**Issue by pqt124** [Snailclimb/JavaGuide#1921]
原文:引用传递：方法接收的直接是实参所引用的对象在堆中的地址。
我看c++中说引用传递是指形参指向的是实参变量的地址，而不是对象的地址。

**Comment by pqt124** [comment]
不知道为什么什么不说就关闭了话题，参考两篇文章吧
http://c.biancheng.net/view/1387.html
https://zhuanlan.zhihu.com/p/130464385

**Comment by Snailclimb** [comment]
> 

这里的描述在 Java 中的定义是没问题的吧。

**Comment by Snailclimb** [comment]
> 不知道为什么什么不说就关闭了话题，参考两篇文章吧 http://c.biancheng.net/view/1387.html https://zhuanlan.zhihu.com/p/130464385


这里的描述在 Java 中的定义是没问题的吧。你去找找 Java 中的定义的吧。

**Comment by pqt124** [comment]
> > 不知道为什么什么不说就关闭了话题，参考两篇文章吧 http://c.biancheng.net/view/1387.html https://zhuanlan.zhihu.com/p/130464385
> 
> 这里的描述在 Java 中的定义是没问题的吧。你去找找 Java 中的定义的吧。

“看到这里，相信你已经知道了 Java 中只有值传递，是没有引用传递的。” 这是你原文章的内容，也就是说java是没有引用传递的，那引用传递的定义就不应该是java的
