### ISSUE TITLE
网络部分的勘误

### ISSUE THREAD

**Issue by chanpero** [Snailclimb/JavaGuide#1922]
1. 《计算机网络常见面试题总结》Telent 协议   ->   Telnet协议
2. 《OSI 和 TCP/IP 网络分层模型详解（基础）》 复杂的网络间题  -> 复杂的网络问题
3. 《HTTP vs HTTPS（应用层）》通常把 HTTPS 中的核心加密协议混成为 SSL/TLS  -> 混称为  （不确定我理解的是否正确）
4. 《TCP 三次握手和四次挥手（传输层）》三次握手:客户端发送带有带有ACK(ACK=y+1) 标志的数据包   -> 带有重复
5. 《TCP 三次握手和四次挥手（传输层）》如果服务端没有因为某些原因而没有收到 ACK 的话  -> 如果服务端因为某些原因而没有收到 ACK 的话
6. 《TCP 传输可靠性保障（传输层）》就把发送放的 cwnd 加 1  -> 发送方
7. 《ARP 协议详解(网络层)》 多个接口都个各自维护一个 ARP 表 -> 都各自

**Comment by Snailclimb** [comment]
> 1. 《计算机网络常见面试题总结》Telent 协议   ->   Telnet协议
> 2. 《OSI 和 TCP/IP 网络分层模型详解（基础）》 复杂的网络间题  -> 复杂的网络问题
> 3. 《HTTP vs HTTPS（应用层）》通常把 HTTPS 中的核心加密协议混成为 SSL/TLS  -> 混称为  （不确定我理解的是否正确）
> 4. 《TCP 三次握手和四次挥手（传输层）》三次握手:客户端发送带有带有ACK(ACK=y+1) 标志的数据包   -> 带有重复
> 5. 《TCP 三次握手和四次挥手（传输层）》如果服务端没有因为某些原因而没有收到 ACK 的话  -> 如果服务端因为某些原因而没有收到 ACK 的话
> 6. 《TCP 传输可靠性保障（传输层）》就把发送放的 cwnd 加 1  -> 发送方
> 7. 《ARP 协议详解(网络层)》 多个接口都个各自维护一个 ARP 表 -> 都各自

感谢，如果能直接提交 pr 就更好了。

**Comment by Snailclimb** [comment]
> 7\. 多个接口都个


> 1. 《计算机网络常见面试题总结》Telent 协议   ->   Telnet协议
> 2. 《OSI 和 TCP/IP 网络分层模型详解（基础）》 复杂的网络间题  -> 复杂的网络问题
> 3. 《HTTP vs HTTPS（应用层）》通常把 HTTPS 中的核心加密协议混成为 SSL/TLS  -> 混称为  （不确定我理解的是否正确）
> 4. 《TCP 三次握手和四次挥手（传输层）》三次握手:客户端发送带有带有ACK(ACK=y+1) 标志的数据包   -> 带有重复
> 5. 《TCP 三次握手和四次挥手（传输层）》如果服务端没有因为某些原因而没有收到 ACK 的话  -> 如果服务端因为某些原因而没有收到 ACK 的话
> 6. 《TCP 传输可靠性保障（传输层）》就把发送放的 cwnd 加 1  -> 发送方
> 7. 《ARP 协议详解(网络层)》 多个接口都个各自维护一个 ARP 表 -> 都各自


前几个月就修正了，忘记在这里同步了。
