### ISSUE TITLE
关于分布式--API网关中Spring Cloud Gateway的描述讨论

### ISSUE THREAD

**Issue by Jidcoo** [Snailclimb/JavaGuide#1930]
### 讨论点：
![image](https://user-images.githubusercontent.com/65707480/221410598-ec00cc64-fa36-497a-ac07-2d6dd752e135.png)

### 我的看法：
其实Spring WebFlux底层实现的IO模型并不是真正意义上的异步IO模型，还是属于同步IO模型中的同步非阻塞模型。我们看起来的异步只是“编程模型”上的异步，最后数据从内核空间拷贝到用户空间的过程还是会阻塞，并不是真正意义上的异步IO。

不知道我的看法是否合理或者正常，欢迎讨论和指点。

**Comment by Snailclimb** [comment]
> ### 讨论点：
> ![image](https://user-images.githubusercontent.com/65707480/221410598-ec00cc64-fa36-497a-ac07-2d6dd752e135.png)
> 
> ### 我的看法：
> 其实Spring WebFlux底层实现的IO模型并不是真正意义上的异步IO模型，还是属于同步IO模型中的同步非阻塞模型。我们看起来的异步只是“编程模型”上的异步，最后数据从内核空间拷贝到用户空间的过程还是会阻塞，并不是真正意义上的异步IO。
> 
> 不知道我的看法是否合理或者正常，欢迎讨论和指点。

是这样的，我这里写的不够准确，感谢指出！

<img width="791" alt="image" src="https://user-images.githubusercontent.com/29880145/221449783-23d2d45e-b197-4207-9f85-f58240656229.png">

**Comment by Snailclimb** [comment]
@Jidcoo  网站会下个月进行同步，Github 上的已经修改了，地址：https://github.com/Snailclimb/JavaGuide/blob/main/docs/distributed-system/api-gateway.md 。
