### ISSUE TITLE
AID->C.drawio  Windows下检出出现错误

### ISSUE THREAD

**Issue by wodeu2** [Snailclimb/JavaGuide#1935]
涉及文件 JavaGuide/docs/database/mysql/images/AID->C.drawio 
由于 windows 系统不支持 AID->C.drawio 这样的命名格式，导致git clone 出现错误：git error unable to create file Invalid argument ，希望能修改下该文件命名。

**Comment by Snailclimb** [comment]
> AID->C

好的
