### ISSUE TITLE
元空间使用的本地内存吧？

### ISSUE THREAD

**Issue by partyabu** [Snailclimb/JavaGuide#1945]
![image](https://user-images.githubusercontent.com/96345331/223133407-49aa9985-0549-47b3-98ff-169f9b9f2f81.png)

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/96345331/223133407-49aa9985-0549-47b3-98ff-169f9b9f2f81.png)

直接内存（Direct Memory） 并不是虚拟机运行时数据区的一部分，也不是《Java虚拟机规范》中定义的内存区域。

- 直接内存是由本地内存分配的，因此直接内存受本机总内存大小的限制。
- 堆外内存：把内存对象分配在Java虚拟机堆以外的内存
- 堆外内存直接受操作系统管理（而不是虚拟机），这样做的结果就是能够在一定程度上减少垃圾回收（GC）对应用程序造成的影响。
- 在一些文章中将直接内存等价于堆外内存。

**Comment by partyabu** [comment]
![image](https://user-images.githubusercontent.com/96345331/223146191-23b99cfa-581b-424f-9c13-b40d14c08b8e.png)
那元空间使用的到底是直接内存还是本地内存？

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/96345331/223146191-23b99cfa-581b-424f-9c13-b40d14c08b8e.png) 那元空间使用的到底是直接内存还是本地内存？

直接内存就是在本地内存上分配的。

> ![image](https://user-images.githubusercontent.com/96345331/223146191-23b99cfa-581b-424f-9c13-b40d14c08b8e.png) 那元空间使用的到底是直接内存还是本地内存？

本地内存更准确一些。

**Comment by Snailclimb** [comment]
> > ![image](https://user-images.githubusercontent.com/96345331/223146191-23b99cfa-581b-424f-9c13-b40d14c08b8e.png) 那元空间使用的到底是直接内存还是本地内存？
> 
> 直接内存就是在本地内存上分配的。
> 
> > ![image](https://user-images.githubusercontent.com/96345331/223146191-23b99cfa-581b-424f-9c13-b40d14c08b8e.png) 那元空间使用的到底是直接内存还是本地内存？
> 
> 本地内存更准确一些。我去统一一下。
