### ISSUE TITLE
Redis常见面试题总结(上) RDB中bgsave指令介绍描述错误

### ISSUE THREAD

**Issue by Ku-M** [Snailclimb/JavaGuide#1948]
> Redis 提供了两个命令来生成 RDB 快照文件： 
> save : 主线程执行，会阻塞主线程；
> bgsave : 子线程执行，不会阻塞主线程，默认选项。

bgsave调用的是子进程。在bgsaveCommand函数中通过redisFork函数创建子进程。

**Comment by Snailclimb** [comment]
> bgsave

感谢指出，已经修复：

<img width="682" alt="image" src="https://user-images.githubusercontent.com/29880145/224518241-371a47bd-6a7c-48a5-b33d-c756ca36a879.png">
