### ISSUE TITLE
Java 并发常见面试题总结（中）读锁为什么不能升级为写锁？这一问题中描述有误

### ISSUE THREAD

**Issue by NanXun-wyd** [Snailclimb/JavaGuide#1949]
当一个线程获得了写锁之后，如果想要降级为读锁，需要先释放写锁，再获取读锁。因为写锁是独占锁，其他线程无法获取写锁，所以在写锁降级为读锁的过程中不会有线程的争夺，也不会影响性能。
但是，读锁无法升级为写锁，因为读锁是共享锁，多个线程可以同时获取读锁，如果将读锁升级为写锁，会导致其他线程无法获取读锁，从而引起线程的争夺，影响性能。因此，如果一个线程获得了读锁，想要获取写锁，必须先释放读锁，再获取写锁。

而原文中的描述是 ： 写锁降级为读锁会引起线程的争夺

**Comment by Snailclimb** [comment]
> 如果想要降级为读锁

这里笔误了，前几天已经修正了。

<img width="739" alt="image" src="https://user-images.githubusercontent.com/29880145/224518007-f3f484f3-5ff8-4d6a-bd07-f4d3dfd0846c.png">
