### ISSUE TITLE
Java 并发常见面试题总结（下） 可能存在的笔误

### ISSUE THREAD

**Issue by NanXun-wyd** [Snailclimb/JavaGuide#1952]
1、线程池的饱和策略有哪些？
原文中：对于可伸缩的应用程序，建议使用 ThreadPoolExecutor.CallerRunsPolicy。当最大池被填满时，此策略为我们提供**可伸缩队列**。
![image](https://user-images.githubusercontent.com/58164619/224765534-76dc87eb-04e1-4524-a943-5dcb0fbf5699.png)
而源代码中只是使用调用者线程来执行新任务并没有看到可伸缩队列的相关代码。

**Comment by Snailclimb** [comment]
> 对于可伸缩的应用程序

感谢指出，这里笔误了，已修改。

举个例子：Spring 通过 `ThreadPoolTaskExecutor` 或者我们直接通过 `ThreadPoolExecutor` 的构造函数创建线程池的时候，当我们不指定 `RejectedExecutionHandler` 饱和策略来配置线程池的时候，默认使用的是 `AbortPolicy`。在这种饱和策略下，如果队列满了，`ThreadPoolExecutor` 将抛出 `RejectedExecutionException` 异常来拒绝新来的任务 ，这代表你将丢失对这个任务的处理。如果不想丢弃任务的话，可以使用`CallerRunsPolicy`。`CallerRunsPolicy` 和其他的几个策略不同，它既不会抛弃任务，也不会抛出异常，而是将任务回退给调用者，使用调用者的线程来执行任务

```java
public static class CallerRunsPolicy implements RejectedExecutionHandler {
  
        public CallerRunsPolicy() { }

        public void rejectedExecution(Runnable r, ThreadPoolExecutor e) {
            if (!e.isShutdown()) {
                // 直接主线程执行，而不是线程池中的线程执行
                r.run();
            }
        }
    }
```
