### ISSUE TITLE
《Java 线程池最佳实践》中, 引用的链接失效

### ISSUE THREAD

**Issue by luoshieryi** [Snailclimb/JavaGuide#1965]
| 还没看够？推荐 why 神的《如何设置线程池参数？美团给出了一个让面试官虎躯一震的回答。》这篇文章，深度剖析，很不错哦！
这段引用的 [《如何设置线程池参数？美团给出了一个让面试官虎躯一震的回答。》](https://mp.weixin.qq.com/s/9HLuPcoWmTqAeFKa1kj-_A)链接已经失效, 会显示公众号已迁移

**Comment by Snailclimb** [comment]
> | 还没看够？推荐 why 神的《如何设置线程池参数？美团给出了一个让面试官虎躯一震的回答。》这篇文章，深度剖析，很不错哦！ 这段引用的 [《如何设置线程池参数？美团给出了一个让面试官虎躯一震的回答。》](https://mp.weixin.qq.com/s/9HLuPcoWmTqAeFKa1kj-_A)链接已经失效, 会显示公众号已迁移

新的地址：https://mp.weixin.qq.com/s/YbyC3qQfUm4B_QQ03GFiNw
