### ISSUE TITLE
JVM垃圾回收详解-G1收集器部分缺少内容

### ISSUE THREAD

**Issue by Choronicle** [Snailclimb/JavaGuide#1966]
在G1收集器的特点：可预测的停顿中，“能让使用者明确指定在一个长度为 M 毫秒的时间片段内”这句话**表述不完整**。
在https://juejin.cn/post/7010034105165299725看到了完整的表述，为“能让使用者明确指定在一个长度为 M 毫秒的时间片段内,消耗在垃圾收集上的时间不得超过 N 毫秒”。

**Comment by Snailclimb** [comment]
> https://juejin.cn/post/7010034105165299725

感谢指出👍
