### ISSUE TITLE
哇，这个项目好多星星啊！

### ISSUE THREAD

**Issue by noear** [Snailclimb/JavaGuide#1968]
感叹一下：）

**Comment by Snailclimb** [comment]
> 感叹一下：）

star 不代表一切，受众面广罢了，大佬的项目很厉害！

**Comment by noear** [comment]
有个用户说，是因为你才认识 solon 框架的。。。我来感谢一下：）

**Comment by Snailclimb** [comment]
> 有个用户说，是因为你才认识 solon 框架的。。。我来感谢一下：）

大佬的项目很早就开始关注了，之前推荐过几次，真的佩服你们这些用心搞开源的技术大佬！

**Comment by noear** [comment]
别的开源可能是大老。不过，我只是个 java 外行：）
