### ISSUE TITLE
ArrayList源码&扩容机制ensureCapacity方法

### ISSUE THREAD

**Issue by NVRGUP** [Snailclimb/JavaGuide#1974]
在向 ArrayList 添加大量元素之前用 ensureCapacity 方法的话，相当于提前扩容，minCapacity=要存入数据的数量！扩容成要存入数据量的1.5倍。这个方法是不是会造成大量的空间浪费？希望博主能够回答一下

**Comment by testggddkk** [comment]
chatGPT回答如下:
使用 ensureCapacity 方法确实会在添加大量元素之前扩容 ArrayList 的容量，以确保有足够的空间来存储要添加的元素，从而避免在添加元素时进行频繁的扩容操作，从而提高性能。

默认情况下，ArrayList 在添加元素时会自动扩容，扩容大小为当前容量的 50%。这种方式确保了在大多数情况下，ArrayList 可以高效地添加元素，但也可能会导致空间浪费。

而通过使用 ensureCapacity 方法，可以避免在添加元素时频繁扩容，但是也可能会分配比实际需要更多的空间，从而导致一定程度的空间浪费。但是，在大多数情况下，这种浪费是可以接受的，因为它可以提高程序的性能。

因此，是否使用 ensureCapacity 方法取决于你的具体需求。如果你需要处理大量数据并且性能很重要，那么使用该方法可能会是一个不错的选择。如果你的数据集比较小，并且空间使用不是主要问题，那么使用默认的扩容方式可能更为简单和可靠。

**Comment by testggddkk** [comment]
让我想到  空间换时间,时间换空间. 看你要啥了

**Comment by NVRGUP** [comment]
> 让我想到 空间换时间,时间换空间. 看你要啥了

谢谢
