### ISSUE TITLE
关于：hashcode的值和对象内存地址的关系

### ISSUE THREAD

**Issue by Sunsherly** [Snailclimb/JavaGuide#1978]
https://javaguide.cn/java/basis/java-basic-questions-02.html#object
我觉得这段话中的最后一句有歧义:"hashCode()定义在 JDK 的 Object 类中，这就意味着 Java 中的任何类都包含有 hashCode() 函数。另外需要注意的是： Object 的 hashCode() 方法是本地方法，也就是用 C 语言或 C++ 实现的，**_该方法通常用来将对象的内存地址转换为整数之后返回。_**"
目前java用的是一种随机数生成算法，和对象的内存地址无关。
可以看一下这个视频分析：【【Java必备知识】打印对象时@后的一串数字是对象的内存地址吗？】 https://www.bilibili.com/video/BV16m4y1B7o5/?share_source=copy_web&vd_source=094093b228f91eeda87ddf9fa0bd8d6b

**Comment by Erzbir** [comment]
确实不应该是"该方法通常用来将对象的内存地址转换为整数之后返回", 因为在OracleOpenJDK8(HotSpot VM)中, 默认是第五种模式: "使用线程局部状态来实现Marsaglia's xor-shift随机数生成", 与地址无关.

OracleOpenJDK8(HotSpot VM)中默认与地址无关, 但在其他VM中不一定, 不同jdk默认可能不同
 
`hashcode`方法有五种模式可以通过:`-XX:hashcode`控制, 0-5六种(使用第六种只需要参数大于4就可以), 其中`4`是返回地址

详细可以参考源码:
https://hg.openjdk.org/jdk8u/jdk8u/hotspot/file/87ee5ee27509/src/share/vm/runtime/globals.hpp
https://hg.openjdk.org/jdk8u/jdk8u/hotspot/file/87ee5ee27509/src/share/vm/runtime/synchronizer.cpp

**Comment by Erzbir** [comment]
@Snailclimb 这个issue可以当bug修复吗

**Comment by Snailclimb** [comment]
> @Snailclimb 这个issue可以当bug修复吗

已合并，再次感谢修正完善！
