### ISSUE TITLE
serialVersionUID 的序列化说明

### ISSUE THREAD

**Issue by MrZQAQ** [Snailclimb/JavaGuide#1983]
目前的版本中关于 serialVersionUID 被 static 修饰时的序列化问题说明是
>serialVersionUID 不是被 static 变量修饰了吗？为什么还会被“序列化”？static 修饰的变量是静态变量，位于方法区，本身是不会被序列化的。 static 变量是属于类的而不是对象。你反序列之后，static 变量的值就像是默认赋予给了对象一样，看着就像是 static 变量被序列化，实际只是假象罢了。

我读到这里对于 UID 是否被序列化还是不清楚。在查找文档之后，我认为官方文档的说法更容易被理解，希望在这段后面增加官方文档的说明。

官方说明如下，并附个人拙译：
> A serializable class can declare its own serialVersionUID explicitly by declaring a field named `"serialVersionUID"` that must be `static`, `final`, and of type `long`; 

> 如果想显式指定 `serialVersionUID` ，则需要在类中使用 `static` 和 `final` 关键字来修饰一个 `long` 类型的变量，变量名字必须为 `"serialVersionUID"` 。

即，serialVersionUID 只是用来被JVM识别，序列化的并不是显式声明的这个变量。

**Comment by Snailclimb** [comment]
> 官方说明如下，并附个人拙译：
> 
> > A serializable class can declare its own serialVersionUID explicitly by declaring a field named `"serialVersionUID"` that must be `static`, `final`, and of type `long`;
> 
> > 如果想显式指定 `serialVersionUID` ，则需要在类中使用 `static` 和 `final` 关键字来修饰一个 `long` 类型的变量，变量名字必须为 `"serialVersionUID"` 。
> 
> 即，serialVersionUID 只是用来被JVM识别，序列化的并不是显式声明的这个变量。

感谢，很不错的补充完善。
