### ISSUE TITLE
关于 Heap 初始化的时间复杂度

### ISSUE THREAD

**Issue by Z1an-Wang** [Snailclimb/JavaGuide#1984]
在 https://github.com/Snailclimb/JavaGuide/blob/main/docs/cs-basics/data-structure/heap.md#%E5%A0%86%E7%9A%84%E7%94%A8%E9%80%94 中提及 Heap 初始化的时间复杂度为 O(nlog(n))。实际上 Heap 初始化的时间复杂度为 O(n)。
参考资料：
1. https://blog.csdn.net/don_lvsml/article/details/19546997
2. https://www.cs.umd.edu/~meesh/351/mount/lectures/lect14-heapsort-analysis-part.pdf

**Comment by Snailclimb** [comment]
> 在 https://github.com/Snailclimb/JavaGuide/blob/main/docs/cs-basics/data-structure/heap.md#%E5%A0%86%E7%9A%84%E7%94%A8%E9%80%94 中提及 Heap 初始化的时间复杂度为 O(nlog(n))。实际上 Heap 初始化的时间复杂度为 O(n)。 参考资料：
> 
> 1. https://blog.csdn.net/don_lvsml/article/details/19546997
> 2. https://www.cs.umd.edu/~meesh/351/mount/lectures/lect14-heapsort-analysis-part.pdf

感谢你，这块确实理解错了，已修复。
