### ISSUE TITLE
四次挥手图示的seq值不准确

### ISSUE THREAD

**Issue by Skiaro** [Snailclimb/JavaGuide#2002]
![63$79964~V39LPZNR0Y_D}Q](https://user-images.githubusercontent.com/76765325/235309142-3a5790bd-a552-4e70-a971-0b518da59ce5.png)
图源 计算机网络（第七版）谢希仁

**Comment by Erzbir** [comment]
@Snailclimb 这种图片错误是重新做图或者引用图片还是在图下方备注?

位置: docs/cs-basics/network/tcp-connection-and-disconnection.md文件的第42行

**Comment by Snailclimb** [comment]
> @Snailclimb 这种图片错误是重新做图或者引用图片还是在图下方备注?
> 
> 位置: docs/cs-basics/network/tcp-connection-and-disconnection.md文件的第42行

如果可以的话，尽量重新作图哈，使用 draw.io 即可。

**Comment by Snailclimb** [comment]
> docs/cs-basics/network/tcp-connection-and-disconnection.md

我修正了哈：
<img width="641" alt="image" src="https://user-images.githubusercontent.com/29880145/235343004-8e665586-4d3e-47d6-b332-81da13650f1e.png">

**Comment by Skiaro** [comment]
好的，修正之后我需要点这个Close with comment吗，第一次提交issue，不太懂

**Comment by Snailclimb** [comment]
> 好的，修正之后我需要点这个Close with comment吗，第一次提交issue，不太懂

嗯嗯  可以的 我来关闭也行，没事。感谢指出，共勉！
