### ISSUE TITLE
NAT协议详解（网络层）勘误！

### ISSUE THREAD

**Issue by huqiwei123** [Snailclimb/JavaGuide#2009]
1. LAN-WAN 间通信提供地址转换 图片的第四步的Dest返回给局域网主机10.0.0.1的值是不是错了？
![image](https://user-images.githubusercontent.com/84982071/236821044-0fc630cf-a61a-4743-bdb2-d041d5c8480b.png)
2. 右侧组织了一个LAN，LAN侧接口的IP地址为10.0.0.4?
<img width="769" alt="CleanShot 2023-05-08 at 20 13 46" src="https://user-images.githubusercontent.com/84982071/236820996-e5e88c8d-22d2-485e-af05-b7e799a8b779.png">

**Comment by Snailclimb** [comment]
> 1. 第四步的Dest返回给局域网主机10.0.0.1的值

感谢指出，已修正。
