### ISSUE TITLE
数据库-SQL-SQL常见面试题

### ISSUE THREAD

**Issue by DrBit666** [Snailclimb/JavaGuide#2012]
<img width="796" alt="image" src="https://github.com/Snailclimb/JavaGuide/assets/46259091/ae377d8b-86a8-481f-b19b-46cfaf32acb9">
截取函数SUBSTRING()：截取字符串，substring(str ,n ,m)：返回字符串 str 从第 n 个字符截取到第 m 个字符（左闭右闭）；❌
截取函数substring(str,n,m)应该为返回字符串str从第n个字符开始截取m个字符而不是第m个字符，n为闭区间。
<img width="281" alt="image" src="https://github.com/Snailclimb/JavaGuide/assets/46259091/6e3841e4-9514-426e-9ffc-665157b83fcd">

**Comment by wuyaoqing** [comment]
SUBSTRING ( expression ,start , length )  估计抄错了

**Comment by Snailclimb** [comment]
> 

感谢指正，已修复。

<img width="611" alt="image" src="https://github.com/Snailclimb/JavaGuide/assets/29880145/15d09e8d-5e23-4bfc-a742-18cbd4242304">
