### ISSUE TITLE
java并发容器中对concurrentHashMap的描述不够正确

### ISSUE THREAD

**Issue by HeWeiGitHub** [Snailclimb/JavaGuide#2019]
## 分段锁是已经抛弃的技术

`在 ConcurrentHashMap 中，无论是读操作还是写操作都能保证很高的性能：在进行读操作时(几乎)不需要加锁，而在写操作时通过锁分段技术只对所操作的段加锁而不影响客户端对其它段的访问。`

以上描述不够正确，1.8之前是分段锁，1.8及以后是sychornized+cas实现的。

**Comment by Snailclimb** [comment]
> 写操作时通过锁分段技术只对

感谢指出，这里没有同步最新内容。

<img width="1410" alt="image" src="https://github.com/Snailclimb/JavaGuide/assets/29880145/559b4f9b-4aab-4ccd-9428-6812a4def2e1">
