### ISSUE TITLE
超链接失效

### ISSUE THREAD

**Issue by wrote-code** [Snailclimb/JavaGuide#2029]
这个链接目前是一个菠菜站，猜测原博主没有续费

![图片](https://github.com/Snailclimb/JavaGuide/assets/39870481/b2d450b6-cb09-43d9-a5c6-a04db3c825ac)

![图片](https://github.com/Snailclimb/JavaGuide/assets/39870481/a939e516-ddf0-4bd4-b933-a5ac58e81ab8)

**Comment by Snailclimb** [comment]
> 这个链接目前是一个菠菜站，猜测原博主没有续费
> 
> ![图片](https://user-images.githubusercontent.com/39870481/240663348-b2d450b6-cb09-43d9-a5c6-a04db3c825ac.png)
> 
> ![图片](https://user-images.githubusercontent.com/39870481/240664013-a939e516-ddf0-4bd4-b933-a5ac58e81ab8.png)

是的 我赶快去移除了，感谢指出👍
