### ISSUE TITLE
十大经典排序_图片和正文中的复杂度很多都对不上

### ISSUE THREAD

**Issue by lingkongkr** [Snailclimb/JavaGuide#2031]
比如图片中写的快排空间复杂度是O(logn)，到正文里就变成O(nlogn)了，真的有点乱套了，起码有三个以上勘误

**Comment by Snailclimb** [comment]
找到一个 插入排序的最好时间复杂度为 O(n) 而不是 O(n^2) ，其他的能帮忙看看不。

**Comment by lingkongkr** [comment]
就是正文和最开始给的图片里面不一致，不知道该以哪个为准了。我对照标记了一下
**图片**
![QQ截图20230528195702](https://github.com/Snailclimb/JavaGuide/assets/88617889/a0a6642f-688f-48d1-9e1b-b986da378226)
**正文**
![QQ截图20230528195723](https://github.com/Snailclimb/JavaGuide/assets/88617889/aff1c2a4-50fa-4420-b28d-d19adb06b38e)
![QQ截图20230528195755](https://github.com/Snailclimb/JavaGuide/assets/88617889/cd43ef96-5f7d-4170-a25d-086de99fe3c6)
![QQ截图20230528200600](https://github.com/Snailclimb/JavaGuide/assets/88617889/119b9267-15ac-49e0-b08d-8e2ce0207607)
![QQ截图20230528200643](https://github.com/Snailclimb/JavaGuide/assets/88617889/79a37e8e-eded-4880-8e24-79d6b4953787)

**Comment by lingkongkr** [comment]
两周了还没改，issue关了是不是就收不到通知了啊

**Comment by Snailclimb** [comment]
> 

早改了呀，可能网站的还没同步上去。
