### ISSUE TITLE
深色模式下无法清晰显示黑色字体和黑色线条

### ISSUE THREAD

**Issue by wrote-code** [Snailclimb/JavaGuide#2032]
这是[页面链接](https://javaguide.cn/tools/gradle/gradle-core-concepts.html#gradle-wrapper-%E4%BB%8B%E7%BB%8D)，这是深色效果：

![图片](https://github.com/Snailclimb/JavaGuide/assets/39870481/e2ba2c8d-ed51-433c-befd-99dba7da479d)

这是正常效果：

![图片](https://github.com/Snailclimb/JavaGuide/assets/39870481/e703ea9e-076a-4dd6-b546-a59b6dae0b4b)

**Comment by Snailclimb** [comment]
> 这是[页面链接](https://javaguide.cn/tools/gradle/gradle-core-concepts.html#gradle-wrapper-%E4%BB%8B%E7%BB%8D)，这是深色效果：
> 
> ![图片](https://user-images.githubusercontent.com/39870481/241749597-e2ba2c8d-ed51-433c-befd-99dba7da479d.png)
> 
> 这是正常效果：
> 
> ![图片](https://user-images.githubusercontent.com/39870481/241749663-e703ea9e-076a-4dd6-b546-a59b6dae0b4b.png)

感谢指出，部分图片是有这个问题。
