### ISSUE TITLE
发现内容上的不严谨

### ISSUE THREAD

**Issue by weiyuchens** [Snailclimb/JavaGuide#2033]
https://javaguide.cn/java/basis/java-basic-questions-01.html

```
Java 语言有哪些特点?

7. 支持网络编程并且很方便（ Java 语言诞生本身就是为简化网络编程设计的，因此 Java 语言不仅支持网络编程而且很方便）；
```

Java语言的设计初衷并不是为了简化网络编程，而是为了解决跨平台应用程序开发的问题。

**Comment by Snailclimb** [comment]
> https://javaguide.cn/java/basis/java-basic-questions-01.html
> 
> ```
> Java 语言有哪些特点?
> 
> 7. 支持网络编程并且很方便（ Java 语言诞生本身就是为简化网络编程设计的，因此 Java 语言不仅支持网络编程而且很方便）；
> ```
> 
> Java语言的设计初衷并不是为了简化网络编程，而是为了解决跨平台应用程序开发的问题。

感谢，确实不严谨，这段话还是大三的时候写的，感谢指出。
