### ISSUE TITLE
单例模式的解释有误

### ISSUE THREAD

**Issue by stargazer1sdh** [Snailclimb/JavaGuide#2082]
[https://github.com/Snailclimb/JavaGuide/blob/9a5f864125d6cb889de54b54a167940255499311/docs/java/concurrent/java-concurrent-questions-02.md?plain=1#L49](https://github.com/Snailclimb/JavaGuide/blob/9a5f864125d6cb889de54b54a167940255499311/docs/java/concurrent/java-concurrent-questions-02.md?plain=1#L49)
![image](https://github.com/Snailclimb/JavaGuide/assets/24764272/3b3812bc-5d79-4401-a4d8-ec827061f578)

这里不存在有序性的问题，因为加synchronized锁和双重null检查，决定了只能有一个线程运行uniqueInstance = new Singleton(); 单线程是不存在有序性问题的。这里加volatile只是为了保证可见性。

**Comment by stargazer1sdh** [comment]
后面又想了一下，可能是我自己想错了，关闭之

**Comment by Snailclimb** [comment]
> 后面又想了一下，可能是我自己想错了，关闭之

好的好的，没事的，精神很不错，要有自己的思考👍
