### ISSUE TITLE
关于404问题

### ISSUE THREAD

**Issue by forkeri** [Snailclimb/JavaGuide#209]
我也遇到了很多404的问题，造成的原因是很多地方的链接有点儿小错误
正确的 .../Java/...
错误的 .../Java相关/...
错误的地方：
1. README.md  Line 199
2. Java\synchronized.md  Line 3
3. 数据结构与算法\数据结构.md  Line84
4. 数据结构与算法\数据结构.md  Line85

**Comment by Snailclimb** [comment]
好的 感谢！已经全部修复！
