### ISSUE TITLE
常用框架/重要知识点/Spring事务详解/@Transactional 注解使用详解/Spring AOP 自调用问题

### ISSUE THREAD

**Issue by JianingWu911** [Snailclimb/JavaGuide#2091]
基于动态代理的AOP，在自调用时候也可以正常开启事务。
如下面代码：
```Java
@Service
public class MyService {

private void method1() {
     ((MyService)AopContext.currentProxy()).method2(); // 先获取该类的代理对象，然后通过代理对象调用method2。
     //......
}
@Transactional
 public void method2() {
     //......
  }
}
```

**Comment by Snailclimb** [comment]
> 基于动态代理的AOP，在自调用时候也可以正常开启事务。 如下面代码：
> 
> ```java
> @Service
> public class MyService {
> 
> private void method1() {
>      ((MyService)AopContext.currentProxy()).method2(); // 先获取该类的代理对象，然后通过代理对象调用method2。
>      //......
> }
> @Transactional
>  public void method2() {
>      //......
>   }
> }
> ```

哈哈哈，这种确实可以。使用了 AopContext.currentProxy() 方法来获取当前类的代理对象，然后通过代理对象调用 method2()。这样就相当于从外部调用了 method2()，所以事务注解才会生效。

**Comment by zbcdd** [comment]
如果AOP是通过CGLIB实现的，那么代理对象继承目标对象，这时候不也可以嵌套增强吗
