### ISSUE TITLE
Java基础常见面试题总结(下)/注解的解析方法有哪几种?/spring中@Component使用反射??

### ISSUE THREAD

**Issue by hwang-how** [Snailclimb/JavaGuide#2096]
spring源码中通过@ComponentScan指定包扫描的路径
在指定包下面扫描带有@Component注解的.class文件,这里使用的是ASM技术来分析字节码文件,并没有在JVM中生成Class对象(因为这样做可能会spring容器启动的时候在JVM中生成大量的Class对象占用内存)
那为什么说@Component使用到了反射机制呢? 还是说源码中其他哪里使用到了反射?

**Comment by Snailclimb** [comment]
> spring源码中通过@componentscan指定包扫描的路径 在指定包下面扫描带有@component注解的.class文件,这里使用的是ASM技术来分析字节码文件,并没有在JVM中生成Class对象(因为这样做可能会spring容器启动的时候在JVM中生成大量的Class对象占用内存) 那为什么说@component使用到了反射机制呢? 还是说源码中其他哪里使用到了反射?

哪个类被Bean注解注释，都是需要通过反射扫描发现的。
