### ISSUE TITLE
Object的hashcode的问题

### ISSUE THREAD

**Issue by Fan4J** [Snailclimb/JavaGuide#21]
在文中讲述hashcode和equals的部分,作者说hashcode是内存地址,这个说法是不准确的.在jdk中Object类的注释中说到,
> As much as is reasonably practical, the hashCode method defined by
    class {@code Object} does return distinct integers for distinct
    objects. (This is typically implemented by converting the internal
    address of the object into an integer, but this implementation
    technique is not required by the
    Java&trade; programming language.)

hashcode是内存地址转成了int,转换的方法是其他语言实现的,不能直接说是内存地址
楼主觉得呢?

**Comment by Snailclimb** [comment]
嗯嗯  ！ 感谢老哥提醒！
