### ISSUE TITLE
文章被隐藏

### ISSUE THREAD

**Issue by JacketFu** [Snailclimb/JavaGuide#2112]
https://javaguide.cn/java/collection/delayqueue-source-code.html
这一篇似乎并没有在网站左侧目录显示，因为对vuepress不熟，不知道怎么排查。

**Comment by Snailclimb** [comment]
> https://javaguide.cn/java/collection/delayqueue-source-code.html 这一篇似乎并没有在网站左侧目录显示，因为对vuepress不熟，不知道怎么排查。

是的，这一篇我忘记同步上去了，后面会更新一下。
