### ISSUE TITLE
事务隔离级别中的可串行化

### ISSUE THREAD

**Issue by zhiyiYo** [Snailclimb/JavaGuide#2117]
[Spring 事务中的隔离级别有哪几种?](https://javaguide.cn/system-design/framework/spring/spring-knowledge-and-questions-summary.html#spring-%E4%BA%8B%E5%8A%A1%E4%B8%AD%E7%9A%84%E9%9A%94%E7%A6%BB%E7%BA%A7%E5%88%AB%E6%9C%89%E5%93%AA%E5%87%A0%E7%A7%8D) 中关于 `TransactionDefinition.ISOLATION_SERIALIZABLE` 是这样描述的：
> 所有的事务依次逐个执行，这样事务之间就完全不可能产生干扰

但是可串行化并不等于串行执行，事务仍然可以并发执行，只是调度结果和串行执行的结果等效

**Comment by Snailclimb** [comment]
> [Spring 事务中的隔离级别有哪几种?](https://javaguide.cn/system-design/framework/spring/spring-knowledge-and-questions-summary.html#spring-%E4%BA%8B%E5%8A%A1%E4%B8%AD%E7%9A%84%E9%9A%94%E7%A6%BB%E7%BA%A7%E5%88%AB%E6%9C%89%E5%93%AA%E5%87%A0%E7%A7%8D) 中关于 `TransactionDefinition.ISOLATION_SERIALIZABLE` 是这样描述的：
> 
> > 所有的事务依次逐个执行，这样事务之间就完全不可能产生干扰
> 
> 但是可串行化并不等于串行执行，事务仍然可以并发执行，只是调度结果和串行执行的结果等效

有参考文案地址么？

**Comment by zhiyiYo** [comment]
https://blog.csdn.net/liuhhaiffeng/article/details/104411705?ydreferer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS5oay8%3D

**Comment by zhiyiYo** [comment]
为啥直接关闭掉了？

**Comment by Snailclimb** [comment]
> 为啥直接关闭掉了？

你这给的参考链接不具备参考性，尽量以官网或者书籍为准。

**Comment by zhiyiYo** [comment]
阿这，本来可串行化就不等于串行调度，下图中的事务调度是冲突可串行化的，执行结果等同于先执行T1再执行T2，T1 的  R(B) 和 T2 的 R(A) 完全可以并行执行
![image](https://github.com/Snailclimb/JavaGuide/assets/65096819/efffb2eb-c379-4cfd-bde4-604ac5fe9d32)

**Comment by Snailclimb** [comment]
> 阿这，本来可串行化就不等于串行调度，下图中的事务调度是冲突可串行化的，执行结果等同于先执行T1再执行T2，T1 的 R(B) 和 T2 的 R(A) 完全可以并行执行 ![image](https://user-images.githubusercontent.com/65096819/258972800-efffb2eb-c379-4cfd-bde4-604ac5fe9d32.png)



> Spring

不是，你要结合Spring来谈，而不是仅仅依靠这个理论，需要的是文献或者实战证明。我这会没时间求证，后续有空了再看。。。
