### ISSUE TITLE
Rockmq内容部分不够完善

### ISSUE THREAD

**Issue by dengminchuan** [Snailclimb/JavaGuide#2132]
看rocketmq时发现关于关于rocketmq高性能读写没有说，消费者拉取消息的方式（pull push）没有写是怎么实现的，我想要添加一些内容

**Comment by dengminchuan** [comment]
已提关于rocketmq高性能读写内容和顺序消费内容的pr

**Comment by Snailclimb** [comment]
> 看rocketmq时发现关于关于rocketmq高性能读写没有说，消费者拉取消息的方式（pull push）没有写是怎么实现的，我想要添加一些内容

可以的，已经合并，感谢完善。这篇文章很久了，一直没来得及完善。
