### ISSUE TITLE
rabbitmq安装文档问题

### ISSUE THREAD

**Issue by tobewithyou1996** [Snailclimb/JavaGuide#214]
![image](https://user-images.githubusercontent.com/31532979/54406309-9c608500-4714-11e9-9cd7-b86f52190449.png)
![image](https://user-images.githubusercontent.com/31532979/54406410-024d0c80-4715-11e9-930c-5cd5e0cd56c0.png)
rabbitmq 和erlang 是需要版本对应的，很多人容易搞错，标注下

**Comment by Snailclimb** [comment]
好的  感谢你！

**Comment by tobewithyou1996** [comment]
不客气
