### ISSUE TITLE
[fix] 勘误 SQL常见面试题总结（2）删除记录（3）

### ISSUE THREAD

**Issue by LinkCastling** [Snailclimb/JavaGuide#2145]
https://javaguide.cn/database/sql/sql-questions-02.html#%E5%88%9B%E5%BB%BA%E4%B8%80%E5%BC%A0%E6%96%B0%E8%A1%A8
中的
`CREATE TABLE IF NOT EXISTS user_info_vip(
    id INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT'自增ID',
    uid INT(11) UNIQUE NOT NULL COMMENT '用户ID',
    nick_name VARCHAR(64) COMMENT'昵称',
    achievement INT(11) DEFAULT 0 COMMENT '成就值',
    level INT(11) COMMENT '用户等级',
    job VARCHAR(32) COMMENT '职业方向',
    register_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间'
)CHARACTER SET UTF8
`
level是MySQL中的关键字 ，应该用反引号包含
正确代码：
`CREATE TABLE IF NOT EXISTS user_info_vip(
    id INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT'自增ID',
    uid INT(11) UNIQUE NOT NULL COMMENT '用户ID',
    nick_name VARCHAR(64) COMMENT'昵称',
    achievement INT(11) DEFAULT 0 COMMENT '成就值',
    `level` INT(11) COMMENT '用户等级',
    job VARCHAR(32) COMMENT '职业方向',
    register_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间'
)CHARACTER SET UTF8
`

**Comment by Snailclimb** [comment]
> https://javaguide.cn/database/sql/sql-questions-02.html#%E5%88%9B%E5%BB%BA%E4%B8%80%E5%BC%A0%E6%96%B0%E8%A1%A8 中的 `CREATE TABLE IF NOT EXISTS user_info_vip( id INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT'自增ID', uid INT(11) UNIQUE NOT NULL COMMENT '用户ID', nick_name VARCHAR(64) COMMENT'昵称', achievement INT(11) DEFAULT 0 COMMENT '成就值', level INT(11) COMMENT '用户等级', job VARCHAR(32) COMMENT '职业方向', register_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间' )CHARACTER SET UTF8 ` level是MySQL中的关键字 ，应该用反引号包含 正确代码： `CREATE TABLE IF NOT EXISTS user_info_vip( id INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT'自增ID', uid INT(11) UNIQUE NOT NULL COMMENT '用户ID', nick_name VARCHAR(64) COMMENT'昵称', achievement INT(11) DEFAULT 0 COMMENT '成就值', `level`INT(11) COMMENT '用户等级', job VARCHAR(32) COMMENT '职业方向', register_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间' )CHARACTER SET UTF8`

感谢指出👍
