### ISSUE TITLE
网站中没有J2EE基础知识.html

### ISSUE THREAD

**Issue by ccjjforever** [Snailclimb/JavaGuide#2146]
![image](https://github.com/Snailclimb/JavaGuide/assets/131140112/aa69e186-7037-445b-88ae-9812c0156e40)
![image](https://github.com/Snailclimb/JavaGuide/assets/131140112/eea46ce4-3cbb-4531-8dd5-26221a310c87)

**Comment by ccjjforever** [comment]
在网站中不用搜索找不到J2EE基础知识.html这个页面
![image](https://github.com/Snailclimb/JavaGuide/assets/131140112/d1920859-e1bf-4ef3-bf1b-10493d8343cc)

**Comment by Snailclimb** [comment]
> 在网站中不用搜索找不到J2EE基础知识.html这个页面 ![image](https://user-images.githubusercontent.com/131140112/263542643-d1920859-e1bf-4ef3-bf1b-10493d8343cc.png)



> ![image](https://user-images.githubusercontent.com/131140112/263542224-aa69e186-7037-445b-88ae-9812c0156e40.png) ![image](https://user-images.githubusercontent.com/131140112/263542278-eea46ce4-3cbb-4531-8dd5-26221a310c87.png)

https://github.com/Snailclimb/JavaGuide/blob/main/docs/system-design/J2EE%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md

**Comment by ccjjforever** [comment]
你好，我的意思是在https://javaguide.cn这个网站中，可以用搜索找到J2EE基础知识.htnl这个页面，但无法通过目录找到
![image](https://github.com/Snailclimb/JavaGuide/assets/131140112/6eb0a3b7-e74e-435c-a770-17dc23577677)

**Comment by Snailclimb** [comment]
> 你好，我的意思是在https://javaguide.cn 这个网站中，可以用搜索找到J2EE基础知识.htnl这个页面，但无法通过目录找到 https://javaguide.cn/system-design/J2EE%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.html 此页面没在网站左侧目录显示 ![image](https://user-images.githubusercontent.com/131140112/263589717-6eb0a3b7-e74e-435c-a770-17dc23577677.png)

我故意没有放上去的，这部分内容并不重要。
