### ISSUE TITLE
linkedhashmap-source-code.md 链表转红黑树条件勘误

### ISSUE THREAD

**Issue by sunquan123** [Snailclimb/JavaGuide#2147]
![Snipaste_2023-08-28_10-29-53](https://github.com/Snailclimb/JavaGuide/assets/37408772/16156547-2075-4a92-ae1b-c885422aaca6)
这里应该改为判断链表上的节点个数达到树化的阈值8，因为源码的判断是从链表初始元素开始遍历，下标是从0开始的，所以判断条件设置为8-1=7，其实是迭代到尾部元素时再判断整个链表长度大于等于8才进行树化操作。源码如下：
![Snipaste_2023-08-28_10-33-04](https://github.com/Snailclimb/JavaGuide/assets/37408772/6944f002-7bd9-45b3-a213-33d736ed2f89)
建议修正一下~

**Comment by chenfei666666** [comment]
判断的阈值得到了8，实际上加上数组的头节点此时链表上的节点数已经达到9个了

**Comment by sunquan123** [comment]
> 判断的阈值得到了8，实际上加上数组的头节点此时链表上的节点数已经达到9个了

对，这里是在第九个元素追加到链表中的时候，进行了树化。所以严谨的说，是“linkedhashmap在插入第九个元素时，判断链表中已存在八个元素，则进行树化”
