### ISSUE TITLE
有些页面404了呀

### ISSUE THREAD

**Issue by leoFitz1024** [Snailclimb/JavaGuide#2148]
![image](https://github.com/Snailclimb/JavaGuide/assets/29174699/71370d1f-48cb-48a9-9b58-29404339a170)
![image](https://github.com/Snailclimb/JavaGuide/assets/29174699/1bcff19c-8609-4a0e-af5d-83527c407c50)

**Comment by leoFitz1024** [comment]
补充，是这个文档中的https://snailclimb.gitee.io/javaguide/#/./docs/java/basis/java-basic-questions-03

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/29174699/263948875-71370d1f-48cb-48a9-9b58-29404339a170.png) ![image](https://user-images.githubusercontent.com/29174699/263948982-1bcff19c-8609-4a0e-af5d-83527c407c50.png)

老版本已经不同步更新，请移步新版网站：https://javaguide.cn/home.html 。
