### ISSUE TITLE
hashmap-source-code article question

### ISSUE THREAD

**Issue by cxhello** [Snailclimb/JavaGuide#2149]
link：https://github.com/Snailclimb/JavaGuide/blob/main/docs/java/collection/hashmap-source-code.md

![image](https://github.com/Snailclimb/JavaGuide/assets/49056040/2816158a-079d-43a6-a0b4-419f980534d9)

我觉得标红的地方改成 `tab[i = (n - 1) & hash] == null` 比较好

**Comment by cxhello** [comment]
> > link：https://github.com/Snailclimb/JavaGuide/blob/main/docs/java/collection/hashmap-source-code.md
> > ![image](https://user-images.githubusercontent.com/49056040/264560388-2816158a-079d-43a6-a0b4-419f980534d9.png)
> > 我觉得标红的地方改成 `tab[i = (n - 1) & hash] == null` 比较好
> 
> 确实，如果有兴趣的话，欢迎使用draw.io 重新绘制完善此图。

好的，还有一个小建议。如果画的图下面可以附带源文件，大家也方便改。

**Comment by Snailclimb** [comment]
> > > link：https://github.com/Snailclimb/JavaGuide/blob/main/docs/java/collection/hashmap-source-code.md
> > > ![image](https://user-images.githubusercontent.com/49056040/264560388-2816158a-079d-43a6-a0b4-419f980534d9.png)
> > > 我觉得标红的地方改成 `tab[i = (n - 1) & hash] == null` 比较好
> > 
> > 
> > 确实，如果有兴趣的话，欢迎使用draw.io 重新绘制完善此图。
> 
> 好的，还有一个小建议。如果画的图下面可以附带源文件，大家也方便改。

这张图也是一位读者PR的，我用 draw.io 绘制的部分图片也同步到了Github。前段时间，由于发现网上有人直接在我的原图上修改成自己绘制的，所以就移除了一部分draw.io源文件。

**Comment by cxhello** [comment]
> > > > > link：https://github.com/Snailclimb/JavaGuide/blob/main/docs/java/collection/hashmap-source-code.md
> > > > > ![image](https://user-images.githubusercontent.com/49056040/264560388-2816158a-079d-43a6-a0b4-419f980534d9.png)
> > > > > 我觉得标红的地方改成 `tab[i = (n - 1) & hash] == null` 比较好
> > > > 
> > > > 
> > > > 确实，如果有兴趣的话，欢迎使用draw.io 重新绘制完善此图。
> > > 
> > > 
> > > 好的，还有一个小建议。如果画的图下面可以附带源文件，大家也方便改。
> 
> 这张图也是一位读者PR的，我用 draw.io 绘制的部分图片也同步到了Github。前段时间，由于发现网上有人直接在我的原图上魔改成自己绘制的，所以就移除了一部分draw.io源文件。

了解了。
