### ISSUE TITLE
能不能有个离线版本的

### ISSUE THREAD

**Issue by huixionghexiyi** [Snailclimb/JavaGuide#215]
非常开心找到这个项目。终于可以好好学习了🤣

**Comment by chang-kun** [comment]
本笔记目前只提供了PDF版，比较适合闲暇阅读，如果各位觉得不错可以帮作者安利给朋友一下，作者在这里感谢各位了！
链接：https://pan.baidu.com/s/1qVIO_J_xnM6wzDchce94nw 提取码：zuua

**Comment by caozhong11** [comment]
**谢谢啦**

**Comment by fantasygg** [comment]
pdf?

**Comment by HHJluoluo** [comment]
🔑🔑

**Comment by Snailclimb** [comment]
有一个离线版本的，现在已经是第二版了，后面还会继续更新。本笔记目前只提供了PDF版，比较适合闲暇阅读，如果各位觉得不错可以帮作者安利给朋友一下，作者在这里感谢各位了！
链接：https://pan.baidu.com/s/1qVIO_J_xnM6wzDchce94nw 提取码：zuua
后续最新版本的更新，我会首先在我的公众号推送，Github也会同步更新，大家可以关注我的公众号及时获取最新版本。
![公众号](
https://my-blog-to-use.oss-cn-beijing.aliyuncs.com/2019-3/%E5%85%AC%E4%BC%97%E5%8F%B7.png)

**Comment by huixionghexiyi** [comment]
哇，那非常感谢啦。真的很有用

**Comment by AspirinVip** [comment]
great！

**Comment by LiuZiQiao** [comment]
力挺

**Comment by ZhuPeng** [comment]
推荐一个可以通过微信小程序查看的方式
![image](https://user-images.githubusercontent.com/4994339/57271000-382cc280-70c0-11e9-8829-4fc6997bd0dd.png)

小程序是开源的，有任何问题和意见可以直接提 Issue 反馈：[GitHub Trending Hub](https://github.com/ZhuPeng/mp-githubtrending)
