### ISSUE TITLE
网站访问问题

### ISSUE THREAD

**Issue by ST-Zhu** [Snailclimb/JavaGuide#2151]
使用平板iPad Air1代的浏览器Safari访问javaguide网站：
1. 在首页点击“开始阅读”后404。
2. 进入“面试指南”页面后，左侧导航栏无法隐藏，且导航子目录无法展开。
![5e8d120894f5c4b49524b33995f9157](https://github.com/Snailclimb/JavaGuide/assets/45200508/f8f1c344-1cc3-434d-a163-7ea6739815c5)
![7ec4c5e8f590c75a72c34570a9bc478](https://github.com/Snailclimb/JavaGuide/assets/45200508/ac0c58a6-eb78-43cd-a309-7e0b1eea3400)

**Comment by Snailclimb** [comment]
> 使用平板iPad Air1代的浏览器Safari访问javaguide网站：
> 
> 1. 在首页点击“开始阅读”后404。
> 2. 进入“面试指南”页面后，左侧导航栏无法隐藏，且导航子目录无法展开。
>    ![5e8d120894f5c4b49524b33995f9157](https://user-images.githubusercontent.com/45200508/264604150-f8f1c344-1cc3-434d-a163-7ea6739815c5.jpg)
>    ![7ec4c5e8f590c75a72c34570a9bc478](https://user-images.githubusercontent.com/45200508/264604359-ac0c58a6-eb78-43cd-a309-7e0b1eea3400.jpg)

收到，清除一下缓存，使用chrome浏览器试试。

**Comment by ST-Zhu** [comment]
emmm试过了，没什么变化。可能是我浏览器的版本比较老？我用电脑访问和手机浏览器访问都是可以的。但是ipad太老了，下不了最新的浏览器-_-||

**Comment by ST-Zhu** [comment]
> > 使用平板iPad Air1代的浏览器Safari访问javaguide网站：
> > 
> > 1. 在首页点击“开始阅读”后404。
> > 2. 进入“面试指南”页面后，右侧导航栏无法展开，且隐藏导航子目录无法展开。
> >    ![5e8d120894f5c4b49524b33995f9157](https://user-images.githubusercontent.com/45200508/264604150-f8f1c344-1cc3-434d-a163-7ea6739815c5.jpg)
> >    ![7ec4c5e8f590c75a72c34570a9bc478](https://user-images.githubusercontent.com/45200508/264604359-ac0c58a6-eb78-43cd-a309-7e0b1eea3400.jpg)
> 
> ，清理一下缓存，使用chrome浏览器试试。

emmm试过了，没什么变化。可能是我浏览器的版本比较老？我用电脑访问和手机浏览器访问都是可以的。但是ipad太老了，下不了最新的浏览器-_-||

**Comment by Snailclimb** [comment]
> > > 使用平板iPad Air1代的浏览器Safari访问javaguide网站：
> > > 
> > > 1. 在首页点击“开始阅读”后404。
> > > 2. 进入“面试指南”页面后，右侧导航栏无法展开，且隐藏导航子目录无法展开。
> > >    ![5e8d120894f5c4b49524b33995f9157](https://user-images.githubusercontent.com/45200508/264604150-f8f1c344-1cc3-434d-a163-7ea6739815c5.jpg)
> > >    ![7ec4c5e8f590c75a72c34570a9bc478](https://user-images.githubusercontent.com/45200508/264604359-ac0c58a6-eb78-43cd-a309-7e0b1eea3400.jpg)
> > 
> > 
> > ，清理一下缓存，使用chrome浏览器试试。
> 
> emmm试过了，没什么变化。可能是我浏览器的版本比较老？我用电脑访问和手机浏览器访问都是可以的。但是ipad太老了，下不了最新的浏览器-_-||

好吧，我暂时解决不了这个问题，可以电脑端访问。
