### ISSUE TITLE
Spring MVC 中关于 Model 2 的问题

### ISSUE THREAD

**Issue by Conquers** [Snailclimb/JavaGuide#2155]
原文：
**Model 2 时代**

学过 Servlet 并做过相关 Demo 的朋友应该了解“Java Bean(Model)+ JSP（View）+Servlet（Controller） ”这种开发模式，这就是早期的 JavaWeb MVC 开发模式。

- Model：系统涉及的数据，也就是 dao 和 bean。
- View：展示模型中的数据，只是用来展示。
- Controller：~~处理用户请求都发送给~~ ，返回数据给 JSP 并展示给用户。

最后一句的表述有点问题，应该是接受用户请求，并将请求发送至 Model，最后返回数据给 JSP 并展示给用户

**Comment by Snailclimb** [comment]
> 接受用户请求，并将请求发送至 Model，最后返回数据给 JSP 并展示给用户

感谢指出，这里不小心被我删除了。
