### ISSUE TITLE
后缀遍历中，演示的代码块中的小错误

### ISSUE THREAD

**Issue by fgfadf** [Snailclimb/JavaGuide#2156]
![java面试指南-数据结构-二叉树后序遍历](https://github.com/Snailclimb/JavaGuide/assets/87141048/df5c2d04-b1fb-452f-a2b4-48ac82899bb9)
《计算机基础》=》《数据结构》=》《树》=》二叉树的遍历中，“后续遍历应该是left在前”，一个小错误

**Comment by Snailclimb** [comment]
> ![java面试指南-数据结构-二叉树后序遍历](https://user-images.githubusercontent.com/87141048/265689161-df5c2d04-b1fb-452f-a2b4-48ac82899bb9.png) 《计算机基础》=》《数据结构》=》《树》=》二叉树的遍历中，“后续遍历应该是left在前”，一个小错误

感谢指出，这里顺序确实有问题。
