### ISSUE TITLE
SpringBoot自动装配详解中有图片丢失

### ISSUE THREAD

**Issue by mervynlam** [Snailclimb/JavaGuide#2158]
![image](https://github.com/Snailclimb/JavaGuide/assets/26081972/2f836857-3073-48b5-858f-f3a16222177f)
SpringBoot自动装配详解中有图片丢失

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/26081972/266920621-2f836857-3073-48b5-858f-f3a16222177f.png) SpringBoot自动装配详解中有图片丢失

感谢指出，这部分图片放掘金上，防盗链原因无法显示，已经修复，网站会月底部署同步。
