### ISSUE TITLE
【JVM内存区域详解】章节中，关于运行时常量池和字符串常量池的位置搞错了

### ISSUE THREAD

**Issue by Chinafrfq** [Snailclimb/JavaGuide#2168]
![image](https://github.com/Snailclimb/JavaGuide/assets/105155111/b38f3766-c190-447a-93ed-69f6fd3f74fe)
这是我问GPT得到的答案，请问这个回答有问题吗

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/105155111/268141631-b38f3766-c190-447a-93ed-69f6fd3f74fe.png) 这是我问GPT得到的答案，请问这个回答有问题吗

请不要过度依赖GPT，这个问题应该是 GPT回答错误，我之前深入查过资料，已经不想再复查了。

**Comment by 3231058107lfc** [comment]
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月15日 08:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [Snailclimb/JavaGuide] 【JVM内存区域详解】章节中，关于运行时常量池和字符串常量池的位置搞错了 (Issue #2168) |


这是我问GPT得到的答案，请问这个回答有问题吗
