### ISSUE TITLE
Java内存区那里有问题

### ISSUE THREAD

**Issue by OrangeHao2** [Snailclimb/JavaGuide#217]
java8之后方法区不是取消了吗，变成了元数据区，是本地内存

**Comment by Snailclimb** [comment]
那个是JDK1.6的，已经添加JDK1,8对应的图片。对应文章：[可能是把Java内存区域讲的最清楚的一篇文章](https://github.com/Snailclimb/Java_Guide/blob/master/Java/%E5%8F%AF%E8%83%BD%E6%98%AF%E6%8A%8AJava%E5%86%85%E5%AD%98%E5%8C%BA%E5%9F%9F%E8%AE%B2%E7%9A%84%E6%9C%80%E6%B8%85%E6%A5%9A%E7%9A%84%E4%B8%80%E7%AF%87%E6%96%87%E7%AB%A0.md)
![Java运行时数据区域JDK1.8](https://my-blog-to-use.oss-cn-beijing.aliyuncs.com/2019-3Java运行时数据区域JDK1.8.png)
