### ISSUE TITLE
关于JMM的疑惑？

### ISSUE THREAD

**Issue by MagicalZhu** [Snailclimb/JavaGuide#2177]
萌新有个疑问：
在 jmm 的 主内存说明中：

> 主内存：所有线程创建的实例对象都存放在主内存中，**不管该实例对象是成员变量还是方法中的本地变量(也称局部变量)**

方法的局部变量不是存储在每个线程的工作内存中吗？并且局部变量的生命周期和线程一致。

**Comment by Snailclimb** [comment]
> 萌新有个疑问： 在 jmm 的 主内存说明中：
> 
> > 主内存：所有线程创建的实例对象都存放在主内存中，**不管该实例对象是成员变量还是方法中的本地变量(也称局部变量)**
> 
> 方法的局部变量不是存储在每个线程的工作内存中吗？并且局部变量的生命周期和线程一致。

所有线程创建的实例对象都存放在内存中，不管该实例对象是成员变量，还是局部变量，类信息、常量、静态变量都是放在主内存中，属于所有线程共享区域，所以存在线程之间安全问题。
