### ISSUE TITLE
INT 类型的值范围描述有误

### ISSUE THREAD

**Issue by yhaiqi87** [Snailclimb/JavaGuide#2186]
mysql-questions-01.md   line93
“例如， TINYINT UNSIGNED 类型的取值范围是 0 ~ 255，而普通的 TINYINT 类型的值范围是 -128 ~ 127。INT UNSIGNED 类型的取值范围是 0 ~ 4,294,967,295，而普通的 TINYINT 类型的值范围是 2,147,483,648 ~ 2,147,483,647。”
应改为
“例如， TINYINT UNSIGNED 类型的取值范围是 0 ~ 255，而普通的 TINYINT 类型的值范围是 -128 ~ 127。INT UNSIGNED 类型的取值范围是 0 ~ 4,294,967,295，而普通的 INT 类型的值范围是 -2,147,483,648 ~ 2,147,483,647。
”

**Comment by Snailclimb** [comment]
> mysql-questions-01.md line93 “例如， TINYINT UNSIGNED 类型的取值范围是 0 ~ 255，而普通的 TINYINT 类型的值范围是 -128 ~ 127。INT UNSIGNED 类型的取值范围是 0 ~ 4,294,967,295，而普通的 TINYINT 类型的值范围是 2,147,483,648 ~ 2,147,483,647。” 应改为 “例如， TINYINT UNSIGNED 类型的取值范围是 0 ~ 255，而普通的 TINYINT 类型的值范围是 -128 ~ 127。INT UNSIGNED 类型的取值范围是 0 ~ 4,294,967,295，而普通的 INT 类型的值范围是 -2,147,483,648 ~ 2,147,483,647。 ”

感谢，这里笔误了。
