### ISSUE TITLE
网安攻击章节有一处表述或有问题

### ISSUE THREAD

**Issue by Ang-Gao** [Snailclimb/JavaGuide#2191]
![image](https://github.com/Snailclimb/JavaGuide/assets/84631878/ce306ecd-d763-4411-a647-359805647f50)

指的应该实现RST，重置位。防火墙或安全系统发送RST包时，通常会中断与特定连接相关的TCP会话。这不仅会清空缓冲区中的连接，还会终止与该连接相关的所有数据传输。
https://javaguide.cn/cs-basics/network/network-attack-means.html#%E9%80%9A%E8%BF%87-ip-%E5%9C%B0%E5%9D%80%E6%88%91%E4%BB%AC%E8%83%BD%E7%9F%A5%E9%81%93%E4%BB%80%E4%B9%88

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/84631878/275272058-ce306ecd-d763-4411-a647-359805647f50.png)
> 
> 指的应该实现RST，重置位。防火墙或安全系统发送RST包时，通常会中断与特定连接相关的TCP会话。这不仅会清空缓冲区中的连接，还会终止与该连接相关的所有数据传输。 https://javaguide.cn/cs-basics/network/network-attack-means.html#%E9%80%9A%E8%BF%87-ip-%E5%9C%B0%E5%9D%80%E6%88%91%E4%BB%AC%E8%83%BD%E7%9F%A5%E9%81%93%E4%BB%80%E4%B9%88

感谢这里属于拼写错误了。
