### ISSUE TITLE
Java集合常见面试题总结(上) ArrayQueue是否应为ArrayDeque

### ISSUE THREAD

**Issue by P1nk64** [Snailclimb/JavaGuide#2192]
![image](https://github.com/Snailclimb/JavaGuide/assets/50233625/0fb42c20-98a2-44cc-a260-f0a85d723ce0)

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/50233625/275296524-0fb42c20-98a2-44cc-a260-f0a85d723ce0.png)

这样确实合适一些。

**Comment by P1nk64** [comment]
非常感谢，我是杨霄。您的消息我已收到，我会尽快回复。
