### ISSUE TITLE
ARP协议并不是网络层协议

### ISSUE THREAD

**Issue by LewyHua** [Snailclimb/JavaGuide#2194]
https://javaguide.cn/cs-basics/network/other-network-questions.html#%E5%B8%B8%E8%A7%81%E7%BD%91%E7%BB%9C%E5%8D%8F%E8%AE%AE

**Comment by Snailclimb** [comment]
> https://javaguide.cn/cs-basics/network/other-network-questions.html#%E5%B8%B8%E8%A7%81%E7%BD%91%E7%BB%9C%E5%8D%8F%E8%AE%AE

在OSI模型中ARP协议属于链路层；而在TCP/IP模型中，ARP协议属于网络层。

相关链接：

https://www.zhihu.com/question/22268146
https://m.nowcoder.com/questionTerminal?uuid=1f145ef2e0824aa19f3fee1b0d8fff55&from=&fromPut=
