### ISSUE TITLE
链接错误问题

### ISSUE THREAD

**Issue by knightio** [Snailclimb/JavaGuide#2196]
https://javaguide.cn/java/concurrent/java-thread-pool-best-practices.html#_3%E3%80%81%E5%BB%BA%E8%AE%AE%E4%B8%8D%E5%90%8C%E7%B1%BB%E5%88%AB%E7%9A%84%E4%B8%9A%E5%8A%A1%E7%94%A8%E4%B8%8D%E5%90%8C%E7%9A%84%E7%BA%BF%E7%A8%8B%E6%B1%A0

本案例来源自：[《线程池运用不当的一次线上事故》](https://club.perfma.com/article/646639)

链接已经变了

本案例来源自：[《线程池运用不当的一次线上事故》](https://heapdump.cn/article/646639)

**Comment by Snailclimb** [comment]
> https://javaguide.cn/java/concurrent/java-thread-pool-best-practices.html#_3%E3%80%81%E5%BB%BA%E8%AE%AE%E4%B8%8D%E5%90%8C%E7%B1%BB%E5%88%AB%E7%9A%84%E4%B8%9A%E5%8A%A1%E7%94%A8%E4%B8%8D%E5%90%8C%E7%9A%84%E7%BA%BF%E7%A8%8B%E6%B1%A0
> 
> 本案例来源自：[《线程池运用不当的一次线上事故》](https://club.perfma.com/article/646639)
> 
> 链接已经变了
> 
> 本案例来源自：[《线程池运用不当的一次线上事故》](https://heapdump.cn/article/646639)

感谢指出，原网站的域名改变了。
