### ISSUE TITLE
java定时任务详解->时间轮部分单位错误

### ISSUE THREAD

**Issue by bonaluo** [Snailclimb/JavaGuide#2197]
java定时任务详解->时间轮部分单位错误 时间轮的单位是ms但是在多层次时间轮举例时使用的单位是s

<img width="673" alt="image" src="https://github.com/Snailclimb/JavaGuide/assets/27731323/cc7e5ccf-dd1a-482c-a65e-9d5c791d72fb">

**Comment by Snailclimb** [comment]
> java定时任务详解->时间轮部分单位错误 时间轮的单位是ms但是在多层次时间轮举例时使用的单位是s
> 
> <img alt="image" width="673" src="https://user-images.githubusercontent.com/27731323/278198026-cc7e5ccf-dd1a-482c-a65e-9d5c791d72fb.png">

笔误了，感谢！

**Comment by bonaluo** [comment]
> > java定时任务详解->时间轮部分单位错误 时间轮的单位是ms但是在多层次时间轮举例时使用的单位是s
> > <img alt="image" width="673" src="https://user-images.githubusercontent.com/27731323/278198026-cc7e5ccf-dd1a-482c-a65e-9d5c791d72fb.png">
> 
> 时间轮的单位不一定是毫秒（ms），也可以是其他的时间单位，比如秒（s），分（m），时（h）等。时间轮的单位取决于时间轮的精度和范围，以及调度任务的需求。

我前面的描述可能不是特别准确, 图例中(文字描述"上图的时间轮")使用的是ms但是举例使用的s, 前后单位就不一致了, 而非时间轮的单位一定是ms

**Comment by Snailclimb** [comment]
> > > java定时任务详解->时间轮部分单位错误 时间轮的单位是ms但是在多层次时间轮举例时使用的单位是s
> > > <img alt="image" width="673" src="https://user-images.githubusercontent.com/27731323/278198026-cc7e5ccf-dd1a-482c-a65e-9d5c791d72fb.png">
> > 
> > 
> > 时间轮的单位不一定是毫秒（ms），也可以是其他的时间单位，比如秒（s），分（m），时（h）等。时间轮的单位取决于时间轮的精度和范围，以及调度任务的需求。
> 
> 我前面的描述可能不是特别准确, 图例中(文字描述"上图的时间轮")使用的是ms但是举例使用的s, 前后单位就不一致了, 而非时间轮的单位一定是ms

哦哦 原来如此 没注意
