### ISSUE TITLE
线程通信问题

### ISSUE THREAD

**Issue by violet617** [Snailclimb/JavaGuide#2199]
我觉得在java并发编程模块缺少线程通信的相关内容

**Comment by Snailclimb** [comment]
> 我觉得在java并发编程模块缺少线程通信的相关内容



> 我觉得在java并发编程模块缺少线程通信的相关内容

虽然没有专门介绍，但里面都有涉及的，比如锁、信号量。

https://javaguide.cn/cs-basics/operating-system/operating-system-basic-questions-01.html#%E8%BF%9B%E7%A8%8B%E9%97%B4%E7%9A%84%E9%80%9A%E4%BF%A1%E6%96%B9%E5%BC%8F%E6%9C%89%E5%93%AA%E4%BA%9B
