### ISSUE TITLE
关于“String s1 = new String("abc");”的疑问

### ISSUE THREAD

**Issue by wangchangxi** [Snailclimb/JavaGuide#2202]
[原文链接](https://javaguide.cn/java/basis/java-basic-questions-02.html#string-s1-new-string-abc-%E8%BF%99%E5%8F%A5%E8%AF%9D%E5%88%9B%E5%BB%BA%E4%BA%86%E5%87%A0%E4%B8%AA%E5%AD%97%E7%AC%A6%E4%B8%B2%E5%AF%B9%E8%B1%A1)

>  String s1 = new String("abc");这句话创建了几个字符串对象？
> 
> 会创建 1 或 2 个字符串对象。
> 
> 1、如果字符串常量池中不存在字符串对象“abc”的引用，那么它将首先在字符串常量池中创建，然后在堆空间中创建，因此将创建总共 2 个字符串对象。
> 
> 2、如果字符串常量池中已存在字符串对象“abc”的引用，则只会在堆中创建 1 个字符串对象“abc”。

原文里提到 `new String("abc")` 会创建 1 或 2 个字符串对象

```sh
 0 new #2 <java/lang/String>
 3 dup
 4 ldc #3 <abc>
 6 invokespecial #4 <java/lang/String.<init> : (Ljava/lang/String;)V>
 9 astore_1
10 return
```

针对具体的字节码有解释说：

> ldc 命令用于判断字符串常量池中是否保存了对应的字符串对象的引用，如果保存了的话直接返回，如果没有保存的话，会在堆中创建对应的字符串对象并将该字符串对象的引用保存到字符串常量池中。

<br/>

通过原文的解释，我测试了一个下面的例子：

```java
// 创建一个String对象，将引用保存到字符串常量池中
String s1 = new String("abc");
// 直接返回字符串常量池中字符串对象"abc"的引用
String s2 = "abc";
System.out.println(s1 == s2); 
```

按照解释 `s1 == s2 ` 的结果应该为 true才对，但实际上是 false，后来我查了一下资料，发现了一些问题:

1. `new String("abc")` 不会将对象的引用保存到字符串常量池中，可以通过 `intern()`方法将字符串添加到字符串常量池并返回共享的引用，如 `String s = new String("abc").intern()`
2. 字节码中的 ldc 指令是 "load constant" 的缩写，它用于将常量加载到操作数栈中。`ldc #3 <abc>` 表示加载常量池中索引为 3 的项，它是一个字符串 "abc"，然后将这个字符串推送到操作数栈的栈顶，以供后续的操作使用。
3. 字符串常量池的字符串引用是在编译时添加到常量池的。当你编写代码并使用字符串字面值，如 `String s1 = "ab";`，编译器会将字符串字面值"ab"添加到字符串常量池中。然后，在运行时，你的代码可以直接引用这个常量池中的"ab"。

这些解释是参考GPT给的回答，按照这个说法，`String s1 = new String("abc");` 这句话只可能是创建了一个对象，并且与字符串常量池不共享，也能很好的解释测试的那个例子。

**Comment by wangchangxi** [comment]
关于测试例子的补充
```java
  // 创建一个String对象，将引用保存到字符串常量池中
  String s1 = new String("abc").intern();
  // 直接返回字符串常量池中字符串对象"abc"的引用
  String s2 = "abc";
  // true
  System.out.println(s1 == s2);
```

**Comment by Snailclimb** [comment]
> [原文链接](https://javaguide.cn/java/basis/java-basic-questions-02.html#string-s1-new-string-abc-%E8%BF%99%E5%8F%A5%E8%AF%9D%E5%88%9B%E5%BB%BA%E4%BA%86%E5%87%A0%E4%B8%AA%E5%AD%97%E7%AC%A6%E4%B8%B2%E5%AF%B9%E8%B1%A1)
> 
> > String s1 = new String("abc");这句话创建了几个字符串对象？
> > 会创建 1 或 2 个字符串对象。
> > 1、如果字符串常量池中不存在字符串对象“abc”的引用，那么它将首先在字符串常量池中创建，然后在堆空间中创建，因此将创建总共 2 个字符串对象。
> > 2、如果字符串常量池中已存在字符串对象“abc”的引用，则只会在堆中创建 1 个字符串对象“abc”。
> 
> 原文里提到 `new String("abc")` 会创建 1 或 2 个字符串对象
> 
> ```shell
>  0 new #2 <java/lang/String>
>  3 dup
>  4 ldc #3 <abc>
>  6 invokespecial #4 <java/lang/String.<init> : (Ljava/lang/String;)V>
>  9 astore_1
> 10 return
> ```
> 
> 针对具体的字节码有解释说：
> 
> > ldc 命令用于判断字符串常量池中是否保存了对应的字符串对象的引用，如果保存了的话直接返回，如果没有保存的话，会在堆中创建对应的字符串对象并将该字符串对象的引用保存到字符串常量池中。
> 
> 
> 通过原文的解释，我测试了一个下面的例子：
> 
> ```java
> // 创建一个String对象，将引用保存到字符串常量池中
> String s1 = new String("abc");
> // 直接返回字符串常量池中字符串对象"abc"的引用
> String s2 = "abc";
> System.out.println(s1 == s2); 
> ```
> 
> 按照解释 `s1 == s2 ` 的结果应该为 true才对，但实际上是 false，后来我查了一下资料，发现了一些问题:
> 
> 1. `new String("abc")` 不会将对象的引用保存到字符串常量池中，可以通过 `intern()`方法将字符串添加到字符串常量池并返回共享的引用，如 `String s = new String("abc").intern()`
> 2. 字节码中的 ldc 指令是 "load constant" 的缩写，它用于将常量加载到操作数栈中。`ldc #3 <abc>` 表示加载常量池中索引为 3 的项，它是一个字符串 "abc"，然后将这个字符串推送到操作数栈的栈顶，以供后续的操作使用。
> 3. 字符串常量池的字符串引用是在编译时添加到常量池的。当你编写代码并使用字符串字面值，如 `String s1 = "ab";`，编译器会将字符串字面值"ab"添加到字符串常量池中。然后，在运行时，你的代码可以直接引用这个常量池中的"ab"。
> 
> 这些解释是参考GPT给的回答，按照这个说法，`String s1 = new String("abc");` 这句话只可能是创建了一个对象，并且与字符串常量池不共享，也能很好的解释测试的那个例子。

```java
// 创建一个String对象，将引用保存到字符串常量池中
String s1 = new String("abc");
// 直接返回字符串常量池中字符串对象"abc"的引用
String s2 = "abc";
System.out.println(s1 == s2); 
```

这个例子中的 s1 和 s2 对应的堆中的对象是不同的哈。

![image](https://github.com/Snailclimb/JavaGuide/assets/29880145/58958ce6-754e-4bf1-be14-a85f5b207edc)

**Comment by wangchangxi** [comment]
> > [原文链接](https://javaguide.cn/java/basis/java-basic-questions-02.html#string-s1-new-string-abc-%E8%BF%99%E5%8F%A5%E8%AF%9D%E5%88%9B%E5%BB%BA%E4%BA%86%E5%87%A0%E4%B8%AA%E5%AD%97%E7%AC%A6%E4%B8%B2%E5%AF%B9%E8%B1%A1)
> > > String s1 = new String("abc");这句话创建了几个字符串对象？
> > > 会创建 1 或 2 个字符串对象。
> > > 1、如果字符串常量池中不存在字符串对象“abc”的引用，那么它将首先在字符串常量池中创建，然后在堆空间中创建，因此将创建总共 2 个字符串对象。
> > > 2、如果字符串常量池中已存在字符串对象“abc”的引用，则只会在堆中创建 1 个字符串对象“abc”。
> > 
> > 
> > 原文里提到 `new String("abc")` 会创建 1 或 2 个字符串对象
> > ```shell
> >  0 new #2 <java/lang/String>
> >  3 dup
> >  4 ldc #3 <abc>
> >  6 invokespecial #4 <java/lang/String.<init> : (Ljava/lang/String;)V>
> >  9 astore_1
> > 10 return
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 针对具体的字节码有解释说：
> > > ldc 命令用于判断字符串常量池中是否保存了对应的字符串对象的引用，如果保存了的话直接返回，如果没有保存的话，会在堆中创建对应的字符串对象并将该字符串对象的引用保存到字符串常量池中。
> > 
> > 
> > 通过原文的解释，我测试了一个下面的例子：
> > ```java
> > // 创建一个String对象，将引用保存到字符串常量池中
> > String s1 = new String("abc");
> > // 直接返回字符串常量池中字符串对象"abc"的引用
> > String s2 = "abc";
> > System.out.println(s1 == s2); 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 按照解释 `s1 == s2 ` 的结果应该为 true才对，但实际上是 false，后来我查了一下资料，发现了一些问题:
> > 
> > 1. `new String("abc")` 不会将对象的引用保存到字符串常量池中，可以通过 `intern()`方法将字符串添加到字符串常量池并返回共享的引用，如 `String s = new String("abc").intern()`
> > 2. 字节码中的 ldc 指令是 "load constant" 的缩写，它用于将常量加载到操作数栈中。`ldc #3 <abc>` 表示加载常量池中索引为 3 的项，它是一个字符串 "abc"，然后将这个字符串推送到操作数栈的栈顶，以供后续的操作使用。
> > 3. 字符串常量池的字符串引用是在编译时添加到常量池的。当你编写代码并使用字符串字面值，如 `String s1 = "ab";`，编译器会将字符串字面值"ab"添加到字符串常量池中。然后，在运行时，你的代码可以直接引用这个常量池中的"ab"。
> > 
> > 这些解释是参考GPT给的回答，按照这个说法，`String s1 = new String("abc");` 这句话只可能是创建了一个对象，并且与字符串常量池不共享，也能很好的解释测试的那个例子。
> 
> ```java
> // 创建一个String对象，将引用保存到字符串常量池中
> String s1 = new String("abc");
> // 直接返回字符串常量池中字符串对象"abc"的引用
> String s2 = "abc";
> System.out.println(s1 == s2); 
> ```
> 
> 这个例子中的 s1 和 s2 对应的堆中的对象是不同的哈。
> 
> ![image](https://user-images.githubusercontent.com/29880145/280205431-58958ce6-754e-4bf1-be14-a85f5b207edc.png)


关于这张图片解释的疑问：
1. ldc 是加载常量池中的值到操作数栈，何来往字符串常量池里保存对象引用一说？
2. 如果`new String("abc")` 在常量池中保存了对象引用，后面 `String s2 = "abc"` 不是会从常量池中直接取出 "abc" 对应的引用，为何说 s1 和 s2对应不同的对象？
3. 将s1改为以下代码后 `String s1 = new String("abc").intern()`, `s1 == s2` 结果为true，是否侧面说明 `new String("abc")` 本身并不会往常量池中保存引用？

**Comment by wangchangxi** [comment]
> > [原文链接](https://javaguide.cn/java/basis/java-basic-questions-02.html#string-s1-new-string-abc-%E8%BF%99%E5%8F%A5%E8%AF%9D%E5%88%9B%E5%BB%BA%E4%BA%86%E5%87%A0%E4%B8%AA%E5%AD%97%E7%AC%A6%E4%B8%B2%E5%AF%B9%E8%B1%A1)
> > > String s1 = new String("abc");这句话创建了几个字符串对象？
> > > 会创建 1 或 2 个字符串对象。
> > > 1、如果字符串常量池中不存在字符串对象“abc”的引用，那么它将首先在字符串常量池中创建，然后在堆空间中创建，因此将创建总共 2 个字符串对象。
> > > 2、如果字符串常量池中已存在字符串对象“abc”的引用，则只会在堆中创建 1 个字符串对象“abc”。
> > 
> > 
> > 原文里提到 `new String("abc")` 会创建 1 或 2 个字符串对象
> > ```shell
> >  0 new #2 <java/lang/String>
> >  3 dup
> >  4 ldc #3 <abc>
> >  6 invokespecial #4 <java/lang/String.<init> : (Ljava/lang/String;)V>
> >  9 astore_1
> > 10 return
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 针对具体的字节码有解释说：
> > > ldc 命令用于判断字符串常量池中是否保存了对应的字符串对象的引用，如果保存了的话直接返回，如果没有保存的话，会在堆中创建对应的字符串对象并将该字符串对象的引用保存到字符串常量池中。
> > 
> > 
> > 通过原文的解释，我测试了一个下面的例子：
> > ```java
> > // 创建一个String对象，将引用保存到字符串常量池中
> > String s1 = new String("abc");
> > // 直接返回字符串常量池中字符串对象"abc"的引用
> > String s2 = "abc";
> > System.out.println(s1 == s2); 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 按照解释 `s1 == s2 ` 的结果应该为 true才对，但实际上是 false，后来我查了一下资料，发现了一些问题:
> > 
> > 1. `new String("abc")` 不会将对象的引用保存到字符串常量池中，可以通过 `intern()`方法将字符串添加到字符串常量池并返回共享的引用，如 `String s = new String("abc").intern()`
> > 2. 字节码中的 ldc 指令是 "load constant" 的缩写，它用于将常量加载到操作数栈中。`ldc #3 <abc>` 表示加载常量池中索引为 3 的项，它是一个字符串 "abc"，然后将这个字符串推送到操作数栈的栈顶，以供后续的操作使用。
> > 3. 字符串常量池的字符串引用是在编译时添加到常量池的。当你编写代码并使用字符串字面值，如 `String s1 = "ab";`，编译器会将字符串字面值"ab"添加到字符串常量池中。然后，在运行时，你的代码可以直接引用这个常量池中的"ab"。
> > 
> > 这些解释是参考GPT给的回答，按照这个说法，`String s1 = new String("abc");` 这句话只可能是创建了一个对象，并且与字符串常量池不共享，也能很好的解释测试的那个例子。
> 
> ```java
> // 创建一个String对象，将引用保存到字符串常量池中
> String s1 = new String("abc");
> // 直接返回字符串常量池中字符串对象"abc"的引用
> String s2 = "abc";
> System.out.println(s1 == s2); 
> ```
> 
> 这个例子中的 s1 和 s2 对应的堆中的对象是不同的哈。
> 
> ![image](https://user-images.githubusercontent.com/29880145/280205431-58958ce6-754e-4bf1-be14-a85f5b207edc.png)


还是上述那个例子，有些对图片的疑问，还望guide哥解答下， @Snailclimb 
1. ldc 指令用于将常量池中的常量值（如字符串、整数、浮点数等）加载到操作数栈上，何来“在字符串常量池保存字符串对应对象引用”的功能？
2. 如果 new String("abc") 真的会去往常量池中保存对象引用，为何要将堆对象的引用保存到字符串常量池中？字符串常量池存储的不是字符串字面量吗？

下面是我自己查资料总结的一些结论：
- 字符串常量池的内容在编译时和运行时都会被加载，编译时加载的是编译期已知的字符串字面量，而运行时加载的是通过 intern() 方法添加到常量池中的引用。
- `String s2 = "abc"`，在编译期字面量"abc"就被加载到了字符串常量池，运行期将 s2 的引用指向 "abc"字面量，并没有在堆中创建新对象；`String s1 = new String("abc")`，s1 的引用指向的是堆中的对象，s1 == s2确实应该为false，二者的引用不相同； `s1.intern() == s2` 为true也是符合预期的，通过intern()方法发现常量池中已经存在字面量 "abc"，s1.intern() 其实就是指向字面量 "abc"的引用。

**Comment by Snailclimb** [comment]
> ```java
> String s1 = new String("abc");
> ```

`String s1 = new String("abc");` 会在堆上创建两个字符串对象，其中一个字符串对象的引用会被保存在字符串常量池中。
