### ISSUE TITLE
MyBatis常见面试题总结的#{} 和 ${} 的区别是什么描述不准确

### ISSUE THREAD

**Issue by yanghuoji** [Snailclimb/JavaGuide#2216]
MyBatis中，${}可以把硬编码的字符串SQL语句当参数使用拼接到XML里sql语句里执行

比如：
sqlStr1 = "left join tableb b on a.id=b.id";
sqlStr2 = "left join tableb c on a.id=c.id";
<sql> select * from tablea a
${sqlStr1}
${sqlStr2}
where 1=1 ......
 </sql>

![image](https://github.com/Snailclimb/JavaGuide/assets/125146618/c5f9c556-c7f2-4ae9-8272-b9f5be54472d)

**Comment by qiaoxingxing** [comment]
@Snailclimb  提交了一个pr
 https://github.com/Snailclimb/JavaGuide/pull/2231
