### ISSUE TITLE
DNS不应算作应用层协议

### ISSUE THREAD

**Issue by mkx000** [Snailclimb/JavaGuide#2217]
[这里把DNS归到了应用层协议里面](https://github.com/Snailclimb/JavaGuide/blob/9dad19c7c9add3027eb66f6871ed656eae4d5f1a/docs/cs-basics/network/other-network-questions.md#%E5%B8%B8%E8%A7%81%E7%BD%91%E7%BB%9C%E5%8D%8F%E8%AE%AE)

根据wikipedia上的定义， [DNS](https://en.wikipedia.org/wiki/Domain_Name_System)应当被认为是一种分布式计算机系统。因此，要么移除DNS这一条，要么应当另加说明。

---------------编辑--------------
[还有这里也把DNS作为协议](https://javaguide.cn/cs-basics/network/other-network-questions.html#dns-%E7%9A%84%E4%BD%9C%E7%94%A8%E6%98%AF%E4%BB%80%E4%B9%88)
[另外补充一个GPT的解释](https://chat.openai.com/share/2854378a-aa6e-47c9-922b-345145cc9294)

**Comment by mkx000** [comment]
https://en.wikipedia.org/wiki/Domain_Name_System，这里又确实把DNS归到了Application layer

**Comment by mkx000** [comment]
<img width="401" alt="dns" src="https://github.com/Snailclimb/JavaGuide/assets/53012116/aa9f165d-771e-4648-b4fa-6565d73dd633">

**Comment by Snailclimb** [comment]
> 这里把DNS归到了应用层协议里面

也就是说：DNS 更常被描述为一种服务或系统，而不是协议。DNS 协议是用于在 DNS 服务器和客户端之间通信的协议，但整个 DNS 系统包括许多其他组件，例如域名注册机构、DNS 服务器和递归解析器等。

**Comment by Snailclimb** [comment]
> [这里把DNS归到了应用层协议里面](https://github.com/Snailclimb/JavaGuide/blob/9dad19c7c9add3027eb66f6871ed656eae4d5f1a/docs/cs-basics/network/other-network-questions.md#%E5%B8%B8%E8%A7%81%E7%BD%91%E7%BB%9C%E5%8D%8F%E8%AE%AE)
> 
> 根据wikipedia上的定义， [DNS](https://en.wikipedia.org/wiki/Domain_Name_System)应当被认为是一种分布式计算机系统。因此，要么移除DNS这一条，要么应当另加说明。
> 
> ---------------编辑-------------- [还有这里也把DNS作为协议](https://javaguide.cn/cs-basics/network/other-network-questions.html#dns-%E7%9A%84%E4%BD%9C%E7%94%A8%E6%98%AF%E4%BB%80%E4%B9%88) [另外补充一个GPT的解释](https://chat.openai.com/share/2854378a-aa6e-47c9-922b-345145cc9294)

一般情况，我们分类时还是会将 DNS 规划到应用层协议中哈。
