### ISSUE TITLE
JWT 身份认证优缺点分析章节sa-token项目地址无效

### ISSUE THREAD

**Issue by mervynlam** [Snailclimb/JavaGuide#2219]
![image](https://github.com/Snailclimb/JavaGuide/assets/26081972/35c94a4f-3680-4ff0-9d5f-5d555ff2f4c8)

**Comment by HauZeeLi** [comment]
《Java 魔法类 Unsafe 详解》中测试unsafe.loadFence();时。
实测注释掉unsafe.loadFence();
flag最终也会修改为true，没有陷入死循环。
jdk版本1.8.0_252

**Comment by Snailclimb** [comment]
> ![image](https://private-user-images.githubusercontent.com/26081972/289909638-35c94a4f-3680-4ff0-9d5f-5d555ff2f4c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NjIxMTYsIm5iZiI6MTcwMjU2MTgxNiwicGF0aCI6Ii8yNjA4MTk3Mi8yODk5MDk2MzgtMzVjOTRhNGYtMzY4MC00ZmYwLTlkNWYtNWQ1NTVmZjJmNGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEzNTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNDhjZTZlMzBkMTc3NTE5MzVjZDJhZTQ1NDNhNTk0NmU2ZTY5NWIxMzhiZjJiYmQwMzFiMTdlY2E1NGRmMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2h_U-Gvky53S1SvHtsldgF7Q3mw7GCyAfE97EGuUD2Y)

感谢指出，已修正，地址：https://github.com/dromara/sa-token 。
