### ISSUE TITLE
《Java 魔法类 Unsafe 详解》unsafe.loadFence();问题

### ISSUE THREAD

**Issue by HauZeeLi** [Snailclimb/JavaGuide#2220]
《Java 魔法类 Unsafe 详解》中测试unsafe.loadFence();时。
实测注释掉unsafe.loadFence();
flag最终也会修改为true，没有陷入死循环。
jdk版本1.8.0_252

**Comment by Snailclimb** [comment]
> 《Java 魔法类 Unsafe 详解》中测试unsafe.loadFence();时。 实测注释掉unsafe.loadFence(); flag最终也会修改为true，没有陷入死循环。 jdk版本1.8.0_252

可能是优化过了？具体原因我也不太清楚。

**Comment by liach** [comment]
陷入死循环只是有可能，不是一定的。实际上这种光检测单变量最适合的是`setOpaque`和`getOpaque`（Java 9+），保证会刷新缓存不陷入死循环。

**Comment by HauZeeLi** [comment]
多谢解答.
