### ISSUE TITLE
Java线程池详解章节-线程池原理分析文字描述顺序有误引起歧义

### ISSUE THREAD

**Issue by liuxiaohui1221** [Snailclimb/JavaGuide#2223]
第2条和第3条文字描述的顺序和代码和图顺序颠倒了吧？
![image](https://github.com/Snailclimb/JavaGuide/assets/23338827/888dd605-ca97-4c16-bd70-b0ed8ae54494)
https://javaguide.cn/java/concurrent/java-thread-pool-summary.html#%E7%BA%BF%E7%A8%8B%E6%B1%A0%E5%8E%9F%E7%90%86%E5%88%86%E6%9E%90

**Comment by liuxiaohui1221** [comment]
问题1：应该是先判断队列是否已满，后判断最大线程池是否已满
问题2：第四点，执行拒绝策略描述可以完整点，比如修改成：在任务队列已满，且已达到最大线程数，则当前任务会被拒绝，执行饱和策略...

**Comment by Snailclimb** [comment]
> 第2条和第3条文字描述的顺序和代码和图顺序颠倒了吧？ ![image](https://private-user-images.githubusercontent.com/23338827/290977975-888dd605-ca97-4c16-bd70-b0ed8ae54494.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NzIwODgsIm5iZiI6MTcwMjk3MTc4OCwicGF0aCI6Ii8yMzMzODgyNy8yOTA5Nzc5NzUtODg4ZGQ2MDUtY2E5Ny00YzE2LWJkNzAtYjBlZDhhZTU0NDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA3NDMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNzQyNWJkNTJiNmQ4NzJiZjU2M2YzMjc0NmQxYWE3MmJjZjg2NDMwZGNkY2Q0NTcwYzg2ZDA0OTE0MGY2OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k0GnyAfSgjJ0qXrPh51rgEL6ka1K1q9uBCn1UfiDKN0) https://javaguide.cn/java/concurrent/java-thread-pool-summary.html#%E7%BA%BF%E7%A8%8B%E6%B1%A0%E5%8E%9F%E7%90%86%E5%88%86%E6%9E%90

顺序就是先判断阻塞队列是否已满。另外，图示只是简化版流程。
