### ISSUE TITLE
Folding Styles of Sidebar

### ISSUE THREAD

**Issue by skeetyu** [Snailclimb/JavaGuide#2224]
Hello, I find some parent directories are collapsible in the sidebar while some not. There are so many times I click on non-collapsible items by mistake, resulting in a not very good user experience.
I wonder if it is by design? If not, I hope to fix the problem to a uniform folding style. 
<img width="324" alt="截屏2023-12-18 19 35 30" src="https://github.com/Snailclimb/JavaGuide/assets/62090366/686d5574-0002-42f3-be08-bd59a46c682e">
 
Besides, I find the sidebar cannot be folded when device's resolution ratio is high. 
If possible, I also hope to fix it to give users freedom to choose whether to fold the sidebar.
<img width="431" alt="截屏2023-12-18 19 53 26" src="https://github.com/Snailclimb/JavaGuide/assets/62090366/e13b4110-4a34-45db-9b20-5aff21b82c58">

**Comment by Snailclimb** [comment]
> 您好，我发现有些父目录可以在侧边栏中折叠，而有些则不能。很多时候我错误地点击了不可折叠的项目，导致用户体验不太好。 我想知道这是设计使然吗？如果没有的话，希望能将问题修复为统一的折叠样式。 <img alt="截屏2023-12-18 19 35 30" width="324" src="https://private-user-images.githubusercontent.com/62090366/291268618-686d5574-0002-42f3-be08-bd59a46c682e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NzE5NjksIm5iZiI6MTcwMjk3MTY2OSwicGF0aCI6Ii82MjA5MDM2Ni8yOTEyNjg2MTgtNjg2ZDU1NzQtMDAwMi00MmYzLWJlMDgtYmQ1OWE0NmM2ODJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA3NDEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYzcwY2E5MTVlYWY4ZDAzZmUwMGVlODFiZWY1MDY2MGIzMTQ3YjQxMGY3OTk2MDQxNTMyMWVlM2QwYWJjY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tJsUX-OunMYBf-ye2oGT0hlGsM3Q8Gb7zu7lWEa81wI">
> 
> 此外，我发现当设备分辨率较高时，侧边栏无法折叠。 如果可以的话，我也希望能够修复它，让用户可以自由选择是否折叠侧边栏。 <img alt="截屏2023-12-18 19 53 26" width="431" src="https://private-user-images.githubusercontent.com/62090366/291271044-e13b4110-4a34-45db-9b20-5aff21b82c58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NzE5NjksIm5iZiI6MTcwMjk3MTY2OSwicGF0aCI6Ii82MjA5MDM2Ni8yOTEyNzEwNDQtZTEzYjQxMTAtNGEzNC00NWRiLTliMjAtNWFmZjIxYjgyYzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA3NDEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzOTcxMWY5YzhlNjNlZmQxZGMyNjkyNGNlZmYwOWM0ZTkxNDZmMDY2YmRiNDkzODM4OWVhZjFkZjIxYjNkMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8EH5jhjrNWlKob5F9i7GRiBSBodUiwoI9w402zaRsjM">

Hello, some directories do not fold, this is my configuration. In addition, the resolution displays the collapse button which is the default for vuepress themes.
