### ISSUE TITLE
Java并发常见面试题总结(中) 构造器线程安全疑问

### ISSUE THREAD

**Issue by NachtZhong** [Snailclimb/JavaGuide#2227]
> 构造方法可以用 synchronized 修饰么？先说结论：构造方法不能使用 synchronized 关键字修饰。
> 构造方法本身就属于线程安全的，不存在同步的构造方法一说。

guide哥你好, 关于这一部分有点疑问, 写了一个测试代码来测试:
```java
public class TestObject {
    static int counter = 0;
    TestObject(){
        counter += 1;
    }
}
```

```java
public class TestConstructorThreadSafe {
    public static void main(String[] args) throws InterruptedException {
        Thread t1 = new Thread(() -> {
            for (int i = 0; i < 10000; i++) {
                TestObject testObject = new TestObject();
            }
        });
        Thread t2 = new Thread(() -> {
            for (int i = 0; i < 10000; i++) {
                TestObject testObject = new TestObject();
            }
        });
        t1.start();
        t2.start();
        t1.join();
        t2.join();
        System.out.println("执行完成后counter的值: " + TestObject.counter);
    }
}
```

过程是两个线程各自循环10000次调用构造函数创建TestObject类实例, 对其counter变量进行自增。最后输出的结果是小于20000的, 这样是否说明构造函数并非是线程安全的呢?

**Comment by Snailclimb** [comment]
> > 构造方法可以用 synchronized 修饰么？先说结论：构造方法不能使用 synchronized 关键字修饰。
> > 构造方法本身就属于线程安全的，不存在同步的构造方法一说。
> 
> guide哥你好, 关于这一部分有点疑问, 写了一个测试代码来测试:
> 
> ```java
> public class TestObject {
>     static int counter = 0;
>     TestObject(){
>         counter += 1;
>     }
> }
> ```
> 
> ```java
> public class TestConstructorThreadSafe {
>     public static void main(String[] args) throws InterruptedException {
>         Thread t1 = new Thread(() -> {
>             for (int i = 0; i < 10000; i++) {
>                 TestObject testObject = new TestObject();
>             }
>         });
>         Thread t2 = new Thread(() -> {
>             for (int i = 0; i < 10000; i++) {
>                 TestObject testObject = new TestObject();
>             }
>         });
>         t1.start();
>         t2.start();
>         t1.join();
>         t2.join();
>         System.out.println("执行完成后counter的值: " + TestObject.counter);
>     }
> }
> ```
> 
> 过程是两个线程各自循环10000次调用构造函数创建TestObject类实例, 对其counter变量进行自增。最后输出的结果是小于20000的, 这样是否说明构造函数并非是线程安全的呢?

测试代码中，counter 是一个静态变量，它是属于类的，而不是属于对象的。所以，当多个线程同时调用构造方法时，它们都会对 counter 进行自增操作，这就会导致线程不安全的问题。你的代码实际上是在测试类变量的线程安全性，而不是构造方法的线程安全性。
