### ISSUE TITLE
关于数据库-字符集详解中的一些疑惑

### ISSUE THREAD

**Issue by mi0e** [Snailclimb/JavaGuide#2235]
原文：[常见的字符集有 ASCII、GB2312、GBK、UTF-8……。](https://github.com/Snailclimb/JavaGuide/blob/f0181eb02061f8d8a591bd4e56a351d4a1648c99/docs/database/character-set.md?plain=1#L24C29-L24C30)

UTF8是字符编码而非字符集吧？所以这里写Unicode应该更合适？

**Comment by Snailclimb** [comment]
> 原文：[常见的字符集有 ASCII、GB2312、GBK、UTF-8……。](https://github.com/Snailclimb/JavaGuide/blob/f0181eb02061f8d8a591bd4e56a351d4a1648c99/docs/database/character-set.md?plain=1#L24C29-L24C30)
> 
> UTF8是字符编码而非字符集吧？所以这里写Unicode应该更合适？

确实要更合适一些。刚看了这篇介绍字符、字符集、字符编码的文章：https://zhuanlan.zhihu.com/p/260192496 ，挺不错的。
