### ISSUE TITLE
spring事务中trancational注解默认回滚策略描述有误

### ISSUE THREAD

**Issue by sunwenhaopro** [Snailclimb/JavaGuide#2236]
[@Transactional(rollbackFor = Exception.class)注解了解吗？

当 @Transactional 注解作用于类上时，该类的所有 public 方法将都具有该类型的事务属性，同时，我们也可以在方法级别使用该标注来覆盖类级别的定义。如果类或者方法加了这个注解，那么这个类里面的方法抛出异常，就会回滚，数据库里面的数据也会回滚。

在 @Transactional 注解中如果不配置rollbackFor属性,那么事务只会在遇到RuntimeException的时候才会回滚，加上 rollbackFor=Exception.class,可以让事务在遇到非运行时异常时也回滚。
-------------------------------
默认的是遇到Error和RuntimeException时都会回滚
![1704768088308](https://github.com/Snailclimb/JavaGuide/assets/95746922/10c91746-4a62-4edd-bad1-435ddaaffd7c)

**Comment by Snailclimb** [comment]
> [@transactional(rollbackFor = Exception.class)注解了解吗？
> 
> 当 @transactional 注解作用于类上时，该类的所有 public 方法将都具有该类型的事务属性，同时，我们也可以在方法级别使用该标注来覆盖类级别的定义。如果类或者方法加了这个注解，那么这个类里面的方法抛出异常，就会回滚，数据库里面的数据也会回滚。
> 
> ## 在 @transactional 注解中如果不配置rollbackFor属性,那么事务只会在遇到RuntimeException的时候才会回滚，加上 rollbackFor=Exception.class,可以让事务在遇到非运行时异常时也回滚。
> 默认的是遇到Error和RuntimeException时都会回滚 ![1704768088308](https://private-user-images.githubusercontent.com/95746922/295085782-10c91746-4a62-4edd-bad1-435ddaaffd7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTkwMzYsIm5iZiI6MTcwNDc5ODczNiwicGF0aCI6Ii85NTc0NjkyMi8yOTUwODU3ODItMTBjOTE3NDYtNGE2Mi00ZWRkLWJhZDEtNDM1ZGRhYWZmZDdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDExMTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5OTY2OTZiZmMwMWMxN2NjYzQ1NGQ2OTZhMjQxMDBkYWNlNTlhMWE0MzA5NWZjZWYzMDJiYWI2OGU5ZWYyYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8F654pwBZL2lpiOOQfSLa3tVLBVcFPWP8ighcM7pfjk)

感谢指出。

Spring @Transactional 注解默认回滚策略是只有在遇到运行时异常（RuntimeException）或者 Error 时才会回滚事务，而不会回滚受检异常（Checked Exception）。这是因为 Spring 认为运行时异常和 Error 是不可预期的错误，而受检异常是可预期的错误，可以通过业务逻辑来处理。
