### ISSUE TITLE
成员变量的存放位置

### ISSUE THREAD

**Issue by Orange-Summer** [Snailclimb/JavaGuide#2239]
[基本类型和包装类型的区别](https://javaguide.cn/java/basis/java-basic-questions-01.html#基本类型和包装类型的区别)中的这句话

> 基本数据类型存放在栈中是一个常见的误区！ 基本数据类型的成员变量如果没有被 static 修饰的话（不建议这么使用，应该要使用基本数据类型对应的包装类型），就存放在堆中。

这句话容易让人有种误解：被 static 修饰的基本数据类型的成员变量存放在栈中。

实际上应该只要成员变量都存放在堆中吧。下面是《深入理解 Java 虚拟机》第三版里的内容，说明被 static 修饰的基本数据类型的成员变量也存放在堆中。

> 准备阶段是正式为类中定义的变量（即静态变量，被 static 修饰的变量）分配内存
并设置类变量初始值的阶段，从概念上讲，这些变量所使用的内存都应当在方法区中进
行分配，但必须注意到方法区本身是一个逻辑上的区域，在 JDK 7 及之前，HotSpot 使
用永久代来实现方法区时，实现是完全符合这种逻辑概念的；而在 JDK 8 及之后，类变
量则会随着 Class 对象一起存放在 Java 堆中

**Comment by Snailclimb** [comment]
> [基本类型和包装类型的区别](https://javaguide.cn/java/basis/java-basic-questions-01.html#%E5%9F%BA%E6%9C%AC%E7%B1%BB%E5%9E%8B%E5%92%8C%E5%8C%85%E8%A3%85%E7%B1%BB%E5%9E%8B%E7%9A%84%E5%8C%BA%E5%88%AB)中的这句话
> 
> > 基本数据类型存放在栈中是一个常见的误区！ 基本数据类型的成员变量如果没有被 static 修饰的话（不建议这么使用，应该要使用基本数据类型对应的包装类型），就存放在堆中。
> 
> 这句话容易让人有种误解：被 static 修饰的基本数据类型的成员变量存放在栈中。
> 
> 实际上应该只要成员变量都存放在堆中吧。下面是《深入理解 Java 虚拟机》第三版里的内容，说明被 static 修饰的基本数据类型的成员变量也存放在堆中。
> 
> > 准备阶段是正式为类中定义的变量（即静态变量，被 static 修饰的变量）分配内存
> > 并设置类变量初始值的阶段，从概念上讲，这些变量所使用的内存都应当在方法区中进
> > 行分配，但必须注意到方法区本身是一个逻辑上的区域，在 JDK 7 及之前，HotSpot 使
> > 用永久代来实现方法区时，实现是完全符合这种逻辑概念的；而在 JDK 8 及之后，类变
> > 量则会随着 Class 对象一起存放在 Java 堆中

感谢确实会让人误解，下面是我的修正。

**基本数据类型存放在栈中是一个常见的误区！** 基本数据类型的存储位置取决于它们的作用域和声明方式。如果它们是局部变量，那么它们会存放在栈中；如果它们是成员变量，那么它们会存放在堆中。

```java
public class Test {
    // 成员变量，存放在堆中
    int a = 10;
    // 被 static 修饰，也存放在堆中，但属于类，不属于对象
    // JDK1.7 字符串常量池和静态变量从永久代移动了 Java 堆中
    static int b = 20; 

    public void method() {
        // 局部变量，存放在栈中
        int c = 30;
        static int d = 40; // 编译错误，不能在方法中使用 static 修饰局部变量
    }
}
```

###
