### ISSUE TITLE
超链接错误

### ISSUE THREAD

**Issue by wrote-code** [Snailclimb/JavaGuide#2240]
超链接里多了行号，点击后需要手动删除行号

![图片](https://github.com/Snailclimb/JavaGuide/assets/39870481/ab12981a-d3b1-46d7-b3b7-e34c8ecf8054)

**Comment by Snailclimb** [comment]
> 超链接里多了行号，点击后需要手动删除行号
> 
> ![图片](https://private-user-images.githubusercontent.com/39870481/295818978-ab12981a-d3b1-46d7-b3b7-e34c8ecf8054.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NzY5ODAsIm5iZiI6MTcwNDk3NjY4MCwicGF0aCI6Ii8zOTg3MDQ4MS8yOTU4MTg5NzgtYWIxMjk4MWEtZDNiMS00NmQ3LWIzYjctZTM0YzhlY2Y4MDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDEyMzgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNDU5NmNkZmRhOGVjODhjMzg0ZWIzMDZmYjYzYWNiZGRiNTEzZjc5MmQ1ZGU2YjNhZDgwYjA1ZDMyYjdjNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LR4nxJAHTdetz7K9K2LqMXzbcb-V7bOIKtjj4wM2tjc)

感谢，已修复。前段时间一个PR规范格式的时候出现的问题：

<img width="1129" alt="image" src="https://github.com/Snailclimb/JavaGuide/assets/29880145/9a759ea7-a959-4a20-a32d-6567d910aef2">
