### ISSUE TITLE
LinkedBlockingQueue的ReentrantLock 锁只支持非公平锁

### ISSUE THREAD

**Issue by wallfacers** [Snailclimb/JavaGuide#2243]
https://javaguide.cn/java/collection/java-collection-questions-01.html#blockingqueue-%E7%9A%84%E5%AE%9E%E7%8E%B0%E7%B1%BB%E6%9C%89%E5%93%AA%E4%BA%9B

LinkedBlockingQueue的ReentrantLock 锁只支持非非公平锁

![image](https://github.com/Snailclimb/JavaGuide/assets/26599681/01914f7f-5734-4de4-976f-7cb21188c548)

源代码
![image](https://github.com/Snailclimb/JavaGuide/assets/26599681/bb3d1c9d-af6b-4479-baf5-6a0174378f41)

**Comment by Snailclimb** [comment]
> https://javaguide.cn/java/collection/java-collection-questions-01.html#blockingqueue-%E7%9A%84%E5%AE%9E%E7%8E%B0%E7%B1%BB%E6%9C%89%E5%93%AA%E4%BA%9B
> 
> LinkedBlockingQueue的ReentrantLock 锁只支持非非公平锁
> 
> ![image](https://private-user-images.githubusercontent.com/26599681/297794859-01914f7f-5734-4de4-976f-7cb21188c548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NjYxODMsIm5iZiI6MTcwNTY2NTg4MywicGF0aCI6Ii8yNjU5OTY4MS8yOTc3OTQ4NTktMDE5MTRmN2YtNTczNC00ZGU0LTk3NmYtN2NiMjExODhjNTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEyMDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyOTM2Zjg3NTJiNzZhNDgzMTBjOTdjMzU1MWNlZTk0OThiYThkMDk3NTk1OTU5ZTYyM2EwNjRiY2JmOTE3NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z4CoEc7bbzQ04ics2wEqNmmYOXeXUDNtWhieSlkLuMY)
> 
> 源代码 ![image](https://private-user-images.githubusercontent.com/26599681/297795620-bb3d1c9d-af6b-4479-baf5-6a0174378f41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NjYxODMsIm5iZiI6MTcwNTY2NTg4MywicGF0aCI6Ii8yNjU5OTY4MS8yOTc3OTU2MjAtYmIzZDFjOWQtYWY2Yi00NDc5LWJhZjUtNmEwMTc0Mzc4ZjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEyMDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ODRlMGFjNWI3NWYzZmM1Y2IzZWE2Mzk2ZDA2OGY4OTI0YjNhNTU5MTlmYjU2YmYwYjUwNWUyNzFmMGYxMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MpQGV-gZc5BzYsn2Seb8iesNA6gnSZkKDHes-o5VPQQ)

感谢指出！
