### ISSUE TITLE
Java集合常见面试题总结(下) 中 HashMap 为什么线程不安全？，还有可能存在扩容时获取不到元素

### ISSUE THREAD

**Issue by holyholic704** [Snailclimb/JavaGuide#2247]
如果 get 方法要获取的节点是个链表或红黑树

线程 1 在执行扩容操作

```java
final Node<K,V>[] resize() {
    
    ...

    // 线程1正在执行扩容操作，但还未执行到这，所以目前通过get方法获取元素，使用的还是旧数组，计算下标时用的还是旧数组的大小
    table = newTab;

    ...

    return newTab;
}
```

线程 2 执行 get 方法

```java
final Node<K,V> getNode(int hash, Object key) {
    Node<K,V>[] tab; Node<K,V> first, e; int n; K k;
    // 线程2仍用旧数组的大小来获取下标位置
    if ((tab = table) != null && (n = tab.length) > 0 &&
        (first = tab[(n - 1) & hash]) != null) {
        ...
        // 假如发现该位置是个红黑树或链表，准备遍历红黑树或链表，这时已经不需要再使用数组了，所以线程1将当前的数组指向数组也没关系
        if ((e = first.next) != null) {
            if (first instanceof TreeNode)
                return ((TreeNode<K,V>)first).getTreeNode(hash, key);
            do {
                if (e.hash == hash &&
                    ((k = e.key) == key || (key != null && key.equals(k))))
                    return e;
            } while ((e = e.next) != null);
        }
    }
    return null;
}
```

线程 1 继续执行扩容操作

```java
final Node<K,V>[] resize() {
    
    ...

    // 线程1继续往后执行
    table = newTab;
    if (oldTab != null) {
        // 将旧数组内的元素移到新数组中
        for (int j = 0; j < oldCap; ++j) {
            Node<K,V> e;
            if ((e = oldTab[j]) != null) {
                oldTab[j] = null;
                ...
                // 红黑树的分割操作
                else if (e instanceof TreeNode)
                ...
                // 链表的分割操作
                else {
                    ...
                }
            }
        }
    }
    return newTab;
}
```

如果线程 2 现在正在遍历红黑树或链表，这时线程 1 可能正在执行分割操作，也可能已经执行完分割操作。不管怎样，线程 2 当前遍历的红黑树或链表中，节点中维护的指针都可能产生了变化，如果很不巧的，线程 2 想查找的元素，正好在另一个红黑树或链表中，就会导致返回 null，虽然这个元素之前确实存在在该位置

**Comment by Snailclimb** [comment]
> 如果 get 方法要获取的节点是个链表或红黑树
> 
> 线程 1 在执行扩容操作
> 
> ```java
> final Node<K,V>[] resize() {
>     
>     ...
> 
>     // 线程1正在执行扩容操作，但还未执行到这，所以目前通过get方法获取元素，使用的还是旧数组，计算下标时用的还是旧数组的大小
>     table = newTab;
> 
>     ...
> 
>     return newTab;
> }
> ```
> 
> 线程 2 执行 get 方法
> 
> ```java
> final Node<K,V> getNode(int hash, Object key) {
>     Node<K,V>[] tab; Node<K,V> first, e; int n; K k;
>     // 线程2仍用旧数组的大小来获取下标位置
>     if ((tab = table) != null && (n = tab.length) > 0 &&
>         (first = tab[(n - 1) & hash]) != null) {
>         ...
>         // 假如发现该位置是个红黑树或链表，准备遍历红黑树或链表，这时已经不需要再使用数组了，所以线程1将当前的数组指向数组也没关系
>         if ((e = first.next) != null) {
>             if (first instanceof TreeNode)
>                 return ((TreeNode<K,V>)first).getTreeNode(hash, key);
>             do {
>                 if (e.hash == hash &&
>                     ((k = e.key) == key || (key != null && key.equals(k))))
>                     return e;
>             } while ((e = e.next) != null);
>         }
>     }
>     return null;
> }
> ```
> 
> 线程 1 继续执行扩容操作
> 
> ```java
> final Node<K,V>[] resize() {
>     
>     ...
> 
>     // 线程1继续往后执行
>     table = newTab;
>     if (oldTab != null) {
>         // 将旧数组内的元素移到新数组中
>         for (int j = 0; j < oldCap; ++j) {
>             Node<K,V> e;
>             if ((e = oldTab[j]) != null) {
>                 oldTab[j] = null;
>                 ...
>                 // 红黑树的分割操作
>                 else if (e instanceof TreeNode)
>                 ...
>                 // 链表的分割操作
>                 else {
>                     ...
>                 }
>             }
>         }
>     }
>     return newTab;
> }
> ```
> 
> 如果线程 2 现在正在遍历红黑树或链表，这时线程 1 可能正在执行分割操作，也可能已经执行完分割操作。不管怎样，线程 2 当前遍历的红黑树或链表中，节点中维护的指针都可能产生了变化，如果很不巧的，线程 2 想查找的元素，正好在另一个红黑树或链表中，就会导致返回 null，虽然这个元素之前确实存在在该位置

感谢指出，如果感兴趣的话，可以在内容上提交一个PR完善一下，
