### ISSUE TITLE
线程池介绍中关于饱和策略的描述问题

### ISSUE THREAD

**Issue by Phony520** [Snailclimb/JavaGuide#2248]
在docs/java/concurrent/java-thread-pool-summary.md中

针对ThreadPoolExecutor构造器中饱和策略的描述，ThreadPoolExecutor 饱和策略定义：“如果当前同时运行的线程数量达到最大线程数量并且队列也已经被放满了任务时，ThreadPoolTaskExecutor 定义一些策略:。。。。。。。”

根据JDK1.8中源码，拒绝策略为ThreadPoolExecutor中定义的静态内部类，而不是ThreadPoolTaskExecutor 定义

**Comment by Snailclimb** [comment]
> ThreadPoolExecutor

感谢指出，这里笔误了。
