### ISSUE TITLE
Zookeeper相关概念总结（入门）ZAB协议分析 链接失效

### ISSUE THREAD

**Issue by Oli51467** [Snailclimb/JavaGuide#2249]
在“ZAB 协议两种基本的模式：崩溃恢复和消息广播”这一小节

**Comment by Snailclimb** [comment]
> 崩溃恢复和消息广播

感谢，已修正，网站会晚一些同步。可以看这篇：https://wingsxdu.com/posts/database/zookeeper/ ，内容更好一些。
