### ISSUE TITLE
建议修改下'最终操作'描述

### ISSUE THREAD

**Issue by findsomeoneyys** [Snailclimb/JavaGuide#225]
首先感谢提供这么好的材料!
然后在这个文章中[Java8Tutorial](https://github.com/Snailclimb/JavaGuide/blob/master/Java/What's%20New%20in%20JDK8/Java8Tutorial.md#match%E5%8C%B9%E9%85%8D) ,关于匹配,计数那里,`最终操作` 看着确实有点不太好理解,我参考了下原文,觉得翻译成`终止操作`会更好理解一点

**Comment by Snailclimb** [comment]
嗯嗯 谢谢的建议！
