### ISSUE TITLE
乐观锁和悲观锁详解，这里是不是少个字

### ISSUE THREAD

**Issue by TeRiRi-H** [Snailclimb/JavaGuide#2251]
并发编程-重要知识点-乐观锁和悲观锁详解
![2024-01-31_173504](https://github.com/Snailclimb/JavaGuide/assets/60426035/9be8bd29-698d-4bd3-804e-a70c999facc1)

**Comment by Snailclimb** [comment]
> 并发编程-重要知识点-乐观锁和悲观锁详解 ![2024-01-31_173504](https://private-user-images.githubusercontent.com/60426035/301111494-9be8bd29-698d-4bd3-804e-a70c999facc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODA4ODUsIm5iZiI6MTcwNjc4MDU4NSwicGF0aCI6Ii82MDQyNjAzNS8zMDExMTE0OTQtOWJlOGJkMjktNjk4ZC00YmQzLTgwNGUtYTcwYzk5OWZhY2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA5NDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhODZmYzNhZTI4MzZjODYyYjc4ZTdkZjY1ZmU2MmE3MDhhZDcwM2I1ZWQ3NGMwODVhMDdjYmJkODNkMDNjYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0E9EL4l0YhrkhXuPooHW5i02cb-P7fuh95MJ8qIlKbQ)

对的，看到pr了，感谢。
