### ISSUE TITLE
常见面试算法题md部分删除排序数组中的重复数字代码错误 

### ISSUE THREAD

**Issue by putixueyanran** [Snailclimb/JavaGuide#2255]
原
public int removeDuplicates(int[] A) {
    if (A == null || A.length == 0) {
        return 0;
    }
    
    int size = 0;
    for (int i = 0; i < A.length; i++) {
        if (A[i] != A[size]) {
            A[++size] = A[i];
        }
    }
    return size + 1;
}

i的起始值建议修改为1

**Comment by Snailclimb** [comment]
> removeDuplicates

不好意思，能把位置更具体一下嘛？我没有找到对应的内容。。。
