### ISSUE TITLE
建议把‘深入理解虚拟机之虚拟机字节码执行引擎’这篇文章改回之前的‘虚拟机类加载机制’

### ISSUE THREAD

**Issue by wanmudong** [Snailclimb/JavaGuide#226]
你好，首先很感谢这篇文章。之前在看这篇Java虚拟机（jvm）.md时，最下面一篇文章是‘虚拟机类加载机制’，包括现在的概要还是之前的，最近刷了一些面经，感觉类加载相关内容确实相对重要，希望可以把对应的链接换回来或者将对应的概要改一下。

**Comment by Snailclimb** [comment]
那个目录是按照《深入理解Java虚拟机》来排的，关于如何创建一个对象可以查看这篇文章<https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Java基础知识.md#28-为什么java中只有值传递>,或者<https://www.cnblogs.com/fanjie/p/6916784.html>

**Comment by Snailclimb** [comment]
《深入理解Java虚拟机》读书笔记这部分内容我后续会进行重构。
