### ISSUE TITLE
[JVM垃圾回收详解]页面下方的参考链接失效了

### ISSUE THREAD

**Issue by MrXionGe** [Snailclimb/JavaGuide#2267]
### 地址
https://javaguide.cn/java/jvm/jvm-garbage-collection.html#%E5%8F%82%E8%80%83
### 截图
![image](https://github.com/Snailclimb/JavaGuide/assets/23261935/d722c8e7-61a7-458f-a4ce-1d9b6e06c998)
这个链接已经失效了，是否考虑删除掉这个地址？

**Comment by Snailclimb** [comment]
> ### 地址
> https://javaguide.cn/java/jvm/jvm-garbage-collection.html#%E5%8F%82%E8%80%83
> 
> ### 截图
> ![image](https://private-user-images.githubusercontent.com/23261935/305692523-d722c8e7-61a7-458f-a4ce-1d9b6e06c998.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDUxODgsIm5iZiI6MTcwODI0NDg4OCwicGF0aCI6Ii8yMzI2MTkzNS8zMDU2OTI1MjMtZDcyMmM4ZTctNjFhNy00NThmLWE0Y2UtMWQ5YjZlMDZjOTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA4MjgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2OWYxNDNiZjU5YTZjN2IwNDUzZWM0NGNmNDdjMTAzNTFjNTZhNWE5MGYxMWMwOTdkOTZkNzI3ODk2MjIzOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jHHvHvbLLhfAWJRFXDCfJ-F6shE4swdcM17MotCNjsw) 这个链接已经失效了，是否考虑删除掉这个地址？

可以的，我去修复下，感谢指出！
