### ISSUE TITLE
建议重新组织目录结构

### ISSUE THREAD

**Issue by yuechuanx** [Snailclimb/JavaGuide#228]
个人觉得这样组织好一点。

- Java
    - 特性
    - 容器
    - 并发
    - JVM
    - I/O
    - 代码规范（希望添加）
- 算法
    - 题解
- 操作系统
- 网络
    - 消息队列
- 数据库
- 系统设计
    - 设计模式
    - 框架
- 工具
    - git
    - docker（希望添加）
- 面试指南
    - 简历制作
    - 面试题总结
    - 面经
- 资料
    - 书单
    - 练手项目（大家可以推荐自己的repo到列表）

**Comment by Snailclimb** [comment]
嗯嗯 老哥 已经完成了第一次修改 相应的文件目录马上也会进行修改，我已经将你加进 Contributor 中。

**Comment by Snailclimb** [comment]
推荐使用 <http://snailclimb.top/JavaGuide/> 在线阅读(访问速度慢的话，请使用<https://snailclimb.gitee.io/javaguide>)，在线阅读内容本仓库同步一致。这种方式阅读的优势在于：有侧边栏阅读体验更好，Gitee pages 的访问速度相对来说也比较快。
