### ISSUE TITLE
[Enhancement] JIT的实现原理

### ISSUE THREAD

**Issue by scwlkq** [Snailclimb/JavaGuide#2283]
面试被问到了 
https://cloud.tencent.com/developer/article/2367465

愿意提供pr 如果assign的话～

**Comment by Snailclimb** [comment]
> 面试被问到了 https://cloud.tencent.com/developer/article/2367465
> 
> 愿意提供pr 如果assign的话～

欢迎提交PR呀！可以直接添加的那篇文章中作为补充，如果内容较多的话，也可以单独起一篇文章，感谢完善！
