### ISSUE TITLE
https://javaguide.cn浏览器浏览这个页面会卡顿，不知道其他人有没有此类问题

### ISSUE THREAD

**Issue by thebesthong** [Snailclimb/JavaGuide#2284]

**Comment by Snailclimb** [comment]
访问的人太多的原因？还是这个页面也什么东西没加载出来？

**Comment by thebesthong** [comment]
页面加载没问题，就是鼠标移动浏览器跟不上，页面下滑会有点卡

**Comment by Snailclimb** [comment]
> 页面加载没问题，就是鼠标移动浏览器跟不上，页面下滑会有点卡

其他页面没问题吗？只有这个一个页面是吧？具体原因我目前也不太了解。

**Comment by thebesthong** [comment]
![Uploading image.png…]()

**Comment by thebesthong** [comment]
<img width="1496" alt="image" src="https://github.com/Snailclimb/JavaGuide/assets/47499994/19127227-663e-49a8-8e62-1270f11f7650">
整个面试指南都有这个问题，录屏录不出来效果

**Comment by thebesthong** [comment]
之前几个月浏览的时候没有这种卡的情况

**Comment by Snailclimb** [comment]
> 之前几个月浏览的时候没有这种卡的情况

哦哦 这个问题我目前也没有好的解决办法，可能是我重新部署了新版本的原因或者你的浏览器的问题。
