### ISSUE TITLE
JavaGuide/Java/Multithread/并发容器总结.md 里面几个网页404

### ISSUE THREAD

**Issue by 247292980** [Snailclimb/JavaGuide#230]
建议更新一下

**Comment by Snailclimb** [comment]
已经更新 感谢！

**Comment by bold881** [comment]
还是并发容器总结.md里面 《这几道Java集合框架面试题在面试中几乎必问》404了

**Comment by caohangwei1314** [comment]
《ConcurrentHashMap 和 Hashtable 的区别》和《ConcurrentHashMap线程安全的具体实现方式/底层具体实现》这两个链接也报404了
