### ISSUE TITLE
jhat从JDK9的时候已经删除了

### ISSUE THREAD

**Issue by Delerrr** [Snailclimb/JavaGuide#2301]
建议在[原文](https://javaguide.cn/java/jvm/jdk-monitoring-and-troubleshooting-tools.html#jhat-%E5%88%86%E6%9E%90-heapdump-%E6%96%87%E4%BB%B6)（最重要的JVM参数总结）加上补充：

jhat从JDK9的时候已经删除了（JEP 241: Remove the jhat Tool）。现在Oracle官方推荐的分析工具是Eclipse Memory Analyzer Tool (MAT) 和 VisualVM。

在实际工作中，除非真的没有别的工具可用，否则一般不会去直接使用jhat命令来分析demp文件，主要原因有二：

*  一般不会在部署应用程序的服务器上直接分析dump文件，即使可以这样做，也会尽量将dump文件拷贝到其他机器上进行分析，因为分析工作是一个耗时且消耗硬件资源的过程，既然都要在其他机器上进行，就没必要受到命令行工具的限制了；
*  jhat的分析功能相对来说很简陋，VisualVM以及专门分析dump文件的Eclipse Memory Analyzer、IBM HeapAnalyzer等工具，都能实现比jhat更强大更专业的分析功能。

参考：

[博客园](https://www.cnblogs.com/caoweixiong/p/14788673.html)

[JEP241](https://openjdk.org/jeps/241)

**Comment by Snailclimb** [comment]
> 建议在[原文](https://javaguide.cn/java/jvm/jdk-monitoring-and-troubleshooting-tools.html#jhat-%E5%88%86%E6%9E%90-heapdump-%E6%96%87%E4%BB%B6)（最重要的JVM参数总结）加上补充：
> 
> jhat从JDK9的时候已经删除了（JEP 241: Remove the jhat Tool）。现在Oracle官方推荐的分析工具是Eclipse Memory Analyzer Tool (MAT) 和 VisualVM。
> 
> 在实际工作中，除非真的没有别的工具可用，否则一般不会去直接使用jhat命令来分析demp文件，主要原因有二：
> 
> * 一般不会在部署应用程序的服务器上直接分析dump文件，即使可以这样做，也会尽量将dump文件拷贝到其他机器上进行分析，因为分析工作是一个耗时且消耗硬件资源的过程，既然都要在其他机器上进行，就没必要受到命令行工具的限制了；
> * jhat的分析功能相对来说很简陋，VisualVM以及专门分析dump文件的Eclipse Memory Analyzer、IBM HeapAnalyzer等工具，都能实现比jhat更强大更专业的分析功能。
> 
> 参考：
> 
> [博客园](https://www.cnblogs.com/caoweixiong/p/14788673.html)
> 
> [JEP241](https://openjdk.org/jeps/241)

感谢，很重要的补充，可以提交一个PR么？或者我下周抽空完善一下。

**Comment by Delerrr** [comment]
我也是初学者，不一定能全面正确地写出来。就不提PR了

**Comment by Snailclimb** [comment]
> 我也是初学者，不一定能全面正确地写出来。就不提PR了

好的，我已修改完善，顺带补充了一个常用的工具MAT。
