### ISSUE TITLE
MySQL update 语句是否用到缓存？

### ISSUE THREAD

**Issue by Delerrr** [Snailclimb/JavaGuide#2305]
在[SQL语句在MySQL中的执行过程](https://javaguide.cn/database/mysql/how-sql-executed-in-mysql.html)里，文中讲到update语句会用到缓存，和网上搜到的一些结果不符，如[小林coding](https://www.xiaolincoding.com/mysql/log/how_update.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E9%9C%80%E8%A6%81-undo-log)

![小林coding](https://github.com/Snailclimb/JavaGuide/assets/95750785/97d28b2c-4682-471a-9313-227a272a6d01)

原文：

![原文](https://github.com/Snailclimb/JavaGuide/assets/95750785/3c9e9501-fa62-4da9-b7f2-d5392ef3f51b)

**Comment by Snailclimb** [comment]
> SQL语句在MySQL中的执行过程

更新语句貌似是会导致与该表相关的查询缓存失效，这里需要修改一下，感谢指出！
