### ISSUE TITLE
连接失效 28. 为什么Java中只有值传递 为什么Java中只有值传递？

### ISSUE THREAD

**Issue by FtdConcept** [Snailclimb/JavaGuide#232]
为什么Java中只有值传递？ 引用的连接失效

**Comment by spikesp** [comment]
https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md#28-%E4%B8%BA%E4%BB%80%E4%B9%88java%E4%B8%AD%E5%8F%AA%E6%9C%89%E5%80%BC%E4%BC%A0%E9%80%92

补充失效的链接位置。

**Comment by Snailclimb** [comment]
已经修复。感谢!
