### ISSUE TITLE
raft选举和心跳超时的设置不符合原论文里的设定的疑问，是因为现在网速、磁盘足够快的原因吗？

### ISSUE THREAD

**Issue by cold-bin** [Snailclimb/JavaGuide#2324]
![image](https://github.com/Snailclimb/JavaGuide/assets/85239590/336ed222-bd6b-41c9-b532-e76dd7e15bf3)

**Comment by Snailclimb** [comment]
> ![image](https://private-user-images.githubusercontent.com/85239590/312872254-336ed222-bd6b-41c9-b532-e76dd7e15bf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDE5NTgsIm5iZiI6MTcxMTQ0MTY1OCwicGF0aCI6Ii84NTIzOTU5MC8zMTI4NzIyNTQtMzM2ZWQyMjItYmQ2Yi00MWM5LWI1MzItZTc2ZGQ3ZTE1YmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA4MjczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MmIzZTA2MmI4YWY2YzhhMWZmZDNiYTA2MjczMzQ1YjdjMmNlMWJkYjZjZDljZTZlMDEzMDVjNDEzY2Y0ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PfF_QF_NJpadRsBbYdUYGJ-_4oY4nIUZjiUPWMPDp2U)

这篇是pr的，这里的具体逻辑我确实没深究过。
