### ISSUE TITLE
serialVersionUID 不是被 static 变量修饰了吗？为什么还会被“序列化”？这个问题最后的总结有问题

### ISSUE THREAD

**Issue by pan-deng** [Snailclimb/JavaGuide#2326]
原文总结是：也就是说，serialVersionUID 只是用来被 JVM 识别，实际并没有被序列化。

总结有问题，实际上 serialVersionUID 是有被序列化的。
虽然 serialVersionUID 是静态的，但其特殊之处在于，Java序列化API特别处理了这一字段，使得它成为序列化/反序列化流程中用于校验版本一致性的一个关键元素。

原文：https://github.com/Snailclimb/JavaGuide/blob/main/docs/java/basis/serialization.md#jdk-%E8%87%AA%E5%B8%A6%E7%9A%84%E5%BA%8F%E5%88%97%E5%8C%96%E6%96%B9%E5%BC%8F

**Comment by Snailclimb** [comment]
> 原文总结是：也就是说，serialVersionUID 只是用来被 JVM 识别，实际并没有被序列化。
> 
> 总结有问题，实际上 serialVersionUID 是有被序列化的。 虽然 serialVersionUID 是静态的，但其特殊之处在于，Java序列化API特别处理了这一字段，使得它成为序列化/反序列化流程中用于校验版本一致性的一个关键元素。
> 
> 原文：https://github.com/Snailclimb/JavaGuide/blob/main/docs/java/basis/serialization.md#jdk-%E8%87%AA%E5%B8%A6%E7%9A%84%E5%BA%8F%E5%88%97%E5%8C%96%E6%96%B9%E5%BC%8F

https://github.com/Snailclimb/JavaGuide/issues/2174

**Comment by Losingways** [comment]
应该是说总结没修改吧（
![image](https://github.com/Snailclimb/JavaGuide/assets/135029570/e2030c5b-c14f-4ddc-b80f-09884ad3e2db)
