### ISSUE TITLE
日文版本

### ISSUE THREAD

**Issue by spikesp** [Snailclimb/JavaGuide#233]
作者您好：

我从ruby转Java三个月，这个项目真的是太棒了。
我看了下issue，有位外国朋友请求英文版，所以我想到如果有多语言版本，那真是非常棒。

虽然我对翻译英文不在行，但是我想我可以帮忙翻译成日文。

对我来说也可以加深理解，对其他日文母语开发者也会有很大的帮助。

不知作者意下如何？ 如果可以的话，有什么流程，规范需要遵守的麻烦告知，谢谢。
期待回复。

**Comment by Snailclimb** [comment]
如果您有时间的话 欢迎您这样做，当然您也可以找几个人一起来做这件事情，如果需要什么帮助可以来问我！

**Comment by spikesp** [comment]
> 如果您有时间的话 欢迎您这样做，当然您也可以找几个人一起来做这件事情，如果需要什么帮助可以来问我！

非常感谢回复。

翻译的过程也是学习的一部分，而且效果很好。
我会积极翻译的。

我也是刚刚参与开源项目，估计接下来会像您多多请教。

**Comment by Snailclimb** [comment]
嗯嗯 好的 没问题，互相学习！

**Comment by Snailclimb** [comment]
老哥这几天提出了很多不错的 issue 和 pr，我已经将老哥加入 Contributor 中。

**Comment by spikesp** [comment]
> 老哥这几天提出了很多不错的 issue 和 pr，我已经将老哥加入 Contributor 中。

感谢作者厚爱，接下来我会继续努力的。

**Comment by xiongbenzzz** [comment]
一gay窝里giaogiao
