### ISSUE TITLE
缓存穿透中的布隆过滤器链接失效了

### ISSUE THREAD

**Issue by honger1234** [Snailclimb/JavaGuide#2333]
如下图，点击查看布隆过滤器的文章，显示页面不存在
![image](https://github.com/Snailclimb/JavaGuide/assets/47131622/e6b440f9-d064-4174-8834-eec92e999cdb)
![image](https://github.com/Snailclimb/JavaGuide/assets/47131622/525ce966-9f47-4282-b480-274a61a5a0ab)

**Comment by Snailclimb** [comment]
> 如下图，点击查看布隆过滤器的文章，显示页面不存在 ![image](https://private-user-images.githubusercontent.com/47131622/313976198-e6b440f9-d064-4174-8834-eec92e999cdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzQxMzAsIm5iZiI6MTcxMDkzMzgzMCwicGF0aCI6Ii80NzEzMTYyMi8zMTM5NzYxOTgtZTZiNDQwZjktZDA2NC00MTc0LTg4MzQtZWVjOTJlOTk5Y2RiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDExMjM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYzA5Y2UxNjAxZjM2OTU5ODRlYzk3Y2I4Mjg2ODk0NTM3MzJjMTc4ZmVmMjgzNTNiMTQ2MmI2M2ZkM2EzODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jxYZOjWe6H2pb5OgyOofOlX2cVHJ6IE_HyQn40AQXj8) ![image](https://private-user-images.githubusercontent.com/47131622/313976299-525ce966-9f47-4282-b480-274a61a5a0ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzQxMzAsIm5iZiI6MTcxMDkzMzgzMCwicGF0aCI6Ii80NzEzMTYyMi8zMTM5NzYyOTktNTI1Y2U5NjYtOWY0Ny00MjgyLWI0ODAtMjc0YTYxYTVhMGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDExMjM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwOTNjNTIzM2E2MjYzN2Q0NzNiOGVhYzJhYjc1YjdjZGM3YWQ5YzViOWNlNzczMmM2MzY3Y2NlZTJiYmE4YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2MUCjiFwHripEGuq74yiNdOzORz3wWvpCWmEoDkOTpI)

嗯嗯 这个之前已经修复了，只是网站还没同步哈。
