### ISSUE TITLE
在外部调用静态方法时，可以使用 类名.方法名 的方式，也可以使用 对象.方法名 的方式"，这里是不是有问题呀

### ISSUE THREAD

**Issue by lazytortoise911** [Snailclimb/JavaGuide#2337]
静态方法是属于类的，不是只能用类调用吗

**Comment by honger1234** [comment]
自己试一试不就知道了，如果不能再发出来

**Comment by honger1234** [comment]
试了一下，是可以的。
![image](https://github.com/Snailclimb/JavaGuide/assets/47131622/5614788b-38a8-42d4-a4d3-9db3fb1f7c25)

**Comment by lazytortoise911** [comment]
谢谢，确实可以这样写。原来只是IDEA不提示对象存在这个方法，并不是没法这样调用，之前理解错了。
