### ISSUE TITLE
[typo]标点符号位置偏移

### ISSUE THREAD

**Issue by spikesp** [Snailclimb/JavaGuide#234]
Java基础中

https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md#18-%E6%88%90%E5%91%98%E5%8F%98%E9%87%8F%E4%B8%8E%E5%B1%80%E9%83%A8%E5%8F%98%E9%87%8F%E7%9A%84%E5%8C%BA%E5%88%AB%E6%9C%89%E9%82%A3%E4%BA%9B

18. 成员变量与局部变量的区别有那些
从语法形式上，看成员变量是属于类的，而局部变量是在方法中定义的变量或是方法的参数；成员变量可以被 public,private,static 等修饰符所修饰，而局部变量不能被访问控制修饰符及 static 所修饰；但是，成员变量和局部变量都能被 final 所修饰；

[从语法形式上，看成员变量是属于类的]

此句是否因为

[从语法形式上看，成员变量是属于类的]

读起来更为通顺。

如有错误，请关闭。

**Comment by Snailclimb** [comment]
我这里显示是没有问题的，你可以再看一下！

**Comment by spikesp** [comment]
![Screen Shot 2019-03-26 at 9 19 39 PM](https://user-images.githubusercontent.com/12581996/54996532-e9920000-500c-11e9-8947-fe936c50b387.png)
我这里截图是显示如此，麻烦您再确认一下。

[从语法形式上，看成员变量是属于类的]

**Comment by yanglbme** [comment]
@spikesp 打字难免偶尔出现点小错误，你可以直接提个 PR，对一些小错误都统一纠正一下，作者直接进行 review 并 merge。
