### ISSUE TITLE
「Java内存区域详解（重点）」 文档的「方法区」部分描述好像有误

### ISSUE THREAD

**Issue by jiang-code88** [Snailclimb/JavaGuide#2346]
在 [方法区](https://javaguide.cn/java/jvm/memory-area.html#%E6%96%B9%E6%B3%95%E5%8C%BA) 文档中

<img width="1355" alt="Snipaste_2024-03-30_18-02-43" src="https://github.com/Snailclimb/JavaGuide/assets/65991061/97af86a2-eece-4cdf-81c9-37d6b3873d1c">

文档说 “1、整个永久代有一个 JVM 本身设置的固定大小上限，无法进行调整”，但是下面有介绍通过 -XX:PermSize 和  -XX:MaxPermSize 参数调整永久代的大小，那这里的 “无法进行调整” 是不是表达有误？

**Comment by Snailclimb** [comment]
> 文档说 “1、整个永久代有一个 JVM 本身设置的固定大小上限，无法进行调整”，但是下面有介绍通过 -XX:PermSize 和 -XX:MaxPermSize 参数调整永久代的大小，那这里的 “无法进行调整” 是不是表达有误？

确实会引起歧义，备注一下会更好：受到 JVM 内存的限制。
