### ISSUE TITLE
关于聚簇索引和非聚簇索引的定义

### ISSUE THREAD

**Issue by li-rongzhi** [Snailclimb/JavaGuide#2350]
在[mysql索引详解](https://github.com/Snailclimb/JavaGuide/blob/main/docs/database/mysql/mysql-index.md)一文中提及聚簇索引和非聚簇索引的定义：
- 聚簇索引（Clustered Index）即索引结构和数据一起存放的索引，并不是一种单独的索引类型。InnoDB 中的主键索引就属于聚簇索引。
- 非聚簇索引(Non-Clustered Index)即索引结构和数据分开存放的索引，并不是一种单独的索引类型。二级索引(辅助索引)就属于非聚簇索引。MySQL 的 MyISAM 引擎，不管主键还是非主键，使用的都是非聚簇索引。

若只针对mysql而言是合理的，但此处应该是不考虑具体数据库，更宽泛的关于聚簇索引和非聚簇索引的定义。聚簇索引应为索引中数据项(data entry)的顺序与实际磁盘中数据(data record)存放的顺序相同（或相近）的索引，非聚簇索引反之。也就是说索引中数据页并不一定要存放完整的数据（data record），可以是真实数据地址。恰好mysql会创建一个包含完整数据的主键索引，所以唯一的聚簇索引就是和数据一起存放的索引。但实质上聚簇索引的定义与所谓索引结构和数据是否一起存放无关。我翻看了两本比较权威的数据库教材：

> If the file containing the records is sequentially ordered, a clustering index is an index whose search key also defines the sequential order of the file. Clustering indices are also called primary indices; the term primary index may appear to denote an index on a primary key, but such indices can in fact be built on any search key. The search key of a clustering index is often the primary key, although that is not necessarily so. Indices whose search key specifies an order different from the sequential order of the file are called nonclustering indices, or secondary indices. The terms “clustered” and “nonclustered” are often used in place of “clustering” and “nonclustering.” - Database System Concepts (SILBERSCHATZ)

> When a file is organized so that the ordering of data records is the same as or close to the ordering of data entries in some index, we say that the index is clustered; otherwise, it clustered is an unclustered index. - Database Management Systems (Ramakrishnan)

**Comment by Snailclimb** [comment]
> 在[mysql索引详解](https://github.com/Snailclimb/JavaGuide/blob/main/docs/database/mysql/mysql-index.md)一文中提及聚簇索引和非聚簇索引的定义：
> 
> * 聚簇索引（Clustered Index）即索引结构和数据一起存放的索引，并不是一种单独的索引类型。InnoDB 中的主键索引就属于聚簇索引。
> * 非聚簇索引(Non-Clustered Index)即索引结构和数据分开存放的索引，并不是一种单独的索引类型。二级索引(辅助索引)就属于非聚簇索引。MySQL 的 MyISAM 引擎，不管主键还是非主键，使用的都是非聚簇索引。
> 
> 若只针对mysql而言是合理的，但此处应该是不考虑具体数据库，更宽泛的关于聚簇索引和非聚簇索引的定义。聚簇索引应为索引中数据项(data entry)的顺序与实际磁盘中数据(data record)存放的顺序相同（或相近）的索引，非聚簇索引反之。也就是说索引中数据页并不一定要存放完整的数据（data record），可以是真实数据地址。恰好mysql会创建一个包含完整数据的主键索引，所以唯一的聚簇索引就是和数据一起存放的索引。但实质上聚簇索引的定义与所谓索引结构和数据是否一起存放无关。我翻看了两本比较权威的数据库教材：
> 
> > If the file containing the records is sequentially ordered, a clustering index is an index whose search key also defines the sequential order of the file. Clustering indices are also called primary indices; the term primary index may appear to denote an index on a primary key, but such indices can in fact be built on any search key. The search key of a clustering index is often the primary key, although that is not necessarily so. Indices whose search key specifies an order different from the sequential order of the file are called nonclustering indices, or secondary indices. The terms “clustered” and “nonclustered” are often used in place of “clustering” and “nonclustering.” - Database System Concepts (SILBERSCHATZ)
> 
> > When a file is organized so that the ordering of data records is the same as or close to the ordering of data entries in some index, we say that the index is clustered; otherwise, it clustered is an unclustered index. - Database Management Systems (Ramakrishnan)

嗯嗯，这里确实主要针对的是 MySQL 数据库。你可以提交一个PR补充完善一下。
