### ISSUE TITLE
Java集合概览部分多写了一个map

### ISSUE THREAD

**Issue by JasonTodd83** [Snailclimb/JavaGuide#2353]
原文：对于Collection 接口，下面又有三个主要的子接口：List、Set 、 Queue、Map。
这里map需要删除
![Snipaste_2024-04-03_15-03-27](https://github.com/Snailclimb/JavaGuide/assets/83108245/322bdcef-098e-4566-adfb-4fa5dc31944e)

**Comment by Snailclimb** [comment]
> 原文：对于Collection 接口，下面又有三个主要的子接口：List、Set 、 Queue、Map。 这里map需要删除 ![Snipaste_2024-04-03_15-03-27](https://private-user-images.githubusercontent.com/83108245/319074512-322bdcef-098e-4566-adfb-4fa5dc31944e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzMxODEsIm5iZiI6MTcxMjEzMjg4MSwicGF0aCI6Ii84MzEwODI0NS8zMTkwNzQ1MTItMzIyYmRjZWYtMDk4ZS00NTY2LWFkZmItNGZhNWRjMzE5NDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA4MjgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MWI3MTJlMjIzZWE5ODVmMDU3MmRmMGJlNDRlYTY3YjE0ZmM1OGRkMDQ4NTQ2NzFmYjUzM2Y3MDU4YzE3ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MESrCJRzkMAWGMgCFyAwO0lM9GtgPD3dXOUwOxYXfmc)

这个还是我后面加上的，笔误了。
