### ISSUE TITLE
Firefox移动端页面返回到顶部按钮不会跟随页面阅读多少变化

### ISSUE THREAD

**Issue by pheotry** [Snailclimb/JavaGuide#2355]
![Screenshot_2024-04-04-15-24-42-801_org mozilla firefox-edit](https://github.com/Snailclimb/JavaGuide/assets/43376740/d96ca6bc-1dd4-4a76-a9be-49313c736381)

正常情况

![image](https://github.com/Snailclimb/JavaGuide/assets/43376740/28fffd80-4d0a-42f6-99d7-30db815699cb)

**Comment by Snailclimb** [comment]
> ![Screenshot_2024-04-04-15-24-42-801_org mozilla firefox-edit](https://private-user-images.githubusercontent.com/43376740/319483848-d96ca6bc-1dd4-4a76-a9be-49313c736381.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMjI5ODYsIm5iZiI6MTcxMjIyMjY4NiwicGF0aCI6Ii80MzM3Njc0MC8zMTk0ODM4NDgtZDk2Y2E2YmMtMWRkNC00YTc2LWE5YmUtNDkzMTNjNzM2MzgxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA5MjQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMTE1NjFjYTgxZGU4MTU3N2Q5NDg4ZDBhOWY4ZTMzN2E3YzI2ODA1MDg0NjA5MzljMzNmNmNkZGQyNWU4ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F5wxQuiEnakbSiwi9I51bM9ZC87aQ2ToBXtXX7rXrFQ)
> 
> 正常情况
> 
> ![image](https://private-user-images.githubusercontent.com/43376740/319483951-28fffd80-4d0a-42f6-99d7-30db815699cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMjI5ODYsIm5iZiI6MTcxMjIyMjY4NiwicGF0aCI6Ii80MzM3Njc0MC8zMTk0ODM5NTEtMjhmZmZkODAtNGQwYS00MmY2LTk5ZDctMzBkYjgxNTY5OWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA5MjQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2Mjg1NjljMTdjYmViMmY2ZWIwMjliYTcwMGU3ZDY3MjE2ZDFhMDMyZTk2YzUwMDM2YTE5MGIxMjMyODRhNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PD00LedV7Tt2mvRA56FOUke8Nwk0AHsdocALVKoXYbY)

好吧，还有这问题，这用的是开源主题，我目前可能没办法修复了。
