### ISSUE TITLE
死信队列这里的介绍语句

### ISSUE THREAD

**Issue by JasonTodd83** [Snailclimb/JavaGuide#2356]
当消息在一个队列中变成死信 (dead message) 之后，它能被重新被发送到另一个交换器中，这个交换器就是 DLX，绑定 DLX 的队列就称之为死信队列。
这里“它能被重新被发送到另一个交换器中”多了一个被字，读起来不通

**Comment by Snailclimb** [comment]
> 当消息在一个队列中变成死信

好的 ，感谢指出，笔误了！

**Comment by JasonTodd83** [comment]
加油！
