### ISSUE TITLE
Mongodb使用b+树，为什么放一篇b树的论证链接？

### ISSUE THREAD

**Issue by fushengshi** [Snailclimb/JavaGuide#2359]
![image](https://github.com/Snailclimb/JavaGuide/assets/50937788/17af0c97-4de6-48b4-8170-b548c38baedc)

**Comment by Snailclimb** [comment]
> ![image](https://private-user-images.githubusercontent.com/50937788/320843414-17af0c97-4de6-48b4-8170-b548c38baedc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzAzNzksIm5iZiI6MTcxMjY3MDA3OSwicGF0aCI6Ii81MDkzNzc4OC8zMjA4NDM0MTQtMTdhZjBjOTctNGRlNi00OGI0LTgxNzAtYjU0OGMzOGJhZWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDEzNDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZWQ2ODFjMWUzZWUxMjI4MjhlZjQzZjIzOTUwOWZiNjVhY2YzNjUwMmVmOWUwZGUxYThmMzMyYjRmM2M4NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fiyUTF8fu5bb8Gwshc68FOhdGUotYsLMBHRhWnEV92g)

放错了，我修正一下，感谢指出！
