### ISSUE TITLE
算法学习与面试里的牛课网分类解析链接失效了

### ISSUE THREAD

**Issue by MasterKun94** [Snailclimb/JavaGuide#236]

**Comment by MasterKun94** [comment]
看了一下是有资源的，只是链接失效了
https://github.com/Snailclimb/JavaGuide/blob/master/docs/dataStructures-algorithms/算法题解析/剑指offer/

**Comment by Snailclimb** [comment]
已经更新并重新排版分类！感谢提醒，非常感谢你！
