### ISSUE TITLE
Java NIO 核心知识总结文章-个别图片背景是透明的，导致深色模式看不清字

### ISSUE THREAD

**Issue by pheotry** [Snailclimb/JavaGuide#2360]
链接https://javaguide.cn/java/io/nio-basis.html#buffer-%E7%BC%93%E5%86%B2%E5%8C%BA

Buffer 缓冲区部分，这张图片
![image](https://github.com/Snailclimb/JavaGuide/assets/43376740/cb8fa761-fe67-4d25-9d70-bd4c6d7c2ce9)

**Comment by Snailclimb** [comment]
> 链接https://javaguide.cn/java/io/nio-basis.html#buffer-%E7%BC%93%E5%86%B2%E5%8C%BA
> 
> Buffer 缓冲区部分，这张图片 ![image](https://private-user-images.githubusercontent.com/43376740/320888611-cb8fa761-fe67-4d25-9d70-bd4c6d7c2ce9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzQzMTIsIm5iZiI6MTcxMjY3NDAxMiwicGF0aCI6Ii80MzM3Njc0MC8zMjA4ODg2MTEtY2I4ZmE3NjEtZmU2Ny00ZDI1LTlkNzAtYmQ0YzZkN2MyY2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE0NDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YzIzZjYzNDVmOTYyYmExMmYzMDA4Y2FiNmIyNzBkZjczYzNmNWUyNmFkOThiMDE0NjBlZDBkZmY2Y2UyYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UUTaHi9WwVPWBwgKVS9AzmIWotTdhj8XUPkH3JeV6x8)

嗯嗯 这个我之前也发现了，透明背景的原因，暂时不准备修改。
