### ISSUE TITLE
构造方法用synchronized关键词修饰解释有误

### ISSUE THREAD

**Issue by N-N-N-N-N-N-N-N-N** [Snailclimb/JavaGuide#2362]
位置: [java并发面试总结(中) -  构造方法可以用 synchronized 修饰么？](https://javaguide.cn/java/concurrent/java-concurrent-questions-02.html#%E6%9E%84%E9%80%A0%E6%96%B9%E6%B3%95%E5%8F%AF%E4%BB%A5%E7%94%A8-synchronized-%E4%BF%AE%E9%A5%B0%E4%B9%88)

提到
"构造方法本身就属于线程安全的，不存在同步的构造方法一说"

实际上 构造方法本身不是线程安全的. 
可以通过以下代码验证

public class ConstructorsSynchronizedTest {

    private static int counter = 0;

    public static void main(String[] args) throws InterruptedException {
        List<ConstructorsDO> list = new CopyOnWriteArrayList<>();
        for (int i = 0; i < 100; i++) {
            new Thread(() -> {
                for (int j = 0; j < 50; j++) {
                    list.add(new ConstructorsDO());
                }
            }).start();
        }
        Thread.sleep(3 * 1000);
        Map<Integer, Long> map = list.stream().collect(Collectors.groupingBy(ConstructorsDO::getNumber, Collectors.counting()));
        for (Map.Entry<Integer, Long> entry : map.entrySet()) {
            if (entry.getValue() > 1) {
                System.out.println("重复数字: " + entry.getKey() + " 重复次数: " + entry.getValue());
            }
        }
    }

    @Data
    public static class ConstructorsDO {
        private Integer number;
        public ConstructorsDO() {
            this.number = ConstructorsSynchronizedTest.counter++;
        }
    }
}`

**Comment by Snailclimb** [comment]
> 位置: [java并发面试总结(中) - 构造方法可以用 synchronized 修饰么？](https://javaguide.cn/java/concurrent/java-concurrent-questions-02.html#%E6%9E%84%E9%80%A0%E6%96%B9%E6%B3%95%E5%8F%AF%E4%BB%A5%E7%94%A8-synchronized-%E4%BF%AE%E9%A5%B0%E4%B9%88)
> 
> 提到 "构造方法本身就属于线程安全的，不存在同步的构造方法一说"
> 
> 实际上 构造方法本身不是线程安全的. 可以通过以下代码验证
> 
> public class ConstructorsSynchronizedTest {
> 
> ```
> private static int counter = 0;
> 
> public static void main(String[] args) throws InterruptedException {
>     List<ConstructorsDO> list = new CopyOnWriteArrayList<>();
>     for (int i = 0; i < 100; i++) {
>         new Thread(() -> {
>             for (int j = 0; j < 50; j++) {
>                 list.add(new ConstructorsDO());
>             }
>         }).start();
>     }
>     Thread.sleep(3 * 1000);
>     Map<Integer, Long> map = list.stream().collect(Collectors.groupingBy(ConstructorsDO::getNumber, Collectors.counting()));
>     for (Map.Entry<Integer, Long> entry : map.entrySet()) {
>         if (entry.getValue() > 1) {
>             System.out.println("重复数字: " + entry.getKey() + " 重复次数: " + entry.getValue());
>         }
>     }
> }
> 
> 
> @Data
> public static class ConstructorsDO {
>     private Integer number;
>     public ConstructorsDO() {
>         this.number = ConstructorsSynchronizedTest.counter++;
>     }
> }
> ```
> 
> }`

感谢指出，这里确实有问题。
