### ISSUE TITLE
关于线程等待和阻塞两种状态

### ISSUE THREAD

**Issue by popoiopp** [Snailclimb/JavaGuide#2366]
[位置](https://javaguide.cn/java/concurrent/java-concurrent-questions-01.html#说说线程的生命周期和状态)
这里有一点不太理解，同样是等待锁释放，使用synchronized关键字线程处于BLOCKED状态，而使用 ReentrantLock 线程是出于WAITING状态

**Comment by Snailclimb** [comment]
> 同样是等待锁释放，使用synchronized关键字线程处于BLOCKED状态，而使用 ReentrantLock 线程是出于WAITING状态

这两种锁机制在处理线程等待时有所区别。
