### ISSUE TITLE
[discussion]Cookie和Session的的区别

### ISSUE THREAD

**Issue by spikesp** [Snailclimb/JavaGuide#237]
[Cookie和Session的的区别](http://snailclimb.top/JavaGuide/#/./java/J2EE%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86?id=cookie%e5%92%8csession%e7%9a%84%e7%9a%84%e5%8c%ba%e5%88%ab)

Cookie其实还可以用在一些方便用户的场景下，设想你某次登陆过一个网站，下次登录的时候不想再次输入账号了，怎么办？这个信息可以写到Cookie里面，访问网站的时候，网站页面的脚本可以读取这个信息，就自动帮你把用户名给填了，能够方便一下用户。这也是Cookie名称的由来，给用户的一点甜头。所以，总结一下：**Session是在服务端保存的一个数据结构**，用来跟踪用户的状态，这个数据可以保存在集群、数据库、文件中；Cookie是客户端保存用户信息的一种机制，用来记录用户的一些信息，也是实现Session的一种方式。

【Session是在服务端保存的一个数据结构】这句话我个人感觉描述地不是很精确。

根据中文wiki定义，
会话（session）是一种持久网络协议，在用户（或用户代理）端和服务器端之间创建关联，从而起到交换数据包的作用机制。

仅供参考，欢迎讨论。

**Comment by Tremblerx** [comment]
Cookie分为“**硬盘Cookie**”和“**浏览器Cookie**”。Session是通过“浏览器Cookie”实现的，浏览器进程关闭，Cookie消失，Session也就不存在了，这也是为什么关闭浏览器Session失效的原因。而“硬盘Cookie”存储在硬盘中供相应网站在一定时间内调用实现免密码登录，如非手动删除或到期不会失效。如有错误，欢迎大佬们指正。

**Comment by jerryoung** [comment]
Cookie 和 Session，都是为了解决无状态的请求的问题。
Cookie：在客户端活跃
Session：在服务端活跃
Cookie和Session解了客户端和服务端的耦。
