### ISSUE TITLE
[typo]Oracle JDK 和 OpenJDK 的对比

### ISSUE THREAD

**Issue by spikesp** [Snailclimb/JavaGuide#238]
[Oracle JDK 和 OpenJDK 的对比](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md#4-oracle-jdk-%E5%92%8C-openjdk-%E7%9A%84%E5%AF%B9%E6%AF%94)

**可能在看这个问题之前很多人和我一样并没有接触和使用过 OpenJDK 。那么Oracle和OpenJDK之间是否存在重大差异？下面通过我通过我收集到一些资料对你解答这个被很多人忽视的问题。**

【下面通过我通过我收集到一些资料对你解答这个被很多人忽视的问题。】
此句，是否应该改为
【下面我通过收集到的一些资料，为你解答这个被很多人忽视的问题。】
较为通顺？

补充：最近在翻译日文版本，所以可能会提出typo相关的issue较为频繁，请见谅！

**Comment by Snailclimb** [comment]
没事 。感谢你，已经按照你说的更新了！
