### ISSUE TITLE
网站已经很久没有从此仓库更新

### ISSUE THREAD

**Issue by floatingrain** [Snailclimb/JavaGuide#2382]
如题，在阅读网站版本的时候发现一些错误，比如

> 下面又有三个主要的子接口：List、Set 、 Queue、Map。

显然其中"Map"是一个错误描述，然而根据提交历史，该错误早已于4月4日从该仓库中更改，为什么到现在都还没有更新到网站上？请问网站从此仓库构建的时间周期是多久？

**Comment by Snailclimb** [comment]
> 如题，在阅读网站版本的时候发现一些错误，比如
> 
> > 下面又有三个主要的子接口：List、Set 、 Queue、Map。
> 
> 显然其中"Map"是一个错误描述，然而根据提交历史，该错误早已于4月4日从该仓库中更改，为什么到现在都还没有更新到网站上？请问网站从此仓库构建的时间周期是多久？

一周/半个月/一个月。

**Comment by Snailclimb** [comment]
> 如题，在阅读网站版本的时候发现一些错误，比如
> 
> > 下面又有三个主要的子接口：List、Set 、 Queue、Map。
> 
> 显然其中"Map"是一个错误描述，然而根据提交历史，该错误早已于4月4日从该仓库中更改，为什么到现在都还没有更新到网站上？请问网站从此仓库构建的时间周期是多久？

除非内容有重大更新，像这种容易分清的小笔误，对阅读没影响的。
