### ISSUE TITLE
HashMap 和 Hashtable 的区别补充

### ISSUE THREAD

**Issue by Mr-Write** [Snailclimb/JavaGuide#2395]
在 Java 集合（下）中，讲到了HashMap 和 Hashtable 的区别，可以再增加一点：
**哈希值使用**：HashTable 直接使用对象的 hashCode，而 HashMap 重新计算 hash 值（二次哈希）。

**Comment by Snailclimb** [comment]
> HashMap

`HashMap` 对哈希值进行了高位和低位的混合扰动处理以减少冲突，而 `Hashtable` 直接使用键的 `hashCode()` 值。
