### ISSUE TITLE
文章中一个无效的SQL举例

### ISSUE THREAD

**Issue by Mr-Write** [Snailclimb/JavaGuide#2399]
文章路径：[数据库/基础/SQL/SQL语法基础知识总结/分组](https://javaguide.cn/database/sql/sql-syntax-summary.html#%E5%88%86%E7%BB%84)

部分原文如下：

**`having`**：

- `having` 用于对汇总的 `group by` 结果进行过滤。
- `having` 一般都是和 `group by` 连用。
- `where` 和 `having` 可以在相同的查询中。

**使用 WHERE 和 HAVING 过滤数据**
```mysql
FROM Customers
WHERE cust_email IS NOT NULL
GROUP BY cust_name
HAVING COUNT(*) >= 1;
```
------

文章中应该是想举一个 having 过滤的示例，但上述 SQL，对 cust_name 进行分组，然后要求 having 组内数量大于 1 的元素。但是既然是分组，那么每组中的记录条数就应该一定存在即 >= 1。因此，上述 SQL 的例子应该并不恰当，是无效示例。

**Comment by Snailclimb** [comment]
> ```sql
> FROM Customers
> WHERE cust_email IS NOT NULL
> GROUP BY cust_name
> HAVING COUNT(*) >= 1;
> ```

感谢指出！这里`COUNT(*) >= 1` 确实总是为真。

```sql
SELECT cust_name, COUNT(*) AS NumberOfOrders
FROM Customers
WHERE cust_email IS NOT NULL
GROUP BY cust_name
HAVING COUNT(*) > 1;
```
