### ISSUE TITLE
[typo]import java和javax有什么区别

### ISSUE THREAD

**Issue by spikesp** [Snailclimb/JavaGuide#240]
[import java和javax有什么区别](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md#16-import-java%E5%92%8Cjavax%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB)

## case1

```
javax 当时只是扩展 API 包来说使用。
```

应该改为

```
javax 当时只是扩展 API 包来使用。
```

## case2

```
javax 逐渐的扩展成为 Java API 的组成部分。
```

应该改为

```
javax 逐渐地扩展成为 Java API 的组成部分。
```

## case3

```
但是，将扩展从 javax 包移动到 java 包将是太麻烦了
```

应该改为

```
但是，将扩展从 javax 包移动到 java 包确实太麻烦了
```

以上均为个人建议，还请作者review。

**Comment by Snailclimb** [comment]
嗯嗯  如果你觉得有更好的说法，可以issue或者直接PR都可以，如果某些知识点你有想添加的东西也可以提issue或者直接pr。因为我所整理和写的很多东西都需要继续完善才能更好。感谢老哥！
