### ISSUE TITLE
sql面试题中一个作者想表达意思的疑惑

### ISSUE THREAD

**Issue by Mr-Write** [Snailclimb/JavaGuide#2403]
文章路径：[数据库/基础/SQL/SQL常见面试题总结（1）/创建高级连接/列出供应商及其可供产品的数量](https://javaguide.cn/database/sql/sql-questions-01.html#%E5%88%97%E5%87%BA%E4%BE%9B%E5%BA%94%E5%95%86%E5%8F%8A%E5%85%B6%E5%8F%AF%E4%BE%9B%E4%BA%A7%E5%93%81%E7%9A%84%E6%95%B0%E9%87%8F)

部分原文如下：

【问题】列出供应商（`Vendors` 表中的 `vend_id`）及其可供产品的数量，包括没有产品的供应商。你需要使用 OUTER JOIN 和 COUNT()聚合函数来计算 `Products` 表中每种产品的数量，最后根据 vend_id 升序排序。

注意：`vend_id` 列会显示在多个表中，因此在每次引用它时都需要完全限定它。

```sql
SELECT vend_id, COUNT(prod_id) AS prod_id
FROM Vendors
LEFT JOIN Products
USING(vend_id)
GROUP BY vend_id
ORDER BY vend_id
```
---

文章中也写了注意要进行限定 `vend_id` 所在表，但是这个 sql 语句并没有做限定，是遗漏了还是故意写个错的？

**Comment by Mr-Write** [comment]
进行限定的 SQL：

```sql
SELECT v.vend_id, COUNT(prod_id) AS prod_id
FROM Vendors v
LEFT JOIN Products p
USING(vend_id)
GROUP BY v.vend_id
ORDER BY v.vend_id
```

**Comment by Snailclimb** [comment]
> 文章路径：[数据库/基础/SQL/SQL常见面试题总结（1）/创建高级连接/列出供应商及其可供产品的数量](https://javaguide.cn/database/sql/sql-questions-01.html#%E5%88%97%E5%87%BA%E4%BE%9B%E5%BA%94%E5%95%86%E5%8F%8A%E5%85%B6%E5%8F%AF%E4%BE%9B%E4%BA%A7%E5%93%81%E7%9A%84%E6%95%B0%E9%87%8F)
> 
> 部分原文如下：
> 
> 【问题】列出供应商（`Vendors` 表中的 `vend_id`）及其可供产品的数量，包括没有产品的供应商。你需要使用 OUTER JOIN 和 COUNT()聚合函数来计算 `Products` 表中每种产品的数量，最后根据 vend_id 升序排序。
> 
> 注意：`vend_id` 列会显示在多个表中，因此在每次引用它时都需要完全限定它。
> 
> ```sql
> SELECT vend_id, COUNT(prod_id) AS prod_id
> FROM Vendors
> LEFT JOIN Products
> USING(vend_id)
> GROUP BY vend_id
> ORDER BY vend_id
> ```
> 
> 文章中也写了注意要进行限定 `vend_id` 所在表，但是这个 sql 语句并没有做限定，是遗漏了还是故意写个错的？

没注意到，当时这段代码我在牛客的编辑运行区执行也是没问题的。
