### ISSUE TITLE
集合-常见面试题下-HashMap 的长度为什么是 2 的幂次方这里逻辑不好

### ISSUE THREAD

**Issue by kiwiboom** [Snailclimb/JavaGuide#2406]
建议改进
_这个数组下标的计算方法是“ (n - 1) & hash”。（n 代表数组长度）。这也就解释了 HashMap 的长度为什么是 2 的幂次方。这个算法应该如何设计呢？_
这句话多余，先介绍公式说就直接说能解释原因不合理。

**Comment by Snailclimb** [comment]
> 建议改进 _这个数组下标的计算方法是“ (n - 1) & hash”。（n 代表数组长度）。这也就解释了 HashMap 的长度为什么是 2 的幂次方。这个算法应该如何设计呢？_ 这句话多余，先介绍公式说就直接说能解释原因不合理。

我都不知道哪一次抽风改成这样描述了，感谢指出！
