### ISSUE TITLE
SHH typo

### ISSUE THREAD

**Issue by ryougi-shiky** [Snailclimb/JavaGuide#2420]
位置：
docs/cs-basics/network/application-layer-protocol.md

<img width="1215" alt="image" src="https://github.com/Snailclimb/JavaGuide/assets/53469345/3c46ed3e-d4b9-49e8-a31f-f921f2be1c25">

如上图中是不是应该写成SSH？

**Comment by Snailclimb** [comment]
> 位置： docs/cs-basics/network/application-layer-protocol.md
> 
> <img alt="image" width="1215" src="https://private-user-images.githubusercontent.com/53469345/345305104-3c46ed3e-d4b9-49e8-a31f-f921f2be1c25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTMzMjAsIm5iZiI6MTcyMDAxMzAyMCwicGF0aCI6Ii81MzQ2OTM0NS8zNDUzMDUxMDQtM2M0NmVkM2UtZDRiOS00OWU4LWEzMWYtZjkyMWYyYmUxYzI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEzMjM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZmIxZjU4MjllN2M0YmU1OWEwMDQ1OTJlNTI3NGM0ZTIzOTBjYjQ0NTliMWI2ZGE2YjYzOTI5OGM5ZDc0M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Pohx2GgrM7X9YMcWurcmqxxgkqQgDOPumou2Glyt7E">
> 如上图中是不是应该写成SSH？

是的。
