### ISSUE TITLE
计算机网络常见面试题总结（上）HTTP Header中常见的字段有误？

### ISSUE THREAD

**Issue by linlin20ai** [Snailclimb/JavaGuide#2423]
![image](https://github.com/Snailclimb/JavaGuide/assets/168981122/b4237fb5-805f-4450-881a-f74d23c1c74a)
If-Modified-Since 允许在对应的内容未被修改的情况下返回 304 未修改（ 304 Not Modified ）
If-None-Match允许在对应的内容未被修改的情况下返回 304 未修改（ 304 Not Modified ）
纯小白，只是看到重复然后上网查了一下，感觉有点不太对

**Comment by Snailclimb** [comment]
> ![image](https://private-user-images.githubusercontent.com/168981122/346415067-b4237fb5-805f-4450-881a-f74d23c1c74a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MTg1OTgsIm5iZiI6MTcyMDQxODI5OCwicGF0aCI6Ii8xNjg5ODExMjIvMzQ2NDE1MDY3LWI0MjM3ZmI1LTgwNWYtNDQ1MC04ODFhLWY3NGQyM2MxYzc0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwNTU4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODEwZTMzMjZiZDI3NWI0MTY2Njg1NTFjYWM4ZWRmOTZmN2NmMzA5MWJmMTFlZjUyMDVhNTUwZDJhYWFhYTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q6B-RoKy7ns-rvBJ2qKxExXTrZphWr-12vEg_qrFgVc) If-Modified-Since 允许在对应的内容未被修改的情况下返回 304 未修改（ 304 Not Modified ） If-None-Match允许在对应的内容未被修改的情况下返回 304 未修改（ 304 Not Modified ） 纯小白，只是看到重复然后上网查了一下，感觉有点不太对

感谢指出。
