### ISSUE TITLE
Java基础常见面试题总结（中）的字符串拼接这里是不是漏了一部分代码？？

### ISSUE THREAD

**Issue by guoyu666** [Snailclimb/JavaGuide#2424]
上面的代码对应的字节码如下：？？？？
![屏幕截图 2024-07-08 112807](https://github.com/Snailclimb/JavaGuide/assets/52870610/935bb4e8-c8a9-4490-b511-a003ea5ee9a3)

**Comment by Mr-Write** [comment]
补充一下。
```
       0: ldc           #2                  // String he
       2: astore_1
       3: ldc           #3                  // String llo
       5: astore_2
       6: ldc           #4                  // String world
       8: astore_3
       9: new           #5                  // class java/lang/StringBuilder
      12: dup
      13: invokespecial #6                  // Method java/lang/StringBuilder."<init>":()V
      16: aload_1
      17: invokevirtual #7                  // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
      20: aload_2
      21: invokevirtual #7                  // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
      24: aload_3
      25: invokevirtual #7                  // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
      28: invokevirtual #8                  // Method java/lang/StringBuilder.toString:()Ljava/lang/String;
      31: astore        4
 ```

**Comment by guoyu666** [comment]
感谢感谢！！

> 补充一下。
> 
> ```
>        0: ldc           #2                  // String he
>        2: astore_1
>        3: ldc           #3                  // String llo
>        5: astore_2
>        6: ldc           #4                  // String world
>        8: astore_3
>        9: new           #5                  // class java/lang/StringBuilder
>       12: dup
>       13: invokespecial #6                  // Method java/lang/StringBuilder."<init>":()V
>       16: aload_1
>       17: invokevirtual #7                  // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
>       20: aload_2
>       21: invokevirtual #7                  // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
>       24: aload_3
>       25: invokevirtual #7                  // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
>       28: invokevirtual #8                  // Method java/lang/StringBuilder.toString:()Ljava/lang/String;
>       31: astore        4
> ```

**Comment by Snailclimb** [comment]
> 上面的代码对应的字节码如下：？？？？ ![屏幕截图 2024-07-08 112807](https://private-user-images.githubusercontent.com/52870610/346419034-935bb4e8-c8a9-4490-b511-a003ea5ee9a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDE3NzIsIm5iZiI6MTcyMDQ0MTQ3MiwicGF0aCI6Ii81Mjg3MDYxMC8zNDY0MTkwMzQtOTM1YmI0ZTgtYzhhOS00NDkwLWI1MTEtYTAwM2VhNWVlOWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDEyMjQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNWMxNTJlM2NhMGNiMWZhOTczMTNlYTBjZTdiYTMxZWMyZjZlYjMwYjViZmQ5NjlmNmY2MGE3MjM4YjBlNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y4fqBv7pYKm6-91JcXK4XeNkWveNKWszMzd8hD5rIfc)

是图片下午出了一会问题，10分钟之后就好了。

<img width="1117" alt="image" src="https://github.com/Snailclimb/JavaGuide/assets/29880145/cf4cf8ed-d65d-4072-b992-052f301e8655">
