### ISSUE TITLE
[typo]Collections 工具类和 Arrays 工具类常见方法

### ISSUE THREAD

**Issue by spikesp** [Snailclimb/JavaGuide#243]
https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Basis/Arrays%2CCollectionsCommonMethods.md#%E6%9F%A5%E6%89%BE%E6%9B%BF%E6%8D%A2%E6%93%8D%E4%BD%9C

int indexOfSubList(List list, List target)//统计targe在list中第一次出现的索引，找不到则返回-1，类比int lastIndexOfSubList(List source, list target).

注释中的target少了一个s.

为了减少作者的工作量，以后如果有较为明显的typo，我就直接PR可以吗？

**Comment by Snailclimb** [comment]
嗯嗯 当然可以啦！你PR之后 我看查阅一下就可以了。感谢！
