### ISSUE TITLE
在DML 语句用法部分为何介绍TRUNCATE关键字用法

### ISSUE THREAD

**Issue by ChenPi222** [Snailclimb/JavaGuide#2430]
https://github.com/Snailclimb/JavaGuide/blob/97dd88a54c9418f47d21544350ed84500324cdc8/docs/database/sql/sql-syntax-summary.md?plain=1#L102
既然是先介绍DML语法，个人感觉最好只用DELETE就好了，外加TRUNCATE可能会混淆记忆
https://github.com/Snailclimb/JavaGuide/blob/97dd88a54c9418f47d21544350ed84500324cdc8/docs/database/sql/sql-syntax-summary.md?plain=1#L151

**Comment by Mr-Write** [comment]
Guide 哥这份资料的准确定位并不是学习、实战资料，而是一份面试指南，也就是说，truncate 我们在实际开发中并不推荐使用，但为什么呢，面试会问，这份资料会告诉你答案。以及 truncate、delete、drop 有什么区别之类的问题，这是面向面试进行食用的资料。

**Comment by ChenPi222** [comment]
@Mr-Write 感谢回复~
正是因为这份资料定位于“面试指南”，所以我觉得有必要在此处指明TRUNCATE不是DML语句，否则按文章结构，这部分理应讲的都是DML语句。谁都不希望之后被问“常用DML命令”的时候首先想到的是TRUNCATE吧hhhh

（BTW，你说的“ truncate、delete、drop 有什么区别之类的问题”我也在前一节看到了，讲得很清晰，不过我这次Issue所引用的部分是后一节的内容）

**Comment by Snailclimb** [comment]
> TRUNCATE

准确来说，这里确实可以注明一下。
