### ISSUE TITLE
实现泛型接口，指定类型时的实现类不需要再声明参数 `T`了吧？

### ISSUE THREAD

**Issue by LiZhi-CASIA** [Snailclimb/JavaGuide#2435]
![image](https://github.com/user-attachments/assets/22dbd7f1-b771-444a-a12d-697829fbef39)

**Comment by Snailclimb** [comment]
> ![image](https://private-user-images.githubusercontent.com/97828772/350933096-22dbd7f1-b771-444a-a12d-697829fbef39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTA3MDIsIm5iZiI6MTcyMTY1MDQwMiwicGF0aCI6Ii85NzgyODc3Mi8zNTA5MzMwOTYtMjJkYmQ3ZjEtYjc3MS00NDRhLWExMmQtNjk3ODI5ZmJlZjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDEyMTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZmQ0YjAzYjYzNzdkMDhiMDc3NWJiYTIzMTAzNWQyMDBhNzZiZTU0MGEwNjAyNGY0NmMzM2EzODA2NzI0ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JscRQtHFmeEpCQYcPoaHWY1OZ0Ox-3D_uoyEVqCQIC4)

是这个的，感谢指出👍
