### ISSUE TITLE
分布式ID章节snowflake算法图片有误

### ISSUE THREAD

**Issue by rookiiiie** [Snailclimb/JavaGuide#2437]
guide哥，snowflake算法（https://javaguide.cn/distributed-system/distributed-id.html#%E7%AE%97%E6%B3%95）图片中
![image](https://github.com/user-attachments/assets/130b7b1c-50d3-4a75-9d37-0a0d71be3c30)
sequence是12bit！

**Comment by Snailclimb** [comment]
> guide哥，snowflake算法（[https://javaguide.cn/distributed-system/distributed-id.html#%E7%AE%97%E6%B3%95）图片中](https://javaguide.cn/distributed-system/distributed-id.html#%E7%AE%97%E6%B3%95%EF%BC%89%E5%9B%BE%E7%89%87%E4%B8%AD) ![image](https://private-user-images.githubusercontent.com/52649646/352129436-130b7b1c-50d3-4a75-9d37-0a0d71be3c30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODM3NzMsIm5iZiI6MTcyMTk4MzQ3MywicGF0aCI6Ii81MjY0OTY0Ni8zNTIxMjk0MzYtMTMwYjdiMWMtNTBkMy00YTc1LTlkMzctMGEwZDcxYmUzYzMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA4NDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZjZkZGE5M2Y1Mjk3Mzc4MzdmOWJkNDkwMzlmNzYzNDgyNDhmZTAyNDM4MDU5YTNkNTQwYzU2NDdkZWZlYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AoMC6y1dqWWcuBJh39Jm61KNO9SOHEjED5Klal3801g) sequence是12bit！

感谢指出，这里笔误了👍
