### ISSUE TITLE
”MySQL索引详解“中的“AVL树”，配图中为什么4在5的右子树上

### ISSUE THREAD

**Issue by Chaobk** [Snailclimb/JavaGuide#2438]
AVL树也是二叉查找树，为什么4会在5的右子树上
![image](https://github.com/user-attachments/assets/a6a67037-09fc-415c-a69d-2120ff393491)

**Comment by Snailclimb** [comment]
> 为什么4会在5的右子树上

感谢！正常来说，应该是这样的吧：

      5
    /   \
   2     8
  / \     \
 1   4     9

**Comment by Chaobk** [comment]
是的，这样看起来是对的了，文档中的应该是有点问题
