### ISSUE TITLE
逻辑笔误纠正

### ISSUE THREAD

**Issue by ChenPi222** [Snailclimb/JavaGuide#2441]
根据上下文，此处应为：
几年前的数据并不一定都是**冷**数据
https://github.com/Snailclimb/JavaGuide/blob/4acc22c947f40a94a14775c5eb5854df4dc7f1c0/docs/high-performance/data-cold-hot-separation.md?plain=1#L26

有点强迫症，随手Issue一下哈哈

**Comment by Snailclimb** [comment]
> 根据上下文，此处应为： 几年前的数据并不一定都是**冷**数据
> 
> https://github.com/Snailclimb/JavaGuide/blob/4acc22c947f40a94a14775c5eb5854df4dc7f1c0/docs/high-performance/data-cold-hot-separation.md?plain=1#L26
> 
> 有点强迫症，随手Issue一下哈哈

感谢，这种笔误确实要修改一下。
