### ISSUE TITLE
图片英语单词错误

### ISSUE THREAD

**Issue by Kisa-Dong** [Snailclimb/JavaGuide#2447]
![image](https://github.com/user-attachments/assets/01837837-1d0f-4cb4-b72d-8dfe67e97d83)

**Comment by Snailclimb** [comment]
> ![image](https://private-user-images.githubusercontent.com/84782008/356446628-01837837-1d0f-4cb4-b72d-8dfe67e97d83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzk2NjEsIm5iZiI6MTcyMzE3OTM2MSwicGF0aCI6Ii84NDc4MjAwOC8zNTY0NDY2MjgtMDE4Mzc4MzctMWQwZi00Y2I0LWI3MmQtOGRmZTY3ZTk3ZDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA0NTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MzIyOWRhNTUzMzZmNmUzZjg2OTA4YWIwNzg3MWFmZDNhMmExZTczY2Y5N2UyMDczMDNlOWU2NmFhMjcwZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iSNcURjHUXzvJlsqefebBs8IlYWohrmRCLziBKpp__I)

感谢！👍
