### ISSUE TITLE
关于"HashMap 的长度为什么是 2 的幂次方"这个问题

### ISSUE THREAD

**Issue by songjiyang** [Snailclimb/JavaGuide#2449]
> 我们首先可能会想到采用 % 取余的操作来实现。但是，重点来了：“取余(%)操作中如果除数是 2 的幂次则等价于与其除数减一的与(&)操作（也就是说 hash%length==hash&(length-1)的前提是 length 是 2 的 n 次方；）。” 并且 采用二进制位操作 & 相对于 % 能够提高运算效率，这就解释了 HashMap 的长度为什么是 2 的幂次方

除了上面所说的位运算比取余效率高之外，我觉得更重要的一个原因是，长度是2的幂次方，可以让HashMap在扩容的时候更均匀。例如:

- length = 8时，length - 1 = 7 的二进制位`0111`
- length = 16时，length - 1 = 15 的二进制位`1111`

这时候原本存在HashMap中的元素计算新的数组位置时 `hash&(length-1)`，取决hash的第四个二进制位（从右往左数），会出现两种情况：
1.  第四个二进制位为0，数组位置不变，也就是说当前元素在新数组和旧数组的位置相同
2. 第四个二进制位为1，数组位置在新数组扩容之后的那一部分

也就是说扩容之后，如果旧数组元素hash值比较均匀（至于hash值均不均匀，取决于前面讲的对象的hashcode()方法和扰动函数）的情况下，会有一半在新数组的前半部分，一半在新数组后半部分，这样达到一个均匀的效果

**Comment by Snailclimb** [comment]
> 除了上面所说的位运算比取余效率高之外，我觉得更重要的一个原因是，长度是2的幂次方，可以让HashMap在扩容的时候更均匀。例如:
> 
> * length = 8时，length - 1 = 7 的二进制位`0111`
> * length = 16时，length - 1 = 15 的二进制位`1111`
> 
> 这时候原本存在HashMap中的元素计算新的数组位置时 `hash&(length-1)`，取决hash的第四个二进制位（从右往左数），会出现两种情况：
> 
> 1. 第四个二进制位为0，数组位置不变，也就是说当前元素在新数组和旧数组的位置相同
> 2. 第四个二进制位为1，数组位置在新数组扩容之后的那一部分
> 
> 也就是说扩容之后，如果旧数组元素hash值比较均匀（至于hash值均不均匀，取决于前面讲的对象的hashcode()方法和扰动函数）的情况下，会有一半在新数组的前半部分，一半在新数组后半部分，这样达到一个均匀的效果

很有道理，感谢完善补充，我会尽快同步到项目中去。

**Comment by Snailclimb** [comment]
> > 我们首先可能会想到采用 % 取余的操作来实现。但是，重点来了：“取余(%)操作中如果除数是 2 的幂次则等价于与其除数减一的与(&)操作（也就是说 hash%length==hash&(length-1)的前提是 length 是 2 的 n 次方；）。” 并且 采用二进制位操作 & 相对于 % 能够提高运算效率，这就解释了 HashMap 的长度为什么是 2 的幂次方
> 
> 除了上面所说的位运算比取余效率高之外，我觉得更重要的一个原因是，长度是2的幂次方，可以让HashMap在扩容的时候更均匀。例如:
> 
> * length = 8时，length - 1 = 7 的二进制位`0111`
> * length = 16时，length - 1 = 15 的二进制位`1111`
> 
> 这时候原本存在HashMap中的元素计算新的数组位置时 `hash&(length-1)`，取决hash的第四个二进制位（从右往左数），会出现两种情况：
> 
> 1. 第四个二进制位为0，数组位置不变，也就是说当前元素在新数组和旧数组的位置相同
> 2. 第四个二进制位为1，数组位置在新数组扩容之后的那一部分
> 
> 也就是说扩容之后，如果旧数组元素hash值比较均匀（至于hash值均不均匀，取决于前面讲的对象的hashcode()方法和扰动函数）的情况下，会有一半在新数组的前半部分，一半在新数组后半部分，这样达到一个均匀的效果

完善后的版本呢：

**

我们首先可能会想到采用 % 取余的操作来实现。但是，重点来了：“**取余(%)操作中如果除数是 2 的幂次则等价于与其除数减一的与(&)操作**（也就是说 `hash%length==hash&(length-1)` 的前提是 length 是 2 的 n 次方）。” 并且，**采用二进制位操作 & 相对于 % 能够提高运算效率**。

除了上面所说的位运算比取余效率高之外，我觉得更重要的一个原因是：**长度是 2 的幂次方，可以让 `HashMap` 在扩容的时候更均匀**。例如:

- length = 8 时，length - 1 = 7 的二进制位`0111`
- length = 16 时，length - 1 = 15 的二进制位`1111`

这时候原本存在 `HashMap` 中的元素计算新的数组位置时 `hash&(length-1)`，取决 hash 的第四个二进制位（从右数），会出现两种情况：

1. 第四个二进制位为 0，数组位置不变，也就是说当前元素在新数组和旧数组的位置相同。
2. 第四个二进制位为 1，数组位置在新数组扩容之后的那一部分。

这里列举一个例子：

```
假设有一个元素的哈希值为 10101100

旧数组元素位置计算：
hash        = 10101100
length - 1  = 00000111
& -----------------
index       = 00000100  (4)

新数组元素位置计算：
hash        = 10101100
length - 1  = 00001111
& -----------------
index       = 00001100  (12)

看第四位（从右数）：
1.高位为 0：位置不变。
2.高位为 1：移动到新位置（原索引位置+原容量）。
```

⚠️注意：这里列举的场景看的是第四个二进制位，更准确点来说看的是高位（从右数），例如 `length = 32` 时，`length - 1 = 31`，二进制为 `11111`，这里看的就是第五个二进制位。

也就是说扩容之后，在旧数组元素 hash 值比较均匀（至于 hash 值均不均匀，取决于前面讲的对象的 `hashcode()` 方法和扰动函数）的情况下，新数组元素也会被分配的比较均匀，最好的情况是会有一半在新数组的前半部分，一半在新数组后半部分。

这样也使得扩容机制变得简单和高效，扩容后只需检查哈希值高位的变化来决定元素的新位置，要么位置不变（高位为 0），要么就是移动到新位置（高位为 1，原索引位置+原容量）。

最后，简单总结一下 `HashMap` 的长度是 2 的幂次方的原因：

1. 位运算效率更高：位运算(&)比取余运算(%)更高效。当长度为 2 的幂次方时，`hash % length` 等价于 `hash & (length - 1)`。
2. 可以更好地保证哈希值的均匀分布：扩容之后，在旧数组元素 hash 值比较均匀的情况下，新数组元素也会被分配的比较均匀，最好的情况是会有一半在新数组的前半部分，一半在新数组后半部分。
3. 扩容机制变得简单和高效：扩容后只需检查哈希值高位的变化来决定元素的新位置，要么位置不变（高位为 0），要么就是移动到新位置（高位为 1，原索引位置+原容量）。

**Comment by songjiyang** [comment]
> > > 我们首先可能会想到采用 % 取余的操作来实现。但是，重点来了：“取余(%)操作中如果除数是 2 的幂次则等价于与其除数减一的与(&)操作（也就是说 hash%length==hash&(length-1)的前提是 length 是 2 的 n 次方；）。” 并且 采用二进制位操作 & 相对于 % 能够提高运算效率，这就解释了 HashMap 的长度为什么是 2 的幂次方
> > 
> > 
> > 除了上面所说的位运算比取余效率高之外，我觉得更重要的一个原因是，长度是2的幂次方，可以让HashMap在扩容的时候更均匀。例如:
> > 
> > * length = 8时，length - 1 = 7 的二进制位`0111`
> > * length = 16时，length - 1 = 15 的二进制位`1111`
> > 
> > 这时候原本存在HashMap中的元素计算新的数组位置时 `hash&(length-1)`，取决hash的第四个二进制位（从右往左数），会出现两种情况：
> > 
> > 1. 第四个二进制位为0，数组位置不变，也就是说当前元素在新数组和旧数组的位置相同
> > 2. 第四个二进制位为1，数组位置在新数组扩容之后的那一部分
> > 
> > 也就是说扩容之后，如果旧数组元素hash值比较均匀（至于hash值均不均匀，取决于前面讲的对象的hashcode()方法和扰动函数）的情况下，会有一半在新数组的前半部分，一半在新数组后半部分，这样达到一个均匀的效果
> 
> 完善后的版本呢：
> 
> **
> 
> 我们首先可能会想到采用 % 取余的操作来实现。但是，重点来了：“**取余(%)操作中如果除数是 2 的幂次则等价于与其除数减一的与(&)操作**（也就是说 `hash%length==hash&(length-1)` 的前提是 length 是 2 的 n 次方）。” 并且，**采用二进制位操作 & 相对于 % 能够提高运算效率**。
> 
> 除了上面所说的位运算比取余效率高之外，我觉得更重要的一个原因是：**长度是 2 的幂次方，可以让 `HashMap` 在扩容的时候更均匀**。例如:
> 
> * length = 8 时，length - 1 = 7 的二进制位`0111`
> * length = 16 时，length - 1 = 15 的二进制位`1111`
> 
> 这时候原本存在 `HashMap` 中的元素计算新的数组位置时 `hash&(length-1)`，取决 hash 的第四个二进制位（从右数），会出现两种情况：
> 
> 1. 第四个二进制位为 0，数组位置不变，也就是说当前元素在新数组和旧数组的位置相同。
> 2. 第四个二进制位为 1，数组位置在新数组扩容之后的那一部分。
> 
> 这里列举一个例子：
> 
> ```
> 假设有一个元素的哈希值为 10101100
> 
> 旧数组元素位置计算：
> hash        = 10101100
> length - 1  = 00000111
> & -----------------
> index       = 00000100  (4)
> 
> 新数组元素位置计算：
> hash        = 10101100
> length - 1  = 00001111
> & -----------------
> index       = 00001100  (12)
> 
> 看第四位（从右数）：
> 1.高位为 0：位置不变。
> 2.高位为 1：移动到新位置（原索引位置+原容量）。
> ```
> 
> ⚠️注意：这里列举的场景看的是第四个二进制位，更准确点来说看的是高位（从右数），例如 `length = 32` 时，`length - 1 = 31`，二进制为 `11111`，这里看的就是第五个二进制位。
> 
> 也就是说扩容之后，在旧数组元素 hash 值比较均匀（至于 hash 值均不均匀，取决于前面讲的对象的 `hashcode()` 方法和扰动函数）的情况下，新数组元素也会被分配的比较均匀，最好的情况是会有一半在新数组的前半部分，一半在新数组后半部分。
> 
> 这样也使得扩容机制变得简单和高效，扩容后只需检查哈希值高位的变化来决定元素的新位置，要么位置不变（高位为 0），要么就是移动到新位置（高位为 1，原索引位置+原容量）。
> 
> 最后，简单总结一下 `HashMap` 的长度是 2 的幂次方的原因：
> 
> 1. 位运算效率更高：位运算(&)比取余运算(%)更高效。当长度为 2 的幂次方时，`hash % length` 等价于 `hash & (length - 1)`。
> 2. 可以更好地保证哈希值的均匀分布：扩容之后，在旧数组元素 hash 值比较均匀的情况下，新数组元素也会被分配的比较均匀，最好的情况是会有一半在新数组的前半部分，一半在新数组后半部分。
> 3. 扩容机制变得简单和高效：扩容后只需检查哈希值高位的变化来决定元素的新位置，要么位置不变（高位为 0），要么就是移动到新位置（高位为 1，原索引位置+原容量）。

好的，很详细！

**Comment by gbccccc** [comment]
准备面试的时候看到了这一段，我不太同意“HashMap大小采用2的n次幂能在扩容的时候更均匀”这个看法，因为“扩容均匀”本质是由扩容时采用重新取余算法决定的，将取余变为位运算是在“HashMap大小采用2的n次幂”场景下的特殊优化，这里本质还是个取余操作。

因此现在这个JavaGuide版本中提到的“HashMap大小采用2的n次幂能在扩容的时候更均匀”逻辑上是不通的，文中的举例对比也不合理，因为如果HashMap大小不是2的n次幂，那么扩容时继续使用位运算就不再合理了，而是理应使用最原始的取余计算，这样同样能保证了均匀，只是计算效率变低了。
