### ISSUE TITLE
http/3.0 比 http/2.0 具有更高安全性的疑惑

### ISSUE THREAD

**Issue by fox-half-tian** [Snailclimb/JavaGuide#2452]
原文链接：[[计算机网络常见面试题总结(上)-HTTP/2.0 和 HTTP/3.0 有什么区别？ | JavaGuide](https://javaguide.cn/cs-basics/network/other-network-questions.html#http-2-0-%E5%92%8C-http-3-0-%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB)](https://javaguide.cn/cs-basics/network/other-network-questions.html#http-2-0-和-http-3-0-有什么区别)

原文内容：

>**安全性**：HTTP/2.0 和 HTTP/3.0 在安全性上都有较高的要求，支持加密通信，但在实现上有所不同。HTTP/2.0 使用 TLS 协议进行加密，而 HTTP/3.0 基于 QUIC 协议，包含了内置的加密和身份验证机制，可以提供更强的安全性。

我去查了一下，QUIC 协议默认集成了 TLS 1.3，而 HTTP/2.0 的 HTTPS使用的也是 TLS 1.3，那么这两者不应该具有相同级别的安全性吗

**Comment by Snailclimb** [comment]
> 原文链接：[[计算机网络常见面试题总结(上)-HTTP/2.0 和 HTTP/3.0 有什么区别？ | JavaGuide](https://javaguide.cn/cs-basics/network/other-network-questions.html#http-2-0-%E5%92%8C-http-3-0-%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB)]([https://javaguide.cn/cs-basics/network/other-network-questions.html#http-2-0-和-http-3-0-有什么区别](https://javaguide.cn/cs-basics/network/other-network-questions.html#http-2-0-%E5%92%8C-http-3-0-%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB))
> 
> 原文内容：
> 
> > **安全性**：HTTP/2.0 和 HTTP/3.0 在安全性上都有较高的要求，支持加密通信，但在实现上有所不同。HTTP/2.0 使用 TLS 协议进行加密，而 HTTP/3.0 基于 QUIC 协议，包含了内置的加密和身份验证机制，可以提供更强的安全性。
> 
> 我去查了一下，QUIC 协议默认集成了 TLS 1.3，而 HTTP/2.0 的 HTTPS使用的也是 TLS 1.3，那么这两者不应该具有相同级别的安全性吗

HTTP/3 报头信息暴露更少，还支持连接迁移。

**Comment by Snailclimb** [comment]
> HTTP/2.0 和 HTTP/3.0 在安全性上都有较高的要求，支持加密通信，但在实现上有所不同。HTTP/2.0 使用 TLS 协议进行加密，而 HTTP/3.0 基于 QUIC 协议，包含了内置的加密和身份验证机制，可以提供更强的安全性。

这样描述会不会更好一点：

HTTP/2.0 和 HTTP/3.0 都支持加密通信，但实现方式不同。HTTP/2.0 依赖 TLS 协议加密，而 HTTP/3.0 基于 QUIC 协议，QUIC 内置了 TLS 1.3，能更快建立连接，并减少网络报头信息暴露，提升了安全性和隐私性。

**Comment by fox-half-tian** [comment]
> > 原文链接：[[计算机网络常见面试题总结(上)-HTTP/2.0 和 HTTP/3.0 有什么区别？ | JavaGuide](https://javaguide.cn/cs-basics/network/other-network-questions.html#http-2-0-%E5%92%8C-http-3-0-%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB)]([https://javaguide.cn/cs-basics/network/other-network-questions.html#http-2-0-和-http-3-0-有什么区别](https://javaguide.cn/cs-basics/network/other-network-questions.html#http-2-0-%E5%92%8C-http-3-0-%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB))
> > 原文内容：
> > > **安全性**：HTTP/2.0 和 HTTP/3.0 在安全性上都有较高的要求，支持加密通信，但在实现上有所不同。HTTP/2.0 使用 TLS 协议进行加密，而 HTTP/3.0 基于 QUIC 协议，包含了内置的加密和身份验证机制，可以提供更强的安全性。
> > 
> > 
> > 我去查了一下，QUIC 协议默认集成了 TLS 1.3，而 HTTP/2.0 的 HTTPS使用的也是 TLS 1.3，那么这两者不应该具有相同级别的安全性吗
> 
> HTTP/3 报头信息暴露更少，还支持连接迁移。

是的，只是因为“HTTP/3.0 基于 QUIC 协议，包含了内置的加密和身份验证机制”就比 HTTP/2.0 的安全性更强，我感觉在原文中表达安全性更强的说服力不是很够。

这个“连接迁移”是不是表达的更强的稳定性呢？手机或者移动设备在 4G 信号下和 WiFi 等网络情况下切换，不会断线重连，用户甚至无任何感知，能够直接实现平滑的信号切换。

我看了一篇文章 https://developer.aliyun.com/article/888447?spm=a2c6h.13262185.profile.8.6990103234MpTE
安全性更强的原因：在 HTTP/2.0 中，TLS 用于加密和认证整个 HTTP 会话，包括所有的 HTTP 头部和数据负载。TLS的工作是在 TCP 层之上，它加密的是在 TCP 连接中传输的应用层的数据，并不会对 TCP 头部以及 TLS 记录层头部进行加密，所以在传输的过程中 TCP 头部可能会被攻击者篡改来干扰通信。而 HTTP/3.0 的 QUIC 对整个数据包（包括报文头和报文体）进行了加密与认证处理，保障安全性。

**Comment by Snailclimb** [comment]
> > > 原文链接：[[计算机网络常见面试题总结(上)-HTTP/2.0 和 HTTP/3.0 有什么区别？ | JavaGuide](https://javaguide.cn/cs-basics/network/other-network-questions.html#http-2-0-%E5%92%8C-http-3-0-%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB)]([https://javaguide.cn/cs-basics/network/other-network-questions.html#http-2-0-和-http-3-0-有什么区别](https://javaguide.cn/cs-basics/network/other-network-questions.html#http-2-0-%E5%92%8C-http-3-0-%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB))
> > > 原文内容：
> > > > **安全性**：HTTP/2.0 和 HTTP/3.0 在安全性上都有较高的要求，支持加密通信，但在实现上有所不同。HTTP/2.0 使用 TLS 协议进行加密，而 HTTP/3.0 基于 QUIC 协议，包含了内置的加密和身份验证机制，可以提供更强的安全性。
> > > 
> > > 
> > > 我去查了一下，QUIC 协议默认集成了 TLS 1.3，而 HTTP/2.0 的 HTTPS使用的也是 TLS 1.3，那么这两者不应该具有相同级别的安全性吗
> > 
> > 
> > HTTP/3 报头信息暴露更少，还支持连接迁移。
> 
> 是的，只是因为“HTTP/3.0 基于 QUIC 协议，包含了内置的加密和身份验证机制”就比 HTTP/2.0 的安全性更强，我感觉在原文中表达安全性更强的说服力不是很够。
> 
> 这个“连接迁移”是不是表达的更强的稳定性呢？手机或者移动设备在 4G 信号下和 WiFi 等网络情况下切换，不会断线重连，用户甚至无任何感知，能够直接实现平滑的信号切换。
> 
> 我看了一篇文章 https://developer.aliyun.com/article/888447?spm=a2c6h.13262185.profile.8.6990103234MpTE 安全性更强的原因：在 HTTP/2.0 中，TLS 用于加密和认证整个 HTTP 会话，包括所有的 HTTP 头部和数据负载。在传统的 TCP +TLS 架构中，TLS 加密的是在 TCP 连接中传输的应用层的数据，并不会对 TCP 头部以及 TLS 记录层头部进行加密，所以在传输的过程中 TCP 头部可能会被攻击者篡改来干扰通信。而 HTTP/3.0 的 QUIC 对整个数据包（包括报文头和报文体）进行了加密与认证处理，保障安全性。

不错的，欢迎提交一个PR完善一下。

**Comment by fox-half-tian** [comment]
> > > > 原文链接：[[计算机网络常见面试题总结(上)-HTTP/2.0 和 HTTP/3.0 有什么区别？ | JavaGuide](https://javaguide.cn/cs-basics/network/other-network-questions.html#http-2-0-%E5%92%8C-http-3-0-%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB)]([https://javaguide.cn/cs-basics/network/other-network-questions.html#http-2-0-和-http-3-0-有什么区别](https://javaguide.cn/cs-basics/network/other-network-questions.html#http-2-0-%E5%92%8C-http-3-0-%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB))
> > > > 原文内容：
> > > > > **安全性**：HTTP/2.0 和 HTTP/3.0 在安全性上都有较高的要求，支持加密通信，但在实现上有所不同。HTTP/2.0 使用 TLS 协议进行加密，而 HTTP/3.0 基于 QUIC 协议，包含了内置的加密和身份验证机制，可以提供更强的安全性。
> > > > 
> > > > 
> > > > 我去查了一下，QUIC 协议默认集成了 TLS 1.3，而 HTTP/2.0 的 HTTPS使用的也是 TLS 1.3，那么这两者不应该具有相同级别的安全性吗
> > > 
> > > 
> > > HTTP/3 报头信息暴露更少，还支持连接迁移。
> > 
> > 
> > 是的，只是因为“HTTP/3.0 基于 QUIC 协议，包含了内置的加密和身份验证机制”就比 HTTP/2.0 的安全性更强，我感觉在原文中表达安全性更强的说服力不是很够。
> > 这个“连接迁移”是不是表达的更强的稳定性呢？手机或者移动设备在 4G 信号下和 WiFi 等网络情况下切换，不会断线重连，用户甚至无任何感知，能够直接实现平滑的信号切换。
> > 我看了一篇文章 https://developer.aliyun.com/article/888447?spm=a2c6h.13262185.profile.8.6990103234MpTE 安全性更强的原因：在 HTTP/2.0 中，TLS 用于加密和认证整个 HTTP 会话，包括所有的 HTTP 头部和数据负载。在传统的 TCP +TLS 架构中，TLS 加密的是在 TCP 连接中传输的应用层的数据，并不会对 TCP 头部以及 TLS 记录层头部进行加密，所以在传输的过程中 TCP 头部可能会被攻击者篡改来干扰通信。而 HTTP/3.0 的 QUIC 对整个数据包（包括报文头和报文体）进行了加密与认证处理，保障安全性。
> 
> 不错的，欢迎提交一个PR完善一下。

好的，已经提交 PR🌹
