### ISSUE TITLE
逻辑笔误和拼写错误修正

### ISSUE THREAD

**Issue by SS4G0923** [Snailclimb/JavaGuide#2459]
https://github.com/Snailclimb/JavaGuide/pull/2456
您好，我在阅读学习的时候发现了一个英文单词拼写错误和一个可能会影响理解的逻辑笔误。
1）SELECT笔误拼写为SELELCT
<img width="685" alt="Screenshot 2024-08-19 at 9 34 17 PM" src="https://github.com/user-attachments/assets/ef66fc79-c4a8-458b-8789-f91027b013b3">
2）FixedThreadPool和SingleThreadExecutor使用的应为无界阻塞队列，正如前一篇文章《Java线程池详解》中所提到的：https://javaguide.cn/java/concurrent/java-thread-pool-summary.html#%E7%BA%BF%E7%A8%8B%E6%B1%A0%E5%B8%B8%E7%94%A8%E7%9A%84%E9%98%BB%E5%A1%9E%E9%98%9F%E5%88%97%E6%80%BB%E7%BB%93

**Comment by Snailclimb** [comment]
> SELELCT

感谢指出👍
