### ISSUE TITLE
unicode描述错误

### ISSUE THREAD

**Issue by mjhxy** [Snailclimb/JavaGuide#2468]
原文：“顺便分享一下之前遇到的笔试题：常用字符编码所占字节数？utf8 :英文占 1 字节，中文占 3 字节，unicode：任何字符都占 2 个字节，gbk：英文占 1 字节，中文占 2 字节。”，来自“Java IO 基础知识总结”

错误：“unicode：任何字符都占 2 个字节”，说法错误，Unicode 本身并不定义字符占用的字节数，而是通过不同的编码方式来实现。

**Comment by Snailclimb** [comment]
> 原文：“顺便分享一下之前遇到的笔试题：常用字符编码所占字节数？utf8 :英文占 1 字节，中文占 3 字节，unicode：任何字符都占 2 个字节，gbk：英文占 1 字节，中文占 2 字节。”，来自“Java IO 基础知识总结”
> 
> 错误：“unicode：任何字符都占 2 个字节”，说法错误，Unicode 本身并不定义字符占用的字节数，而是通过不同的编码方式来实现。

感谢指出👍
