### ISSUE TITLE
Throwable 类常用方法有哪些 中，部分内容写反了

### ISSUE THREAD

**Issue by fengjrrz** [Snailclimb/JavaGuide#2479]
Guide中写的：
String getMessage(): 返回异常发生时的简要描述
String toString(): 返回异常发生时的详细信息
应该是：
String getMessage(): 返回异常发生时的详细信息
String toString(): 返回异常发生时的简要描述
看的源码上的注释这么写的

**Comment by Snailclimb** [comment]
> Guide中写的： String getMessage(): 返回异常发生时的简要描述 String toString(): 返回异常发生时的详细信息 应该是： String getMessage(): 返回异常发生时的详细信息 String toString(): 返回异常发生时的简要描述 看的源码上的注释这么写的

感谢指出！
