### ISSUE TITLE
使用 this 和 super 要注意的问题

### ISSUE THREAD

**Issue by spikesp** [Snailclimb/JavaGuide#248]
[使用 this 和 super 要注意的问题](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Basis/final%E3%80%81static%E3%80%81this%E3%80%81super.md#super-%E5%85%B3%E9%94%AE%E5%AD%97)

使用 this 和 super 要注意的问题：

super 调用父类中的其他构造方法时，调用时要放在构造方法的首行！this 调用本类中的其他构造方法时，也要放在首行。
this、super不能用在static方法中。

------------------------------------
这里能否提供代码实例？

super调用父类其他构造方法，我对这句的意思理解有点模糊。

super调用父类构造方法，应该不是是指super.  是 super()吧? 我参考stackoverflow的提问，说调用super（）是在构造器中调用的时候需要在第一行。这里所说的是这个意思吗？

父类其他构造方法，是指除了默认的构造方法之外的构造方法吗？

以下是我搜了一下相关回答的链接：
https://stackoverflow.com/questions/1168345/why-do-this-and-super-have-to-be-the-first-statement-in-a-constructor

https://stackoverflow.com/questions/16182310/whats-the-different-between-super-and-super-in-java

望各位朋友赐教。

**Comment by spikesp** [comment]
噢，issue提完，突然看明白
【super 调用父类中的其他构造方法时，调用时要放在构造方法的首行！】这句话的意思了。

原来【调用时要放在构造方法的首行】这句，就表示super（）是在构造器里调用的。

可能是我个人理解能力不够或者中文造诣不好，不过如果将此句改成：

在构造器中使用super（）调用父类中的其他构造方法时，该语句必须处于构造器的首行，否则编译器会报错。

可能会更好理解一些。

**Comment by Snailclimb** [comment]
嗯嗯 可以的 很棒的思考！
