### ISSUE TITLE
JVM 1.8 运行时常量池问题

### ISSUE THREAD

**Issue by Rancho-7** [Snailclimb/JavaGuide#2481]
在jdk1.8中，yu运行时常量池究竟是位于元空间中还是堆中？
在网上看到有说位于堆中的说法，但是我们当前网站中说的是位于元空间中。
来自美团技术团队
![image](https://github.com/user-attachments/assets/9dee1925-a185-4ec9-87b6-41e9d639069d)
我们网站
![image](https://github.com/user-attachments/assets/780c84a1-2f48-4edc-b8f4-29affe789129)

**Comment by Snailclimb** [comment]
> 在jdk1.8中，yu运行时常量池究竟是位于元空间中还是堆中？ 在网上看到有说位于堆中的说法，但是我们当前网站中说的是位于元空间中。 来自美团技术团队 ![image](https://private-user-images.githubusercontent.com/59016860/366272341-9dee1925-a185-4ec9-87b6-41e9d639069d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDExNTEsIm5iZiI6MTcyNjA0MDg1MSwicGF0aCI6Ii81OTAxNjg2MC8zNjYyNzIzNDEtOWRlZTE5MjUtYTE4NS00ZWM5LTg3YjYtNDFlOWQ2MzkwNjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA3NDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiZjIxZTY0YjViMWNjYjdiZGU3MjYyNDE0ZDI5MTY1MTE5MTY0Y2U3ZTZhYzk1ZWY5MWM5NWMzOTc2YmE3ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cTD9xu4pyTV9wot-3LvePYj2XkK_KFosdqkdTJq-IPk) 我们网站 ![image](https://private-user-images.githubusercontent.com/59016860/366272039-780c84a1-2f48-4edc-b8f4-29affe789129.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDExNTEsIm5iZiI6MTcyNjA0MDg1MSwicGF0aCI6Ii81OTAxNjg2MC8zNjYyNzIwMzktNzgwYzg0YTEtMmY0OC00ZWRjLWI4ZjQtMjlhZmZlNzg5MTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA3NDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZjM2NjU5MjU3YTBlM2RhZTVlMzcyY2YwMmJmMWY4ZTAzOWRmY2Q4N2QwY2NhODQ3ZDU4MWYwNzJjYTNhNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FXc_SbUD5pbe9WfFK8DBrPCNE30rlUWPQM5xmSx_V-s)

我是这样理解的：

<img width="768" alt="image" src="https://github.com/user-attachments/assets/58974594-9b6f-45e6-9ace-138192a2e45c">
