### ISSUE TITLE
#{} 和 ${} 的区别是什么？ 答案优化

### ISSUE THREAD

**Issue by doveppp** [Snailclimb/JavaGuide#2490]
现在的答案是：

- ${}是...

- #{}是...

把他俩倒换一下位置吧，先`#{}`再 `${}`，和题目对应起来，今天面试问我整好给答反了😭😭😭

**Comment by Snailclimb** [comment]
> 现在的答案是：
> 
> * ${}是...
> * #{}是...
> 
> 把他俩倒换一下位置吧，先`#{}`再 `${}`，和题目对应起来，今天面试问我整好给答反了😭😭😭

好的好的，哈哈哈，还能这样。
