### ISSUE TITLE
这里应该是二级标题

### ISSUE THREAD

**Issue by cjvox** [Snailclimb/JavaGuide#2503]
#2500 
这里应该是二级标题，早上提交的时候少打一个＃
文件链接：[https://github.com/Snailclimb/JavaGuide/blob/main/docs/database/redis/redis-skiplist.md](url)

**Comment by Snailclimb** [comment]
> #2500 这里应该是二级标题，早上提交的时候少打一个＃ 文件链接：[https://github.com/Snailclimb/JavaGuide/blob/main/docs/database/redis/redis-skiplist.md](url)

嗯嗯
