### ISSUE TITLE
Java9后，StringBuffer、StringBuilder内部还是使用 char[] 实现的

### ISSUE THREAD

**Issue by sunss20** [Snailclimb/JavaGuide#2512]
**Java9后，StringBuffer、StringBuilder内部还是使用 char[] 实现的**
![a69454f0ba647e9ab4c5cbf0207dfd44](https://github.com/user-attachments/assets/1db081c7-7d44-4a3a-809e-9e2263d4a1fc)
![e51e6d4c4fbae2d0022349b35f6b6724](https://github.com/user-attachments/assets/09d409ed-f1fb-4575-b531-3b33a4fd5f88)

**Comment by Snailclimb** [comment]
> **Java9后，StringBuffer、StringBuilder内部还是使用 char[] 实现的** ![a69454f0ba647e9ab4c5cbf0207dfd44](https://private-user-images.githubusercontent.com/186402451/380431269-1db081c7-7d44-4a3a-809e-9e2263d4a1fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNzI0MjYsIm5iZiI6MTczMDA3MjEyNiwicGF0aCI6Ii8xODY0MDI0NTEvMzgwNDMxMjY5LTFkYjA4MWM3LTdkNDQtNGEzYS04MDllLTllMjI2M2Q0YTFmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QyMzM1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDBhM2JiYTllMGNkYmQ2YWFiOTJkNWViZGI3OWE4ZDA4NTYwMzExYjUwY2I4NzQ3MGVhMzRlNWQ3NWZlNzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5HZY3r3lPOeD4JXHdEF49eXVcpxSy1NsYURii59Sn_I) ![e51e6d4c4fbae2d0022349b35f6b6724](https://private-user-images.githubusercontent.com/186402451/380431276-09d409ed-f1fb-4575-b531-3b33a4fd5f88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNzI0MjYsIm5iZiI6MTczMDA3MjEyNiwicGF0aCI6Ii8xODY0MDI0NTEvMzgwNDMxMjc2LTA5ZDQwOWVkLWYxZmItNDU3NS1iNTMxLTNiMzNhNGZkNWY4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QyMzM1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmQwZGE2YzNjMzVkNjQ5Mjk2YTVhYjA0Mzg0YzUyYmI5MDhkMWFiNjE5N2RiNjA3Mzk1NmM2ZTNmOTZjOWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.O2O4p7p2vlnsq0SZiuGqKELzUcPYkvFBu5cnH-lfYH4)


不对吧，你这是AI提供的答案么？我看了源码：Java 9 及以后版本，String、StringBuilder 和 StringBuffer 都使用 byte[] 数组存储字符串，并通过 coder 字段来标识编码方式 (LATIN1 或 UTF16)。

<img width="774" alt="image" src="https://github.com/user-attachments/assets/74a25e37-40fb-4dff-9dbd-be0d344a55b1">


<img width="935" alt="image" src="https://github.com/user-attachments/assets/78ded1aa-0efe-4762-bb1a-f13151eb0610">
