### ISSUE TITLE
ConcurrentHashMap 1.7 中 rehash 方法内部有两个 for 循环的原因

### ISSUE THREAD

**Issue by HoeYeungHo** [Snailclimb/JavaGuide#2524]
首先看到第二个`for`循环

```java
for (HashEntry<K,V> p = e; p != lastRun; p = p.next) {
    V v = p.value;
    int h = p.hash;
    int k = h & sizeMask;
    HashEntry<K,V> n = newTable[k];
    newTable[k] = new HashEntry<K,V>(h, p.key, v, n);
}
```

内部使用了`new HashEntry<K,V>(h, p.key, v, n)`创建了一个新的`HashEntry`，而不是复用之前的，是因为如果复用之前的，那么会导致正在遍历（如正在执行`get`方法）的线程由于指针的修改无法遍历下去。

> 当它们不再被可能正在并发遍历表的任何读取线程引用时，被替换的节点将被垃圾回收。
>
> The nodes they replace will be garbage collectable as soon as they are no longer referenced by any reader thread that may be in the midst of concurrently traversing table

为什么需要再使用一个`for`循环找到`lastRun`，其实是为了减少对象创建的次数，正如注解中所说的

> 从统计上看，在默认的阈值下，当表容量加倍时，只有大约六分之一的节点需要被克隆。
>
> Statistically, at the default threshold, only about one-sixth of them need cloning when a table doubles.

例如，扩容前的链表为这样，并且有另外一个线程正在访问

![扩容前](https://github.com/user-attachments/assets/71e19b1c-a6ed-48c9-bb05-d08fff5d5275)

在扩容时进行HashEntry的克隆，另外的线程还能继续遍历。

![扩容后](https://github.com/user-attachments/assets/96b10d34-2543-43be-b938-ca56b07191ce)

其中，绿色的为新创建的HashEntry。

**Comment by Snailclimb** [comment]
> 首先看到第二个`for`循环
> 
> ```java
> for (HashEntry<K,V> p = e; p != lastRun; p = p.next) {
>     V v = p.value;
>     int h = p.hash;
>     int k = h & sizeMask;
>     HashEntry<K,V> n = newTable[k];
>     newTable[k] = new HashEntry<K,V>(h, p.key, v, n);
> }
> ```
> 
> 内部使用了`new HashEntry<K,V>(h, p.key, v, n)`创建了一个新的`HashEntry`，而不是复用之前的，是因为如果复用之前的，那么会导致正在遍历（如正在执行`get`方法）的线程由于指针的修改无法遍历下去。
> 
> > 当它们不再被可能正在并发遍历表的任何读取线程引用时，被替换的节点将被垃圾回收。
> > The nodes they replace will be garbage collectable as soon as they are no longer referenced by any reader thread that may be in the midst of concurrently traversing table
> 
> 为什么需要再使用一个`for`循环找到`lastRun`，其实是为了减少对象创建的次数，正如注解中所说的
> 
> > 从统计上看，在默认的阈值下，当表容量加倍时，只有大约六分之一的节点需要被克隆。
> > Statistically, at the default threshold, only about one-sixth of them need cloning when a table doubles.
> 
> 例如，扩容前的链表为这样，并且有另外一个线程正在访问
> 
> ![扩容前](https://private-user-images.githubusercontent.com/60749707/383880124-71e19b1c-a6ed-48c9-bb05-d08fff5d5275.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5ODg3NzMsIm5iZiI6MTczMDk4ODQ3MywicGF0aCI6Ii82MDc0OTcwNy8zODM4ODAxMjQtNzFlMTliMWMtYTZlZC00OGM5LWJiMDUtZDA4ZmZmNWQ1Mjc1LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDE0MDc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZjk5NTViY2FmNGU2MWVhMTA1MGE0NmEyZDNmMTY5YzMxNTk1MGJhMTBiOTUzM2JiNTc2NmJiZDViZjMwNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dm_peV5FMSE8d36KrWDOB3SqxlFmYMTbSCCuk2hUhI8)
> 
> 在扩容时进行HashEntry的克隆，另外的线程还能继续遍历。
> 
> ![扩容后](https://private-user-images.githubusercontent.com/60749707/383880300-96b10d34-2543-43be-b938-ca56b07191ce.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5ODg3NzMsIm5iZiI6MTczMDk4ODQ3MywicGF0aCI6Ii82MDc0OTcwNy8zODM4ODAzMDAtOTZiMTBkMzQtMjU0My00M2JlLWI5MzgtY2E1NmIwNzE5MWNlLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDE0MDc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YmJmOTJlZmUzZmU4YmQ1NTdkYTJhNjE3NGVlNTBhMDdhNjZhOWY4ZGYwNzg1ZDMzYWJlOWRmOWIxNGY3MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sN6T-DDyfKTPU8Q7_3gpVK7Ded0WFc4S-RhT7FcgDLQ)
> 
> 其中，绿色的为新创建的HashEntry。

感谢补充，可以的话，欢迎提交一个PR完善下哈~
