### ISSUE TITLE
集合中使用`isEmpty()`判空利用`ConcurrentHashMap`的例子不合理

### ISSUE THREAD

**Issue by HoeYeungHo** [Snailclimb/JavaGuide#2525]
在`ConcurrentHashMap` 1.8中，`size()`方法和`isEmpty()`方法都会调用`sumCount()`方法，他们的时间复杂度均与`Node`数组的大小有关。更合适的例子应用使用`ConcurrentLinkedQueue`，其`isEmpty()`方法的时间复杂度近似为`O(1)`，而`size()`方法的时间复杂度为`o(n)`。

在`ConcurrentLinkedQueue`中，`isEmpty()`方法通过`first()`方法进行判断，其中`first()`方法返回的是队列中第一个值不为`null`的节点

```java
public boolean isEmpty() {
    return first() == null;
}

Node<E> first() {
    restartFromHead:
    for (;;) {
        for (Node<E> h = head, p = h, q;;) {
            boolean hasItem = (p.item != null);
            if (hasItem || (q = p.next) == null) {  // 当前节点值不为空 或 到达队尾
                updateHead(h, p);  // 将head设置为p
                return hasItem ? p : null;
            }
            else if (p == q) continue restartFromHead;
            else p = q;  // p = p.next
        }
    }
}
```

由于在插入与删除元素时，都会执行`updateHead(h, p)`方法，所以该方法的执行的时间复杂度可以近似为`O(1)`。而出现节点值为`null`的原因是在迭代器中使用的逻辑删除

```java
private class Itr implements Iterator<E> {

    public void remove() {
        Node<E> l = lastRet;
        if (l == null) throw new IllegalStateException();
        l.item = null;
        lastRet = null;
    }
}
```

而`size()`方法需要遍历整个链表，时间复杂度为$O(n)$

```java
public int size() {
    int count = 0;
    for (Node<E> p = first(); p != null; p = succ(p))
        if (p.item != null)
            if (++count == Integer.MAX_VALUE)
                break;
    return count;
}
```

此外，我认为可以说明`ConcurrentHashMap`是JDK 1.8中的，因为对于JDK 1.7，在`ConcurrentHashMap` 1.7中，将元素数量存储在每个`Segment`中，`size()` 方法需要统计每个`Segment`的数量，而`isEmpty()`只需要找到第一个不为空的`Segment`即可。

**Comment by Snailclimb** [comment]
> 在`ConcurrentHashMap` 1.8中，`size()`方法和`isEmpty()`方法都会调用`sumCount()`方法，他们的时间复杂度均与`Node`数组的大小有关。更合适的例子应用使用`ConcurrentLinkedQueue`，其`isEmpty()`方法的时间复杂度近似为`O(1)`，而`size()`方法的时间复杂度为`o(n)`。
> 
> 在`ConcurrentLinkedQueue`中，`isEmpty()`方法通过`first()`方法进行判断，其中`first()`方法返回的是队列中第一个值不为`null`的节点

感谢指出，欢迎提交PR完善一下哈~
