### ISSUE TITLE
外链的引用地址有问题

### ISSUE THREAD

**Issue by TlgYuri** [Snailclimb/JavaGuide#2528]
![image](https://github.com/user-attachments/assets/87d078d9-17f7-4e26-a86b-6b17ca2292f8)
![image](https://github.com/user-attachments/assets/8b89c4da-383d-4297-b9f9-d5aa5046a957)
《Java基础常见面试题总结(上)》里面的外链
文章《有关 JIT 的实现细节: JVM C1、C2 编译器》实际会跳转到《基于静态编译构建微服务应用》

**Comment by Snailclimb** [comment]
> 有关 JIT 的实现细节

感谢，补充两篇：

> - [基本功 | Java 即时编译器原理解析及实践 - 美团技术团队](https://tech.meituan.com/2020/10/22/java-jit-practice-in-meituan.html)
> - [基于静态编译构建微服务应用 - 阿里巴巴中间件](https://mp.weixin.qq.com/s/4haTyXUmh8m-dBQaEzwDJw)
