### ISSUE TITLE
Redis 过期 key 默认是定期删除

### ISSUE THREAD

**Issue by HoeYeungHo** [Snailclimb/JavaGuide#2536]
> Redis 采用的是 定期删除+惰性/懒汉式删除 结合的策略，这也是大部分缓存框架的选择。定期删除对内存更加友好，惰性删除对 CPU 更加友好。两者各有千秋，结合起来使用既能兼顾 CPU 友好，又能兼顾内存友好。

Redis 默认只开启了定期删除，惰性删除需要通过配置 `lazyfree-lazy-eviction yes` 开启。

![image](https://github.com/user-attachments/assets/eeddcdc2-a8e3-4642-a575-5577dccfe8f4)

**Comment by fox-half-tian** [comment]
这个配置你理解错了。以 Redis6.0 源码为例。

首先，懒惰删除是开启的，且不可配置，这就是一段写死了的代码，因为这是保证 key 过期删除的安全性的兜底方案。在获取之前会先判断是否过期，如果过期了，就释放删除。懒惰删除对应实现为 expireIfNeeded() 函数，如下图。

![image](https://github.com/user-attachments/assets/aefb3a37-921a-466f-9700-d8c2aeac73dd)


至于lazyfree-lazy-eviction参数的作用，主要是用于在内存淘汰策略中，当达到了最大内存限制，对于大 key 是否要异步删除。

![image](https://github.com/user-attachments/assets/2675b4e8-4dfa-4d80-9ccc-b9d823d6eb71)

我们继续追freeMemoryIfNeededAndSafe() 函数中的实现。如下图，可以看到如果开启了lazyfree-lazy-eviction即设为 yes，则调用 dbAsyncDelete() 方法来异步删除淘汰的大 key。
![image](https://github.com/user-attachments/assets/589dfde8-b0d0-4a15-894e-2a3325593164)

最后值得说明的是：

1. 在 dbAsyncDelete() 这个方法里，大 key 指的是 value 的大小，衡量的是 value 内存释放的工作量，有一个阈值是可以配置的。而 key，是无论如何都是会被同步删除的。
2. unlink 这个命令，最终也是调用的 dbAsyncDelete() 函数。
3. 所谓的异步删除，在 redis 的实现中，实际上是将删除大 value 的任务放到一个任务队列，然后由一个 bio 后台线程来删除。

**Comment by HoeYeungHo** [comment]
谢谢老哥！刚刚看了下源码和注释，发现是自己的问题！
