### ISSUE TITLE
缓存穿透使用布隆过滤器解决的描述是否有误

### ISSUE THREAD

**Issue by Fan223** [Snailclimb/JavaGuide#2538]
这里写的是把可能存在的请求的值放入布隆过滤器，不应该是 key 吗，我正是要通过 key 获取值，怎么先知道值是多少然后去判断，知道的话那不不用获取直接返回了，不应该是判断 key 存不存在，然后通过 key 去获取值
![image](https://github.com/user-attachments/assets/1476d76e-1e8e-46c7-bbfc-97e570c7d68d)

**Comment by fox-half-tian** [comment]
你说的 key-value 是双列集合里的概念，而 set、list、布隆过滤器这些是单列集合，存储的元素我们通常称为 “值”

**Comment by Snailclimb** [comment]
> 这里写的是把可能存在的请求的值放入布隆过滤器，不应该是 key 吗，我正是要通过 key 获取值，怎么先知道值是多少然后去判断，知道的话那不不用获取直接返回了，不应该是判断 key 存不存在，然后通过 key 去获取值 ![image](https://private-user-images.githubusercontent.com/91018044/387114945-1476d76e-1e8e-46c7-bbfc-97e570c7d68d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTkyNzIsIm5iZiI6MTczMTkxODk3MiwicGF0aCI6Ii85MTAxODA0NC8zODcxMTQ5NDUtMTQ3NmQ3NmUtMWU4ZS00NmM3LWJiZmMtOTdlNTcwYzdkNjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA4MzYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZGIyNTY3NTRiNWMzZjg3YTFiYjEzNDViYjEwNGNjNTNlMTFiN2ZiYzE3M2Y2YjNjNTRkMTU3YmNhMTk0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xANeaFA5OkWeBVYYsS0zzfUN9-hFP6f8Dk74s6hSS60)

这里的值其实也是指代的是对应的 key-value 。

**Comment by Fan223** [comment]
> > 这里写的是把可能存在的请求的值放入布隆过滤器，不应该是 key 吗，我正是要通过 key 获取值，怎么先知道值是多少然后去判断，知道的话那不不用获取直接返回了，不应该是判断 key 存不存在，然后通过 key 去获取值 ![image](https://private-user-images.githubusercontent.com/91018044/387114945-1476d76e-1e8e-46c7-bbfc-97e570c7d68d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTkyNzIsIm5iZiI6MTczMTkxODk3MiwicGF0aCI6Ii85MTAxODA0NC8zODcxMTQ5NDUtMTQ3NmQ3NmUtMWU4ZS00NmM3LWJiZmMtOTdlNTcwYzdkNjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA4MzYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZGIyNTY3NTRiNWMzZjg3YTFiYjEzNDViYjEwNGNjNTNlMTFiN2ZiYzE3M2Y2YjNjNTRkMTU3YmNhMTk0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xANeaFA5OkWeBVYYsS0zzfUN9-hFP6f8Dk74s6hSS60)
> 
> 这里的值其实也是指代的是对应的 key-value 。

就是从实现上来说，应该就是只把key放入布隆过滤器中吧，这里的 key-value，value 应该是不用管的。请求的值，比如我要请求用户的邮箱，值指的应该是具体的比如xxx@xxx.com，那我肯定不会把这个存入布隆过滤器，而是可能存user:email:id之类的，那么这里说的请求的值放入布隆过滤器是不是描述有点问题。
我知道表达的就是一个判断是否存在的意思，就是看上去感觉有点歧义，至少我第一眼看是感觉有点疑惑的，也可能有点抠字眼，理解不同。
还有前面那位说的布隆过滤器中描述为值，这个我觉得是没啥问题的，不过文中的“值”前面加了条件，请求的值，那么应该是先以前面的条件为准。如果把请求去掉，直接描述为把所有值放入布隆过滤器，这个“值”就能代表布隆过滤器里的值的意思，可能有点抠字眼，但是语义理解的话，应该是这样，个人感觉。
emm，也不用仔细考究这个，只是第一眼有点疑惑，从上下文和用法知道是这个意思就行
