### ISSUE TITLE
Redis在线环境链接打不开，地址疑似更换。

### ISSUE THREAD

**Issue by mjhxy** [Snailclimb/JavaGuide#2540]
在“Redis常见面试题总结(上)”中的“个人学习的话，你可以自己本机安装 Redis 或者通过 Redis 官网提供的[在线 Redis 环境](https://try.redis.io/)（少部分命令无法使用）来实际体验 Redis。”，链接无法访问，好像是官方换成了以下地址https://redis.io/try-free/ 
![image](https://github.com/user-attachments/assets/97dffb06-2c2e-4aa0-979d-dbefdc6d1396)

**Comment by Snailclimb** [comment]
> [在线 Redis 环境](https://try.redis.io/)（

这个网站已经关闭了貌似，我下次更新备注一下。
