### ISSUE TITLE
Invalid URL in 计算机网络常见面试题总结(上)

### ISSUE THREAD

**Issue by wickdynex** [Snailclimb/JavaGuide#2543]
### Invalid URL

<img width="1191" alt="image" src="https://github.com/user-attachments/assets/71382993-3ad3-437e-822d-3b9a7cae6d62">

[黑客技术？没你想象的那么难！——DNS 劫持篇](https://cloud.tencent.com/developer/article/1197474)

### Page

<img width="1437" alt="image" src="https://github.com/user-attachments/assets/72105857-9dae-467b-acb9-a07ddd87f508">

**Comment by Snailclimb** [comment]
> ### Invalid URL
> <img alt="image" width="1191" src="https://private-user-images.githubusercontent.com/149244585/390335729-71382993-3ad3-437e-822d-3b9a7cae6d62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NTg1NDcsIm5iZiI6MTczMjc1ODI0NywicGF0aCI6Ii8xNDkyNDQ1ODUvMzkwMzM1NzI5LTcxMzgyOTkzLTNhZDMtNDM3ZS04MjJkLTNiOWE3Y2FlNmQ2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwMTQ0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Yjk4NDc1OWRlNjlmODU0YTY2ODA0Zjc4ZGJlN2Y0YjZkODQwZDZkNjlhYzY0ODkwNzE4NDE4ZTIzN2U5M2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sFExSJ4K5ZreiCLipeHGc47glVToKieaQZ-jN5rn5ec">
> [黑客技术？没你想象的那么难！——DNS 劫持篇](https://cloud.tencent.com/developer/article/1197474)
> 
> ### Page
> <img alt="image" width="1437" src="https://private-user-images.githubusercontent.com/149244585/390336018-72105857-9dae-467b-acb9-a07ddd87f508.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NTg1NDcsIm5iZiI6MTczMjc1ODI0NywicGF0aCI6Ii8xNDkyNDQ1ODUvMzkwMzM2MDE4LTcyMTA1ODU3LTlkYWUtNDY3Yi1hY2I5LWEwN2RkZDg3ZjUwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwMTQ0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzMwNTI4N2NhMzUwMDVmNWVkZjE1ZWFkNjliNjExMzM4ZWExZTlkNjM4NTM4ZGNmYjhkOWVkMzI3ZTE2ZjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.62pL7QbgBd6PFK2NEok5Z3ub33bwVF1Nn6mlCuQDmto">

嗯嗯，这篇应该是原作者删除了👍
