### ISSUE TITLE
勘误 块的最常见的大小

### ISSUE THREAD

**Issue by Asong205** [Snailclimb/JavaGuide#2552]
文中提到：硬盘的最小存储单位是扇区(Sector)，块(block)由多个扇区组成。文件数据存储在块中。块的最常见的大小是 4kb，约为 8 个连续的扇区组成（每个扇区存储 512 字节）。
KB：通常指的是“千字节”（KiloByte），是数据存储的一个单位。1 KB 等于 1024 字节（Byte）。这是基于二进制的定义，因为计算机内部使用二进制系统。
kb（小写b）：虽然也可以用来表示数据大小，但在计算机科学中，它更常被用来表示“千比特”（KiloBit）。1 kb 等于 1024 比特（Bit）。比特是信息量的基本单位，一个字节包含8个比特。
因此：块的最常见的大小是 4kb ×  ；块的最常见的大小是 4KB √

**Comment by Asong205** [comment]
位置：https://javaguide.cn/cs-basics/operating-system/linux-intro.html#inode-%E4%BB%8B%E7%BB%8D

**Comment by Snailclimb** [comment]
> 文中提到：硬盘的最小存储单位是扇区(Sector)，块(block)由多个扇区组成。文件数据存储在块中。块的最常见的大小是 4kb，约为 8 个连续的扇区组成（每个扇区存储 512 字节）。 KB：通常指的是“千字节”（KiloByte），是数据存储的一个单位。1 KB 等于 1024 字节（Byte）。这是基于二进制的定义，因为计算机内部使用二进制系统。 kb（小写b）：虽然也可以用来表示数据大小，但在计算机科学中，它更常被用来表示“千比特”（KiloBit）。1 kb 等于 1024 比特（Bit）。比特是信息量的基本单位，一个字节包含8个比特。 因此：块的最常见的大小是 4kb × ；块的最常见的大小是 4KB √



> 文中提到：硬盘的最小存储单位是扇区(Sector)，块(block)由多个扇区组成。文件数据存储在块中。块的最常见的大小是 4kb，约为 8 个连续的扇区组成（每个扇区存储 512 字节）。 KB：通常指的是“千字节”（KiloByte），是数据存储的一个单位。1 KB 等于 1024 字节（Byte）。这是基于二进制的定义，因为计算机内部使用二进制系统。 kb（小写b）：虽然也可以用来表示数据大小，但在计算机科学中，它更常被用来表示“千比特”（KiloBit）。1 kb 等于 1024 比特（Bit）。比特是信息量的基本单位，一个字节包含8个比特。 因此：块的最常见的大小是 4kb × ；块的最常见的大小是 4KB √

感谢指出~
