### ISSUE TITLE
建议划分【协议】专栏

### ISSUE THREAD

**Issue by keepal7** [Snailclimb/JavaGuide#257]
您好，从目前项目中来看，关于协议HTTP、TCP/IP等协议内容比较分散。建议专门开放一个专栏讲述HTTP/HTTPS、TCP/IP、MQTT等常见协议。
当然这些协议内容大都比较庞大，而且有些协议在网上还存在一些争议，并且很难有清晰统一的版本，整理起来肯定也费时费力。
当然，这个项目主题是JAVA类知识点，协议似乎有些偏移了主题。但是不可否认这些常用的协议对我们完善知识架构体系的作用还是有的。
以上，希望您抽空考虑一下这个建议，如果有需要的话，我也希望能帮上您的忙。最近由于业务需求，我这边会去专门学习MQTT协议以及相关实现，需要的话，我在学习完后可以提供一个相关的入门级文档。
最后，感谢您及您的这个项目。

**Comment by Snailclimb** [comment]
嗯嗯  确实 协议这部分平时也没太注意，如果确实有必要的话，我觉得是不是可以将“协议”放在“网络”那一分类中？

**Comment by keepal7** [comment]
> 嗯嗯 确实 协议这部分平时也没太注意，如果确实有必要的话，我觉得是不是可以将“协议”放在“网络”那一分类中？

网络协议只是在我协议这个整体的一部分，不过我们平常接触的多的也是这些基础的网络协议，放在“网络”分类里也没有什么太大问题。同时我这边想了下，“协议”这个概念太大了，其实更具体一些好一点，比如网络协议。另外，协议这个东西整理起来真是费时费力，光是一个TCP/IP协议族就能整理好久，所以我这边的建议也有欠考虑。目前我觉得以JAVA核心知识点为主，然后在扩展过程中有涉及到“网络协议”模块的可以慢慢整合，慢慢更新。以上，是我这边的想法，您可以考虑下，如果有需要我很乐意能贡献一份力。

**Comment by Snailclimb** [comment]
嗯嗯 确实。我觉得协议这部分涉及的内容也是蛮多，我们可以考虑只把那些对于我们Java后端开发平时比较重要的总结一下，如果都总结的话可能就太耗时耗力了。我本人对着部分的了解也不是蛮多。如果你想总结的话，那就很感谢了。嘿嘿！

**Comment by Snailclimb** [comment]
> 嗯嗯 确实 协议这部分平时也没太注意，如果确实有必要的话，我觉得是不是可以将“协议”放在“网络”那一分类中？



> > 嗯嗯 确实 协议这部分平时也没太注意，如果确实有必要的话，我觉得是不是可以将“协议”放在“网络”那一分类中？
> 
> 网络协议只是在协议这个整体的一部分，不过我们平常接触的多的也是这些基础的网络协议，放在“网络”分类里也没有什么太大问题。同时我这边想了下，“协议”这个概念太大了，其实更具体一些好一点，比如网络协议。另外，协议这个东西整理起来真是费时费力，光是一个TCP/IP协议族就能整理好久，所以我这边的建议也有欠考虑。目前我觉得以JAVA核心知识点为主，然后在扩展过程中有涉及到“网络协议”模块的可以慢慢整合，慢慢更新。以上，是我这边的想法，您可以考虑下，如果有需要我很乐意能贡献一份力。

嗯嗯 确实。我觉得协议这部分涉及的内容也是蛮多，我们可以考虑只把那些对于我们Java后端开发平时比较重要的总结一下，如果都总结的话可能就太耗时耗力了。我本人对着部分的了解也不是蛮多。如果你想总结的话，那就很感谢了。嘿嘿！

**Comment by keepal7** [comment]
> > 嗯嗯 确实 协议这部分平时也没太注意，如果确实有必要的话，我觉得是不是可以将“协议”放在“网络”那一分类中？
> 
> > > 嗯嗯 确实 协议这部分平时也没太注意，如果确实有必要的话，我觉得是不是可以将“协议”放在“网络”那一分类中？
> > 
> > 
> > 网络协议只是在协议这个整体的一部分，不过我们平常接触的多的也是这些基础的网络协议，放在“网络”分类里也没有什么太大问题。同时我这边想了下，“协议”这个概念太大了，其实更具体一些好一点，比如网络协议。另外，协议这个东西整理起来真是费时费力，光是一个TCP/IP协议族就能整理好久，所以我这边的建议也有欠考虑。目前我觉得以JAVA核心知识点为主，然后在扩展过程中有涉及到“网络协议”模块的可以慢慢整合，慢慢更新。以上，是我这边的想法，您可以考虑下，如果有需要我很乐意能贡献一份力。
> 
> 嗯嗯 确实。我觉得协议这部分涉及的内容也是蛮多，我们可以考虑只把那些对于我们Java后端开发平时比较重要的总结一下，如果都总结的话可能就太耗时耗力了。我本人对着部分的了解也不是蛮多。如果你想总结的话，那就很感谢了。嘿嘿！

我可以尝试下整理一些协议基础内容，往深了去那就力所不能及啦，我先试试看，要是整理好了，再发您那边看下，要是能用就再好不过啦，要是达不到的话，就再继续学习总结下，不过这个整理的周期可能会有点长哦

**Comment by Snailclimb** [comment]
> > > 嗯嗯 确实 协议这部分平时也没太注意，如果确实有必要的话，我觉得是不是可以将“协议”放在“网络”那一分类中？
> > 
> > 
> > > > 嗯嗯 确实 协议这部分平时也没太注意，如果确实有必要的话，我觉得是不是可以将“协议”放在“网络”那一分类中？
> > > 
> > > 
> > > 网络协议只是在协议这个整体的一部分，不过我们平常接触的多的也是这些基础的网络协议，放在“网络”分类里也没有什么太大问题。同时我这边想了下，“协议”这个概念太大了，其实更具体一些好一点，比如网络协议。另外，协议这个东西整理起来真是费时费力，光是一个TCP/IP协议族就能整理好久，所以我这边的建议也有欠考虑。目前我觉得以JAVA核心知识点为主，然后在扩展过程中有涉及到“网络协议”模块的可以慢慢整合，慢慢更新。以上，是我这边的想法，您可以考虑下，如果有需要我很乐意能贡献一份力。
> > 
> > 
> > 嗯嗯 确实。我觉得协议这部分涉及的内容也是蛮多，我们可以考虑只把那些对于我们Java后端开发平时比较重要的总结一下，如果都总结的话可能就太耗时耗力了。我本人对着部分的了解也不是蛮多。如果你想总结的话，那就很感谢了。嘿嘿！
> 
> 我可以尝试下整理一些协议基础内容，往深了去那就力所不能及啦，我先试试看，要是整理好了，再发您那边看下，要是能用就再好不过啦，要是达不到的话，就再继续学习总结下，不过这个整理的周期可能会有点长哦

哈哈 没问题呀。不要耽误自己平时工作就好！到时候帮你完善，嘿嘿！

**Comment by keepal7** [comment]
> > > > 嗯嗯 确实 协议这部分平时也没太注意，如果确实有必要的话，我觉得是不是可以将“协议”放在“网络”那一分类中？
> > > 
> > > 
> > > > > 嗯嗯 确实 协议这部分平时也没太注意，如果确实有必要的话，我觉得是不是可以将“协议”放在“网络”那一分类中？
> > > > 
> > > > 
> > > > 网络协议只是在协议这个整体的一部分，不过我们平常接触的多的也是这些基础的网络协议，放在“网络”分类里也没有什么太大问题。同时我这边想了下，“协议”这个概念太大了，其实更具体一些好一点，比如网络协议。另外，协议这个东西整理起来真是费时费力，光是一个TCP/IP协议族就能整理好久，所以我这边的建议也有欠考虑。目前我觉得以JAVA核心知识点为主，然后在扩展过程中有涉及到“网络协议”模块的可以慢慢整合，慢慢更新。以上，是我这边的想法，您可以考虑下，如果有需要我很乐意能贡献一份力。
> > > 
> > > 
> > > 嗯嗯 确实。我觉得协议这部分涉及的内容也是蛮多，我们可以考虑只把那些对于我们Java后端开发平时比较重要的总结一下，如果都总结的话可能就太耗时耗力了。我本人对着部分的了解也不是蛮多。如果你想总结的话，那就很感谢了。嘿嘿！
> > 
> > 
> > 我可以尝试下整理一些协议基础内容，往深了去那就力所不能及啦，我先试试看，要是整理好了，再发您那边看下，要是能用就再好不过啦，要是达不到的话，就再继续学习总结下，不过这个整理的周期可能会有点长哦
> 
> 哈哈 没问题呀。不要耽误自己平时工作就好！到时候帮你完善，嘿嘿！

好嘞，我这边先抽空整理着，整理好了初稿我再通过微信或者邮箱发给您，这个issue就先关啦哦
