### ISSUE TITLE
fork之后链接失效

### ISSUE THREAD

**Issue by jsg1943** [Snailclimb/JavaGuide#258]
fork之后链接失效，如【多线程/并发容器总结】一文，链接会变成https://github.com/Snailclimb/JavaGuide/blob/master/Java/Multithread/%E5%B9%B6%E5%8F%91%E5%AE%B9%E5%99%A8%E6%80%BB%E7%BB%93.md
需要把链接中的Snailclimb改成自己的用户名才有效。

**Comment by Snailclimb** [comment]
你好 我觉得你可能fork的不是master分支，请 fork master分支。这个分支是最新的内容。
