### ISSUE TITLE
关于MySQL高性能优化规范建议-数据库基本设计规范-存储引擎的选择

### ISSUE THREAD

**Issue by jinyahuan** [Snailclimb/JavaGuide#268]
文中“1. 所有表必须使用 Innodb 存储引擎”，我认为是不合理的，如果不是非常重要（即不开事务也不影响功能的，比如文章的评论之类的）的表，且读多写少的完全可以用 myisam（~~还能压缩数据~~），但只要和业务逻辑或金钱相关的即使读多写少也确实要用 innodb.
[参考了这份文档](https://dev.mysql.com/doc/refman/5.7/en/optimizing-myisam.html)

其实官方提供了一份[优化文档](https://dev.mysql.com/doc/refman/5.7/en/optimization.html)（文档不是官方整理的--）,有空的话大家一起慢慢可以做份中文版的。

**Comment by oraoto** [comment]
[文档](https://dev.mysql.com/doc/refman/5.7/en/optimize-overview.html#optimize-database-level)说MyISAM只有只读的表才支持压缩，而InnoDB读写都支持：

>  Compression is available for all kinds of workloads with InnoDB tables, and for read-only MyISAM tables
