### ISSUE TITLE
Java基础知识18.2

### ISSUE THREAD

**Issue by yshch2008** [Snailclimb/JavaGuide#279]
从变量在内存中的存储方式来看:如果成员变量是使用static修饰的，那么这个成员变量是属于类的，如果没有使用使用static修饰，这个成员变量是属于实例的。而对象存在于堆内存，局部变量则存在于栈内存。

是不是说反了？

**Comment by Snailclimb** [comment]
> 从变量在内存中的存储方式来看:如果成员变量是使用static修饰的，那么这个成员变量是属于类的，如果没有使用使用static修饰，这个成员变量是属于实例的。而对象存在于堆内存，局部变量则存在于栈内存。
> 
> 是不是说反了？

应该没有问题吧？
