### ISSUE TITLE
建议添加一个Scrum的文章

### ISSUE THREAD

**Issue by BruceAn1978** [Snailclimb/JavaGuide#28]
这个文章很不错：https://www.jianshu.com/p/790bbce5f127。

图文表达很清晰，对概念的把握和理解很准确，建议添加到开发方法类别中。

**Comment by Snailclimb** [comment]
页面不存在了

**Comment by HiAscend** [comment]
@BruceAn1978 页面不存在了，请更新页面。

**Comment by BruceAn1978** [comment]
https://www.jianshu.com/p/dd450558b65e
