### ISSUE TITLE
hashMap 中的新元素是加入 是头插法吗? 个人觉得是尾插法

### ISSUE THREAD

**Issue by wenchaomartin** [Snailclimb/JavaGuide#280]
应该是尾插发 .
jdk  部分源码 1.8 

            else {
//计数 hash冲突中 链表中的元素多少个
                for (int binCount = 0; ; ++binCount) {
// 核心代码  p 是  计算出来的第一个节点  
                    if ((e = p.next) == null) {
//知道链表的最后一个元素.创建新节点. // 头插法说不通 node .next == null 
                        p.next = newNode(hash, key, value, null);
                        if (binCount >= TREEIFY_THRESHOLD - 1) // -1 for 1st
                            treeifyBin(tab, hash);
                        break;
                    }
                    if (e.hash == hash &&
                        ((k = e.key) == key || (key != null && key.equals(k))))
                        break;
// p e 想交换 .达到计数和循环遍历的结果
                    p = e;
                }
            }

**Comment by Snailclimb** [comment]
> 应该是尾插发 .
> jdk 部分源码 1.8
> 
> ```
>         else {
> ```
> //计数 hash冲突中 链表中的元素多少个
> for (int binCount = 0; ; ++binCount) {
> // 核心代码 p 是 计算出来的第一个节点
> if ((e = p.next) == null) {
> //知道链表的最后一个元素.创建新节点. // 头插法说不通 node .next == null
> p.next = newNode(hash, key, value, null);
> if (binCount >= TREEIFY_THRESHOLD - 1) // -1 for 1st
> treeifyBin(tab, hash);
> break;
> }
> if (e.hash == hash &&
> ((k = e.key) == key || (key != null && key.equals(k))))
> break;
> // p e 想交换 .达到计数和循环遍历的结果
> p = e;
> }
> }

这个内容在什么位置的呢？

**Comment by wenchaomartin** [comment]
jdk 1.8 hashMap 中的put 核心代码.
    final V putVal(int hash, K key, V value, boolean onlyIfAbsent,
                   boolean evict) {
        Node<K,V>[] tab; Node<K,V> p; int n, i;
// 判断 数组中是否为empty .然后扩容
        if ((tab = table) == null || (n = tab.length) == 0)
            n = (tab = resize()).length;
//通过 计算获得数组中的下标 ,判断此下标中是否有节点. 没有新增一个一个next==null 的节点
        if ((p = tab[i = (n - 1) & hash]) == null)
            tab[i] = newNode(hash, key, value, null);
        else {
// 如果吃下标中有节点
            Node<K,V> e; K k;
//判断 此节点的hash 与  即将插入的节点的hash 是否一致.  如果是 哈希相同 key的值一致,则覆盖value.
            if (p.hash == hash &&
                ((k = p.key) == key || (key != null && key.equals(k))))
                e = p;

            else if (p instanceof TreeNode)
                e = ((TreeNode<K,V>)p).putTreeVal(this, tab, hash, key, value);
            else {
//key 不相同 则循环计数 
                for (int binCount = 0; ; ++binCount) {
p是数组的第一个节点. 
                    if ((e = p.next) == null) {
//尾插 一个新节点.
                        p.next = newNode(hash, key, value, null);
//大于一定数量, 转化造成红黑树插入 没有研究代码.
                        if (binCount >= TREEIFY_THRESHOLD - 1) // -1 for 1st
                            treeifyBin(tab, hash);
                        break;
                    }
/找到 hash 相同 key 相同. 跳出循环.
                    if (e.hash == hash &&
                        ((k = e.key) == key || (key != null && key.equals(k))))
                        break;
                    p = e;
                }
            }
//找到 hash key 相同的那个节点.
            if (e != null) { // existing mapping for key
//换掉值.
                V oldValue = e.value;
                if (!onlyIfAbsent || oldValue == null)
                    e.value = value;
                afterNodeAccess(e);
                return oldValue;
            }
        }
        ++modCount;
        if (++size > threshold)
            resize();
        afterNodeInsertion(evict);
        return null;
    }
至于这样的插入一个新元素.
现在只考虑是hash冲突时  链表节点小于8的情况.

它是 比较  hash  和 key 是否相同
二者都是相同则 是 跳出循环计数 ,覆盖节点的value .(即是 找个之前的那个值相同的节点. 新值覆盖)
key 不同则是 循环 到最后一个最后一个节点.
尾加一个新的节点..

conclusion :
 在 hash冲突时(即是数组的槽被占了) 遍历计数链表的数目. 大于8 变成红黑树结构.
小于8 则看 链表中是否有hash 相同 ,key的eqals相同节点. 如有 .则覆盖.
没有且链表数目小于的则是 尾部加入新节点...

**Comment by wenchaomartin** [comment]
@Snailclimb

**Comment by Snailclimb** [comment]
> 应该是尾插发 .
> jdk 部分源码 1.8
> 
> ```
>         else {
> ```
> //计数 hash冲突中 链表中的元素多少个
> for (int binCount = 0; ; ++binCount) {
> // 核心代码 p 是 计算出来的第一个节点
> if ((e = p.next) == null) {
> //知道链表的最后一个元素.创建新节点. // 头插法说不通 node .next == null
> p.next = newNode(hash, key, value, null);
> if (binCount >= TREEIFY_THRESHOLD - 1) // -1 for 1st
> treeifyBin(tab, hash);
> break;
> }
> if (e.hash == hash &&
> ((k = e.key) == key || (key != null && key.equals(k))))
> break;
> // p e 想交换 .达到计数和循环遍历的结果
> p = e;
> }
> }

1.8 以后好像才是尾插法。我上面好像已经注明了？
