### ISSUE TITLE
搞定JVM垃圾回收就是这么简单.md 内容有遗漏

### ISSUE THREAD

**Issue by xinghuoxg** [Snailclimb/JavaGuide#285]
[搞定JVM垃圾回收就是这么简单.md](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/%E6%90%9E%E5%AE%9AJVM%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6%E5%B0%B1%E6%98%AF%E8%BF%99%E4%B9%88%E7%AE%80%E5%8D%95.md)这篇文章里
section1, 年轻代Survivor区满了之后如何处理，对部分描述有遗漏

**Comment by Snailclimb** [comment]
> [搞定JVM垃圾回收就是这么简单.md](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/%E6%90%9E%E5%AE%9AJVM%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6%E5%B0%B1%E6%98%AF%E8%BF%99%E4%B9%88%E7%AE%80%E5%8D%95.md)这篇文章里
> section1, 年轻代Survivor区满了之后如何处理，对部分描述有遗漏

可以提一个PR吗？我还没搞清你的意思，不好意思。

**Comment by xinghuoxg** [comment]
已提PR
