### ISSUE TITLE
有点不走心啊

### ISSUE THREAD

**Issue by YuKongEr** [Snailclimb/JavaGuide#29]
![image](https://user-images.githubusercontent.com/23350349/45858161-a1a8cc80-bd8e-11e8-98e6-15b5f9ad6918.png)

这个解释是什么东西啊，有点误导人

**Comment by YuKongEr** [comment]
建议这种代码用`final`  代码行标识

**Comment by Snailclimb** [comment]
不好意思。 有些地方确实不完善， 感谢您的指导！我大概今天之前改正 ，然后重新书写这部分内容！现在还有些重要的事情要完成！请见谅！

**Comment by YuKongEr** [comment]
![image](https://user-images.githubusercontent.com/23350349/45858452-0add0f80-bd90-11e8-8d76-84f2ed00ed6f.png)
这个应该是描述错误可以改正一下

**Comment by HiAscend** [comment]
> ![image](https://user-images.githubusercontent.com/23350349/45858161-a1a8cc80-bd8e-11e8-98e6-15b5f9ad6918.png)
> 
> 这个解释是什么东西啊，有点误导人

这是哪篇MD的内容？能写清楚么？
