### ISSUE TITLE
数据库资料缺乏一个基础sql书籍，我觉得《sql基础教程》不错，另外有关sql规范也可以介绍下

### ISSUE THREAD

**Issue by AlexanderJan** [Snailclimb/JavaGuide#290]

**Comment by Snailclimb** [comment]
感谢建议，已经更新在这里：https://github.com/Snailclimb/JavaGuide/edit/master/docs/database/MySQL.md

**Comment by Snailclimb** [comment]
感谢建议，已经更新：https://github.com/Snailclimb/JavaGuide/blob/master/docs/database/MySQL.md。
sql规范可以参考：https://github.com/Snailclimb/JavaGuide/blob/master/docs/database/MySQL%E9%AB%98%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96%E8%A7%84%E8%8C%83%E5%BB%BA%E8%AE%AE.md
