### ISSUE TITLE
JVM文章知识点疑问

### ISSUE THREAD

**Issue by kinglaw1204** [Snailclimb/JavaGuide#292]
文章提到：JDK1.7及之后版本的 JVM 已经将运行时常量池从方法区中移了出来，在 Java 堆（Heap）中开辟了一块区域存放运行时常量池。

我查了Java虚拟机规范文档1.7-12的文档都是说常量池内存从方法区分配。原文如下：
Each run-time constant pool is allocated from the Java Virtual Machine's method area 。
链接如下：https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-2.html#jvms-2.5.5

所以这里是不是某个特殊的虚拟机移除了，这里最好说明下，不然可能会误导。

**Comment by Snailclimb** [comment]
老哥  你好啊！JDK1.7及之后版本的 JVM 已经将运行时常量池确实从方法区中移了出来，在 Java 堆（Heap）中开辟了一块区域存放运行时常量池。一般文章如果没有特殊说明都是针对HotSpot虚拟机。就比如方法区这个概念是所有虚拟机都具有的概念，而永久代是HotSpot虚拟机对方法区这个概念实现，只在HotSpot虚拟机中有。
我觉得问题在于官方文档给的是整个虚拟机层面的，而我们平时研究的一般是HotSpot虚拟机，毕竟这个我们用的比较多。可以看一下《实战Java虚拟机》和《深入理解Java虚拟机：JVM高级特性与最佳实践》

**Comment by Snailclimb** [comment]
> 文章提到：JDK1.7及之后版本的 JVM 已经将运行时常量池从方法区中移了出来，在 Java 堆（Heap）中开辟了一块区域存放运行时常量池。
> 
> 我查了Java虚拟机规范文档1.7-12的文档都是说常量池内存从方法区分配。原文如下：
> Each run-time constant pool is allocated from the Java Virtual Machine's method area 。
> 链接如下：https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-2.html#jvms-2.5.5
> 
> 所以这里是不是某个特殊的虚拟机移除了，这里最好说明下，不然可能会误导。

老哥 你好啊！一般情况下没有特殊说明都是指的是HotSpot虚拟机，毕竟我们研究的就是这个虚拟机。我觉得官方文档给的是整个JVM设计层面的，就比如官方文档:https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-2.html#jvms-2.5.4 中并没有提到方法区被移除，但是实际上JDK 1.8 的时候，方法区（HotSpot的永久代）被彻底移除了（JDK1.7就已经开始了），取而代之是元空间，元空间使用的是直接内存。

总结：我觉得问题在于官方文档给的是整个虚拟机层面的，而我们平时研究的一般是HotSpot虚拟机，毕竟这个我们用的比较多。可以看一下《实战Java虚拟机》和《深入理解Java虚拟机：JVM高级特性与最佳实践》

**Comment by kinglaw1204** [comment]
我找到了Hot Spot 虚拟机的[jeps122](http://openjdk.java.net/jeps/122),里面是提到了hotspot 虚拟机移除永久代（方法区），把永久代中的三大块内容，类元数据，字符串，类的静态数据进行了转移，类元数据转移到本地内存，而字符串和类的静态数据转移到了堆内存，也确实是常量池转移到了堆内存。

**Comment by jee2017** [comment]
结合上面和文章中的图，我的理解是jdk1.8后运行时常量池里面 属于字面量部分 的字符串和类的静态数据转移到了堆内存，而剩下的属于符号引用部分的类元数据转移到元空间。   那么文中的这句话 ：JDK1.7及之后版本的 JVM 已经将运行时常量池从方法区中移了出来，在 Java 堆（Heap）中开辟了一块区域存放运行时常量池。    这里的运行时常量池是不是应该替换成字符串常量池比较合适？

**Comment by jee2017** [comment]
文章提到：JDK1.7以及之后的处理方式是在常量池中记录此字符串的引用，并返回该引用
JDK1.8常量池应该也是保存字符串对象的吧？
