### ISSUE TITLE
uniqueInstance 中 volatile解释问题

### ISSUE THREAD

**Issue by Xiaoyang-Zhu** [Snailclimb/JavaGuide#293]
有一个问题，就是在 [synchronized关键字里面的](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Multithread/JavaConcurrencyAdvancedCommonInterviewQuestions.md) 单例模式的代码中，解释到 uniqueInstance “使用 volatile 可以禁止 JVM 的指令重排，保证在多线程环境下也能正常运行“，但是代码里 new Singleton() 本身就被 synchronized修释了，也就是说，不会被多线程同时执行。所以，我认为这里的解释应是， 使用 volatile 可以保证 变量 uniqueInstance的可见性 （一个线程更新后，另一个线程会马上知道内容变了），而不是顺序性（JVM指令重排）。

_Originally posted by @Xiaoyang-Zhu in https://github.com/Snailclimb/JavaGuide/issues/178#issuecomment-487372424_

**Comment by jinyahuan** [comment]
我感觉你理解错了，``` volatile ```关键字的可见性，只确保取值时是最新的，如果线程X已经取了某个值A了，后来某个线程Y将其变成值B，那么线程X取的还是值A，除非你重新取值，不会变成最新的值。CAS就是因为这个原因所以才有ABA问题。而不是``` 一个线程更新后，另一个线程会马上知道内容变了） ```。

更多内容（为什么``` volatile ```限制指令重排序的原理等等）看这个博文[就是要你懂Java中volatile关键字实现原理](https://www.cnblogs.com/xrq730/p/7048693.html)

**Comment by Xiaoyang-Zhu** [comment]
那么我们先不说可见性的问题，因为new操作本身就在synchronized里，就保证了有也只有一个线程在执行，为什么还要说保证JVM指令重排呢，就算它不保证JVM指令重排，也能保证线程安全啊？这个怎么解释？

**Comment by jinyahuan** [comment]
对的，但是``` synchronized ```能保证被包裹的语句块有序，但是案例是语句块，不是用在方法上，所以并发时，只要在还没遇到``` synchronized ```语句块，其它互不相干的语句块都有可能被重排序，不过案例上因为没有其它语句所以怪怪的。

比如你加上最简单的操作
``` java
    public static Singleton getUniqueInstance() {
       //先判断对象是否已经实例过，没有实例化过才进入加锁代码
        if (uniqueInstance == null) {
            System.out.println("a");
            System.out.println("b");

            // 以上的操作有可能被重排序
            //类对象加锁
            synchronized (Singleton.class) {
                if (uniqueInstance == null) {
                    uniqueInstance = new Singleton();
                }
            }
        }
        return uniqueInstance;
    }
```

**Comment by Xiaoyang-Zhu** [comment]
这点我明白，但他的解释是 volatile是保证 new Singleton操作中的三个子操作的有序性？ 我是说，因为new操作本身就在synchronized块里，所以保不保证三个子操作的有序性，是完全没必要，你能明白我的意思吗？

**Comment by jinyahuan** [comment]
嗯，明白，我觉得是防止进入``` synchronized ```块之前有其它的实例化操作之类的，虽然感觉很不可能--

**Comment by Xiaoyang-Zhu** [comment]
volatile的主要功能就是 可见性 和 有序性嘛，这是毋庸置疑的，我是说，他这里在单例模式中加 volatile 的解释好像不是很合适。本来在synchronized中的代码是只有一个线程的，所以有序性是可保证可不保证的，如果加在单例模式中加 volatile不是因为他解释的有序性的话，那么我认为八成就是 可见性了，可能我开始解释的有些问题，但好像是比较合理的解释了，你觉得呢？

**Comment by jinyahuan** [comment]
嗯，同意。
貌似确实没用，如果只是为了这一次实例化类用了``` volatile ```也太大材小用了。。。

**Comment by pHraySc** [comment]
这里就是为了禁止指令重排序哈。因为DCL有两次if(instance == null)都判断，而instance = new Singleton();在实现上有3个步骤：
1.在堆上开辟内存空间，分配内存地址给Singleton这个对象；
2.赋初值，也就是类加载中的准备和初始化等过程；
3.将instance引用指向堆上的这个对象的地址。
public static Singleton getInstance4() {
if (instance2 == null) { // 1
synchronized (Singleton.class) {
if (instance2 == null) {
instance2 = new Singleton();
}
        }
    }
return instance;
}
这里重点看1注释位置，如果A线程进行synchronized同步快，在未加volatile情况下，上面的3个步骤以1、3、2顺序进行，对A线程是没有影响，因为同步快里面只有A线程拿到了锁，
但！！！如果此时B线程调用了getInstance4（）这个方法，你想想，是否就直接判断instance不为null（因为已经将instance指向了堆上的Singleton对象的地址了），所以进行return instance这一步，此时B线程获取到的实例instance根本没有获取到一个完全初始化的对象，也就是说对象里面的类变量，实例变量，常量，都还没有赋初值，那么程序必然报错。
所以...





在 2019-05-02 18:50:57，"Homer" <notifications@github.com> 写道：


嗯，明白，我觉得是防止进入synchronized块之前有其它的实例化操作之类的，虽然感觉很不可能--

**Comment by jinyahuan** [comment]
> 这里就是为了禁止指令重排序哈。因为DCL有两次if(instance == null)都判断，而instance = new Singleton();在实现上有3个步骤： 1.在堆上开辟内存空间，分配内存地址给Singleton这个对象； 2.赋初值，也就是类加载中的准备和初始化等过程； 3.将instance引用指向堆上的这个对象的地址。 public static Singleton getInstance4() { if (instance2 == null) { // 1 synchronized (Singleton.class) { if (instance2 == null) { instance2 = new Singleton(); } } } return instance; } 这里重点看1注释位置，如果A线程进行synchronized同步快，在未加volatile情况下，上面的3个步骤以1、3、2顺序进行，对A线程是没有影响，因为同步快里面只有A线程拿到了锁， 但！！！如果此时B线程调用了getInstance4（）这个方法，你想想，是否就直接判断instance不为null（因为已经将instance指向了堆上的Singleton对象的地址了），所以进行return instance这一步，此时B线程获取到的实例instance根本没有获取到一个完全初始化的对象，也就是说对象里面的类变量，实例变量，常量，都还没有赋初值，那么程序必然报错。 所以... 在 2019-05-02 18:50:57，"Homer" <notifications@github.com> 写道： 嗯，明白，我觉得是防止进入synchronized块之前有其它的实例化操作之类的，虽然感觉很不可能-- — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

为了寻找真理重新找了 jls --。看 [jls8, 17.4.5 Happens-before Order, (652页)](https://docs.oracle.com/javase/specs/jls/se8/jls8.pdf)。里面有句``` The default initialization of any object happens-before any other actions (other than default-writes) of a program. ```，这句话就说明当执行操作时，这个对象已经分配了内存了，也就不存在步骤1了

**Comment by pHraySc** [comment]
额，先行发生是内存模型的概念，应该不是在这里运用的。看看 深入jvm虚拟机396页呢。




| |
沈诚
邮箱：sc_19951214@126.com
|

签名由 网易邮箱大师 定制

在2019年05月03日 09:17，Homer 写道：

这里就是为了禁止指令重排序哈。因为DCL有两次if(instance == null)都判断，而instance = new Singleton();在实现上有3个步骤： 1.在堆上开辟内存空间，分配内存地址给Singleton这个对象； 2.赋初值，也就是类加载中的准备和初始化等过程； 3.将instance引用指向堆上的这个对象的地址。 public static Singleton getInstance4() { if (instance2 == null) { // 1 synchronized (Singleton.class) { if (instance2 == null) { instance2 = new Singleton(); } } } return instance; } 这里重点看1注释位置，如果A线程进行synchronized同步快，在未加volatile情况下，上面的3个步骤以1、3、2顺序进行，对A线程是没有影响，因为同步快里面只有A线程拿到了锁， 但！！！如果此时B线程调用了getInstance4（）这个方法，你想想，是否就直接判断instance不为null（因为已经将instance指向了堆上的Singleton对象的地址了），所以进行return instance这一步，此时B线程获取到的实例instance根本没有获取到一个完全初始化的对象，也就是说对象里面的类变量，实例变量，常量，都还没有赋初值，那么程序必然报错。 所以... 在 2019-05-02 18:50:57，"Homer" notifications@github.com 写道： 嗯，明白，我觉得是防止进入synchronized块之前有其它的实例化操作之类的，虽然感觉很不可能-- — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

为了寻找真理重新找了 jls --。看 jls8, 17.4.5 Happens-before Order, (652页)。里面有句The default initialization of any object happens-before any other actions (other than default-writes) of a program.，这句话就说明当执行操作时，这个对象已经分配了内存了，也就不存在步骤1了

**Comment by jinyahuan** [comment]
。。。首先，那个变量是``` static ```的，也就是 jvm 启动完后，这个变量就已经初始化了，只不过没有最终的指向而已。我等下看下类加载机制得了，算是复习一遍--

**Comment by Xiaoyang-Zhu** [comment]
明白了，是要防止在初始化对象前，对这个instance的引用。

**Comment by Xiaoyang-Zhu** [comment]
@pHraySc 不过，你这个第2步也有些问题：“2.赋初值，也就是类加载中的准备和初始化等过程；”  类加载其实在为对象分配内存之前，这里的 2 应该是赋初值初始化对象。并不是类加载。

**Comment by jinyahuan** [comment]
[jvms8, 5.5 Initialization, (357页开始)](https://docs.oracle.com/javase/specs/jvms/se8/jvms8.pdf)
我简单说下我的理解：当 jvm 执行``` new ```或调用 static 方法，get/set 静态 filed 时，如果该类没有初始化则会初始化该类/接口，执行类/接口的初始化时会上同步锁（只能有一个线程进行初始化，其它线程会中断初始化，并重复此过程直到被通知初始化成功），...其它处理略，然后执行 initialization method，然后初始化完，通知其它线程，然后解锁。

所以不会出现半成品的初始化！

**Comment by pHraySc** [comment]
这里我指的获取到没有初始化完全的对象给这个实例是在初始化外部获取这个对象的情况，当然一个类在初始化时，肯定是单线程的，但不代表在一个线程初始化类的过程中另一个线程不能获得这个正在初始化类的引用。也正是因为静态类的加载是单线程，因此单机模式建议使用静态内部类的方式安全的获取单例的实例。




| |
沈诚
邮箱：sc_19951214@126.com
|

签名由 网易邮箱大师 定制

在2019年05月03日 18:49，Homer 写道：

jvms8, 5.5 Initialization, (357页开始)
我简单说下我的理解：当 jvm 执行new或调用 static 方法，get/set 静态 filed 时，如果该类没有初始化则会初始化该类/接口，执行类/接口的初始化时会上同步锁（只能有一个线程进行初始化，其它线程会中断初始化，并重复此过程直到被通知初始化成功），...其它处理略，然后执行 initialization method，然后初始化完，通知其它线程，然后解锁。

所以不会出现半成品的初始化！

**Comment by jinyahuan** [comment]
你仔细看就知道了
```
For each class or interface C, there is a unique initialization lock LC. The mapping from C to LC is left to the discretion of the Java Virtual Machine implementation.
For example, LC could be the Class object for C, or the monitor associated with that Class object. 
```
这段，不知道我有没有理解错，就是是锁整个类。

**Comment by jinyahuan** [comment]
不纠结这个锁了，刚才看了字节码，确定了刚才的新想法
``` java
         L9 {
             new cn/jinyahuan/classroom/course/java/thread/Singleton
             dup
             invokespecial cn/jinyahuan/classroom/course/java/thread/Singleton.<init>()V
             putstatic cn/jinyahuan/classroom/course/java/thread/Singleton.uniqueInstance:cn.jinyahuan.classroom.course.java.thread.Singleton
         }
```
static 字段 new 完后还要执行 putstatic 才会到常量池，在此之前还是默认值 null.

**Comment by ArvinDevel** [comment]
> > 这里就是为了禁止指令重排序哈。因为DCL有两次if(instance == null)都判断，而instance = new Singleton();在实现上有3个步骤： 1.在堆上开辟内存空间，分配内存地址给Singleton这个对象； 2.赋初值，也就是类加载中的准备和初始化等过程； 3.将instance引用指向堆上的这个对象的地址。 public static Singleton getInstance4() { if (instance2 == null) { // 1 synchronized (Singleton.class) { if (instance2 == null) { instance2 = new Singleton(); } } } return instance; } 这里重点看1注释位置，如果A线程进行synchronized同步快，在未加volatile情况下，上面的3个步骤以1、3、2顺序进行，对A线程是没有影响，因为同步快里面只有A线程拿到了锁， 但！！！如果此时B线程调用了getInstance4（）这个方法，你想想，是否就直接判断instance不为null（因为已经将instance指向了堆上的Singleton对象的地址了），所以进行return instance这一步，此时B线程获取到的实例instance根本没有获取到一个完全初始化的对象，也就是说对象里面的类变量，实例变量，常量，都还没有赋初值，那么程序必然报错。 所以... 在 2019-05-02 18:50:57，"Homer" [notifications@github.com](mailto:notifications@github.com) 写道： 嗯，明白，我觉得是防止进入synchronized块之前有其它的实例化操作之类的，虽然感觉很不可能-- — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 为了寻找真理重新找了 jls --。看 [jls8, 17.4.5 Happens-before Order, (652页)](https://docs.oracle.com/javase/specs/jls/se8/jls8.pdf)。里面有句`The default initialization of any object happens-before any other actions (other than default-writes) of a program.`，这句话就说明当执行操作时，这个对象已经分配了内存了，也就不存在步骤123顺序有问题了。
>
>
创建对象应该定义为4步：
1.allocate memory
2.default initialization
3.constructor initialization
4.assign to reference and return
这个default initialization过程紧邻着分配内存，并且保证了和后序读的happens-before关系，但第三步和第四步间的关系可能会被优化为乱序。
详见jls中的对象创建过程[jls8-12章5小节](https://docs.oracle.com/javase/specs/jls/se8/jls8.pdf)

**Comment by jinyahuan** [comment]
正好复习到了，重新总结下：
[代码还是上面的那个类](https://github.com/Snailclimb/JavaGuide/issues/293#issuecomment-489128992)，下面是用javap -c 反编译后的字节码：
```
public class Singleton {
  public static Singleton getUniqueInstance();
    Code:
       0: getstatic     #2                  // Field uniqueInstance:LSingleton;
       3: ifnonnull     37
       6: ldc           #3                  // class Singleton
       8: dup
       9: astore_0
      10: monitorenter
      11: getstatic     #2                  // Field uniqueInstance:LSingleton;
      14: ifnonnull     27
      17: new           #3                  // class Singleton
      20: dup
      21: invokespecial #4                  // Method "<init>":()V
      24: putstatic     #2                  // Field uniqueInstance:LSingleton;
      27: aload_0
      28: monitorexit
      29: goto          37
      32: astore_1
      33: aload_0
      34: monitorexit
      35: aload_1
      36: athrow
      37: getstatic     #2                  // Field uniqueInstance:LSingleton;
      40: areturn
    Exception table:
       from    to  target type
          11    29    32   any
          32    35    32   any
}
```

拿出最关键的几句指令：
```
      17: new           #3                  // class Singleton
      20: dup
      21: invokespecial #4                  // Method "<init>":()V
      24: putstatic     #2                  // Field uniqueInstance:LSingleton;
```
new 是分配内存，创建对象（并初始化默认值），并将引用地址压入栈顶
dup 是复制栈顶元素，并压入栈顶，也就是栈最上面两个元素就是 Singleton 对象的引用

然后到了最关键的地方了，下面这两个指令单线程下可以乱序指令，因为结果是一样的，但是多线程下，如果先执行了putstatic指令，那么静态字段uniqueInstance就有半初始化状态（也就是 new 指令后）的引用地址了，已经不为null了：
invokespecial 调用实例化相关的方法，这里会消耗掉一份栈顶的元素，也就是 Singleton 对象的引用
putstatic 给指定的静态字段uniqueInstance赋值，这里会消耗掉一份栈顶的元素，也就是 Singleton 对象的引用

觉得有收获的话，赞起来！

**Comment by jinyahuan** [comment]
@Snailclimb 这个问题说的原文的解释是有问题的
[可以参考这个](https://github.com/Snailclimb/JavaGuide/issues/293#issuecomment-687618396)，jvms，jls，修正下
