### ISSUE TITLE
Java面试突击-V3.0，错别字

### ISSUE THREAD

**Issue by OneKe** [Snailclimb/JavaGuide#294]
6.8 redis 持久化机制（怎么保证 redis 挂掉之后再重启数据可以进行恢复）
1.在第一句  应该是 恢复数据 不是 回复数据。
2.AOF重写是一个有歧义的名字，该功能是通过读取数据库中的键值对来实现的，程序无须对现有AOF文件进行任伺读入、分析或者写入操作。（应该是‘任何’）

**Comment by Snailclimb** [comment]
感谢您指出错别字，非常感谢！建议下次可以提PR，这样比较方便。

**Comment by Snailclimb** [comment]
> 6.8 redis 持久化机制（怎么保证 redis 挂掉之后再重启数据可以进行恢复）
> 1.在第一句 应该是 恢复数据 不是 回复数据。
> 2.AOF重写是一个有歧义的名字，该功能是通过读取数据库中的键值对来实现的，程序无须对现有AOF文件进行任伺读入、分析或者写入操作。（应该是‘任何’）

怎么保证 redis 挂掉之后再重启数据可以进行恢复
