### ISSUE TITLE
17. 接口和抽象类的区别是什么？ 第4点有歧义

### ISSUE THREAD

**Issue by q920447939** [Snailclimb/JavaGuide#295]
地址: https://snailclimb.top/JavaGuide/#/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86?id=_17-%E6%8E%A5%E5%8F%A3%E5%92%8C%E6%8A%BD%E8%B1%A1%E7%B1%BB%E7%9A%84%E5%8C%BA%E5%88%AB%E6%98%AF%E4%BB%80%E4%B9%88%EF%BC%9F

4.一个类实现接口的话要实现接口的所有方法，而抽象类不一定。
我做了一个实验: 如果Bclass 不实现check()方法那么编译不通过

```java
class  Bclass extends  Aclass {
    @Override
    String dosomething() {
        return null;
    }

}

abstract class Aclass {
    abstract String dosomething();
    abstract String check();

    public void say () {

    }
}

```

**Comment by Snailclimb** [comment]
已经做了修改，感谢！
