### ISSUE TITLE
图挂了 

### ISSUE THREAD

**Issue by changdy** [Snailclimb/JavaGuide#304]
https://github.com/Snailclimb/JavaGuide/blob/15fc507affc141e905573210241ba5d3d616080f/docs/java/%E5%8F%AF%E8%83%BD%E6%98%AF%E6%8A%8AJava%E5%86%85%E5%AD%98%E5%8C%BA%E5%9F%9F%E8%AE%B2%E7%9A%84%E6%9C%80%E6%B8%85%E6%A5%9A%E7%9A%84%E4%B8%80%E7%AF%87%E6%96%87%E7%AB%A0.md#%E4%BA%8C-%E8%BF%90%E8%A1%8C%E6%97%B6%E6%95%B0%E6%8D%AE%E5%8C%BA%E5%9F%9F
 
`JDK 1.8 之前：` 和 `JDK 1.8 ：`
两张图挂了.

**Comment by Snailclimb** [comment]
> https://github.com/Snailclimb/JavaGuide/blob/15fc507affc141e905573210241ba5d3d616080f/docs/java/%E5%8F%AF%E8%83%BD%E6%98%AF%E6%8A%8AJava%E5%86%85%E5%AD%98%E5%8C%BA%E5%9F%9F%E8%AE%B2%E7%9A%84%E6%9C%80%E6%B8%85%E6%A5%9A%E7%9A%84%E4%B8%80%E7%AF%87%E6%96%87%E7%AB%A0.md#%E4%BA%8C-%E8%BF%90%E8%A1%8C%E6%97%B6%E6%95%B0%E6%8D%AE%E5%8C%BA%E5%9F%9F
> 
> `JDK 1.8 之前：` 和 `JDK 1.8 ：`
> 两张图挂了.

感谢！已经修复！
