### ISSUE TITLE
建议：关于“Java内存区域”的描述

### ISSUE THREAD

**Issue by jinyahuan** [Snailclimb/JavaGuide#308]
标题我觉得改成``` Java-HotSpot 内存区域```会更好，或者在内容里面标记 HotSpot。因为 JDK 使用 HotSpot 作为默认虚拟机，他的实现方式不一定和对应版本的 jvms 一样。或者其它的 jvm 实现可能会和 HotSpot 有点不一样，比如 OpenJ9 (没深入了解过机制--)。

就比如“运行时数据区”，jvms8 中其实还是写的“Method Area”，而 hotspot (JDK8) 中的实现是叫“Metaspace” (通过 jmap -heap PID 显示的内容)。

**Comment by pHraySc** [comment]
诶，方法区是运行时数据区而元空间是相对垃圾回收分区来讲的吗？jdk8以前叫永久代这个。元空间或者永久代应该是属于运行时数据区的方法区部分的吧。




| |
沈诚
邮箱：sc_19951214@126.com
|

签名由 网易邮箱大师 定制

在2019年05月08日 18:05，Homer 写道：

标题我觉得改成 Java-HotSpot 内存区域会更好，或者在内容里面标记是，因为 JDK 使用 HotSpot 作为默认虚拟机，他的实现方式会和对应版本的 jvms 有点不一样。

就比如“运行时数据区”，jvms8 中其实还是写的“Method Area”，而 hotspot (JDK8) 中的实现是叫“Metaspace” (通过 jmap -heap PID 显示的内容)。

**Comment by jinyahuan** [comment]
对的，所以我感觉用 HotSpot 标记那块的标题更好 hotspot (JDK8)， hotspot (JDK6)。毕竟 hotspot 其实也是有两个版本：开源版和 oracle jdk 版，更不用说还有其它的 jvm 实现了。

**Comment by Snailclimb** [comment]
因为一般没有特别要求 我们研究的都会受益 HotSpot虚拟机，所以没有加上。

**Comment by jinyahuan** [comment]
嗯，那我关了。我看到你也声明了下！
