### ISSUE TITLE
关于Stringbuilder和Stringbuffer的描述错误

### ISSUE THREAD

**Issue by lowry15** [Snailclimb/JavaGuide#321]
在Java基础知识中：12. String StringBuffer 和 StringBuilder 的区别是什么? 其中线程安全性描述的时候，说错了，应该是用Stringbuilder仅能获得 10%~15% 左右的性能提升，但却要冒多线程不安全的风险。

**Comment by Snailclimb** [comment]
StringBuilder 是线程不安全的，我们一般都是使用 StringBuffer。
