### ISSUE TITLE
[MySQL常见的两种存储引擎：MyISAM与InnoDB的爱恨情仇] 一文中主从引擎的选择应该错误了

### ISSUE THREAD

**Issue by changdy** [Snailclimb/JavaGuide#322]
[MySQL常见的两种存储引擎：MyISAM与InnoDB的爱恨情仇](https://juejin.im/post/5b1685bef265da6e5c3c1c34)
`在数据库做主从分离的情况下，经常选择MyISAM作为主库的存储引擎。`
应该是 InnoDB 作为主 ,MyISAM作为从吧

**Comment by Snailclimb** [comment]
> MyISAM

已经更正！
