### ISSUE TITLE
Java基础知识 32 Java 中的异常处理【错误】

### ISSUE THREAD

**Issue by lpe234** [Snailclimb/JavaGuide#328]
Java异常类层次结构图，其中的`ClassNotFoundException`不属于`RuntimeException `

**Comment by Snailclimb** [comment]
> Java异常类层次结构图，其中的`ClassNotFoundException`不属于`RuntimeException `

我觉得 `ClassNotFoundException`是属于运行时异常，因为这个异常是在 `Classloader` 加载类的时候发现并不存在当前类路径曝出的异常。
