### ISSUE TITLE
链接失效了

### ISSUE THREAD

**Issue by fanchenggang** [Snailclimb/JavaGuide#333]
![image](https://user-images.githubusercontent.com/20358122/58418817-7879d200-80bb-11e9-804d-358fbe888de9.png)

![image](https://user-images.githubusercontent.com/20358122/58418829-816aa380-80bb-11e9-942d-cb52d29a3be5.png)

**Comment by fanchenggang** [comment]
ReentrantLock 和 ReentrantReadWriteLock 这个

**Comment by Snailclimb** [comment]
> ReentrantLock 和 ReentrantReadWriteLock 这个

https://github.com/Snailclimb/JavaGuide/issues/333#issuecomment-496191801
