### ISSUE TITLE
一点小错误

### ISSUE THREAD

**Issue by chowc** [Snailclimb/JavaGuide#334]
[Java 并发进阶常见面试题总结](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Multithread/JavaConcurrencyAdvancedCommonInterviewQuestions.md#java-%E5%B9%B6%E5%8F%91%E8%BF%9B%E9%98%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98%E6%80%BB%E7%BB%93) 的 [说说自己是怎么使用 synchronized 关键字，在项目中用到了吗](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Multithread/JavaConcurrencyAdvancedCommonInterviewQuestions.md#12-%E8%AF%B4%E8%AF%B4%E8%87%AA%E5%B7%B1%E6%98%AF%E6%80%8E%E4%B9%88%E4%BD%BF%E7%94%A8-synchronized-%E5%85%B3%E9%94%AE%E5%AD%97%E5%9C%A8%E9%A1%B9%E7%9B%AE%E4%B8%AD%E7%94%A8%E5%88%B0%E4%BA%86%E5%90%97)

这一小节，“synchronized 关键字加到静态方法上是给对象实例上锁。” 应为“synchronized 关键字加到实例方法上是给对象实例上锁。”

**Comment by chowc** [comment]
另外，同样是这一小节，“尽量不要使用 synchronized(String a) 因为JVM中，字符串常量池具有缓存功能！” 这一句可以展开讲讲原因吗？

谢谢。

**Comment by zeminpiao** [comment]
感觉是因为 被synchronized的那个String 有可能被其他线程所用 所以会有潜在的死锁问题

**Comment by chowc** [comment]
> 感觉是因为 被synchronized的那个String 有可能被其他线程所用 所以会有潜在的死锁问题

例如线程 A 对 `String str` 进行加锁：

```java
synchronized(str) {
    // do something
}
```

然后因为 str 是存在字符串常量池里的，所以其他线程也可以同时操作它，例如线程 B：
```java
str.substring(0, len);
```

不过，不太明白这样怎么导致死锁？

**Comment by LiWenGu** [comment]
因为 JVM 缓存了字符串，所以在同一个 JVM 中，当你两个不同的实例，对同一个字符串进行加锁时会出现锁竞争，如下代码，会出现锁竞争导致串行：
```java
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

class Scratch {
    public static void main(String[] args) throws InterruptedException {
        ExecutorService executor = Executors.newFixedThreadPool(4);
        // 同一个 JVM 同，下面四个类内部本质都对同一个字符串加了锁，这是因为字符串缓存技术
        // 既然它们本质是锁了同一个字符串缓存对象，因此是串行打印的
        StringLock stringLock1 = new StringLock();
        StringLock stringLock2 = new StringLock();
        StringInternLock stringInternLock1 = new StringInternLock();
        StringInternLock stringInternLock2 = new StringInternLock();
        executor.submit(() -> {
            stringLock1.lock();
        });
        executor.submit(() -> {
            stringLock2.lock();
        });
        executor.submit(() -> {
            stringInternLock1.lock();
        });
        executor.submit(() -> {
            stringInternLock2.lock();
        });
        executor.shutdown();
    }


}

class StringLock {
    public void lock() {
        // 不同实例，通过 `=` 方法拿到的字符串都是同一个对象，即从缓存池中拿的
        String lockStr = "lock";
        synchronized (lockStr) {
            System.out.println(Thread.currentThread().getName() + "获得了锁");
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ignored) {
            }
            System.out.println(Thread.currentThread().getName() + "释放了锁");
        }
    }
}

class StringInternLock {
    public void lock() {
        String lockStr = new String("lock");
        // 当你注释下面这行代码你就会发现，串行变并行了
        // 这是因为 new String 方法拿到的字符串的新创建的对象，锁不同的对象，就不会有锁竞争
        // 而 intern 方法到的字符串是从缓存池拿的，锁同一个对象，又有锁竞争了
        lockStr = lockStr.intern();
        synchronized (lockStr) {
            System.out.println(Thread.currentThread().getName() + "获得了锁");
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ignored) {
            }
            System.out.println(Thread.currentThread().getName() + "释放了锁");
        }
    }
}
```
如下代码会导致死锁：
```java
class Scratch {
    public static void main(String[] args) {
        DeathLock deathLock = new DeathLock();
        ExecutorService executor = Executors.newFixedThreadPool(2);
        executor.submit(() -> {
            deathLock.lockOne();
        });
        executor.submit(() -> {
            deathLock.lockTwo();
        });
        executor.shutdown();
    }
}

class DeathLock {

    public void lockOne() {
        String b = "1".substring(0, 1);
        synchronized (b) {
            String a = "2";
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ignored) {
            }
            System.out.println("获取锁B，尝试获取锁A," + System.identityHashCode(b) + "," + System.identityHashCode(b));
            synchronized (a) {
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ignored) {
                }
            }
        }
    }

    public void lockTwo() {
        String a = new String("2").intern();
        synchronized (a) {
            String b = "1";
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ignored) {
            }
            System.out.println("持有锁A，尝试获取锁B," + System.identityHashCode(a) + "," + System.identityHashCode(b));
            synchronized (b) {
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ignored) {
                }
            }
        }
    }
}
```

**Comment by chowc** [comment]
> 因为 JVM 缓存了字符串，所以在同一个 JVM 中，当你两个不同的实例，对同一个字符串进行加锁时会出现锁竞争，如下代码，会出现锁竞争导致串行：
> 
> ```java
> import java.util.concurrent.ExecutorService;
> import java.util.concurrent.Executors;
> 
> class Scratch {
>     public static void main(String[] args) throws InterruptedException {
>         ExecutorService executor = Executors.newFixedThreadPool(4);
>         // 同一个 JVM 同，下面四个类内部本质都对同一个字符串加了锁，这是因为字符串缓存技术
>         // 既然它们本质是锁了同一个字符串缓存对象，因此是串行打印的
>         StringLock stringLock1 = new StringLock();
>         StringLock stringLock2 = new StringLock();
>         StringInternLock stringInternLock1 = new StringInternLock();
>         StringInternLock stringInternLock2 = new StringInternLock();
>         executor.submit(() -> {
>             stringLock1.lock();
>         });
>         executor.submit(() -> {
>             stringLock2.lock();
>         });
>         executor.submit(() -> {
>             stringInternLock1.lock();
>         });
>         executor.submit(() -> {
>             stringInternLock2.lock();
>         });
>         executor.shutdown();
>     }
> 
> 
> }
> 
> class StringLock {
>     public void lock() {
>         // 不同实例，通过 `=` 方法拿到的字符串都是同一个对象，即从缓存池中拿的
>         String lockStr = "lock";
>         synchronized (lockStr) {
>             System.out.println(Thread.currentThread().getName() + "获得了锁");
>             try {
>                 Thread.sleep(1000);
>             } catch (InterruptedException ignored) {
>             }
>             System.out.println(Thread.currentThread().getName() + "释放了锁");
>         }
>     }
> }
> 
> class StringInternLock {
>     public void lock() {
>         String lockStr = new String("lock");
>         // 当你注释下面这行代码你就会发现，串行变并行了
>         // 这是因为 new String 方法拿到的字符串的新创建的对象，锁不同的对象，就不会有锁竞争
>         // 而 intern 方法到的字符串是从缓存池拿的，锁同一个对象，又有锁竞争了
>         lockStr = lockStr.intern();
>         synchronized (lockStr) {
>             System.out.println(Thread.currentThread().getName() + "获得了锁");
>             try {
>                 Thread.sleep(1000);
>             } catch (InterruptedException ignored) {
>             }
>             System.out.println(Thread.currentThread().getName() + "释放了锁");
>         }
>     }
> }
> ```
> 
> 如下代码会导致死锁：
> 
> ```java
> class Scratch {
>     public static void main(String[] args) {
>         DeathLock deathLock = new DeathLock();
>         ExecutorService executor = Executors.newFixedThreadPool(2);
>         executor.submit(() -> {
>             deathLock.lockOne();
>         });
>         executor.submit(() -> {
>             deathLock.lockTwo();
>         });
>         executor.shutdown();
>     }
> }
> 
> class DeathLock {
> 
>     public void lockOne() {
>         String b = "1".substring(0, 1);
>         synchronized (b) {
>             String a = "2";
>             try {
>                 Thread.sleep(1000);
>             } catch (InterruptedException ignored) {
>             }
>             System.out.println("获取锁B，尝试获取锁A," + System.identityHashCode(b) + "," + System.identityHashCode(b));
>             synchronized (a) {
>                 try {
>                     Thread.sleep(1000);
>                 } catch (InterruptedException ignored) {
>                 }
>             }
>         }
>     }
> 
>     public void lockTwo() {
>         String a = new String("2").intern();
>         synchronized (a) {
>             String b = "1";
>             try {
>                 Thread.sleep(1000);
>             } catch (InterruptedException ignored) {
>             }
>             System.out.println("持有锁A，尝试获取锁B," + System.identityHashCode(a) + "," + System.identityHashCode(b));
>             synchronized (b) {
>                 try {
>                     Thread.sleep(1000);
>                 } catch (InterruptedException ignored) {
>                 }
>             }
>         }
>     }
> }
> ```

锁争用的问题倒是很好理解，但是死锁的代码，就算不是字符串，而是普通的 `Object one = new Object()`，每个线程调用一次方法都会创建自己的 `one` 对象，且对其他线程不可见，那么还能起到加锁的作用吗？

一点小疑问。感谢 comment。

**Comment by LiWenGu** [comment]
实例方法锁实例对象，实例对象不同，锁就是独立的，就起不到加锁的作用。第一个例子中 `lockStr.intern();` 注释掉就能回答你这个问题了。

**Comment by bbbooo313** [comment]
[jincaipingtai123.com](jincaipingtai123.com)  老哥换个友链吗？
联系QQ：1297532431
