### ISSUE TITLE
zookeeper

### ISSUE THREAD

**Issue by kevin-cat** [Snailclimb/JavaGuide#337]
zookeeper 没有说他的缺点，可以比较一下其他的产品，这样理解会更深入

**Comment by LiWenGu** [comment]
具体是哪篇文章？
zk 一般说缺点就是 CP，它为了保证顺序一致性，会丢失可用性，但是说这个缺点也是有场景的有对比的，即在`注册中心`的场景，对比像 `Eureka` 这样保证 AP 的系统，不能更好符合场景。但是如果你做 `配置中心`的场景，那它就不是缺点了，因为你可以容忍不可用，但是需要数据一致性。  
还有一点是Paxos算法的复杂吧，我看一遍忘一遍。。。而 `Raft` 算法就比较 ”先进“ 了
