### ISSUE TITLE
同步与异步的问题

### ISSUE THREAD

**Issue by FmLe** [Snailclimb/JavaGuide#339]
对于io上同步与异步描述的不知道是否正确，和我理解的不一样．从你的描述上看，同步基本上和阻塞是一样的东西，都是挂在那里．我理解的是同步非阻塞线程，它的同步表示为会不停地来检测ｉo的返回状态．而异步则由系统来回调．同步和阻塞不是一个概念．

**Comment by yungelee** [comment]
＞　同步： 同步就是发起一个调用后，被调用者未处理完请求之前，调用不返回。
＞　阻塞： 阻塞就是发起一个请求，调用者一直等待请求结果返回，也就是当前线程会被挂起，无法从事其他任务，只有当条件就绪才能继续。
ps, 没看出你这两个描述点有什么本质不同．

**Comment by Snailclimb** [comment]
同步侧重于调用者未处理完请求前结果不返回，而阻塞侧重于其他线程被挂起。不知道这样你能理解不？

**Comment by yungelee** [comment]
确实不好理解,因为不知道实际io运行的模型到底是怎样的,没有实际运行.最近看了一些io多路复用的资料,它也同步阻塞的, 玩linux的人一般是认为同步指的是io实际操作是有自己来去自己发起的, 异步是由内核来操作实际io操作,然后拷贝到用户空间,用户进程被唤醒.比如nio是同步的,就是它发起操作的时候马上返回,但是一旦内核的io数据准备好了后,就会自己去调io操作.所以前面直接返回是非阻塞,后面自己来拷贝数据是同步,后面拷贝也会稍微阻塞一会,因为拷贝数据要时间.这是我的理解.

**Comment by yungelee** [comment]
> 同步侧重于调用者未处理完请求前结果不返回，而阻塞侧重于其他线程被挂起。不知道这样你能理解不？

为处理完结果不返回,线程不能做其他的事情了吧,这个时候难道不是挂起吗?你认为不返回的线程还能执行控制流吗?

**Comment by yungelee** [comment]
> 同步侧重于调用者未处理完请求前结果不返回，而阻塞侧重于其他线程被挂起。不知道这样你能理解不？

未处理完结果不返回, 线程一般是不能做其他的事情了吧, 这个时候难道不是挂起吗?你认为不返回的线程还能执行控制流吗?

**Comment by wangpeipei90** [comment]
同步消息的线程还可以不断轮询内核即epoll, 判断数据收到后再进行数据拷贝（同步非阻塞）。
相对于同步阻塞的挂起，显然同步非阻塞更加浪费CPU，好处是IO更快。

**Comment by yungelee** [comment]
> U，好处是IO更快。

我赞同你的看法,同步非阻塞是更加浪费cpu,但是它的轮巡内核, 有对应的唤醒休眠机制,所以可以适当降低资源浪费.好处可以同时让线程处理其他的请求和业务.

**Comment by wangpeipei90** [comment]
个人理解，同步阻塞与非阻塞的区别仅在于等待数据期间内核进程的状态，如果内核进程处理其他事情，那就是用户进程挂起，否则，内核仍然在loop的话，也就是用户进程没有挂起。

**Comment by yungelee** [comment]
> 个人理解，同步阻塞与非阻塞的区别仅在于等待数据期间内核进程的状态，如果内核进程处理其他事情，那就是用户进程挂起，否则，内核仍然在loop的话，也就是用户进程没有挂起。

一般不说内核进程,所线程吧, 内核是所有进程共享的进程空间.关于挂起的说法也有点不赞同哦.

**Comment by fibeing** [comment]
test comment

**Comment by nihao12358** [comment]
- 

- 

- 

- 

- ``

**Comment by Snailclimb** [comment]
我会根据你们的讨论对JavaGuide这部分做一些修改，感谢🙏
