### ISSUE TITLE
关于ThreadLocal原理的理解

### ISSUE THREAD

**Issue by SevenGm111** [Snailclimb/JavaGuide#344]
以下是我的观点：ThreadLocal实际上只是ThreadLocalMap的一个装配类而已，里面的所有方法里的核心操作就是获取线程中的ThreadLocalMap，然后进行各种操作。比如说ThreadLocal里的get方法就是获取到访问线程的ThreadLocalMap集合，然后取出对应的value；set()方法就是获取ThreadLocaMap集合，然后调用map的set方法把值写进去。

以下是我面试时的话：
  原理是每个Thread（线程）中都有一个ThreadLocalMap的变量，而ThreadLocalMap是以ThreadLocal为key，变量值为value的结构，用ThreadLocal修饰后的变量，每次线程访问时，ThreadLocal做的事情就是装配的工作，即从访问的线程中获取ThreadLocalMap，然后将key设为修饰这个变量的ThreadLocal，value设置为变量值，再返还给线程。因此ThreadLocal实际上只是ThreadLocalMap的一个装配类而已，里面的所有方法里的核心操作就是获取线程中的ThreadLocalMap，然后进行各种操作。

**Comment by SevenGm111** [comment]
不过我还有个疑问，为什么每个线程访问同一个ThreadLocal会有不同的值呢，既然ThreadLocal是给来访问的线程都复制一个副本，那应该副本的内容都是一样的啊

**Comment by yongroot** [comment]
我以为，假设多个线程同时创建并获取其主存变量，内容是一样，但每个线程对其修改都只会作用于其副本，实现互不干扰的。

Seven <notifications@github.com> 于2019年6月11日周二 下午2:46写道：

**Comment by Snailclimb** [comment]
> 不过我还有个疑问，为什么每个线程访问同一个ThreadLocal会有不同的值呢，既然ThreadLocal是给来访问的线程都复制一个副本，那应该副本的内容都是一样的啊

每个`Thread`中都具备一个`ThreadLocalMap`，而`ThreadLocalMap`可以存储以`ThreadLocal`为key的键值对。

```java
public class Thread implements Runnable {
 ......
//与此线程有关的ThreadLocal值。由ThreadLocal类维护
ThreadLocal.ThreadLocalMap threadLocals = null;

//与此线程有关的InheritableThreadLocal值。由InheritableThreadLocal类维护
ThreadLocal.ThreadLocalMap inheritableThreadLocals = null;
 ......
}


```
