### ISSUE TITLE
NIO 指的是 Non-blocking IO

### ISSUE THREAD

**Issue by yihsi** [Snailclimb/JavaGuide#345]
参见 https://en.wikipedia.org/wiki/Non-blocking_I/O_(Java)

**Comment by Snailclimb** [comment]
参见《Netty实战》P30
![](https://my-blog-to-use.oss-cn-beijing.aliyuncs.com/2019-6/微信截图_20190611221620.png)

**Comment by Snailclimb** [comment]
> 参见 https://en.wikipedia.org/wiki/Non-blocking_I/O_(Java)

这部分内容会重构。

**Comment by jinyahuan** [comment]
对的应该是非阻塞，而且严格意义上应该有1.0和2.0(异步)。

see [java doc i/o api](https://docs.oracle.com/javase/8/docs/technotes/guides/io/index.html)

**Comment by jasondeepny** [comment]
io nio aio bio

Homer <notifications@github.com> 于2019年6月14日周五 下午10:03写道：

**Comment by sanwancoder** [comment]
也认为指non-blocking IO
