### ISSUE TITLE
Shell编程入门中Shell流程控制if语句错误

### ISSUE THREAD

**Issue by huixionghexiyi** [Snailclimb/JavaGuide#350]
if [ $a = $b ]
是不是应该是
if [ $a == $b ] 才对。
还有为什么3会大于9呢？
而且在前面段落中也没有看见 '>' ,'<'这样的运算符。不太理解是为什么。希望能得到您的回复。

**Comment by huixionghexiyi** [comment]
还有就是接着下面的函数，省略function关键字的函数的函数名似乎不能为function。
也就是说：function(){...}，这样是不对的。

**Comment by Snailclimb** [comment]
> if [ $a = $b ]
> 是不是应该是
> if [ $a == $b ] 才对。
> 还有为什么3会大于9呢？
> 而且在前面段落中也没有看见 '>' ,'<'这样的运算符。不太理解是为什么。希望能得到您的回复。

原文位置：https://github.com/Snailclimb/JavaGuide/blob/master/docs/operating-system/Shell.md#if-%E6%9D%A1%E4%BB%B6%E8%AF%AD%E5%8F%A5
已经修复。判断两个数字是否相等或者大小的时候应该用特有符号。

```shell
#!/bin/bash
a=3;
b=9;
if [ $a -eq $b ]
then
   echo "a 等于 b"
elif [ $a -gt $b ]
then
   echo "a 大于 b"
else
   echo "a 小于 b"
fi
```

**Comment by Snailclimb** [comment]
> 还有就是接着下面的函数，省略function关键字的函数的函数名似乎不能为function。
> 也就是说：function(){...}，这样是不对的。

嗯嗯 ，应该属于笔误，感谢指出。原文位置：https://github.com/Snailclimb/JavaGuide/blob/master/docs/operating-system/Shell.md#shell-%E5%87%BD%E6%95%B0

修改后如下：

### 不带参数没有返回值的函数

```shell
#!/bin/bash
hello(){
    echo "这是我的第一个 shell 函数!"
}
echo "-----函数开始执行-----"
hello
echo "-----函数执行完毕-----"
```

输出结果：

```
-----函数开始执行-----
这是我的第一个 shell 函数!
-----函数执行完毕-----
```
