### ISSUE TITLE
自旋锁推荐文章内容有错误

### ISSUE THREAD

**Issue by majinkai** [Snailclimb/JavaGuide#353]
> 关于自旋锁，大家可以看一下这篇文章，非常不错：《 面试必备之深入理解自旋锁》

这段话中引用的文章里面，示例代码TicketLock和TicketLockV2中的代码：
`ticketNum.incrementAndGet();`

这里是有问题的，调用的是incrementAndGet，这样currentTicketNum就是1，而此时serviceNum是0，永远都获取不到锁，应该用getAndIncrement

**Comment by Snailclimb** [comment]
> > 关于自旋锁，大家可以看一下这篇文章，非常不错：《 面试必备之深入理解自旋锁》
> 
> 这段话中引用的文章里面，示例代码TicketLock和TicketLockV2中的代码：
> `ticketNum.incrementAndGet();`
> 
> 这里是有问题的，调用的是incrementAndGet，这样currentTicketNum就是1，而此时serviceNum是0，永远都获取不到锁，应该用getAndIncrement

请问这是那篇文章里面的？
