### ISSUE TITLE
java->容器->剖析面试最常见问题之Java基础知识->图片显示错误

### ISSUE THREAD

**Issue by ZhangDi-d** [Snailclimb/JavaGuide#357]
java->容器->剖析面试最常见问题之Java基础知识->ConcurrentHashMap 和 Hashtable 的区别->JDK1.8的ConcurrentHashMap（TreeBin: 红黑二叉树节点 Node: 链表节点） 图片显示错误

**Comment by Snailclimb** [comment]
> java->容器->剖析面试最常见问题之Java基础知识->ConcurrentHashMap 和 Hashtable 的区别->JDK1.8的ConcurrentHashMap（TreeBin: 红黑二叉树节点 Node: 链表节点） 图片显示错误

感谢指出，已经修复。谢谢了。
