### ISSUE TITLE
计算机网络基础知识

### ISSUE THREAD

**Issue by Georgiana-Unity** [Snailclimb/JavaGuide#370]
![image](https://user-images.githubusercontent.com/51913397/60413444-8dd8a380-9c07-11e9-8a93-315d1a3edea7.png)
主机是核心部分吧

**Comment by Snailclimb** [comment]
- 边缘部分：由各主机构成，用户直接进行信息处理和信息共享；低速连入核心网。
- 核心部分：由各路由器连网，负责为边缘部分提供高速远程分组交换。

**Comment by bbbooo313** [comment]
[jincaipingtai123.com](jincaipingtai123.com)  老哥换个友链吗？
联系QQ：1297532431
