### ISSUE TITLE
关于继承的问题

### ISSUE THREAD

**Issue by yellowgg** [Snailclimb/JavaGuide#374]
在本项目的java基础中，9. 构造器 Constructor 是否可被 override? 这一项里
文中提到
“在讲继承的时候我们就知道父类的私有属性和构造方法并不能被继承，所以 Constructor 也就不能被 override（重写）,但是可以 overload（重载）,所以你可以看到一个类中有多个构造函数的情况。”
第一句我有疑问，父类的私有属性是可以被继承的吧，只是拥有而不能使用
因为在同目录的11. Java 面向对象编程三大特性: 封装 继承 多态里面提到
“子类拥有父类对象所有的属性和方法（包括私有属性和私有方法），但是父类中的私有属性和方法子类是无法访问，只是拥有。”
所以两者是不是冲突，我认为是前者有误。

**Comment by fantasygg** [comment]
不冲突

**Comment by yellowgg** [comment]
> 不冲突

那我还是有疑问，请问“在讲继承的时候我们就知道父类的私有属性和构造方法并不能被继承”这句话是否有问题？

**Comment by BigBoomDream** [comment]
子类是可以继承父类的私有属性的，但是不能被访问，可以通过get，set方法来访问------------------ 原始邮件 ------------------
发件人: "yellowgg"<notifications@github.com>
发送时间: 2019年7月4日(星期四) 中午11:32
收件人: "Snailclimb/JavaGuide"<JavaGuide@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [Snailclimb/JavaGuide] 关于继承的问题 (#374)


 
不冲突
  
那我还是有疑问，请问“在讲继承的时候我们就知道父类的私有属性和构造方法并不能被继承”这句话是否有问题？
 
&mdash;

**Comment by yellowgg** [comment]
> 子类是可以继承父类的私有属性的，但是不能被访问，可以通过get，set方法来访问
我同意你的说法，所以文章里面说父类的私有属性不能被继承是有误的吧。

**Comment by yellowgg** [comment]
> 子类是可以继承父类的私有属性的，但是不能被访问，可以通过get，set方法来访问------------------ 原始邮件 ------------------ 发件人: "yellowgg"<notifications@github.com> 发送时间: 2019年7月4日(星期四) 中午11:32 收件人: "Snailclimb/JavaGuide"<JavaGuide@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: Re: [Snailclimb/JavaGuide] 关于继承的问题 (#374) 不冲突 那我还是有疑问，请问“在讲继承的时候我们就知道父类的私有属性和构造方法并不能被继承”这句话是否有问题？ &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

我同意你的说法，所以文章里面提到“父类的私有属性不能被继承”是有误的吧

**Comment by ganxingrui** [comment]
子类可以继承父类私有的属性和方法，但是子类对象不能访问该属性和方法。 2156808384 邮箱：2156808384@qq.com 签名由 网易邮箱大师 定制 在2019年07月04日 11:47，yellowgg 写道： 子类是可以继承父类的私有属性的，但是不能被访问，可以通过get，set方法来访问------------------ 原始邮件 ------------------ 发件人: "yellowgg"notifications@github.com 发送时间: 2019年7月4日(星期四) 中午11:32 收件人: "Snailclimb/JavaGuide"JavaGuide@noreply.github.com; 抄送: "Subscribed"subscribed@noreply.github.com; 主题: Re: [Snailclimb/JavaGuide] 关于继承的问题 (#374) 不冲突 那我还是有疑问，请问“在讲继承的时候我们就知道父类的私有属性和构造方法并不能被继承”这句话是否有问题？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. 我同意你的说法，所以文章里面提到“父类的私有属性不能被继承”是有误的吧 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by yellowgg** [comment]
我佛了emmmm

**Comment by fantasygg** [comment]
> 我佛了emmmm

**总结一下**: 父类的私有属性和方法确实不能被继承, 但子类可以拥有父类的私有属性和方法. 前者是从**Java的定义**来说，后者是从**内存**的角度来说。所以两个说法不冲突。

至于子类想要访问父类的私有属性,就像楼上说的,可以通过getter setter

这里如果感觉有些绕的话,可以看一下 [知乎回答](https://www.zhihu.com/question/51345942) 下面climber的答案讲的挺清晰

**Comment by yellowgg** [comment]
> > 我佛了emmmm
> 
> **总结一下**: 父类的私有属性和方法确实不能被继承, 但子类可以拥有父类的私有属性和方法. 前者是从**Java的定义**来说，后者是从**内存**的角度来说。所以两个说法不冲突。
> 
> 至于子类想要访问父类的私有属性,就像楼上说的,可以通过getter setter
> 
> 这里如果感觉有些绕的话,可以看一下 [知乎回答](https://www.zhihu.com/question/51345942) 下面climber的答案讲的挺清晰

多谢你的评论，知乎这篇我在你发之前也看过的，其实我都明白说的东西，但是就是作为一道题而言，私有属性被继承这一点，有的说可以有的说不可以，因为刚好在牛客网刷题刷过类似的几道，所以才引发了我对这两种说法的疑惑 我的理解是 确实继不继承跟修饰符没关系，子类肯定是拥有父类的全部属性的，就是拥有的同时并不能直接操作私有属性,如此看来，确实文中不算是冲突了

**Comment by Snailclimb** [comment]
你们的讨论很棒！点赞！

**Comment by YangAnLin** [comment]
这个文字描述的,差点晕了

**Comment by qweenhool** [comment]
创建一个子类对象的时候并不会创建一个父类对象，但是父类中的private属性却被赋值了，造成了子类无法访问只能拥有，相当于没有被继承，就像拥有了你爸的银行卡但是却不知道密码，那拥有了又有什么用呢？这么解释是不是合二为一了？

**Comment by duzou98** [comment]
能不能别总是推送邮件了？很烦的


------------------ 原始邮件 ------------------
发件人: "qweenhool"<notifications@github.com>;
发送时间: 2019年7月12日(星期五) 上午9:49
收件人: "Snailclimb/JavaGuide"<JavaGuide@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [Snailclimb/JavaGuide] 关于继承的问题 (#374)




创建一个子类对象的时候并不会创建一个父类对象，但是父类中的private属性却被赋值了，造成了子类无法访问只能拥有，相当于没有被继承，就像拥有了你爸的银行卡但是却不知道密码，那拥有了又有什么用呢？这么解释是不是合二为一了？

**Comment by jadeStoneStonger** [comment]
因为你watch了。取消watch就好了

**Comment by bbbooo313** [comment]
不冲突 [jincaipingtai123.com](jincaipingtai123.com)
