### ISSUE TITLE
链接失效(404)

### ISSUE THREAD

**Issue by yellowgg** [Snailclimb/JavaGuide#378]
在线阅读的版本(两个)里都有一个链接失效了，报错404。
JavaGuide->java->容器->Java容器常见面试题/知识点总结中，**说一说 ArrayList 的扩容机制吧**的链接失效了，两个都失效了，
![image](https://user-images.githubusercontent.com/27286340/60776105-11d8e100-a15c-11e9-9ee7-a1990155ecb2.png)

[在线阅读失效链接1](https://snailclimb.top/JavaGuide/#/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98?id=%E8%AF%B4%E4%B8%80%E8%AF%B4-arraylist-%E7%9A%84%E6%89%A9%E5%AE%B9%E6%9C%BA%E5%88%B6%E5%90%A7)
[在线阅读失效链接2](https://snailclimb.gitee.io/javaguide/#/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98?id=%E8%AF%B4%E4%B8%80%E8%AF%B4-arraylist-%E7%9A%84%E6%89%A9%E5%AE%B9%E6%9C%BA%E5%88%B6%E5%90%A7)

**Comment by Snailclimb** [comment]
感谢感谢，指出的位置非常详细，已经修复！
