### ISSUE TITLE
关于在线阅读版本未同步

### ISSUE THREAD

**Issue by yellowgg** [Snailclimb/JavaGuide#384]
在gitee的在线阅读版本中，java基础少了一个阅读项，
![image](https://user-images.githubusercontent.com/27286340/61094456-e0c11f00-a481-11e9-8cea-4fb985b9ae41.png)
在snailclimb.top的在线阅读版本中，其阅读项的名字也未同步过来
![image](https://user-images.githubusercontent.com/27286340/61094590-7361be00-a482-11e9-9523-f1fc52495e98.png)

在gitHub中正常的为
![image](https://user-images.githubusercontent.com/27286340/61094532-2a116e80-a482-11e9-9e48-2c1c4b17ae30.png)

[gitee笨笨传送门](https://snailclimb.gitee.io/javaguide/#/?id=java)
[top笨笨传送门](https://snailclimb.top/JavaGuide/#/?id=java)

可惜我不能提PR，不然就自己动手了，知道作者大大你辛苦了

**Comment by Snailclimb** [comment]
好的 感谢提醒，马上同步！
