### ISSUE TITLE
建议对分布式session、jwt 做一个专题讲解

### ISSUE THREAD

**Issue by yzsunlight** [Snailclimb/JavaGuide#394]
目前分布式session及jwt比较常用，建议做一个讲解

**Comment by Snailclimb** [comment]
好的 感谢建议！

**Comment by sanwancoder** [comment]
JSON Web Token 入门教程 [
](http://www.ruanyifeng.com/blog/2018/07/json_web_token-tutorial.html)

**Comment by sanwancoder** [comment]
分布式session现在一般公司用得[spring session](https://spring.io/projects/spring-session)

**Comment by jerryoung** [comment]
最近我在坐这个方面的东西，有兴趣可以一起来做。

**Comment by Snailclimb** [comment]
已经为 JavaGuide 开了一个权限认证方面的专题，地址：[https://github.com/Snailclimb/JavaGuide#权限认证](https://github.com/Snailclimb/JavaGuide#权限认证)。期待对这个方面有研究的朋友一起维护！
