### ISSUE TITLE
勘误：字符串算法题-#6字符串转换整数有误

### ISSUE THREAD

**Issue by yxdmax** [Snailclimb/JavaGuide#396]
### 我发起这个 ISSUE 的主要目的
- [ ] 讨论
- [x] 勘误
- [ ] 建议
### 涉及文章的相对路径
[几道常见的子符串算法题.md #6-把字符串转换成整数](https://github.com/Snailclimb/JavaGuide/blob/master/docs/dataStructures-algorithms/%E5%87%A0%E9%81%93%E5%B8%B8%E8%A7%81%E7%9A%84%E5%AD%90%E7%AC%A6%E4%B8%B2%E7%AE%97%E6%B3%95%E9%A2%98.md#6-%E6%8A%8A%E5%AD%97%E7%AC%A6%E4%B8%B2%E8%BD%AC%E6%8D%A2%E6%88%90%E6%95%B4%E6%95%B0)
### 错误原文或讨论点
原文：
```java
public static int StrToInt(String str) {
    ......
    return flag == 1 ? res : -res;
}
```
应改为：

```java
public static int StrToInt(String str) {
    ......
    return flag != 2 ? res : -res;
}
```
***

[算法总结——几道常见的子符串算法题------把字符串转换成整数](https://github.com/Snailclimb/JavaGuide/issues/70)
Issue #70 提过此问题，但是并未修改！

***

**Comment by Snailclimb** [comment]
好的  Issue提交格式很棒！非常感谢！已经修改！
