### ISSUE TITLE
后端程序员必备的 Linux 基础知识 章节图片不显示

### ISSUE THREAD

**Issue by mgzu** [Snailclimb/JavaGuide#404]
应该是稀土社区禁止图片外链

**Comment by Snailclimb** [comment]
> 应该是稀土社区禁止图片外链

我这里显示的貌似没有问题，会不会是你的网络问题。

**Comment by mgzu** [comment]
@Snailclimb 我发链接给其他人访问，图片也 403 了。

**Comment by Snailclimb** [comment]
> @Snailclimb 我发链接给其他人访问，图片也 403 了。

好像是可以访问的，不知道是不是墙的问题。
