### ISSUE TITLE
勘误：servlet部分有错误

### ISSUE THREAD

**Issue by yywa** [Snailclimb/JavaGuide#405]
![image](https://user-images.githubusercontent.com/26457020/61770326-90ea3c80-ae1f-11e9-9849-72516d58e02d.png)
![image](https://user-images.githubusercontent.com/26457020/61770337-95165a00-ae1f-11e9-81f1-7a330e403f1a.png)
![image](https://user-images.githubusercontent.com/26457020/61770347-99db0e00-ae1f-11e9-8241-ef2de81f81bd.png)

**Comment by Snailclimb** [comment]
不好意思，没看懂是什么错误。

**Comment by yywa** [comment]
单词写错了。

**Comment by yellowgg** [comment]
已经修改过了，可以关闭此issue了， @Snailclimb 
另外多谢你提出的错误 @yywa
