### ISSUE TITLE
链接404

### ISSUE THREAD

**Issue by Horstson** [Snailclimb/JavaGuide#429]
大佬，docs/system-design/website-architecture/分布式.md，
“图解 Paxos 一致性协议”，“Zookeeper ZAB 协议分析” ，这俩链接失效了！

**Comment by Snailclimb** [comment]
> 大佬，docs/system-design/website-architecture/分布式.md，
> “图解 Paxos 一致性协议”，“Zookeeper ZAB 协议分析” ，这俩链接失效了！

已经修复！
