### ISSUE TITLE
大佬，你这个总结是不是写反了？

### ISSUE THREAD

**Issue by zhangyong5566** [Snailclimb/JavaGuide#43]
![qq 20181024095846](https://user-images.githubusercontent.com/11458535/47401270-3c703e80-d773-11e8-9deb-a6bc953bdc04.png)
StringBuid不是多线程StringBuff单线程？

**Comment by lovewestwind** [comment]
不正是 因为这样所以多线程下用buffer？

**Comment by violetmoon027** [comment]
任何操作String的都应该在StringBuffer或者StringBuilder中执行，因为你不能一直确定少量的操作一直都是少量的操作，还有就是多线程下用StringBuilder,单线程下使用StringBuffer。

**Comment by zhangyong5566** [comment]
所以对你总结的这个单线程操作字符串缓冲区下操作大量数据 = StringBuilder，多线程操作字符串缓冲区下操作大量数据 = StringBuffer不是很理解。。难道是单线程下操作大量数据为了提高效率使用StringBuilder？多线程下操作数据为了安全而使用StringBuffer？

**Comment by lovewestwind** [comment]
stringBuffer中大量的sync方法保证线程安全，不是为了在多线程环境下用还在什么环境下用。
当然你如果能保证你的程序在多线程环境下能够正常顺序执行你的stringBuilder操作也可以在多线程中用stringbuilder。

**Comment by zhangyong5566** [comment]
明白了

**Comment by luxunnb** [comment]
别人这个哪儿有问题嘛，拼接字符串无论是Stringbuffer还是StringBuilder都会比String快，StringBuilder作过线程安全处理，多线程环境下就应该用StringBuilder

**Comment by zhangyong5566** [comment]
@luxunnb 你根本没明白我跟作者说什么，点开你的StringBuilder和StringBuffe源码看到底哪个做了线程安全处理。。。。

**Comment by luxunnb** [comment]
你的意思是考虑效率还是啥意思。我的意思是多线程你没有做线程安全处理情况下用StringBuffer，它做过线程安全处理，方法都synchronized修饰。我刚刚记返了。。。。。

**Comment by zhangyong5566** [comment]
@luxunnb 我知道这三者的区别，就是对作者总结有点疑惑，作者是这样写的：“单线程操作字符串缓冲区下操作大量数据 = StringBuilder，多线程操作字符串缓冲区下操作大量数据 = StringBuffer“。
现在理解了我是这样理解的：多线程操作大量字符串，既然是自己开了多线程操作字符串，那就有可能不安全，那我们就应该保证字符串安全所以用StringBuffer线程安全的，单线程操作大量字符串，在一个线程里，肯定是安全的所以应该用StringBuilder去提高效率。

**Comment by Snailclimb** [comment]
各位可以将自己觉得比较好的解释 PR 提交给我哦！期待！

**Comment by freestylefly** [comment]
StringBuffer线程安全且用了大量同步

**Comment by lidaoping1990** [comment]
并发性要求高的情况下了？
