### ISSUE TITLE
发现错误

### ISSUE THREAD

**Issue by sundayong** [Snailclimb/JavaGuide#439]
Java 基础知识疑难点总结里边的１．２有个错误：

Integer x = 3;
Integer y = 3;
System.out.println(x == y);// true
Integer a = new Integer(3);
Integer b = new Integer(3);
System.out.println(a == b);//false
System.out.println(a.equals(b));//false

最后一个应该是true 了

**Comment by Snailclimb** [comment]
> Java 基础知识疑难点总结里边的１．２有个错误：
> 
> Integer x = 3;
> Integer y = 3;
> System.out.println(x == y);// true
> Integer a = new Integer(3);
> Integer b = new Integer(3);
> System.out.println(a == b);//false
> System.out.println(a.equals(b));//false
> 
> 最后一个应该是true 了

你好，你看的好像不是最新的版本。

**Comment by wangpeipei90** [comment]
Java API上说Object.equals()方法：
The equals method for class Object implements the most discriminating possible equivalence relation on objects; that is, for any non-null reference values x and y, this method returns true if and only if x and y refer to the same object (x == y has the value true).

之前的哪个版本说a.equals(b) 会返回True结果呢？
