### ISSUE TITLE
ArrayList-Grow.md ensureCapacity本地测试demo与预期不一致

### ISSUE THREAD

**Issue by qingfengfoo** [Snailclimb/JavaGuide#441]
使用ensureCapacity方法前：370
使用ensureCapacity方法后：3808

Process finished with exit code 0
这个是我本地测试最后那个demo的结果，与文档的预期结果恰恰相反，这是为什么呢？

**Comment by Snailclimb** [comment]
> 使用ensureCapacity方法前：370
> 使用ensureCapacity方法后：3808
> 
> Process finished with exit code 0
> 这个是我本地测试最后那个demo的结果，与文档的预期结果恰恰相反，这是为什么呢？

我又试了一遍没有问题
