### ISSUE TITLE
AQS讲解中举例不严谨

### ISSUE THREAD

**Issue by cutdir** [Snailclimb/JavaGuide#442]
文中有一个举例：以ReentrantLock为例，state初始化为0，表示未锁定状态。A线程lock()时，会调用tryAcquire()独占该锁并将state+1。
这段话只试用与非公平锁场景，对于公平锁，在资源可用(state=0)时，会判断下等待队列(虚拟队列)是否有等待节点且第一个等待节点的对应线程是不是当前线程，是的话才会独占资源。

**Comment by Snailclimb** [comment]
> 文中有一个举例：以ReentrantLock为例，state初始化为0，表示未锁定状态。A线程lock()时，会调用tryAcquire()独占该锁并将state+1。
> 这段话只试用与非公平锁场景，对于公平锁，在资源可用(state=0)时，会判断下等待队列(虚拟队列)是否有等待节点且第一个等待节点的对应线程是不是当前线程，是的话才会独占资源。

你好可以提个pr吗？我觉得你说的很不错！
