### ISSUE TITLE
String intern方法，在jdk1.7之后的变化

### ISSUE THREAD

**Issue by LicoCode** [Snailclimb/JavaGuide#443]
JDK1.7之后，String常量池 从 Perm 区移动到了 Java Heap区，intern方法的实现也会有一些变化。
String对象调用intern方法时，当常量池中已经包含一个等于此 String 对象内容的字符串，则返回常量池中该字符串的引用；如果没有，JDK1.7之前（不包括1.7）的处理方式是在常量池中创建与此String内容相同的字符串，而JDK1.7之后的处理方式是在常量池中记录该字符串的引用，并返回该引用。
下面两段代码是我在jdk1.8.0_201上做的一些验证
{
        //String常量池中不存在"abcdef"的情况下，调用intern方法
        //jdk version：jdk1.8.0_201
        String a = new String("abc") + "def";
        String c = a.intern();
        String b = "abcdef";
        System.out.println(a == b);        //true     
        System.out.println(a == c);        //true
        System.out.println(b == c);        //true
}
{
        //String常量池中已经存在"abcdef"的情况下，调用intern方法
        //jdk version：jdk1.8.0_201
        String a = new String("abc") + "def";
        String b = "abcdef";
        String c = a.intern();
        System.out.println(a == b);        //false
        System.out.println(a == c);        //false
        System.out.println(b == c);        //true
}
参考文章：https://tech.meituan.com/2014/03/06/in-depth-understanding-string-intern.html

**Comment by mjiuming** [comment]
哥们……你版本号标错来

**Comment by LicoCode** [comment]
哦哦，因为我电脑上安装jdk的是1.8版本，就是测试下，了解详细的可以看https://tech.meituan.com/2014/03/06/in-depth-understanding-string-intern.html

**Comment by Snailclimb** [comment]
> 当常量池中没有该字符串时，JDK7的intern（）方法的实现不再是在常量池中创建与此String内容相同的字符串，而改为在常量池中记录java Heap中首次出现的该字符串的引用，并返回该引用。
> {
> //jdk version：jdk1.8.0_201
> String a = new String("abc") + "def";
> String c = a.intern();
> String b = "abcdef";
> System.out.println(a == b); //true
> System.out.println(a == c); //true
> System.out.println(b == c); //true
> }
> {
> //jdk version：jdk1.8.0_201
> String a = new String("abc") + "def";
> String b = "abcdef";
> String c = a.intern();
> System.out.println(a == b); //false
> System.out.println(a == c); //false
> System.out.println(b == c); //true
> }

我没有找到具体位置，请问可以提一个pr吗？

**Comment by dq205877** [comment]
你这描述和代码都容易误导人，能写清楚点么




------------------ 原始邮件 ------------------
发件人: "SnailClimb"<notifications@github.com>;
发送时间: 2019年8月20日(星期二) 晚上7:54
收件人: "Snailclimb/JavaGuide"<JavaGuide@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [Snailclimb/JavaGuide] String intern方法，在jdk1.7之后的变化 (#443)



 
当常量池中没有该字符串时，JDK7的intern（）方法的实现不再是在常量池中创建与此String内容相同的字符串，而改为在常量池中记录java Heap中首次出现的该字符串的引用，并返回该引用。
 {
 //jdk version：jdk1.8.0_201
 String a = new String("abc") + "def";
 String c = a.intern();
 String b = "abcdef";
 System.out.println(a == b); //true
 System.out.println(a == c); //true
 System.out.println(b == c); //true
 }
 {
 //jdk version：jdk1.8.0_201
 String a = new String("abc") + "def";
 String b = "abcdef";
 String c = a.intern();
 System.out.println(a == b); //false
 System.out.println(a == c); //false
 System.out.println(b == c); //true
 }
  
我没有找到具体位置，请问可以提一个pr吗？

**Comment by zhiweiHong** [comment]
> > 当常量池中没有该字符串时，JDK7的intern（）方法的实现不再是在常量池中创建与此String内容相同的字符串，而改为在常量池中记录java Heap中首次出现的该字符串的引用，并返回该引用。
> > {
> > //jdk version：jdk1.8.0_201
> > String a = new String("abc") + "def";
> > String c = a.intern();
> > String b = "abcdef";
> > System.out.println(a == b); //true
> > System.out.println(a == c); //true
> > System.out.println(b == c); //true
> > }
> > {
> > //jdk version：jdk1.8.0_201
> > String a = new String("abc") + "def";
> > String b = "abcdef";
> > String c = a.intern();
> > System.out.println(a == b); //false
> > System.out.println(a == c); //false
> > System.out.println(b == c); //true
> > }
> 
> 我没有找到具体位置，请问可以提一个pr吗？
