### ISSUE TITLE
J2EE 基础知识--引用文章的一个小问题

### ISSUE THREAD

**Issue by Horstson** [Snailclimb/JavaGuide#449]
大神您好，https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/J2EE%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md#get%E5%92%8Cpost%E8%AF%B7%E6%B1%82%E7%9A%84%E5%8C%BA%E5%88%AB，
这里，您引用了一篇文章，
https://mp.weixin.qq.com/s?__biz=MzI3NzIzMzg3Mw==&mid=100000054&idx=1&sn=71f6c214f3833d9ca20b9f7dcd9d33e4#rd。
这篇文章里有提到 GET产生一个TCP数据包；POST产生两个TCP数据包。
这个尝试抓包验证了一下。Firefox，Chrome都没有没有发现post两个包的情况。另外，看别人  也有同样的尝试，文章在这里  https://blog.csdn.net/zerooffdate/article/details/78962818 ，     以及后续，https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html#sec8.2.3。  您看这个是不是有问题呢？

**Comment by Snailclimb** [comment]
> 大神您好，[https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/J2EE%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md#get%E5%92%8Cpost%E8%AF%B7%E6%B1%82%E7%9A%84%E5%8C%BA%E5%88%AB，](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/J2EE%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md#get%E5%92%8Cpost%E8%AF%B7%E6%B1%82%E7%9A%84%E5%8C%BA%E5%88%AB%EF%BC%8C)
> 这里，您引用了一篇文章，
> [https://mp.weixin.qq.com/s?__biz=MzI3NzIzMzg3Mw==&mid=100000054&idx=1&sn=71f6c214f3833d9ca20b9f7dcd9d33e4#rd。](https://mp.weixin.qq.com/s?__biz=MzI3NzIzMzg3Mw==&mid=100000054&idx=1&sn=71f6c214f3833d9ca20b9f7dcd9d33e4#rd%E3%80%82)
> 这篇文章里有提到 GET产生一个TCP数据包；POST产生两个TCP数据包。
> 这个尝试抓包验证了一下。Firefox，Chrome都没有没有发现post两个包的情况。另外，看别人 也有同样的尝试，文章在这里 https://blog.csdn.net/zerooffdate/article/details/78962818 ， 以及后续，[https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html#sec8.2.3。](https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html#sec8.2.3%E3%80%82) 您看这个是不是有问题呢？

可以帮我提个 pr 吗？

**Comment by Horstson** [comment]
好的
