### ISSUE TITLE
链表不是随机访问的，概念上有点错误。

### ISSUE THREAD

**Issue by tidus5** [Snailclimb/JavaGuide#46]
Java相关/这几道Java集合框架面试题几乎必问.md
里的

ArraysList 底层是数组，而 LinkedList 底层是链表。数组天然支持随机访问，时间复杂度为 O（1），所以称为快速随机访问。实际上链表也是支持的，不过需要遍历到特定位置才行，时间复杂度为 O（n）。

这句，链表也是支持的， 如果理解为 支持快速随机访问，那么则是错误的。需要遍历的就不叫快速随机访问了

**Comment by Snailclimb** [comment]
已经更正，非常感谢！
