### ISSUE TITLE
getMessage()与toString()方法描述有问题

### ISSUE THREAD

**Issue by MrKingHH** [Snailclimb/JavaGuide#468]
public string getMessage():返回异常发生时的详细信息
public string toString():返回异常发生时的简要描述
应该是反了。getMessage()是简要描述，toString()是详细信息。

**Comment by Snailclimb** [comment]
请问这个是那一篇文章里面的？

**Comment by MrKingHH** [comment]
java基础知知识->[Throwable类常用方法](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md#throwable%E7%B1%BB%E5%B8%B8%E7%94%A8%E6%96%B9%E6%B3%95)

**Comment by Snailclimb** [comment]
感谢你！

> java基础知知识->[Throwable类常用方法](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md#throwable%E7%B1%BB%E5%B8%B8%E7%94%A8%E6%96%B9%E6%B3%95)

感谢你！
