### ISSUE TITLE
LinkedList是双向链表不是双向循环链表

### ISSUE THREAD

**Issue by nvkwo3314200** [Snailclimb/JavaGuide#47]
jdk1.8中
``
/**
     * Links e as last element.
     */
    void linkLast(E e) {
        final Node<E> l = last;
        final Node<E> newNode = new Node<>(l, e, null);
        last = newNode;
        if (l == null)
            first = newNode;
        else
            l.next = newNode;
        size++;
        modCount++;
    }
``
newNode的next并没有指向first而是null

LinkBefore方法中还用pred == null来判断是否插入到第一个node
``
  /**
     * Inserts element e before non-null Node succ.
     */
    void linkBefore(E e, Node<E> succ) {
        // assert succ != null;
        final Node<E> pred = succ.prev;
        final Node<E> newNode = new Node<>(pred, e, succ);
        succ.prev = newNode;
        if (pred == null)
            first = newNode;
        else
            pred.next = newNode;
        size++;
        modCount++;
    }
``
所以没看出来循环

**Comment by freestylefly** [comment]
是@

**Comment by Snailclimb** [comment]
之前没有分清双向链表和双向循环链表 感谢您提出来！
