### ISSUE TITLE
关于JDK的版本发布，这个项目里面的描述现在显然已经有点不合时宜了

### ISSUE THREAD

**Issue by kenshinji** [Snailclimb/JavaGuide#471]
在[这里](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Java基础知识.md#4-oracle-jdk-和-openjdk-的对比)提到 `Oracle JDK版本将每三年发布一次，而OpenJDK版本每三个月发布一次；`, 从JDK9开始，官方就对于版本发布有了一些更改 https://blogs.oracle.com/java-platform-group/update-and-faq-on-the-java-se-release-cadence

**Comment by Snailclimb** [comment]
@kenshinji 感谢你的指出！已经做了相应修改，参见：https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md#4-oracle-jdk-%E5%92%8C-openjdk-%E7%9A%84%E5%AF%B9%E6%AF%94
