### ISSUE TITLE
MyISAM与InnoDB，是不是有问题

### ISSUE THREAD

**Issue by wuhengc** [Snailclimb/JavaGuide#473]
MyISAM更适合读密集的表，而InnoDB更适合写密集的表。 在数据库做主从分离的情况下，经常选择MyISAM作为主库的存储引擎。

MyISAM更适合读密集的表 ，那主库写得话应该采用InnoDB，有歧义

**Comment by wangjunji1** [comment]
在国内基本没有人用myisam的存储引擎，其本上还是innodb,主从同步的引擎必须一样。没有主和从不用一样的引擎

**Comment by wuhengc** [comment]
确实是这样，感谢回复

**Comment by Snailclimb** [comment]
这个是那个位置的？这里吗 ？https://github.com/Snailclimb/JavaGuide/blob/master/docs/database/MySQL.md#myisam%E5%92%8Cinnodb%E5%8C%BA%E5%88%AB
