### ISSUE TITLE
目录快速链接的问题

### ISSUE THREAD

**Issue by woaibiancheng01214** [Snailclimb/JavaGuide#477]
在”Java基础知识回顾“里面，点击最上面的目录里面的“面向对象和面向过程的区别“的时候，url里面显示的是：

https://snailclimb.gitee.io/javaguide/#/java/Java基础知识?id=1-面向对象和面向过程的区别

而实际上如果看这个链接真正导向的标题的id，多了一个下划线：
https://snailclimb.gitee.io/javaguide/#/java/Java基础知识?id=_1-面向对象和面向过程的区别

从而导致没办法直接点击目录里的标题

**Comment by Snailclimb** [comment]
左侧有导航栏，看左边的导航栏就好，好像没啥影响。这里阅读不会出现这种问题：https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md#1-%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1%E5%92%8C%E9%9D%A2%E5%90%91%E8%BF%87%E7%A8%8B%E7%9A%84%E5%8C%BA%E5%88%AB
