### ISSUE TITLE
整型部分equals

### ISSUE THREAD

**Issue by MakenChan** [Snailclimb/JavaGuide#480]
jdk 1.8中
    public boolean equals(Object obj) {
        if (obj instanceof Integer) {
            return value == ((Integer)obj).intValue();
        }
        return false;
    }    
Integer integer = new Integer(300);
 Integer integer2 = new Integer(300);
integer.equals(integer2); //true

**Comment by Snailclimb** [comment]
> jdk 1.8中
> public boolean equals(Object obj) {
> if (obj instanceof Integer) {
> return value == ((Integer)obj).intValue();
> }
> return false;
> }
> Integer integer = new Integer(300);
> Integer integer2 = new Integer(300);
> integer.equals(integer2); //true

请问这部分对应的内容具体在哪里呢？提issue时请详细说明一下。

**Comment by MakenChan** [comment]
> > jdk 1.8中
> > public boolean equals(Object obj) {
> > if (obj instanceof Integer) {
> > return value == ((Integer)obj).intValue();
> > }
> > return false;
> > }
> > Integer integer = new Integer(300);
> > Integer integer2 = new Integer(300);
> > integer.equals(integer2); //true
> 
> 请问这部分对应的内容具体在哪里呢？提issue时请详细说明一下。

Java 基础知识疑难点总结-》1.1. 正确使用 equals 方法-》1.2. 整型包装类值的比较
