### ISSUE TITLE
想问下Spring Boot，MyBatis，SpringCloud这些框架有整理吗？

### ISSUE THREAD

**Issue by starjuly** [Snailclimb/JavaGuide#483]
如题

**Comment by Snailclimb** [comment]
SpringCloud 目前没有整理！SpringBoot 常见问题正在总结中，一些案例整理在这里：https://github.com/Snailclimb/springboot-guide，https://github.com/Snailclimb/spring-security-jwt-guide

**Comment by Snailclimb** [comment]
如果有对 SpringCloud 比较了解，期望整理知识的朋友可以联系我，除了得到展示之外还会有不错的报酬！

**Comment by starjuly** [comment]
好的，谢谢

**Comment by HaiminLi** [comment]
现在Spring Cloud有人开始整理的吗？我想整理Spring Cloud，但是了解的不是很全面，有没有一起合作的？

**Comment by jizhuozhi** [comment]
Spring Cloud Netflix已经进入维护状态了，要考虑下Spring Cloud Alibaba或者Spring Cloud HashiCorp么？

**Comment by CONTINUE12** [comment]
+1
