### ISSUE TITLE
分布式事务解决方案

### ISSUE THREAD

**Issue by zqxul** [Snailclimb/JavaGuide#484]

**Comment by LiWenGu** [comment]
本来想整理，后来发现没有实战，只有理论知识写的很难服众，毕竟没有实际场景的熏陶，就不误导人了。
不过我们正在调研中的是有两个，可以给你参考：
1. ons(rocketmq商用版) 的事务消息
2. seata 项目，sc-alibaba 项目中的事务消息处理方案。
