### ISSUE TITLE
为什么微服务的篇幅全都是Spring Cloud, 为什么它会成为微服务的准则和未来的趋势? 

### ISSUE THREAD

**Issue by liukch** [Snailclimb/JavaGuide#488]
我在<【面试精选】关于大型网站系统架构你不得不懂的10个问题> 这一篇中看到有一段话:
"现在大公司都在用并且未来的趋势都是 Spring Cloud".
我不是很理解, 为什么 Spring Cloud 会是大公司都在用, 而且为什么也是未来的趋势呢?
现在整个业内都是在用Spring Cloud 来实现微服务思想了吗? 
为什么未来的趋势也是 Spring Cloud? 现在市面上如此多的开源工具, 唯独它可以是未来的趋势?

**Comment by Snailclimb** [comment]
> 我在<【面试精选】关于大型网站系统架构你不得不懂的10个问题> 这一篇中看到有一段话:
> "现在大公司都在用并且未来的趋势都是 Spring Cloud".
> 我不是很理解, 为什么 Spring Cloud 会是大公司都在用, 而且为什么也是未来的趋势呢?
> 现在整个业内都是在用Spring Cloud 来实现微服务思想了吗?
> 为什么未来的趋势也是 Spring Cloud? 现在市面上如此多的开源工具, 唯独它可以是未来的趋势?

你好，你对"现在大公司都在用并且未来的趋势都是 Spring Cloud".这句话的理解貌似有点误解。
做微服务  Spring Cloud  在各个领域都提供了不错的解决方案，我遇到过的微服务项目大部分都是采用 Spring Cloud 。说未来趋势是它，也是因为感觉它逐渐成为Java微服务领域大部分项目的首选，不过这也只是我的个人看法而已。
