### ISSUE TITLE
《为什么 Java 中只有值传递？》错别字

### ISSUE THREAD

**Issue by JackWei1996** [Snailclimb/JavaGuide#496]
![image](https://user-images.githubusercontent.com/27356215/66480197-a727a080-ead0-11e9-9da6-37dcfe7106af.png)

**Comment by Snailclimb** [comment]
@JackWei1996 感谢！太仔细了，赞👍！

**Comment by JackWei1996** [comment]
也非常感谢您的分享，写的很好很详细~
