### ISSUE TITLE
有一个关于LinkedList增加和删除元素时间复杂度的问题

### ISSUE THREAD

**Issue by wangzitiansky** [Snailclimb/JavaGuide#497]
原文中写到：LinkedList 采用链表存储，所以插入，删除元素时间复杂度不受元素位置的影响，都是近似 O（1）
但是假如是对特定位置的元素进行add(int index, E element) , 或者进行remove(int index)的时候,
时间复杂度是O(1)吗？？？
 LinkedList也要先查找这个元素，查找的时间复杂度是O(n),再进行插入的时间复杂度是O(1)。所以总时间复杂度应该是O(n)吧

**Comment by wangzitiansky** [comment]
原文地址： https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.md

**Comment by wangzitiansky** [comment]
stackoverflow上面对于这个问题的讨论
https://stackoverflow.com/questions/322715/when-to-use-linkedlist-over-arraylist-in-java/322742?r=SearchResults#322742

**Comment by T-Noino** [comment]
说得很清楚, 多谢

**Comment by Snailclimb** [comment]
已经修改！

**Comment by Snailclimb** [comment]
非常感谢！🙏
