### ISSUE TITLE
下载到本地用什么阅读器浏览比较方便

### ISSUE THREAD

**Issue by jackyzp** [Snailclimb/JavaGuide#498]
请问一下作者，这个文件夹下载到本地，应该使用什么阅读器来查看比较方便，
我这一直用记事本查看一点也不方便，麻烦提供下链接
，谢谢

**Comment by Snailclimb** [comment]
楼上正解！

**Comment by jackyzp** [comment]
非常感谢1楼提供 链接

**Comment by DavidSharch** [comment]
可以使用微软的vsc，Visual Studio Code。可以直接把项目拖入阅读

**Comment by kelaosng** [comment]
Markdown

**Comment by yanwenjun98** [comment]
你下一个 vs code 这个阅读起来还是很方便的
