### ISSUE TITLE
is:issue is:open设计模式部分-适配器引用文章错误 sheji

### ISSUE THREAD

**Issue by powerLeePlus** [Snailclimb/JavaGuide#502]
![image](https://user-images.githubusercontent.com/25865085/66714557-9043bf80-edea-11e9-80d5-fe8b4480ea8f.png)
第一个文章里对象适配代码示例有错误，
![image](https://user-images.githubusercontent.com/25865085/66714585-e284e080-edea-11e9-9562-e237dd63386c.png)
第二个文章这部分讲解是对的

**Comment by LiWenGu** [comment]
正好认识原作者，已联系他改正。  

---

你可以看看仓库里面推荐的[设计模式书籍](https://github.com/Snailclimb/JavaGuide/blob/master/docs/data/java-recommended-books.md#设计模式)

关联PR: #515

**Comment by Snailclimb** [comment]
赞！
