### ISSUE TITLE
目录拼写错误，可改可不改

### ISSUE THREAD

**Issue by China99** [Snailclimb/JavaGuide#510]
【JavaGuide/media/pictures/kafaka】
可以将kafaka修改为kafka

**Comment by Snailclimb** [comment]
[Rustin-Liu](https://github.com/Rustin-Liu)已经修改！再次感谢一下，已经加入 Contributor中。

**Comment by Rustin-Liu** [comment]
> [Rustin-Liu](https://github.com/Rustin-Liu)已经修改！再次感谢一下，已经加入 Contributor中。

也谢谢您的资料！
