### ISSUE TITLE
望增加部分内容

### ISSUE THREAD

**Issue by yjxsy1996** [Snailclimb/JavaGuide#522]
希望可以新增一些关于volatile关键字得分析和ThreadLocal得分析，谢谢！

**Comment by T-Noino** [comment]
这个博客: http://tutorials.jenkov.com/java-concurrency/volatile.html, 关于volatile和threadLocal说得挺好的

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: yf <notifications@github.com>
发送时间: Wednesday, October 30, 2019 3:58:16 PM
收件人: Snailclimb/JavaGuide <JavaGuide@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [Snailclimb/JavaGuide] 望增加部分内容 (#522)


希望可以新增一些关于volatile关键字得分析和ThreadLocal得分析，谢谢！

―

**Comment by yjxsy1996** [comment]
thank you , friend !
