### ISSUE TITLE
关于各种Bean的命名

### ISSUE THREAD

**Issue by ijkzen** [Snailclimb/JavaGuide#525]
最近，我在写一个spring boot的小项目，但是关于Bean的命名有一些混乱，也没有办法查到一些有用的资料，所以向大家求助：
1. 与数据库相关联的实体类该如何命名？（无关表名）
2. 单纯的实体类该如何命名？
3. RequestBody的实体类该如何命名？
4. ResponseBody的实体类该如何命名？

先谢谢大家了

**Comment by LiWenGu** [comment]
参考：
1. https://github.com/alibaba/p3c/blob/master/p3c-gitbook/%E7%BC%96%E7%A8%8B%E8%A7%84%E7%BA%A6/%E5%91%BD%E5%90%8D%E9%A3%8E%E6%A0%BC.md
2. https://github.com/apache/dubbo/search?q=Response&unscoped_q=Response
3. https://github.com/apache/dubbo/search?q=Request&unscoped_q=Request

---

1. 数据传输对象：xxxDTO，xxx为业务领域相关的名称。
2. 数据对象：xxxDO，xxx即为数据表名。
3. 请求：xxxReuqest。例：io.etcd.jetcd.api.WatchCreateRequest;
4. 响应：xxxResponse。例：org.apache.dubbo.rpc.AppResponse;

ps：我一般都是缩写，Request -> Req，Response -> Resp

**Comment by ijkzen** [comment]
> 
> 
> 参考：
> 
>     1. https://github.com/alibaba/p3c/blob/master/p3c-gitbook/%E7%BC%96%E7%A8%8B%E8%A7%84%E7%BA%A6/%E5%91%BD%E5%90%8D%E9%A3%8E%E6%A0%BC.md
> 
>     2. https://github.com/apache/dubbo/search?q=Response&unscoped_q=Response
> 
>     3. https://github.com/apache/dubbo/search?q=Request&unscoped_q=Request
> 
> 
>     1. 数据传输对象：xxxDTO，xxx为业务领域相关的名称。
> 
>     2. 数据对象：xxxDO，xxx即为数据表名。
> 
>     3. 请求：xxxReuqest。例：io.etcd.jetcd.api.WatchCreateRequest;
> 
>     4. 响应：xxxResponse。例：org.apache.dubbo.rpc.AppResponse;
> 
> 
> ps：我一般都是缩写，Request -> Req，Response -> Resp

感谢大哥的回答，对我帮助很大
