### ISSUE TITLE
String常量池的位置，是在Heap里还是其他地方方法区？

### ISSUE THREAD

**Issue by KennyNg-19** [Snailclimb/JavaGuide#527]
看到引用了这张说在heap里的图，

![在heap里](https://cdn.journaldev.com/wp-content/uploads/2012/11/String-Pool-Java1.png)

但也有这样 不在heap里的
![不在heap的](https://user-images.githubusercontent.com/31399290/68081523-20a17d00-fe4a-11e9-8398-18e8469f8bc7.png)

请问String的常量池，是在内存哪个区域呀？
包装类的呢？

**Comment by LiWenGu** [comment]
先说答案：7u40+ 以及 Java 8 **常量池在堆中**
代码示例：
```java
public static void main(String[] args) throws Exception{
    // JDK8
    // 1. -XX:MaxMetaspaceSize=10m -XX:MetaspaceSize=10m 没有报错
    // 2. -Xmx10m -Xms10m -XX:-UseGCOverheadLimit 报错：java.lang.OutOfMemoryError: Java heap space
    List<String> a= new ArrayList<>();
    for (int i = 0; i < 10000000; i++) {
        a.add(String.valueOf(i).intern());
    }
}
```
在第二种情况得到的异常信息就知道，其实常量池是在堆中。以下为大佬的回答：  
地址：https://stackoverflow.com/questions/42247199/string-pool-in-java-8  
![image](https://user-images.githubusercontent.com/15909210/68296706-2e683400-00d0-11ea-8251-32608790689d.png)

**Comment by Snailclimb** [comment]
我把图片重新画了一遍，避免引起歧义。![字符串拼接](https://my-blog-to-use.oss-cn-beijing.aliyuncs.com/2019-7/字符串拼接-常量池2.png)

**Comment by LiWenGu** [comment]
相关 Issue：

[内存区域中表述错误](https://github.com/Snailclimb/JavaGuide/issues/586)
