### ISSUE TITLE
2.6节，图片加载有问题

### ISSUE THREAD

**Issue by gpqhl0071** [Snailclimb/JavaGuide#530]
https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/jvm/Java%E5%86%85%E5%AD%98%E5%8C%BA%E5%9F%9F.md

这篇文档，2.6节，图片加载有问题。

https://camo.githubusercontent.com/17620721a9f326a235aeec8956949cec03f3f125/687474703a2f2f6d792d626c6f672d746f2d7573652e6f73732d636e2d6265696a696e672e616c6979756e63732e636f6d2f31382d392d31342f32363033383433332e6a7067

**Comment by Snailclimb** [comment]
我这边是好的吗，大概率是网络问题。

**Comment by gpqhl0071** [comment]
哦，的确是，我强制多算了几次，可以刷出来，可能是网络的问题 。
