### ISSUE TITLE
公众号获取的资料链接无法打开

### ISSUE THREAD

**Issue by KateJC** [Snailclimb/JavaGuide#534]
在redis总结一章中https://github.com/Snailclimb/JavaGuide/blob/master/docs/database/Redis/Redis.md
在文档末尾提到“公众号后台回复关键字“1 获取到的资源” 
https://shimo.im/docs/CPB0PK05rP4CFmI2/
![image](https://user-images.githubusercontent.com/28619416/68448368-42ba4700-021e-11ea-8949-815630e53265.png)

在该石墨文档中 其中 “尚硅谷Java方向视频” 这一链接下载的文档中
![image](https://user-images.githubusercontent.com/28619416/68448349-32a26780-021e-11ea-9e4f-5455d5b4e0c4.png)

关于大数据的云盘链接全都失效
![image](https://user-images.githubusercontent.com/28619416/68448330-228a8800-021e-11ea-82b0-3810da6fcb92.png)

![image](https://user-images.githubusercontent.com/28619416/68448395-5b2a6180-021e-11ea-9ff1-187d898e1a41.png)

请问博主，还有没有关于大数据的相关资料分享得咧

**Comment by Snailclimb** [comment]
你好 我今天会花时间对资料进行重新整理，这个是尚硅谷官方分享的，可能是暂停分享了吧。
