### ISSUE TITLE
可否写一些有关线程池的问题

### ISSUE THREAD

**Issue by luyuanwan** [Snailclimb/JavaGuide#541]
可否写一些有关线程池的问题（支付宝问这个问题比较多）
1. 线程池中的线程数量如何确定，在CPU密集型和IO密集型程序中如何确定

**Comment by Snailclimb** [comment]
> 可否写一些有关线程池的问题（支付宝问这个问题比较多）
> 
> 1. 线程池中的线程数量如何确定，在CPU密集型和IO密集型程序中如何确定

好的 没问题。预计这周会加入到 https://github.com/Snailclimb/JavaGuide#并发 下面。
