### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by gpqhl0071** [Snailclimb/JavaGuide#542]
地址：
[https://github.com/Snailclimb/JavaGuide/blob/master/docs/database/Redis/Redis.md](https://github.com/Snailclimb/JavaGuide/blob/master/docs/database/Redis/Redis.md)

题目：如何保证缓存与数据库双写时的数据一致性?

我觉得这个解答晦涩难懂，而且开发中也不常用。

我觉得这句描述，更实用且好记：先读缓存，缓存没有的话，就读数据库，然后取出数据后放入缓存，同时返回响应。

[详细参考](https://www.javazhiyin.com/22969.html)

**Comment by Snailclimb** [comment]
好的 感谢你！
