### ISSUE TITLE
C++ 语言内置了多线程机制的哦

### ISSUE THREAD

**Issue by chxuan** [Snailclimb/JavaGuide#544]
大佬你好，大佬在Java基础知识->Java 语言有哪些特点上写到C++ 语言没有内置的多线程机制，其实
从C++11开始（2011年的时候）C++就引入了多线程库，在windows、linux、macos都可以使用std::thread和std::async来创建线程。

参考链接：
http://www.cplusplus.com/reference/thread/thread/?kw=thread

**Comment by Snailclimb** [comment]
好的 感谢老哥，这个确实知识盲区了，大学学的 C++也是比较老的版本了。

**Comment by Snailclimb** [comment]
已经修改了哦 ，再次表示感谢🙏！https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md#2-java-%E8%AF%AD%E8%A8%80%E6%9C%89%E5%93%AA%E4%BA%9B%E7%89%B9%E7%82%B9

**Comment by yondddd** [comment]
1
