### ISSUE TITLE
Arraylist 与 LinkedList 区别中说法不对吧

### ISSUE THREAD

**Issue by povs2012** [Snailclimb/JavaGuide#545]
② LinkedList 采用链表存储，所以对于add(E e)方法的插入，删除元素时间复杂度不受元素位置的影响，近似 O（1），如果是要在指定位置i插入和删除元素的话（(add(int index, E element)） 时间复杂度应为o(n))因为需要新创立一个新的链表，复制前i-1个元素并在第i位加入新的元素，最后附上n-i个元素。

指定位置插入时间复杂度为O(n)的原因不对吧，指定位置插入是因为需要先移动到指定位置再插入，不是因为需要复制链表元素

**Comment by povs2012** [comment]
看到了另外一个问题了

**Comment by povs2012** [comment]
我看别人讨论了这个问题，但好像最新的文档里还是这种描述。

**Comment by Snailclimb** [comment]
已经修改！非常感谢，上次应该是忘记提交了。
