### ISSUE TITLE
关于面试CAS的疑问

### ISSUE THREAD

**Issue by luyuanwan** [Snailclimb/JavaGuide#548]
在面试中经常会被问到 ： 请说一下CAS的原理    虽然心里清楚，但不知道该怎么说，希望能在文档中写一点关于CAS原理的内容。不知道各位同学意见如何，欢迎一起讨论。

**Comment by guozhongdong** [comment]
个人认为主要还是基于硬件的CAS实现的，再往下也没法在细化了。

**Comment by wangpeipei90** [comment]
不如写一些根据cas原理的并发应用吧，比如原子类，锁机制

**Comment by junjun-yang** [comment]
CAS就是操作系统层面的一个原子指令了，遇到这种问题建议往其他方面发散、比如CAS的具体应用、再不行直接解释下compare and swap这三个单词

**Comment by lc275** [comment]
> 在面试中经常会被问到 ： 请说一下CAS的原理 虽然心里清楚，但不知道该怎么说，希望能在文档中写一点关于CAS原理的内容。不知道各位同学意见如何，欢迎一起讨论。

CAS 是compare and swap 的缩写，底层由计算机硬件CPU指令实现，确保了执行是原子性的不会被中断。原理是比较期望值与内存中的值，如果相等就执行替换操作，比如要对变量i执行加1操作，原来的值是1 执行了加1操作变成2 ，那操作就是 CAS（expect:1,acture :2）,也就是期望内存种的值还是1，在当前线程执行加一的过程中没有其他线程参与进来。
CAS一般是用在竞争不太激烈的情况下，否则导致CPU空转，这实际是一种乐观锁，跟数据库的乐观锁的思路是一样的
