### ISSUE TITLE
关于jdk9的PlatformClassLoader

### ISSUE THREAD

**Issue by guang19** [Snailclimb/JavaGuide#555]
最近我在复习ClassLoader这一块,我用的jdk11,其实也不知道该不该说,毕竟这只是版本的不同.
jdk9引入了模块化系统,取消了ExtensionClassLoader,新增了PaltformClassLoader.并且双亲委派机制也受到一定影响.

参考:https://yq.aliyun.com/articles/518315

**Comment by Snailclimb** [comment]
可以的  老哥！优秀！

**Comment by YangGuang19** [comment]
哪里，与您相比，我还需要更加努力。
