### ISSUE TITLE
StackOverflowError和OutOfMemoryError均是错误,而不是异常

### ISSUE THREAD

**Issue by YangGuang19** [Snailclimb/JavaGuide#557]
如题:
![error](https://user-images.githubusercontent.com/41150022/69211368-d255e300-0b98-11ea-96e7-8155de97d707.png)

**Comment by Snailclimb** [comment]
你好请问这个出处在哪里？我找到的这个有 https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md#32-java-%E4%B8%AD%E7%9A%84%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86 但是文章中描述的没问题啊。

**Comment by YangGuang19** [comment]
jvm的那一块
![IMG_20191122_111623](https://user-images.githubusercontent.com/41150022/69395365-a877fa00-0d19-11ea-8992-e3b8031f8f31.jpg)

**Comment by Snailclimb** [comment]
感谢 @YangGuang19 已经修改完毕！
