### ISSUE TITLE
希望能更新公众号的pdf版本

### ISSUE THREAD

**Issue by yussuy** [Snailclimb/JavaGuide#558]
公众号的pdf有一些内容没有更新，因为自己不方便在线阅读，直接clone项目又不方便打印。想打印出纸质版学习，希望公众号的pdf版本能更新。

**Comment by Snailclimb** [comment]
不好意思，这个比较耗费时间，目前可能没有时间去做这件事情。

**Comment by Snailclimb** [comment]
pdf版本： [《JavaGuide面试突击版》](https://snailclimb.gitee.io/javaguide/#/./docs/javaguide%E9%9D%A2%E8%AF%95%E7%AA%81%E5%87%BB%E7%89%88)
