### ISSUE TITLE
阿里巴巴 Java 开发手册（详尽版）链接失效了

### ISSUE THREAD

**Issue by qjh0122** [Snailclimb/JavaGuide#559]
阿里巴巴 Java 开发手册（详尽版） https://github.com/alibaba/p3c/blob/master/阿里巴巴 Java 开发手册（详尽版）.pdf

**Comment by Snailclimb** [comment]
刚刚看了并没有失效啊。https://github.com/alibaba/p3c/blob/master/阿里巴巴Java开发手册（华山版）.pdf

**Comment by qjh0122** [comment]
> 刚刚看了并没有失效啊。[https://github.com/alibaba/p3c/blob/master/阿里巴巴Java开发手册（华山版）.pdf](https://github.com/alibaba/p3c/blob/master/%E9%98%BF%E9%87%8C%E5%B7%B4%E5%B7%B4Java%E5%BC%80%E5%8F%91%E6%89%8B%E5%86%8C%EF%BC%88%E5%8D%8E%E5%B1%B1%E7%89%88%EF%BC%89.pdf)

我的我的 链接没copy全不好意思= =
