### ISSUE TITLE
面向对象和面向过程的区别？

### ISSUE THREAD

**Issue by chejdj** [Snailclimb/JavaGuide#562]
看了一下答案，觉得这个问题问的核心应该是 问这两种思想的区别，而不是从性能角度，而且性能取决于具体实现方式。
面向过程：我认为关注点在于一件事分成几个步骤去做。
面向对象：关注点在于这件事应该由哪些对象去做。
个人观点，可以讨论一下哈，不喜勿喷

**Comment by jimcarol** [comment]
面向佛祖编程

**Comment by Rustin-Liu** [comment]
我觉得本身这两种范式都跟性能没什么关系吧，两种范式都能写出高性能的代码，而且性能还是要看场景和语言本身吧。
面向对象更多的会花很多精力在抽象和封装上吧，怎么把解决这件事相关的行为和主体抽象封装复用吧。面向过程更多的会聚焦在怎么步骤化的解决这个问题。
但是，实际上编程语言都在进化和演变，现代编程语言几乎都多多少少支持两种范式混合开发，有时候界限其实不是很明显，还有更多的语言甚至往函数式范式进化和演变，比如说Rust,它就可以支持几乎所有的编程范式，连函数式的基建都做的很好。
在我个人看来有时候使用大量的抽象和封装很容易造成过度的封装和过度设计的问题，所以我们应该辩证的看万物皆对象吧。没有绝对的界限，只有合适不合适吧。
还有我要说 Rust 大法好。

**Comment by chejdj** [comment]
> 我觉得本身这两种范式都跟性能没什么关系吧，两种范式都能写出高性能的代码，而且性能还是要看场景和语言本身吧。
> 面向对象更多的会花很多精力在抽象和封装上吧，怎么把解决这件事相关的行为和主体抽象封装复用吧。面向过程更多的会聚焦在怎么步骤化的解决这个问题。
> 但是，实际上编程语言都在进化和演变，现代编程语言几乎都多多少少支持两种范式混合开发，有时候界限其实不是很明显，还有更多的语言甚至往函数式范式进化和演变，比如说Rust,它就可以支持几乎所有的编程范式，连函数式的基建都做的很好。
> 在我个人看来有时候使用大量的抽象和封装很容易造成过度的封装和过度设计的问题，所以我们应该辩证的看万物皆对象吧。没有绝对的界限，只有合适不合适吧。
> 还有我要说 Rust 大法好。

很赞同，可以修改这个Java->基础下的那个回答
