### ISSUE TITLE
”在浏览器中输入url地址到显示主页的过程,整个过程会使用哪些协议“中提到的IP数据包在路由器之间使用的协议为OPSF协议错误，应该为OSPF协议。

### ISSUE THREAD

**Issue by RyanLeisure** [Snailclimb/JavaGuide#568]
IP数据包在路由器之间传播大致分为IGP和BGP协议，而IGP目前主流为OSPF协议，思科，华为和H3C等主流厂商都有各自实现并使用；BGP协议为不同AS（自治系统号）间路由传输，也分为I-BGP和E-BGP，详细资料请查看《TCP/IP卷一》

**Comment by Snailclimb** [comment]
> IP数据包在路由器之间传播大致分为IGP和BGP协议，而IGP目前主流为OSPF协议，思科，华为和H3C等主流厂商都有各自实现并使用；BGP协议为不同AS（自治系统号）间路由传输，也分为I-BGP和E-BGP，详细资料请查看《TCP/IP卷一》

非常感谢！已经修改 -> [原文地址](https://github.com/Snailclimb/JavaGuide/blob/master/docs/essential-content-for-interview/PreparingForInterview/%E7%BE%8E%E5%9B%A2%E9%9D%A2%E8%AF%95%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%80%BB%E7%BB%93.md#3-%E5%9C%A8%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%AD%E8%BE%93%E5%85%A5-url-%E5%9C%B0%E5%9D%80%E5%88%B0%E6%98%BE%E7%A4%BA%E4%B8%BB%E9%A1%B5%E7%9A%84%E8%BF%87%E7%A8%8B%E6%95%B4%E4%B8%AA%E8%BF%87%E7%A8%8B%E4%BC%9A%E4%BD%BF%E7%94%A8%E5%93%AA%E4%BA%9B%E5%8D%8F%E8%AE%AE)
