### ISSUE TITLE
这里是不是字打错了

### ISSUE THREAD

**Issue by ZLCG** [Snailclimb/JavaGuide#571]
![image](https://user-images.githubusercontent.com/40761601/69806864-db8d2280-121e-11ea-8160-33277e8f380c.png)
https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/jvm/%E7%B1%BB%E5%8A%A0%E8%BD%BD%E8%BF%87%E7%A8%8B.md

**Comment by LiWenGu** [comment]
是的
