### ISSUE TITLE
Java 内存区域中堆的划分有问题

### ISSUE THREAD

**Issue by jiebcoder** [Snailclimb/JavaGuide#578]
<img width="519" alt="屏幕快照 2019-12-03 15 26 10" src="https://user-images.githubusercontent.com/47094935/70029118-4fde1200-15e1-11ea-92e3-9efef5f500ae.png">
应该是：堆内存只能分为两块：新生代 Young Generation 和老年代 Old Generation。
永生代 Permanent Generation 是在 JDK 1.8 之前，HotSpot 虚拟机把方法区当成永久代

**Comment by LiWenGu** [comment]
文中已经注明了是 JDK 7 版本之前。
不过 `Young Ceneration` 有笔误。
