### ISSUE TITLE
关于rocketmq单机/分布式消息中心指的是？

### ISSUE THREAD

**Issue by mimajiushi** [Snailclimb/JavaGuide#581]
本人目前rocketmq也就稍稍入门，请问：https://snailclimb.gitee.io/javaguide/#/docs/system-design/data-communication/RocketMQ-Questions?id=_1-单机版消息中心
中的分布式消息中心是指阿里的商业版本吗？网上百度搜不到分布式消息中心具体是开源实现还是商业版本

**Comment by LiWenGu** [comment]
1. 不是。

https://www.oschina.net/p/rocketmq 的描述：
>RocketMQ 是一款开源的分布式消息系统，基于高可用分布式集群技术，提供低延时的、高可靠的消息发布与订阅服务。

RocketMQ  本身是分布式的。阿里商业版和开源版你可以理解为：一个是 RocketMQ 代码为 1.0 版本，一个是 RocketMQ 代码为 2.0 版本，只理解区别代码的区别。  
因此你可以使用基于开源版的搭建集群版的分布式消息中心-RocketMQ，也可以直接使用商业版的集群-RokcetMQ。

这是开源版的集群搭建教程：http://rocketmq.apache.org/docs/cluster-deployment/

**Comment by mimajiushi** [comment]
> 1. 不是。
> 
> https://www.oschina.net/p/rocketmq 的描述：
> 
> > RocketMQ 是一款开源的分布式消息系统，基于高可用分布式集群技术，提供低延时的、高可靠的消息发布与订阅服务。
> 
> RocketMQ 本身是分布式的。阿里商业版和开源版你可以理解为：一个是 RocketMQ 代码为 1.0 版本，一个是 RocketMQ 代码为 2.0 版本，只理解区别代码的区别。
> 因此你可以使用基于开源版的搭建集群版的分布式消息中心-RocketMQ，也可以直接使用商业版的集群-RokcetMQ。
> 
> 这是开源版的集群搭建教程：http://rocketmq.apache.org/docs/cluster-deployment/

了解了，非常感谢
