### ISSUE TITLE
关于字符串常量至少一个字符结束标志？

### ISSUE THREAD

**Issue by Lunaticf** [Snailclimb/JavaGuide#584]
Java的String对象应该并不需要也没有字符结束标志把，与C是不同的。

**Comment by freestylefly** [comment]
是这样子的

**Comment by Snailclimb** [comment]
感谢感谢！已经做了修改。

**在 C 语言中，字符串或字符数组最后都会有一个额外的字符‘\0’来表示结束。但是，Java 语言中没有结束符这一概念。** 这是一个值得深度思考的问题，具体原因推荐看这篇文章： https://blog.csdn.net/sszgg2006/article/details/49148189。
