### ISSUE TITLE
内存区域中表述错误

### ISSUE THREAD

**Issue by maoz123** [Snailclimb/JavaGuide#586]
![image](https://user-images.githubusercontent.com/33593433/70415759-5b758100-1a98-11ea-9afe-993fb4781f59.png)
我再oracle官网看到的 ：
![image](https://user-images.githubusercontent.com/33593433/70415819-7c3dd680-1a98-11ea-9187-19451b9ad666.png)
常量池一直是在方法中allocate的，只是方法区在JDK1.7和1.7之后的版本实现方式不一样。1.8之后方法去用元空间实现的，因此常量池也是在元空间中的，而不是在堆中。

**Comment by LiWenGu** [comment]
可以在提问之前在 issues 搜索是否有相关的问题。 
[String常量池的位置，是在Heap里还是其他地方方法区？](#527)

---

另外你说：
>1.8之后方法去用元空间实现的，因此常量池也是在元空间中的，而不是在堆中。

方法区"变成了”元空间，不仅仅只是名字不一样，它们存储的东西也发生了改变。

**Comment by maoz123** [comment]
我的理解是尽管存储的东西改变了，但是常量池还是在方法去里面，应该也在元空间里面。不知道我的理解有没有偏差， @LiWenGu 你有何高见？ 希望能有所指教。

**Comment by LiWenGu** [comment]
[String常量池的位置，是在Heap里还是其他地方方法区？](https://github.com/Snailclimb/JavaGuide/issues/527)
这个 Issue 你参考下。

---

另外这个更加细节，把 jdk8 堆中存放的都说了：https://stackoverflow.com/questions/53678418/java-memory-areas-in-java-8。
