### ISSUE TITLE
POST 请求能把请求参数放到 HTTP 请求报文的请求头部吗

### ISSUE THREAD

**Issue by jiebcoder** [Snailclimb/JavaGuide#590]
![image](https://user-images.githubusercontent.com/47094935/70681260-c6f86200-1cd5-11ea-80fe-31ccefe770ad.png)
网上搜的好像都是请求正文 request body 啊。

**Comment by rocky-peng** [comment]
消息体就是request body

**Comment by jiebcoder** [comment]
> 消息体就是request body

不不，我的意思是网上搜的只能把参数放到消息体里，不能放到消息头里。

**Comment by Snailclimb** [comment]
实际上可以把 get 和 post 当作两个不同的行为，两者并没有什么本质区别，底层都是 TCP 连接。 get请求用来从服务器上获得资源，而post是用来向服务器提交数据。比如你要获取人员列表可以用 get 请求，你需要创建一个人员可以用 post 。这也是 Restful  API 最基本的一个要求。

**Comment by Snailclimb** [comment]
如果你写个 web 后端应该对这个会有比较形象的认识。
