### ISSUE TITLE
单位换算写错-不了解布隆过滤器？一文给你整的明明白白！

### ISSUE THREAD

**Issue by fengyelingdu** [Snailclimb/JavaGuide#591]
不了解布隆过滤器？一文给你整的明明白白！
1.什么是布隆过滤器？下的
“这样申请一个 100w 个元素的位数组只占用 1000000 / 8 = 125000_B = 15625 byte ≈ 15.3kb 的空间。”写错

**Comment by Snailclimb** [comment]
> 不了解布隆过滤器？一文给你整的明明白白！
> 1.什么是布隆过滤器？下的
> “这样申请一个 100w 个元素的位数组只占用 1000000 / 8 = 125000_B = 15625 byte ≈ 15.3kb 的空间。”写错

是这样意思么？

> 位数组中的每个元素都只占用 1 bit ，并且每个元素只能是 0 或者 1。这样申请一个 100w 个元素的位数组只占用  1000000 / 8 = 125000 Bit = 15625 Byte ≈ 15.3kb 的空间。

**Comment by fengyelingdu** [comment]
> 100



> > 不了解布隆过滤器？一文给你整的明明白白！
> > 1.什么是布隆过滤器？下的
> > “这样申请一个 100w 个元素的位数组只占用 1000000 / 8 = 125000_B = 15625 byte ≈ 15.3kb 的空间。”写错
> 
> 是这个意思么？
> 
> > 位数组中的每个元素都只占用 1 bit ，并且每个元素只能是 0 或者 1。这样申请一个 100w 个元素的位数组只占用  1000000 / 8 = 125000 Bit = 15625 Byte ≈ 15.3kb 的空间。

100w数据不该是 1000000 / 8 = 125000 Byte么？

**Comment by fengyelingdu** [comment]
> > 不了解布隆过滤器？一文给你整的明明白白！
> > 1.什么是布隆过滤器？下的
> > “这样申请一个 100w 个元素的位数组只占用 1000000 / 8 = 125000_B = 15625 byte ≈ 15.3kb 的空间。”写错
> 
> 是这个意思么？
> 
> > 位数组中的每个元素都只占用 1 bit ，并且每个元素只能是 0 或者 1。这样申请一个 100w 个元素的位数组只占用  1000000 / 8 = 125000 Bit = 15625 Byte ≈ 15.3kb 的空间。

100w数据不该是 1000000 / 8 = 125000 Byte么？

**Comment by Snailclimb** [comment]
好的把 我看错了。。。

**Comment by fengyelingdu** [comment]
> 好的把 我看错了。。。

嗯嗯，看到15.3k我说怎么觉得有点不对劲
