### ISSUE TITLE
就是JDK8的新特性讲解的TODO疑问

### ISSUE THREAD

**Issue by yjxsy1996** [Snailclimb/JavaGuide#593]
就是关于JDK新特性那章节的接口默认方法中，有个地方使用了“//TODO通过匿名内部类方式访问接口”，这点我感觉容易导致歧义，因为这里我感觉好像是注释的感觉，但是按道理说TODO是表示程序中的代码还有部分任务没有完成，后面待解决的意思，作者觉得呢？

**Comment by Snailclimb** [comment]
=
