### ISSUE TITLE
集合框架里面关于Arraylist 与 LinkedList 区别的疑问

### ISSUE THREAD

**Issue by happy888liu** [Snailclimb/JavaGuide#605]
集合框架里面关于Arraylist 与 LinkedList 区别中，看到这句话
LinkedList 不支持高效的随机元素访问，而 ArrayList 支持。快速随机访问就是通过元素的序号快速获取元素对象(对应于get(int index) 方法)
![image](https://user-images.githubusercontent.com/10581712/71542869-b703a200-29a6-11ea-9b0a-6c07070986d1.png)

我看LinkedList有提供get(int index)相关的api啊？这句话是不是写的有误还是其他意思啊？

**Comment by chenmrU** [comment]
因为一个低层是链表，一个是数组，就是这两个的区别

**Comment by happy888liu** [comment]
但原文中那种说法算是歧义吗？

**Comment by chenmrU** [comment]
原文说的是“高效”

**Comment by happy888liu** [comment]
> 因为一个底层是链表，一个是数组，就是这两个的区别

**Comment by loserwangzhi** [comment]
liu说的在理
