### ISSUE TITLE
redis的文章中图片显示不完整

### ISSUE THREAD

**Issue by ambition0802** [Snailclimb/JavaGuide#606]
redis的文章中图片显示不完整

文章地址：
https://github.com/Snailclimb/JavaGuide/blob/master/docs/database/Redis/Redis.md#redis-%E7%AE%80%E4%BB%8B

显示不完整的图片
![image](https://user-images.githubusercontent.com/30753647/71551706-5d43bc00-2a28-11ea-9abe-1de62eacc96f.png)

**Comment by Snailclimb** [comment]
你好 这种情况属于网络问题。

**Comment by ambition0802** [comment]
好的  谢谢
