### ISSUE TITLE
HashMap源码分析中put的方法的流程图的疑问

### ISSUE THREAD

**Issue by zhongshanhao** [Snailclimb/JavaGuide#608]
<img src="https://my-blog-to-use.oss-cn-beijing.aliyuncs.com/2019-7/put%E6%96%B9%E6%B3%95.png">
图中若key存在，直接覆盖其节点值，这时不应该将size加1吧？按照源码分析应该直接返回被覆盖之前的值吧？

**Comment by LiWenGu** [comment]
直接覆盖之后应该就会 return，不会有后续操作。这个图确实有问题。
参考 JDK8 HashMap.java 658 行

**Comment by zhongshanhao** [comment]
> 直接覆盖之后应该就会 return，不会有后续操作。这个图确实有问题。
> 参考 JDK8 HashMap.java 658 行

确实，源码实现是直接返回被覆盖的值的。

**Comment by softwareCQT** [comment]
如果是putIfAbsent的话才不会被覆盖掉，返回原来的值，主要看那个onlyIfAbsent

**Comment by hokage123** [comment]
PutIfAbsent Or OnlyIfabsent serve what purpose
If Put() method work for the key if it is not present
Otherwise it overrides the value of key.

**Comment by shahainloong** [comment]
扩容之后返回null，直接覆盖的话会返回原来的value值。

**Comment by sunchaser-lilu** [comment]
长度大于8后转换成红黑树那里有问题吧？后续不会执行红黑树插入逻辑，只是长度大于8后会进行树化，节点已经在上一步插入至链表了。

参考 JDK8 HashMap.java 642 行 -> 执行尾插至链表逻辑
参考 JDK8 HashMap.java 644 行 -> 判断大于8后执行treeifyBin树化逻辑

**Comment by monkback** [comment]
链表长度大于8就会直接转化为红黑树吗？文章前面提到，还需要判断数组桶的长度，如果大于64才会转换；否则是先进行扩容的

**Comment by sAMs126** [comment]
有一个疑问，是否可以这样理解，除了直接追加数组元素 `tab[i] = newNode(hash, key, value, null);` 这种方式，其他的插入/覆盖方式，都不会对整个数组的长度产生影响，也就**无从谈起数组扩容**？

但是 `treeifyBin(tab, hash);` 方法中的

```java
if (tab == null || (n = tab.length) < MIN_TREEIFY_CAPACITY) resize();
```

难道是仅仅只会在整个数组为空，或者长度小于 64 是进行扩容？

> Replaces all linked nodes in bin at index for given hash unless table is too small, in which case resizes instead.

**Comment by 2firenut** [comment]
> 

是的
