### ISSUE TITLE
【缓存穿透】的概念的一点疑问

### ISSUE THREAD

**Issue by Shellbye** [Snailclimb/JavaGuide#610]
首先非常感谢博主的整理工作，真的是受益匪浅。

然后我读到关于[缓存穿透](https://snailclimb.gitee.io/javaguide/#/docs/database/Redis/Redis?id=%e7%bc%93%e5%ad%98%e7%a9%bf%e9%80%8f)的这部分时，有一个疑问。博主的文章中说

 > 缓存穿透说简单点就是大量请求的 key 根本不存在于缓存中，导致请求直接到了数据库上，根本没有经过缓存这一层

我查了一部分资料（见后），发现大家对这个缓存穿透的定义似乎还更深入了一层，就是这个 key 不光不在缓存中，而且也不在数据库中，这样就会导致这个 key 会持续访问数据库。而如果这个 key 只是不在缓存中，那么第一次读取数据库之后，后面就没有这个问题了。

https://blog.csdn.net/zeb_perfect/article/details/54135506
https://juejin.im/post/5c9a67ac6fb9a070cb24bf34

**Comment by wangpeipei90** [comment]
难道缓存穿透的内容说的不正是这个问题吗？key不存在数据库中，所以直接返回给客户端而无法缓存。黑客正是利用制造的大量不存在的key越过缓存，对数据库直接发起大量请求，算是DOS攻击的一种吧

**Comment by Snailclimb** [comment]
是的。你的说法是没问题的，请求不在数据库中的数据一般情况下也不会在缓存。比如，我们的用户请求数据库表中一个根本不存在的 id ，解决办法就是采用布隆过滤器或者将这个不存在的数据提前缓存在缓存中。

**Comment by Shellbye** [comment]
@wangpeipei90 博主的文章中关于这部分的定义，没有明确提到“而且也不在数据库中”，我觉得这个才是重点。
