### ISSUE TITLE
链接失效问题

### ISSUE THREAD

**Issue by langzigyq** [Snailclimb/JavaGuide#615]
在[java基础知识回顾](https://snailclimb.gitee.io/javaguide/#/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86)中

问题一：5.Java和C++的区别? https://blog.csdn.net/sszgg2006/article/details/49148189。
这里附带的外链有个句号，导致链接过去404，需要把句号去掉

问题二：28. 为什么Java中只有值传递？ 
这里附带的外链也是404

**Comment by LiWenGu** [comment]
可能是生成文档的那时候，代码是老版本。我看现在的源文档是正常的：https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md
可能需要作者重新生成下文档？

**Comment by Snailclimb** [comment]
已经同步最新版本 ！感谢各位老哥！
