### ISSUE TITLE
这里是否也需要进行修正

### ISSUE THREAD

**Issue by caohangwei1314** [Snailclimb/JavaGuide#616]
https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/jvm/JVM%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6.md
![image](https://user-images.githubusercontent.com/38202858/72033796-46c21e00-32ce-11ea-9989-13254afa2b46.png)

https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/jvm/Java%E5%86%85%E5%AD%98%E5%8C%BA%E5%9F%9F.md
![image](https://user-images.githubusercontent.com/38202858/72033808-50e41c80-32ce-11ea-898a-2fb9ee8adf3b.png)

前一个页面的动态对象年龄判定说法没有得到修正，两个页面不一致

**Comment by Snailclimb** [comment]
感谢感谢🙏已经修改完善！
