### ISSUE TITLE
“服务之间的调用为啥不直接用 HTTP 而用 RPC？”这边的错误比较多

### ISSUE THREAD

**Issue by koalarun** [Snailclimb/JavaGuide#619]
1、HTTP和RPC不是一个层面的东西，不能直接比较
2、RPC框架可以使用HTTP协议，也可以不使用HTTP协议；HTTP协议只是RPC框架可选择的一种通讯协议；rest/soap webservice也属于RPC框架，采用http协议通讯；
3、HTTP协议在应用层，传输层也是采用了TCP协议，TCP协议是固定的，大家都一样，不存在HTTP协议的TCP和RCP的TCP的区别；“http1.1协议的 TCP 报文包含太多在传输过程中可能无用的信息”应该修改为http1.1协议自身携带的报文内容太多；而且http1.1采用纯文本形式通讯，存在“队头堵塞”问题，因此效率低；http2采用二进制编码，头压缩，分帧多路复用等技术提高了通讯效率；
4、自定义的私有通讯协议（可以基于TCP、UDP，或基于谷歌最新的QUIC）可以避免HTTP协议自身的一些问题，从而提高通讯效率；

**Comment by Snailclimb** [comment]
理解的很透彻！赞！

**Comment by koalarun** [comment]
"rest/soap webservice也属于RPC框架"这边写错了，rest/soap webservice是属于RPC协议，不是框架。实现rest/soap webservice RPC协议的框架有很多
