### ISSUE TITLE
CountDownLatch的三种典型用法：死锁检测

### ISSUE THREAD

**Issue by rocky-peng** [Snailclimb/JavaGuide#620]
有没有大佬能提供下这个场景的一个代码demo吗？  这个没有理解到。

[CountDownLatch的三种典型用法](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Multithread/AQS.md#41-countdownlatch-%E7%9A%84%E4%B8%89%E7%A7%8D%E5%85%B8%E5%9E%8B%E7%94%A8%E6%B3%95)

**Comment by lc275** [comment]
恐怕也是从哪里抄的[https://www.jianshu.com/p/4b6fbdf5a08f](url)

系统的学习还是建议你看看 java并发编程实战

**Comment by zwxisboy** [comment]
我也没看懂这个
