### ISSUE TITLE
基本类型缓存

### ISSUE THREAD

**Issue by awerdx520** [Snailclimb/JavaGuide#627]
在[缓存](https://snailclimb.gitee.io/javaguide/#/docs/java/jvm/Java%E5%86%85%E5%AD%98%E5%8C%BA%E5%9F%9F?id=_43-8-%e7%a7%8d%e5%9f%ba%e6%9c%ac%e7%b1%bb%e5%9e%8b%e7%9a%84%e5%8c%85%e8%a3%85%e7%b1%bb%e5%92%8c%e5%b8%b8%e9%87%8f%e6%b1%a0)
> Java 基本类型的包装类的大部分都实现了常量池技术，即 Byte,Short,Integer,Long,Character,Boolean；这 5 种包装类默认创建了数值 [-128，127] 的相应类型的缓存数据，但是超出此范围仍然会去创建新的对象.

其中Boolean 直接返回True Or False。Character 的缓存是0-127(\u0000 ~ \u007f)。
```java
public static Boolean valueOf(boolean b) {
    return (b ? TRUE : FALSE);
}
```
``` java
private static class CharacterCache {         
    private CharacterCache(){}
          
    static final Character cache[] = new Character[127 + 1];          
    static {             
        for (int i = 0; i < cache.length; i++)                 
            cache[i] = new Character((char)i);         
    }   
}
```

**Comment by Snailclimb** [comment]
赞赞赞！感谢补充更正！谢谢您！
