### ISSUE TITLE
 JavaGuide/docs/java/Multithread/JavaConcurrencyAdvancedCommonInterviewQuestions.md 

### ISSUE THREAD

**Issue by DemoTransfer** [Snailclimb/JavaGuide#628]
3.3. ThreadLocal原理
====

**每个```Thread```中都具备一个```ThreadLocalMap```，而```ThreadLocalMap```可以存储以```ThreadLocal```为key的键值对。** 比如我们在同一个线程中声明了两个 ```ThreadLocal``` 对象的话，会使用 ```Thread```内部的```ThreadLocalMap```变量存放数据的，```ThreadLocalMap```的 ```key``` 就是 ```ThreadLocal```对象，```value``` 就是 ```ThreadLocal``` 对象调用```set```方法设置的值。ThreadLocal```是map结构是为了让每个线程可以关联多个```ThreadLocal```变量。这也就解释了```ThreadLocal```声明的变量为什么在每一个线程都有自己的专属本地变量。

上述中：```ThreadLocal```是map结构是为了让每个线程可以关联多个```ThreadLocal```变量。这句话描述的并不是很合适。是否可以用下面这段话代替，并且给出相关的图片描述。

![ThreadLocal数据结构](https://upload-images.jianshu.io/upload_images/7432604-ad2ff581127ba8cc.jpg?imageMogr2/auto-orient/strip|imageView2/2/w/806)

> ThreadLocal内部维护的是一个类似Map的ThreadLocalMap数据结构，key为当前对象的Thread对象，值为泛型的Object。

**Comment by Snailclimb** [comment]
好的好的！赞！马上修改。

> ps:希望疫情尽快结束！在家太无赖了哦！
