### ISSUE TITLE
操作系统隐藏 Java虚拟机（JVM）中的 READY 和 RUNNING 状态？

### ISSUE THREAD

**Issue by sandbarTrue** [Snailclimb/JavaGuide#637]
操作系统隐藏 Java虚拟机（JVM）中的 READY 和 RUNNING 状态，它只能看到 RUNNABLE 状态（图源：HowToDoInJava：Java Thread Life Cycle and Thread States），所以 Java 系统一般将这两个状态统称为 RUNNABLE（运行中） 状态 。

这里是不是应该是jvm隐藏了操作系统的READY 和 RUNNING 状态？

另外上面那个图好像有问题，下面的内容没有显示出来

![image](https://user-images.githubusercontent.com/17819209/73995999-5d26cc80-4995-11ea-9f28-802422721c01.png)

**Comment by Snailclimb** [comment]
是的 这里是因为 github 网络问题。你可以去码云看看，速度比较快。

**Comment by sandbarTrue** [comment]
好的
