### ISSUE TITLE
jdk9的接口被允许定义私有方法

### ISSUE THREAD

**Issue by guang19** [Snailclimb/JavaGuide#639]
如题:
![image](https://user-images.githubusercontent.com/41150022/74601451-8fdd6d00-50d9-11ea-921f-d629e936349d.png)

Java越来越复杂了...

希望老哥在这加上:
![image](https://user-images.githubusercontent.com/41150022/74601461-a7b4f100-50d9-11ea-9c75-15fcf8e9d80e.png)

**Comment by Snailclimb** [comment]
好的 感谢老哥！

**Comment by Snailclimb** [comment]
总结一下 jdk7~jdk9 Java 中接口概念的变化：

1. 在 jdk 7 或更早版本中，接口里面只能有常量变量和抽象方法。这些接口方法必须由选择实现接口的类实现。
2. jdk8 的时候接口可以有默认方法和静态方法功能。
3. Jdk 9 在接口中引入了私有方法和私有静态方法。
