### ISSUE TITLE
容器-HashSet如何检查重复

### ISSUE THREAD

**Issue by madanmei** [Snailclimb/JavaGuide#647]
"HashSet会先计算对象的hashcode值来判断对象加入的位置，同时也会与其他加入的对象的hashcode值作比较" 表述不准。应该表述为新加入对象时，java会通过对象的hashcode值来判断对象加入的位置及是否有重复的hashcode。

**Comment by Snailclimb** [comment]
已经修正！如下：

当你把对象加入 HashSet 时，HashSet 会先计算对象的 hashcode 值来判断对象加入的位置，同时也会与该位置其他已经加入的对象的 hashcode 值作比较，如果没有相符的 hashcode，HashSet 会假设对象没有重复出现。但是如果发现有相同 hashcode 值的对象，这时会调用 `equals()`方法来检查 hashcode 相等的对象是否真的相同。如果两者相同，HashSet 就不会让其加入操作成功。如果不同的话，就会重新散列到其他位置。

**Comment by lwmfjc** [comment]
> 已经修正！如下：
> 
> 当你把对象加入 HashSet 时，HashSet 会先计算对象的 hashcode 值来判断对象加入的位置，同时也会与该位置其他已经加入的对象的 hashcode 值作比较，如果没有相符的 hashcode，HashSet 会假设对象没有重复出现。但是如果发现有相同 hashcode 值的对象，这时会调用 `equals()`方法来检查 hashcode 相等的对象是否真的相同。如果两者相同，HashSet 就不会让其加入操作成功。如果不同的话，就会重新散列到其他位置。

你好，这个地方有个疑问，不知道是不是我理解有问题，可以帮忙解答下吗。就是这句话"如果不同的话，就会重新散列到其他位置"，HashSet的底层应该是和HashMap一样的吧，那么如果hash值相同而key不同，是不是应该是使用拉链法放到链表里，而不是重新进行散列到其他位置呢 （我的理解是在同一个数组元素上的链表不同位置）

**Comment by Snailclimb** [comment]
> > 已经修正！如下：
> > 当你把对象加入 HashSet 时，HashSet 会先计算对象的 hashcode 值来判断对象加入的位置，同时也会与该位置其他已经加入的对象的 hashcode 值作比较，如果没有相符的 hashcode，HashSet 会假设对象没有重复出现。但是如果发现有相同 hashcode 值的对象，这时会调用 `equals()`方法来检查 hashcode 相等的对象是否真的相同。如果两者相同，HashSet 就不会让其加入操作成功。如果不同的话，就会重新散列到其他位置。
> 
> 你好，这个地方有个疑问，不知道是不是我理解有问题，可以帮忙解答下吗。就是这句话"如果不同的话，就会重新散列到其他位置"，HashSet的底层应该是和HashMap一样的吧，那么如果hash值相同而key不同，是不是应该是使用拉链法放到链表里，而不是重新进行散列到其他位置呢 （我的理解是在同一个数组元素上的链表不同位置，而不是"重新散列到数组另一个元素上"），谢谢！

HashSet是调用的HashMap的put()方法，而put()方法中有这么一行逻辑，如果哈希值和key都一样，就会直接拿新值覆盖旧值，而HashSet就是利用这个特性来保证唯一性。

```java
 if (p.hash == hash && ((k = p.key) == key || (key != null && key.equals(k))))
     e = p;
```

这是最新的描述：


当你把对象加入HashSet时，HashSet 会先计算对象的hashcode值来判断对象加入的位置，同时也会与其他加入的对象的 hashcode 值作比较，如果没有相符的 hashcode，HashSet 会假设对象没有重复出现。但是如果发现有相同 hashcode 值的对象，这时会调用equals()方法来检查 hashcode 相等的对象是否真的相同。如果两者相同，HashSet 就不会让加入操作成功。

**Comment by lwmfjc** [comment]
> > > 已经修正！如下：
> > > 当你把对象加入 HashSet 时，HashSet 会先计算对象的 hashcode 值来判断对象加入的位置，同时也会与该位置其他已经加入的对象的 hashcode 值作比较，如果没有相符的 hashcode，HashSet 会假设对象没有重复出现。但是如果发现有相同 hashcode 值的对象，这时会调用 `equals()`方法来检查 hashcode 相等的对象是否真的相同。如果两者相同，HashSet 就不会让其加入操作成功。如果不同的话，就会重新散列到其他位置。
> > 
> > 
> > 你好，这个地方有个疑问，不知道是不是我理解有问题，可以帮忙解答下吗。就是这句话"如果不同的话，就会重新散列到其他位置"，HashSet的底层应该是和HashMap一样的吧，那么如果hash值相同而key不同，是不是应该是使用拉链法放到链表里，而不是重新进行散列到其他位置呢 （我的理解是在同一个数组元素上的链表不同位置，而不是"重新散列到数组另一个元素上"），谢谢！
> 
> HashSet是调用的HashMap的put()方法，而put()方法中有这么一行逻辑，如果哈希值和key都一样，就会直接拿新值覆盖旧值，而HashSet就是利用这个特性来保证唯一性。
> 
> ```java
>  if (p.hash == hash && ((k = p.key) == key || (key != null && key.equals(k))))
>      e = p;
> ```
> 
> 这是最新的描述：
> 
> 当你把对象加入HashSet时，HashSet 会先计算对象的hashcode值来判断对象加入的位置，同时也会与其他加入的对象的 hashcode 值作比较，如果没有相符的 hashcode，HashSet 会假设对象没有重复出现。但是如果发现有相同 hashcode 值的对象，这时会调用equals()方法来检查 hashcode 相等的对象是否真的相同。如果两者相同，HashSet 就不会让加入操作成功。

好的~懂了，谢谢你！
