### ISSUE TITLE
异步概念错误

### ISSUE THREAD

**Issue by guang19** [Snailclimb/JavaGuide#650]
![image](https://user-images.githubusercontent.com/41150022/75085617-0bba3800-5566-11ea-847e-829519ecca37.png)

个人认为这句话描述错误:
"被调用者并没有返回结果，此时我们可以处理其他的请求，被调用者通常依靠事件，回调等机制来通知调用者其返回结果。"

同步:
比如调用一个方法计算1 - 100的和，如果该方法没有计算完成，那么该方法就不返回。

异步:
异步需要操作系统的支持。
调用一个方法计算1-100的和，刚调用这个方法就返回了，但是由于它没有返回结果，所以需要被调用的这个方法来通知调用者，或者通过一个回调函数来告诉被调用的方法在计算出结果后该做些什么。

阻塞:
比如调用一个方法计算1-100的和。如果该方法一直计算，没有返回，那么调用方法的线程就必须等待方法执行完成。

非阻塞:
比如调用一个方法计算1-100的和。就算该方法一直计算，不返回，当前线程也不必一直阻塞的等待方法的结果，而是中途可以去做其它的事情,但也要轮询的检查方法是否处理完。

>我所理解的同步与异步的概念是针对被调用者而言的，阻塞与非阻塞是针对调用者而言的。

>同步/异步与阻塞/非阻塞这2组概念一毛钱关系都没有，虽然上面举的烧水的例子确实没错，但很容易让人以为这2组概念有啥关系。。

**Comment by Snailclimb** [comment]
> ![image](https://user-images.githubusercontent.com/41150022/75085617-0bba3800-5566-11ea-847e-829519ecca37.png)
> 
> 个人认为这句话描述错误:
> "被调用者并没有返回结果，此时我们可以处理其他的请求，被调用者通常依靠事件，回调等机制来通知调用者其返回结果。"
> 
> 同步:
> 比如调用一个方法计算1 - 100的和，如果该方法没有计算完成，那么该方法就不返回。
> 
> 异步:
> 异步需要操作系统的支持。
> 调用一个方法计算1-100的和，刚调用这个方法就返回了，但是由于它没有返回结果，所以需要被调用的这个方法来通知调用者，或者通过一个回调函数来告诉被调用的方法在计算出结果后该做些什么。
> 
> 阻塞:
> 比如调用一个方法计算1-100的和。如果该方法一直计算，没有返回，那么调用方法的线程就必须等待方法执行完成。
> 
> 非阻塞:
> 比如调用一个方法计算1-100的和。就算该方法一直计算，不返回，当前线程也不必一直阻塞的等待方法的结果，而是中途可以去做其它的事情,但也要轮询的检查方法是否处理完。
> 
> > 我所理解的同步与异步的概念是针对被调用者而言的，阻塞与非阻塞是针对调用者而言的。
> 
> > 同步/异步与阻塞/非阻塞这2组概念一毛钱关系都没有，虽然上面举的烧水的例子确实没错，但很容易让人以为这2组概念有啥关系。。

感谢更正！确实有问题，我觉得我最开始对异步的描述有点像是反应式编程。

**Comment by Snailclimb** [comment]
这两个概念实在让人头大，网上的回答也是千姿百态！太难了。
