### ISSUE TITLE
Java基础知识12-AbstractStringBuilder类中不是使用char[]数组保存字符串, 而是byte[]

### ISSUE THREAD

**Issue by theoYe** [Snailclimb/JavaGuide#655]
AbstractStringBuilder类中不是使用char[]数组保存字符串, 而是byte[]
如下图

![image](https://user-images.githubusercontent.com/55373826/75324472-fe78b280-58b1-11ea-8cad-8af871ea0fb3.png)

**Comment by Snailclimb** [comment]
> AbstractStringBuilder类中不是使用char[]数组保存字符串, 而是byte[]
> 如下图
> 
> ![image](https://user-images.githubusercontent.com/55373826/75324472-fe78b280-58b1-11ea-8cad-8af871ea0fb3.png)

感谢你的更正！JavaGuide有你变得更好！
