### ISSUE TITLE
泛型的实际应用章节的问题

### ISSUE THREAD

**Issue by wangyuheng** [Snailclimb/JavaGuide#659]
[gitee](https://snailclimb.gitee.io/javaguide/#/docs/java/Java%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E9%A2%98?id=%e4%bd%bf%e7%94%a8%e6%95%b0%e7%bb%84%e5%ae%9e%e7%8e%b0%e6%a0%88)

[github](https://github.com/Snailclimb/JavaGuide/blob/78813345a39efc808a4206bcf00aecca378ec249/docs/java/Java%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E9%A2%98.md)

```java
    //TODO：返回栈顶元素并出栈
    private int pop() {
        count--;
        if (count == -1)
            throw new IllegalArgumentException("Stack is empty.");

        return storage[count];
    }
```

如果先执行 `count--` 当Exception被捕获之后，count数值会偏差，导致push数据时ArrayIndexOutOfBoundsException

**Comment by Snailclimb** [comment]
正解！感谢老哥！
