### ISSUE TITLE
补充类初始化的可能情况

### ISSUE THREAD

**Issue by guang19** [Snailclimb/JavaGuide#661]
![image](https://user-images.githubusercontent.com/41150022/75540656-63214200-5a57-11ea-9c63-7183b5645f67.png)

如上所写的：“比如 new 一个类，读取一个静态字段(未被 final 修饰)、或调用一个类的静态方法时。”

应该是遇到一条new指令，即创建一个类的实例对象时，会初始化对象。
我整理了一下可能的情况:

>只有主动去使用类才会初始化类，总共有8种情况会涉及到主动使用类。

1. 当jvm执行new指令时会初始化类。即当程序创建一个类的实例对象。
2. 当jvm执行getstatic指令时会初始化类。即程序访问类的静态变量(不是静态常量，常量会被加载到运行时常量池)。
3. 当jvm执行putstatic指令时会初始化类。即程序给类的静态变量赋值。
4. 当jvm执行invokestatic指令时会初始化类。即程序调用类的静态方法。
5. 当使用反射主动调用这个类时,也会初始化类,如Class.forname("..."),newInstance()等等。
6. 当初始化子类的时候，会先初始化这个子类的所有父类，然后才会初始化这个子类。
7. 当一个类是启动类时，即这个类拥有main方法，那么jvm会首先初始化这个类。
8. MethodHandle和VarHandle可以看作是轻量级的反射调用机制，而要想使用这2个调用，
就必须先使用findStaticVarHandle来初始化要调用的类。

**Comment by Snailclimb** [comment]
这部分内容已经更新同步！感谢老哥！建议老哥可以尝试采用提 pr 的形式，这样处理速度快一点。
