### ISSUE TITLE
Full GC和 Major GC是不同的

### ISSUE THREAD

**Issue by guang19** [Snailclimb/JavaGuide#664]
![image](https://user-images.githubusercontent.com/41150022/75743705-d7583000-5d4c-11ea-867a-5efb20427057.png)

个人在网上查阅相关资料的时候发现如题所说的观点。
有的文章说 Full GC与Major GC一样是属于对老年代的GC，
也有的文章说 Full GC 是对整个堆区的GC，所以这点需要各位同学自行
分辨Full GC语义。
见: [知乎讨论](https://www.zhihu.com/question/41922036)

**Comment by Snailclimb** [comment]
好的 老哥细致啊！👍

**Comment by Snailclimb** [comment]
![Screen Shot 2020-03-04 at 12 15 36 PM](https://user-images.githubusercontent.com/29880145/75844747-efde4e00-5e11-11ea-9d32-3b3ed28bbbcd.jpg)

**Comment by hulu888** [comment]
full gc收集的是整个堆和方法区
![截屏2020-05-20 下午10 11 18](https://user-images.githubusercontent.com/12171626/82456573-fd3cd780-9ae6-11ea-83c8-348a0ae133fa.png)
出自《深入理解Java虚拟机：JVM高级特性与最佳实践》（第三版）
