### ISSUE TITLE
回文串构成的第二种情况定义有误

### ISSUE THREAD

**Issue by heibai23** [Snailclimb/JavaGuide#665]
+ 位置：算法-几道常见的子符串算法题-4.1
+ 内容：字符出现次数为双数的组合+一个只出现一次的字符
+ 有误点：只出现一次有误，因为也可以是出现三次、五次
   + 例子：aabbcccd，此时最长应为 abcccba，c出现为三次
+ 个人见解：应该为**字符出现次数为偶数的组合+单个字符中出现次数最多且为奇数次的字符**

**Comment by timmmGZ** [comment]
同意

**Comment by Snailclimb** [comment]
> * 位置：算法-几道常见的子符串算法题-4.1
> * 内容：字符出现次数为双数的组合+一个只出现一次的字符
> * 有误点：只出现一次有误，因为也可以是出现三次、五次
>   
>   * 例子：aabbcccd，此时最长应为 abcccba，c出现为三次
> * 个人见解：应该为**字符出现次数为偶数的组合+单个字符中出现次数最多且为奇数次的字符**

已经更改，感谢老哥！

**Comment by orekiJY** [comment]
还是有问题...
依照题意，即使某个字符出现总次数为奇数2n+1，也可以使用其中的2n个字符来组成对称字符串
无论字符是否出现最多次，都应该尽可能用上该字符，最后再根据是否存在奇数+1
