### ISSUE TITLE
Java反射的内容跳到了404。目测是链接里的大小写写错了吧……

### ISSUE THREAD

**Issue by linhui0705** [Snailclimb/JavaGuide#667]
RT

![Snip20200304_2](https://user-images.githubusercontent.com/13863156/75838574-43946b80-5e01-11ea-90b8-c459cdb524d6.png)

![Snip20200304_1](https://user-images.githubusercontent.com/13863156/75838565-4000e480-5e01-11ea-8d79-bddb8a20fad4.png)

![Snip20200304_5](https://user-images.githubusercontent.com/13863156/75838729-af76d400-5e01-11ea-98eb-98fbaf938a1a.png)

**Comment by linhui0705** [comment]
点开的链接是小写字母b，而实际上是大写的

**Comment by Snailclimb** [comment]
感谢，已经修复！
