### ISSUE TITLE
JVM垃圾回收一节中晋升年龄问题

### ISSUE THREAD

**Issue by LoenDou** [Snailclimb/JavaGuide#672]
关于默认的晋升年龄是15，这个说法的来源大部分都是《深入理解Java虚拟机》这本书。
如果你去Oracle的官网阅读[相关的虚拟机参数](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/java.html)，你会发现在-XX:MaxTenuringThreshold=threshold这里有个说明，Sets the maximum tenuring threshold for use in adaptive GC sizing. The largest value is 15. The default value is 15 for the parallel (throughput) collector, and 6 for the CMS collector.
默认晋升年龄并不都是15，这个是要区分垃圾收集器的，CMS就是6.

**Comment by Snailclimb** [comment]
嗯嗯 感谢老哥！这部分大家确实都是看《深入理解Java虚拟机》这本书的！

**Comment by ambition0802** [comment]
太细节了，这位大兄弟，点赞。
