### ISSUE TITLE
JavaGuide/docs/java/Java程序设计题.md中的错误

### ISSUE THREAD

**Issue by TaiPark** [Snailclimb/JavaGuide#673]
文中使用数组实现栈代码内：
`//TODO：返回栈顶元素并出栈
    private int pop() {
        if (count == -1)
            throw new IllegalArgumentException("Stack is empty.");
        count--;
        return storage[count];
    }`
实际运行后发现当count==0时，栈已为空，此时做count--操作会报错：
`storage[count]=java.lang.IndexOutOfBoundsException:Invalid array index:-1`
是否应该将报空的条件修改为：
`if(count == 0)`

**Comment by Snailclimb** [comment]
好的 感谢提醒！👍
