### ISSUE TITLE
建议添加PWA支持

### ISSUE THREAD

**Issue by Gahon1995** [Snailclimb/JavaGuide#674]
建议能够添加pwa支持，这样在移动端使用时能够更加方便快速的浏览

**Comment by Snailclimb** [comment]
刚刚查了一下 PWA 的解释：https://juejin.im/post/5a6c86e451882573505174e7 。目前提供了在线阅读：https://snailclimb.gitee.io/javaguide/#/ ，pdf 版本预计今晚更新出来，详见Readme。

**Comment by Gahon1995** [comment]
我看那个docsify有pwa支持的配置，所以想着加进去的话阅读体验会不会好一点

**Comment by Snailclimb** [comment]
已经加了[pwa](https://github.com/Snailclimb/JavaGuide/commit/36b025c6b40ae7df7ca5bd2c0bd929327739bbcb)，不过由于我的图片存放在阿里云 oss ，没网的情况下还是无法访问图片。
