### ISSUE TITLE
招聘贴：阿里巴巴消息业务/基础团队招聘（校招/社招）

### ISSUE THREAD

**Issue by hepin1989** [Snailclimb/JavaGuide#676]
我们团队都是Java哈，也有cpp、ios和android，大家刷好题了就可以随时来碾压我们了。欢迎大家加入。
招聘, 微信：kerisle，
大家也可以直接发邮件
hepin.p@alibaba-inc.com

![image](https://user-images.githubusercontent.com/501740/76274299-353fc700-62bb-11ea-8e9d-2a0c080ab336.png)

**Comment by yuanjinzhong** [comment]
@hepin1989   何品大神，买了你翻译的netty

**Comment by hepin1989** [comment]
@yuanjinzhong 不好意思，在这里丢人了，招人比较困难，你感兴趣吗？可以来聊一下。社招也有的。

**Comment by Snailclimb** [comment]
我来个大佬点个赞！哈哈

**Comment by ambition0802** [comment]
何品老师  招聘持续多久啊

**Comment by hepin1989** [comment]
@ambition0802 校招的话可能最近会结束了；社招是一直有的。您这边感兴趣吗？我们面试的题目都相对简单，不需要刷leecode

**Comment by Apache001** [comment]
不会netty呀

**Comment by HaiminLi** [comment]
进入阿里对我来说有点难了，何品老师给点建议，指点迷津

**Comment by hepin1989** [comment]
@HaiminLi 可以加微信探讨，都有个过程的，没有那么难，你可以的。

**Comment by hepin1989** [comment]
@Apache001 只是考察下网络知识，并发什么的而已哈

**Comment by guang19** [comment]
前辈,大专要吗? ~_~

**Comment by Snailclimb** [comment]
> 前辈,大专要吗? ~_~

哈哈 老哥 技术过硬，好好把握机会啊！

**Comment by guang19** [comment]
嗯嗯

**Comment by ambition0802** [comment]
> @ambition0802 校招的话可能最近会结束了；社招是一直有的。您这边感兴趣吗？我们面试的题目都相对简单，不需要刷leecode

好的  是有兴趣的，毕业在现在公司快干了三年了，有打算跳槽。过小段时间准备好了 我主动联系你吧

**Comment by hepin1989** [comment]
@ambition0802 感谢，我自己所在的团队是消息基础团队，上层还有业务团队啥的，反正我觉得选择面比较广的。

**Comment by Snailclimb** [comment]
> 嗯嗯

老哥 加了我微信不？私聊一下呗！

**Comment by hepin1989** [comment]
@Snailclimb 没收到请求，不好意思，我的微信是 kerisle

**Comment by hw118118** [comment]
经验少简历很难过，但是java基础不错以及源码理解不错，个人感觉实力挺不错的，可以尝试吗？大神
