### ISSUE TITLE
关于static静态代码块的执行时间问题

### ISSUE THREAD

**Issue by MatrixFour** [Snailclimb/JavaGuide#677]
在作者的原文中**javaguide/#/docs/java/basic/final、static、this、super.md**是这样描述的：
>**静态代码块只在第一次new执行一次**，之后不再执行，而非静态代码块在每new一次就执行一次。
     
&emsp;但我认为作者的描述不够全面，静态代码块可能在第一次new的时候执行，但不一定只在第一次new的时候执行。
&emsp;参考博客[java的static块执行时机](https://blog.csdn.net/berber78/article/details/46472789)的介绍，第一次new属于初始化阶段，但初始化阶段除了第一次new还有其他的可能，请作者再更新文档，添加详细的介绍。
&emsp;谢谢！

**Comment by AlisaBen** [comment]
unsubscribe

**Comment by Snailclimb** [comment]
> 在作者的原文中**javaguide/#/docs/java/basic/final、static、this、super.md**是这样描述的：
> 
> > **静态代码块只在第一次new执行一次**，之后不再执行，而非静态代码块在每new一次就执行一次。
> 
>  但我认为作者的描述不够全面，静态代码块可能在第一次new的时候执行，但不一定只在第一次new的时候执行。
>  参考博客[java的static块执行时机](https://blog.csdn.net/berber78/article/details/46472789)的介绍，第一次new属于初始化阶段，但初始化阶段除了第一次new还有其他的可能，请作者再更新文档，添加详细的介绍。
>  谢谢！

收到！🙏感谢

**Comment by jal1234** [comment]
.....

**Comment by miemiehoho** [comment]
static静态代码块 是在类初始化的时候执行的，和 new或者 Class.forName("ClassDemo")  没有任何关系。
