### ISSUE TITLE
布隆过滤器代码执行报OOM错误

### ISSUE THREAD

**Issue by Anastasia-Zhang** [Snailclimb/JavaGuide#681]
你好，我在执行你写的布隆过滤器的代码的时候，调用 `String value1 = "https://javaguide.cn/";` ` filter.add(value1);` 的时候
报以下错误：
`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3308)
	at java.util.BitSet.ensureCapacity(BitSet.java:337)
	at java.util.BitSet.expandTo(BitSet.java:352)
	at java.util.BitSet.set(BitSet.java:447)
	at java.util.BitSet.set(BitSet.java:464)
	at BloomFilter.add(BloomFilter.java:62)
	at BloomFilter.main(BloomFilter.java:85)`
不知道大家有没有出现过这种错误，我试着调整运行时堆内存大小，有的时候会运行无错，有的时候会运行出错。

**Comment by Snailclimb** [comment]
> 你好，我在执行你写的布隆过滤器的代码的时候，调用 `String value1 = "https://javaguide.cn/";` ` filter.add(value1);` 的时候
> 报以下错误：
> `Exception in thread "main" java.lang.OutOfMemoryError: Java heap space at java.util.Arrays.copyOf(Arrays.java:3308) at java.util.BitSet.ensureCapacity(BitSet.java:337) at java.util.BitSet.expandTo(BitSet.java:352) at java.util.BitSet.set(BitSet.java:447) at java.util.BitSet.set(BitSet.java:464) at BloomFilter.add(BloomFilter.java:62) at BloomFilter.main(BloomFilter.java:85)`
> 不知道大家有没有出现过这种错误，我试着调整运行时堆内存大小，有的时候会运行无错，有的时候会运行出错。

解决了么？我没遇到过这个问题。
