### ISSUE TITLE
Java并发包里面的并发基础语句错误

### ISSUE THREAD

**Issue by Fsym3cm** [Snailclimb/JavaGuide#682]
在第五节，第一段多了一个不会

**Comment by Fsym3cm** [comment]
第七节，第二段切换会 --> 回

**Comment by Snailclimb** [comment]
> 在第五节，第一段多了一个不会

老哥 文章具体位置能说一下，根据你的描述我未能定位到正确位置。

**Comment by Fsym3cm** [comment]
JavaGuide/docs/java/Multithread/并发编程基础知识.md
第五节 线程优先级 第一段，第二行两个不会不会
第七节 上下文切换 第二段，第一行切换会 -> 切换回

**Comment by yangxiaozz** [comment]
—



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chengzimm"; 
发送时间: 2020年3月16日(星期一) 下午4:01
收件人: "Snailclimb/JavaGuide";
抄送: "Subscribed";
主题: Re: [Snailclimb/JavaGuide] Java并发包里面的并发基础语句错误 (#682)





 
第七节，第二段切换会 --&gt; 回
 
&mdash;

**Comment by Snailclimb** [comment]
> JavaGuide/docs/java/Multithread/并发编程基础知识.md
> 第五节 线程优先级 第一段，第二行两个不会不会
> 第七节 上下文切换 第二段，第一行切换会 -> 切换回

老哥 你看的什么版本？这个文件我已经没用了。
