### ISSUE TITLE
Java Guide PDF 35点中NIO解释错误

### ISSUE THREAD

**Issue by Cherrymelon** [Snailclimb/JavaGuide#684]
> NIO (New I/O)

NIO为Non-blocking IO

**Comment by Saiyueze** [comment]
> > NIO (New I/O)
> 
> NIO为Non-blocking IO

NIO 解释成 (New I/O) 不完全错误，这个可以去查 java 1.4 的手册。

**Comment by halk947** [comment]
> > > NIO (New I/O)
> > 
> > 
> > NIO为Non-blocking IO
> 
> NIO 解释成 (New I/O) 不完全错误，这个可以去查 java 1.4 的手册。

根据维基百科，还是NIO更合理

https://en.wikipedia.org/wiki/Non-blocking_I/O_(Java)

**Comment by Snailclimb** [comment]
已经修改完善！感谢指出！
