### ISSUE TITLE
关于CountDownLatch 死锁检测的用法 疑问

### ISSUE THREAD

**Issue by zwxisboy** [Snailclimb/JavaGuide#685]
#死锁检测：一个非常方便的使用场景是，你可以使用 n 个线程访问共享资源，在每次测试阶段的线程数目是不同的，并尝试产生死锁。#
没看懂，搜了一下大部分都是在讲怎么运用CountDownLatch 制造死锁，有没有人能举例一下？

**Comment by Snailclimb** [comment]
刚刚看了一下这里的描述,有点迷惑，我删除了这部分描述。CountDownLatch的await使用不当的话很容易产生死锁。
