### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by deepforce** [Snailclimb/JavaGuide#688]
**Issue:**
[Java基础知识](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md)中 _4. Oracle JDK 和 OpenJDK_ 的对比 的第一点的链接失效了。

**ScreenShot:**
![image](https://user-images.githubusercontent.com/10813672/77249614-b83c1800-6bff-11ea-9d0a-36a78bca8fe7.png)

**Suggestion:**
删除Markdown链接里最后的句号。

**Comment by Snailclimb** [comment]
> **Issue:**
> [Java基础知识](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md)中 _4. Oracle JDK 和 OpenJDK_ 的对比 的第一点的链接失效了。
> 
> **ScreenShot:**
> ![image](https://user-images.githubusercontent.com/10813672/77249614-b83c1800-6bff-11ea-9d0a-36a78bca8fe7.png)
> 
> **Suggestion:**
> 删除Markdown链接里最后的句号。

收到！

**Comment by Snailclimb** [comment]
> > **Issue:**
> > [Java基础知识](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.md)中 _4. Oracle JDK 和 OpenJDK_ 的对比 的第一点的链接失效了。
> > **ScreenShot:**
> > ![image](https://user-images.githubusercontent.com/10813672/77249614-b83c1800-6bff-11ea-9d0a-36a78bca8fe7.png)
> > **Suggestion:**
> > 删除Markdown链接里最后的句号。
> 
> 收到！
