### ISSUE TITLE
Java基础知识部分第36点关于静态代码块的描述有误

### ISSUE THREAD

**Issue by CodeASN** [Snailclimb/JavaGuide#692]
[链接:](https://snailclimb.gitee.io/javaguide/#/docs/java/basic/final,static,this,super?id=static%e9%9d%99%e6%80%81%e4%bb%a3%e7%a0%81%e5%9d%97%e4%b8%8e%e9%9d%9e%e9%9d%99%e6%80%81%e4%bb%a3%e7%a0%81%e5%9d%97%e6%9e%84%e9%80%a0%e4%bb%a3%e7%a0%81%e5%9d%97)

原文是:

> "当执行 Test.test(); 时输出：
> 
> 静态代码块!--静态方法中的内容! --静态方法中的代码块！--"

实际上静态代码块只会执行一次,调用test()的时候不会执行

**Comment by wangpeipei90** [comment]
同意。
```
Test test=new Test();
Test.test();
```
输出
```
静态代码块！--非静态代码块！--默认构造方法！
静态方法中的内容! --静态方法中的代码块！--
```
单独
```
Test.test()
```
输出
```
静态代码块！--静态方法中的内容! --静态方法中的代码块！--
```

**Comment by Snailclimb** [comment]
这部分内容已经更正，感谢你们指出！
