### ISSUE TITLE
关于《一条sql语句在mysql中如何执行的》中的疑问

### ISSUE THREAD

**Issue by cafe3165** [Snailclimb/JavaGuide#697]
**2.2更新语句**

 以上就是一条查询 sql 的执行流程，那么接下来我们看看一条更新语句如何执行的呢？sql 语句如下：
update tb_student A set A.age='19' where A.name=' 张三 ';
我们来给张三修改下年龄，在实际数据库肯定不会设置年龄这个字段的，不然要被技术负责人打的。

> **为什么不能设置年龄这个字段？**

**Comment by ttr5966** [comment]
年龄字段当然不需要我们设置  他是自然增长的啊  ------------------ 原始邮件 ------------------
发件人: "Joseph"<notifications@github.com>
发送时间: 2020年3月27日(星期五) 中午12:54
收件人: "Snailclimb/JavaGuide"<JavaGuide@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Snailclimb/JavaGuide] 关于《一条sql语句在mysql中如何执行的》中的疑问 (#697)




 
2.2更新语句
 
以上就是一条查询 sql 的执行流程，那么接下来我们看看一条更新语句如何执行的呢？sql 语句如下：
 update tb_student A set A.age='19' where A.name=' 张三 ';
 我们来给张三修改下年龄，在实际数据库肯定不会设置年龄这个字段的，不然要被技术负责人打的。
  
为什么不能设置年龄这个字段？
  
&mdash;

**Comment by Snailclimb** [comment]
> **2.2更新语句**
> 
> 以上就是一条查询 sql 的执行流程，那么接下来我们看看一条更新语句如何执行的呢？sql 语句如下：
> update tb_student A set A.age='19' where A.name=' 张三 ';
> 我们来给张三修改下年龄，在实际数据库肯定不会设置年龄这个字段的，不然要被技术负责人打的。
> 
> > **为什么不能设置年龄这个字段？**



> **2.2更新语句**
> 
> 以上就是一条查询 sql 的执行流程，那么接下来我们看看一条更新语句如何执行的呢？sql 语句如下：
> update tb_student A set A.age='19' where A.name=' 张三 ';
> 我们来给张三修改下年龄，在实际数据库肯定不会设置年龄这个字段的，不然要被技术负责人打的。
> 
> > **为什么不能设置年龄这个字段？**

我去改改这部分，的确不用设置，哈哈！

**Comment by wangpeipei90** [comment]
年龄确实每年都在变化的。所以正确做法是set birthday,然后查询age的时候通过birthday和当前时间确定age
