### ISSUE TITLE
算法总结——几道常见的子符串算法题------把字符串转换成整数

### ISSUE THREAD

**Issue by niyiwei** [Snailclimb/JavaGuide#70]
https://github.com/Snailclimb/JavaGuide/blob/master/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E4%B8%8E%E7%AE%97%E6%B3%95/%E6%90%9E%E5%AE%9ABAT%E9%9D%A2%E8%AF%95%E2%80%94%E2%80%94%E5%87%A0%E9%81%93%E5%B8%B8%E8%A7%81%E7%9A%84%E5%AD%90%E7%AC%A6%E4%B8%B2%E7%AE%97%E6%B3%95%E9%A2%98.md
把字符串转换成整数如果传入的字符串没有 + 或者 - 号则 flag=0，那样会默认返回负数结果。
int flag = 0;
    if (chars[0] == '+')
      flag = 1;
    else if (chars[0] == '-')
      flag = 2;
return flag == 1 ? res : -res;

如 “123” flag = 0  返回 -123

**Comment by Snailclimb** [comment]
你好  不用的哦 ！请仔细查看代码。
```java
	public static int StrToInt(String str) {
		if (str.length() == 0)
			return 0;
		char[] chars = str.toCharArray();
		// 判断是否存在符号位
		int flag = 0;
		if (chars[0] == '+')
			flag = 1;
		else if (chars[0] == '-')
			flag = 2;
		int start = flag > 0 ? 1 : 0;
		int res = 0;// 保存结果
		for (int i = start; i < chars.length; i++) {
			if (Character.isDigit(chars[i])) {// 调用Character.isDigit(char)方法判断是否是数字，是返回True，否则False
				int temp = chars[i] - '0';
				res = res * 10 + temp;
			} else {
				return 0;
			}
		}
		return flag == 1 ? res : -res;

	}
```

**Comment by niyiwei** [comment]
您好，您可以尝试运行一下传入 ”123“ 这样的参数试试

**Comment by ZS9527** [comment]
`flag == 1 ? res : -res;` 
你好。当字符串没有“+”，“-”前缀导致flag为0的时候，不是会自动加入-号的吗？

**Comment by niyiwei** [comment]
> `flag == 1 ? res : -res;`
> 你好。当字符串没有“+”，“-”前缀导致flag为0的时候，不是会自动加入-号的吗？

自动加入-号不就是错误的答案么？负数

**Comment by ZS9527** [comment]
> > `flag == 1 ? res : -res;`
> > 你好。当字符串没有“+”，“-”前缀导致flag为0的时候，不是会自动加入-号的吗？
> 
> 自动加入-号不就是错误的答案么？负数

我初学者，不太清楚是不是故意这么设置的，还是我看的不全。
