### ISSUE TITLE
操作系统关于LFU描述有误

### ISSUE THREAD

**Issue by DeaglePC** [Snailclimb/JavaGuide#703]
>LFU页面置换算法（最少使用页面排序算法） : LFU（Least Frequently Used）算法会让系统维护一个按最近一次访问时间排序的页面链表，链表首节点是最近刚刚使用过的页面，链表尾节点是最久未使用的页面。访问内存时，找到相应页面，并把它移到链表之首。缺页时，置换链表尾节点的页面。也就是说内存内使用越频繁的页面，被保留的时间也相对越长。

这里开头说`算法会让系统维护一个按最近一次访问时间排序的页面链表，链表首节点是最近刚刚使用过的页面，链表尾节点是最久未使用的页面。访问内存时，找到相应页面，并把它移到链表之首。`这里明显是在说LRU呀，和后面的`也就是说内存内使用越频繁的页面，被保留的时间也相对越长。
`矛盾，应该改为 **按照使用的频率排序，最先淘汰掉使用频率低的，而不是最久未使用的**。

**Comment by wangpeipei90** [comment]
From wikipedia:
The simplest method to employ an LFU algorithm is to assign a counter to every block that is loaded into the cache. Each time a reference is made to that block the counter is increased by one. When the cache reaches capacity and has a new block waiting to be inserted the system will search for the block with the lowest counter and remove it from the cache.

**Comment by Snailclimb** [comment]
已经修改！感谢指出。
