### ISSUE TITLE
使用索引的注意事项？  相关疑问

### ISSUE THREAD

**Issue by cafe3165** [Snailclimb/JavaGuide#705]
其中第7点：
7. 在使用InnoDB时使用与业务无关的自增主键作为主键，即使用逻辑主键，而不要使用业务主键。

为什么呀？

**Comment by ttr5966** [comment]
使用业务主键如果要修改频繁的话  会造成之后查询的不方便吧------------------ 原始邮件 ------------------
发件人: "Joseph"<notifications@github.com>
发送时间: 2020年4月1日(星期三) 上午8:32
收件人: "Snailclimb/JavaGuide"<JavaGuide@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Snailclimb/JavaGuide] 使用索引的注意事项？  相关疑问 (#705)




 
其中第7点：
 7. 在使用InnoDB时使用与业务无关的自增主键作为主键，即使用逻辑主键，而不要使用业务主键。
 
为什么呀？
 
&mdash;

**Comment by wangpeipei90** [comment]
@ttr5966 能不能具体解释一下为什么业务主键频繁修改就会造成查询的不方便呢？

**Comment by ttr5966** [comment]
Mysql底层是使用的InnoDB，主键是聚簇索引，主键索引位置同时存储索引值和该行记录。 在B+树的数据结构中叶子节点存储数据，如果没定义主键，则会使用非空且唯一的字段，默认为作为主键，如果前面两者都不存在则使用内置6个字节长度的行标ROWID作为主键。在定义主键非自增id，那么计算主键索引值可能每次结果都不会出现连续的，这样在插入B+树叶子节点的时候，就不会在最后一个叶子节点尾部插入。而是中间某个叶子节点插入节点，导致插入数据需要不断对页数据进行重排，效率会明显降低------------------ 原始邮件 ------------------
发件人: "wangpeipei90"<notifications@github.com>
发送时间: 2020年4月2日(星期四) 上午9:49
收件人: "Snailclimb/JavaGuide"<JavaGuide@noreply.github.com>;
抄送: "ttr5966"<1484465887@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Snailclimb/JavaGuide] 使用索引的注意事项？  相关疑问 (#705)




 
@ttr5966 能不能具体解释一下为什么业务主键频繁修改就会造成查询的不方便呢？
 
&mdash;
