### ISSUE TITLE
这里的异常类似乎写错了

### ISSUE THREAD

**Issue by mikeygithub** [Snailclimb/JavaGuide#708]
![image](https://user-images.githubusercontent.com/36464578/78275267-f14f8300-7543-11ea-99e3-6426bb4ba813.png)

**Comment by Snailclimb** [comment]
你好，拼写错了吗？建议好好阅读最基本的向别人提交issue的基本准则，对你有用的。
![](https://imgkr.cn-bj.ufileos.com/ae9a3c70-5892-4d55-ae4f-273c5325e3df.png)
