### ISSUE TITLE
Redis数据结构编码

### ISSUE THREAD

**Issue by FuPingstar** [Snailclimb/JavaGuide#716]
Redis数据结构那篇，每种数据结构Guide哥都只说了一种编码，其实Redis的每种数据结构都至少对应了两种编码，对应编码转换与存储的数据有关，可以说的详细一些吗

**Comment by Snailclimb** [comment]
> Redis数据结构那篇，每种数据结构Guide哥都只说了一种编码，其实Redis的每种数据结构都至少对应了两种编码，对应编码转换与存储的数据有关，可以说的详细一些吗

刚刚对这部分内容加了相关说明，可以的话老哥可以帮忙完善下，最近没有精力做这件事情。

**Comment by FuPingstar** [comment]
请问一下，给这个项目贡献的方式，pr？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"SnailClimb"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 晚上9:07
收件人:&nbsp;"Snailclimb/JavaGuide"<JavaGuide@noreply.github.com&gt;;
抄送:&nbsp;"fupingstar"<1442038633@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Snailclimb/JavaGuide] Redis数据结构编码 (#716)





  
Redis数据结构那篇，每种数据结构Guide哥都只说了一种编码，其实Redis的每种数据结构都至少对应了两种编码，对应编码转换与存储的数据有关，可以说的详细一些吗
  
刚刚对这部分内容加了相关说明，可以的话老哥可以帮忙完善下，最近没有精力做这件事情。

**Comment by Snailclimb** [comment]
> 请问一下，给这个项目贡献的方式，pr？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"SnailClimb"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月7日(星期二) 晚上9:07 收件人:&nbsp;"Snailclimb/JavaGuide"<JavaGuide@noreply.github.com&gt;; 抄送:&nbsp;"fupingstar"<1442038633@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Snailclimb/JavaGuide] Redis数据结构编码 (#716) Redis数据结构那篇，每种数据结构Guide哥都只说了一种编码，其实Redis的每种数据结构都至少对应了两种编码，对应编码转换与存储的数据有关，可以说的详细一些吗 刚刚对这部分内容加了相关说明，可以的话老哥可以帮忙完善下，最近没有精力做这件事情。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是的！👍
