### ISSUE TITLE
Java基础知识18.4成员变量如果没有被赋初值，则会自动以类型的默认值而赋值（一种情况例外被 final 修饰但没有被 static 修饰的成员变量必须显示地赋值）；而局部变量则不会自动赋值。

### ISSUE THREAD

**Issue by Gene1994** [Snailclimb/JavaGuide#72]
Java基础知识18.4
原文：成员变量如果没有被赋初值，则会自动以类型的默认值而赋值（一种情况例外被 final 修饰但没有被 static 修饰的成员变量必须显示地赋值）；而局部变量则不会自动赋值。
我试了一下 同时被final 和 static修饰的变量也需要被显示地赋值？这里是作者笔误吗？还是我理解的不对？

**Comment by Snailclimb** [comment]
已更正！
