### ISSUE TITLE
Paxos算法是1998年诞生的

### ISSUE THREAD

**Issue by StupidTortoise** [Snailclimb/JavaGuide#724]
Paxos算法是1998年诞生的，不是1898年

**Comment by IZ-ZI** [comment]
https://en.wikipedia.org/wiki/Paxos_(computer_science)

**Comment by Snailclimb** [comment]
90年就提出来了，只是98年才被发表论文。

**Comment by wangpeipei90** [comment]
The Paxos protocol was first published in 1989, not 1900. 
在system-design/website-architecture/分布式.md中写道：早在1900年就诞生了著名的 Paxos经典算法 （Zookeeper就采用了Paxos算法的近亲兄弟Zab算法）
