### ISSUE TITLE
关于git入门的操作推荐网站

### ISSUE THREAD

**Issue by lingr7** [Snailclimb/JavaGuide#729]
Learn Git Branching  https://oschina.gitee.io/learn-git-branching/
以上网站可以方便的演示基本的git操作，讲解得明明白白。每一个基本命令的作用和结果。
建议添加进去。

**Comment by Snailclimb** [comment]
爱了爱了！

**Comment by lingr7** [comment]
发现同样功能的网站，访问要方便一点，两个应该同出一源吧。[Learn Git Branching](https://learngitbranching.js.org/?demo=&locale=zh_CN)
