### ISSUE TITLE
2.1.32小节中Java 异常类层次结构图的一些问题

### ISSUE THREAD

**Issue by XuyiK** [Snailclimb/JavaGuide#734]
作者在这一小节中使用的配图里在`RuntimeException`中包含了`ClassNotFoundException`：

![微信截图_20200418100205](https://user-images.githubusercontent.com/32639811/79625418-b2344b00-815b-11ea-9d67-dea00df0eb86.png)
但通过查阅[Java SE8文档](https://docs.oracle.com/javase/8/docs/api/)，可知`ClassNotFoundException`并不继承自`RuntimeException`，应属于checked异常：

![微信截图_20200418100731](https://user-images.githubusercontent.com/32639811/79625570-7057d480-815c-11ea-998c-a3837c4a2ce3.png)

**Comment by Snailclimb** [comment]
> 作者在这一小节中使用的配图里在`RuntimeException`中包含了`ClassNotFoundException`：
> 
> ![微信截图_20200418100205](https://user-images.githubusercontent.com/32639811/79625418-b2344b00-815b-11ea-9d67-dea00df0eb86.png)
> 但通过查阅[Java SE8文档](https://docs.oracle.com/javase/8/docs/api/)，可知`ClassNotFoundException`并不继承自`RuntimeException`，应属于checked异常：
> 
> ![微信截图_20200418100731](https://user-images.githubusercontent.com/32639811/79625570-7057d480-815c-11ea-998c-a3837c4a2ce3.png)

感谢，已经更正！
