### ISSUE TITLE
2.3.6 小节中关于线程生命周期和状态的配图有误

### ISSUE THREAD

**Issue by XuyiK** [Snailclimb/JavaGuide#736]
作者所使用的这张图中有一处小细节有误，
![微信截图_20200418103352](https://user-images.githubusercontent.com/32639811/79626112-2ec92880-8160-11ea-8fcc-6a4bad843579.png)
这里原图的作者出了一点小纰漏，`join`是`Thread`类下的方法，但这里写成了`Object`，**应改为`Thread.join()`**，建议作者在配图后指出，以免误导读者。
![微信截图_20200418103627](https://user-images.githubusercontent.com/32639811/79626166-967f7380-8160-11ea-819a-c0c7e2a582a8.png)

感谢作者大大的面试笔记，我真的受益良多！！

**Comment by Snailclimb** [comment]
> 作者所使用的这张图中有一处小细节有误，
> ![微信截图_20200418103352](https://user-images.githubusercontent.com/32639811/79626112-2ec92880-8160-11ea-8fcc-6a4bad843579.png)
> 这里原图的作者出了一点小纰漏，`join`是`Thread`类下的方法，但这里写成了`Object`，**应改为`Thread.join()`**，建议作者在配图后指出，以免误导读者。
> ![微信截图_20200418103627](https://user-images.githubusercontent.com/32639811/79626166-967f7380-8160-11ea-819a-c0c7e2a582a8.png)
> 
> 感谢作者大大的面试笔记，我真的受益良多！！

感谢你！

**Comment by peteryuanpan** [comment]
作者您好，我给这个ISSUE补充了一个图，需要的话可以用上
![image](https://user-images.githubusercontent.com/10209135/97448112-3c5f3680-196b-11eb-8443-b45f25e63178.png)

**Comment by jayxiaohe** [comment]
> 订正(来自issue736)：原图中 wait 到 runnable 状态的转换中，join实际上是Thread类的方法，但这里写成了Object。
这里应该是：**runnable** 到 **wait** 状态的转换中，join实际上是Thread类的方法，但这里写成了Object。而不是 wait 到 runnable
