### ISSUE TITLE
JVM 类的生命周期 初始化阶段 规定的几种主动引用情况有缺失

### ISSUE THREAD

**Issue by Planeswalker23** [Snailclimb/JavaGuide#745]
还有一种是：
当一个接口中定义了JDK8新加入的默认方法（被default关键字修饰的接口方法）时，如果有这个接口的实现类发生了初始化，那该接口要在其之前被初始化。

参见《深入理解Java虚拟机（第三版）》7.2 类加载的时机

[这是我的验证代码示例](https://github.com/Planeswalker23/all-in-one/blob/master/source-code/jvm/src/main/java/classloader/initialize/DrivingQuoteDemo6.java)

**Comment by Snailclimb** [comment]
赞！刚看了书籍是这样的。感谢！

**Comment by vickllny** [comment]
不懂就问。这是否和 "初始化一个类，如果其父类还未初始化，则先触发该父类的初始化"  一个意思？
