### ISSUE TITLE
Java 并发基础常见面试题总结-2.4中“所有对象都在这里分配内存”说法有误

### ISSUE THREAD

**Issue by huangsansui** [Snailclimb/JavaGuide#746]
我在“Java 并发基础常见面试题总结“这一章节中看到2.4小节有以下一句话：
“堆和方法区是所有线程共享的资源，其中堆是进程中最大的一块内存，主要用于存放新创建的对象 (所有对象都在这里分配内存)”。
此处 (所有对象都在这里分配内存) 的说法不完全正确，在《深入理解Java虚拟机中》关于Java堆内存有这样一段描述：
但是，随着JIT编译期的发展与逃逸分析技术逐渐成熟，栈上分配、标量替换优化技术将会导致一些微妙的变化，所有的对象都分配到堆上也渐渐变得不那么“绝对”了。
从jdk 1.7开始已经默认开启逃逸分析，如果某些方法中的对象引用没有被返回或者未被外面使用（也就是未逃逸出去），那么对象可以直接在栈上分配内存。

**Comment by Snailclimb** [comment]
是的！刚看了这本书，是这样描述的。感谢！
