### ISSUE TITLE
private方法可以被重写

### ISSUE THREAD

**Issue by codemongkey** [Snailclimb/JavaGuide#748]
java基础知识，10. 重载和重写的区别的第二点说private方法不可以被重写，实际是可以的

**Comment by Snailclimb** [comment]
> java基础知识，10. 重载和重写的区别的第二点说private方法不可以被重写，实际是可以的

那是新方法而不是重写得到的，可以参考《java编程思想》相关内容

**Comment by codemongkey** [comment]
> > java基础知识，10. 重载和重写的区别的第二点说private方法不可以被重写，实际是可以的
> 
> 那是新方法而不是重写得到的，可以参考《java编程思想》相关内容

好的，哈哈，老哥回复及时啊
