### ISSUE TITLE
关于计算机网络中的TCP三次握手【2.3 为什么要传回 SYN】【2.4 传了 SYN,为啥还要传 ACK】一些疑问

### ISSUE THREAD

**Issue by heroinxj** [Snailclimb/JavaGuide#751]
1. [2.3 为什么要传回 SYN](https://snailclimb.gitee.io/javaguide/#/docs/network/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C?id=_23-%e4%b8%ba%e4%bb%80%e4%b9%88%e8%a6%81%e4%bc%a0%e5%9b%9e-syn)
我觉得“接收端传回发送端所发送的 SYN 是为了告诉发送端，我接收到的信息确实就是你所发送的信号了。”这句话表述有问题，应该改为“接收端传回发送端所发送的 ACK是为了告诉发送端，我接收到的信息确实就是你所发送的信号了；而回传SYN则是为了建立并确认从接收端到发送端的通信。”
2. [2.4 传了 SYN,为啥还要传 ACK](https://snailclimb.gitee.io/javaguide/#/docs/network/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C?id=_24-%e4%bc%a0%e4%ba%86-syn%e4%b8%ba%e5%95%a5%e8%bf%98%e8%a6%81%e4%bc%a0-ack)
1.我觉得题目应该改成【传回了ACK，为什么还要传回SYN】，原因仍旧是2.3中所论述的。关于此部分我写了一篇博客：[TCP三次握手（TCP 3-Way Handshake Process）](https://blog.csdn.net/Xjheroin/article/details/105646070)欢迎讨论。
2.关于本节中的下半部分配图和文字应该是[2.5为什么要四次挥手](https://snailclimb.gitee.io/javaguide/#/docs/network/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C?id=_25-%e4%b8%ba%e4%bb%80%e4%b9%88%e8%a6%81%e5%9b%9b%e6%ac%a1%e6%8c%a5%e6%89%8b)中的
![image](https://user-images.githubusercontent.com/42102865/80051188-30249780-854a-11ea-98c0-59760df57662.png)
----
如有错误，欢迎解惑。

特别感谢作者的开源，赞 ！！！

**Comment by Snailclimb** [comment]
感谢！已经修改如下：
![image](https://user-images.githubusercontent.com/29880145/80577474-89546580-8a39-11ea-9957-a6749dd61d10.png)

网络这部分内容正在重构。

**Comment by heroinxj** [comment]
好的，大佬辛苦了
