### ISSUE TITLE
关于重写的疑惑

### ISSUE THREAD

**Issue by WangZhen-Ddm** [Snailclimb/JavaGuide#756]
在jdk1.8中
`public class HashMap<K,V> extends AbstractMap<K,V> implements Map<K,V>, Cloneable, Serializable`
HashMap继承了AbstractMap这一抽象类并实现了Map<>接口，为何其中的代码都未加@override进行重写

**Comment by debugjoker** [comment]
@override注解不是必须要加的

**Comment by wangpeipei90** [comment]
难道override不是重载么？怎么重载和重写的中英文如此混乱

**Comment by WangZhen-Ddm** [comment]
> 难道override不是重载么？怎么重载和重写的中英文如此混乱

重载是overload

**Comment by WangPeil** [comment]
@override在源码期有效，主要是为了提醒人在编写代码过程中注意实现或覆盖父类方法。

**Comment by wangpeipei90** [comment]
@WangZhen-Ddm 我指的是重载overloading，然后annotation用override标识。这issue的问题居然说是重写
