### ISSUE TITLE
关于Mysql-据库索引总结1-使用索引的注意事项中，“加索引的列设置为 NOT NULL ，而进行全表扫描”

### ISSUE THREAD

**Issue by nudt681** [Snailclimb/JavaGuide#758]
`加索引的列设置为 NOT NULL ，否则将导致引擎放弃使用索引而进行全表扫描`
经过试验把某一列设置为default null，where是可以走索引

**Comment by LiWenGu** [comment]
先说结论，你是对的。另外 `index` 是否设置 `NULL` 是不影响性能的
>And, in case you’re wondering, allowing NULL values in the index really doesn’t impact performance
>来源：[高性能MySQL第四章](1) 

NULL 值的索引查找流程参考：https://juejin.im/post/5d5defc2518825591523a1db

[1]: https://www.oreilly.com/library/view/high-performance-mysql/0596003064/ch04.html
