### ISSUE TITLE
JDK1.8 的ArrayList 的默认构造函数，初始化的list的长度为0

### ISSUE THREAD

**Issue by haodedong** [Snailclimb/JavaGuide#76]
你好：
    /**
     *默认构造函数，其默认初始容量为10
     */
    public ArrayList() {
        this.elementData = DEFAULTCAPACITY_EMPTY_ELEMENTDATA;
    }

 DEFAULTCAPACITY_EMPTY_ELEMENTDATA 为0
初始化为10，是在首次add() 的时候进行的

**Comment by Vampx** [comment]
是的
![image](https://user-images.githubusercontent.com/13953891/49849789-1e8b9580-fe16-11e8-9d71-2ff62e6c1f9b.png)

**Comment by Snailclimb** [comment]
@haodedong 请标注对应的位置 这部分我记得我写的也是10 但是这个初始其实是空数组 当添加第一个元素的时候才变成10

**Comment by haodedong** [comment]
https://github.com/Snailclimb/JavaGuide/blob/master/Java%E7%9B%B8%E5%85%B3/ArrayList.md

**Comment by Snailclimb** [comment]
已经改正！感谢！
