### ISSUE TITLE
mysql组合索引的问题

### ISSUE THREAD

**Issue by cafe3165** [Snailclimb/JavaGuide#764]
在《数据库索引.md》中最左前缀原则

>假设创建的联合索引由三个字段组成:
ALTER TABLE table ADD INDEX index_name (num,name,age) 
那么当查询的条件有为:num / (num AND name) / (num AND name AND age)时，索引才生效。所以在创建联合索引时，尽量把查询最频繁的那个字段作为最左(第一个)字段。查询的时候也尽量以这个字段为第一条件。

我使用explain 来测试，发现查询条件只要有num，哪怕是用 OR 连接非索引字段，也能用到组合索引（possible_keys显示为组合索引），怎么看待这个情况呢？

**Comment by LiWenGu** [comment]
关键在于 `possible_keys` 列是什么意思  
`possible_keys` 列的意思是该 sql 语句可能会使用到的所有索引，但是真正使用到什么索引得看 `key` 列，如果 `key` 列为 NULL，说明该 sql 实际就没有使用索引。
>官网：https://dev.mysql.com/doc/refman/8.0/en/explain-output.html

你测试的语句应该是 `possible_keys` 列有值，但是 `key` 列为 NULL，就说明没有使用到索引。举个另例  

建表语句：
```sql
CREATE TABLE `test_possible_key` (
  `a` int(11) NOT NULL AUTO_INCREMENT,
  `b` int(11) NOT NULL,
  PRIMARY KEY (`a`),
  UNIQUE KEY `assemble` (`a`,`b`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```
查询语句1： 
```sql
explain select * from test_possible_key where a = 1 or b = 2;
```
输出：  

<img width="270" alt="image" src="https://user-images.githubusercontent.com/15909210/81176512-d2775d00-8fd7-11ea-89f0-ca0de9bea644.png">

`possible_keys` 列是两个索引，但是 `key` 列是 `assemble` 索引，说明他最终使用了 `assemble` 索引。

**Comment by LiWenGu** [comment]
解决了问题记得 close issue，还有啥疑问
