### ISSUE TITLE
操作系统文章中配图错误

### ISSUE THREAD

**Issue by siriusol** [Snailclimb/JavaGuide#765]
链接：
https://snailclimb.gitee.io/javaguide/#/docs/operating-system/basis?id=%e4%b8%80-%e6%93%8d%e4%bd%9c%e7%b3%bb%e7%bb%9f%e5%9f%ba%e7%a1%80
第 2.2 节 进程有哪几种状态
配图中从ready指向running的箭头有一个方向反了

**Comment by Snailclimb** [comment]
> 链接：
> https://snailclimb.gitee.io/javaguide/#/docs/operating-system/basis?id=%e4%b8%80-%e6%93%8d%e4%bd%9c%e7%b3%bb%e7%bb%9f%e5%9f%ba%e7%a1%80
> 第 2.2 节 进程有哪几种状态
> 配图中从ready指向running的箭头有一个方向反了

哈哈 是滴 老哥太仔细了 👍
