### ISSUE TITLE
反射机制章节报错

### ISSUE THREAD

**Issue by MartinMxn** [Snailclimb/JavaGuide#776]
在反射章节中会在这一行报错
`
TargetObject targetObject = (TargetObject) tagetClass.newInstance();
`
Exception in thread "main" java.lang.InstantiationException: xxx.TargetObject

**Comment by LiWenGu** [comment]
哪篇章节，贴下地址

**Comment by MartinMxn** [comment]
> 哪篇章节，贴下地址，我关键字搜索，没搜到

在基础反射章节 Link:
https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/basic/reflection.md

**Comment by Snailclimb** [comment]
> 在反射章节中会在这一行报错
> `TargetObject targetObject = (TargetObject) tagetClass.newInstance();`
> Exception in thread "main" java.lang.InstantiationException: xxx.TargetObject

```java
 Class<?> tagetClass = Class.forName("cn.javaguide.TargetObject");
```
后面的包名替换一下就行了。

**Comment by MartinMxn** [comment]
> > 在反射章节中会在这一行报错
> > `TargetObject targetObject = (TargetObject) tagetClass.newInstance();`
> > Exception in thread "main" java.lang.InstantiationException: xxx.TargetObject
> 
> ```java
>  Class<?> tagetClass = Class.forName("cn.javaguide.TargetObject");
> ```
> 
> 后面的包名替换一下就行了。

没有解决。。报的不是class not found的错 怎么会是包名的问题
没替换是class not found 
替换了是我说的【java.lang.InstantiationException】。。

【我试验的解决方法】刚才stackoveflow查了半天找到了 文档教程里的TargetObject类声明了带参数的构造方法，覆盖了不带参数的，再声明一个不带参数的即可解决

`
public TargetObject() {}
`

【希望下次处理issue能先跑一边。。】

**Comment by LiWenGu** [comment]
> > > 在反射章节中会在这一行报错
> > > `TargetObject targetObject = (TargetObject) tagetClass.newInstance();`
> > > Exception in thread "main" java.lang.InstantiationException: xxx.TargetObject
> > 
> > 
> > ```java
> >  Class<?> tagetClass = Class.forName("cn.javaguide.TargetObject");
> > ```
> > 
> > 
> > 后面的包名替换一下就行了。
> 
> 没有解决。。报的不是class not found的错 怎么会是包名的问题
> 没替换是class not found
> 替换了是我说的【java.lang.InstantiationException】。。
> 
> 【我试验的解决方法】刚才stackoveflow查了半天找到了 文档教程里的TargetObject类声明了带参数的构造方法，覆盖了不带参数的，再声明一个不带参数的即可解决
> 
> `public TargetObject() {}`
> 
> 【希望下次处理issue能先跑一边。。】

我看了下，七天之前的源码是有无参构造函数的：
<img width="618" alt="image" src="https://user-images.githubusercontent.com/15909210/82309948-5711a480-99f6-11ea-8509-3742406d740a.png">
我运行了下，也是没问题的，你发下你之前报错的源码和文档对比，我看看有什么出入

**Comment by MartinMxn** [comment]
> > > > 在反射章节中会在这一行报错
> > > > `TargetObject targetObject = (TargetObject) tagetClass.newInstance();`
> > > > Exception in thread "main" java.lang.InstantiationException: xxx.TargetObject
> > > 
> > > 
> > > ```java
> > >  Class<?> tagetClass = Class.forName("cn.javaguide.TargetObject");
> > > ```
> > > 
> > > 
> > > 后面的包名替换一下就行了。
> > 
> > 
> > 没有解决。。报的不是class not found的错 怎么会是包名的问题
> > 没替换是class not found
> > 替换了是我说的【java.lang.InstantiationException】。。
> > 【我试验的解决方法】刚才stackoveflow查了半天找到了 文档教程里的TargetObject类声明了带参数的构造方法，覆盖了不带参数的，再声明一个不带参数的即可解决
> > `public TargetObject() {}`
> > 【希望下次处理issue能先跑一边。。】
> 
> 我看了下，七天之前的源码是有无参构造函数的：
> <img alt="image" width="618" src="https://user-images.githubusercontent.com/15909210/82309948-5711a480-99f6-11ea-8509-3742406d740a.png">
> 我运行了下，也是没问题的，你发下你之前报错的源码和文档对比，我看看有什么出入

Ok, 之前构造函数是赋固定值 我以为是带参数的就自动生成了 我不是copy的 如果直接copy文档是没有错误的  感谢回复
