### ISSUE TITLE
Guide哥，这个案例（接近8000字的Spring/SpringBoot常用注解总结！安排！）的示例完整代码有吗

### ISSUE THREAD

**Issue by yaochunguang** [Snailclimb/JavaGuide#786]

**Comment by yaochunguang** [comment]
接近8000字的Spring/SpringBoot常用注解总结！安排！

**Comment by Snailclimb** [comment]
> _No description provided._

我都是给的简单的代码片段，这个项目 :https://github.com/Snailclimb/spring-security-jwt-guide 涵盖了大部分注解的使用，或许对你有帮助。
