### ISSUE TITLE
能具体讲解下为什么一个Kafka的partition副本挂了，会导致整个partition不可用么？

### ISSUE THREAD

**Issue by Gannalyo** [Snailclimb/JavaGuide#788]
![image](https://user-images.githubusercontent.com/34175244/82339524-b4225000-9a20-11ea-92fd-fd0b2c35c950.png)

谢谢

**Comment by Snailclimb** [comment]
因为此时不满足 min.insync.replicas 规定的至少要被写入的副本数量。
![image](https://user-images.githubusercontent.com/29880145/82805488-b3713a00-9eb6-11ea-84f2-fbd65a62afa8.png)
