### ISSUE TITLE
Full GC收集的是整个堆区和方法区

### ISSUE THREAD

**Issue by hulu888** [Snailclimb/JavaGuide#789]
对于该处的问题有确定的答案
![截屏2020-05-20 下午10 17 57](https://user-images.githubusercontent.com/12171626/82457646-3fb2e400-9ae8-11ea-8b20-7267477f75fc.png)

full gc收集的是整个堆区和方法区
![截屏2020-05-20 下午10 11 18](https://user-images.githubusercontent.com/12171626/82457742-5ce7b280-9ae8-11ea-8284-d6973477dc1a.png)
出自《深入理解Java虚拟机：JVM高级特性与最佳实践》（第三版）

**Comment by LiWenGu** [comment]
文档描述有误，知乎原文的分歧在于：Major GC 的语义问题。
但是针对 Full GC 是一致的：收集整个堆+元空间（1.8）  

---

你看书里对于 `Major GC` 描述也说有分歧，需要读者按上下文才能区分具体是什么回收。
