### ISSUE TITLE
在事务隔离级别中，MySQL InnoDB 存储引擎的隔离级别的描述也许有个问题

### ISSUE THREAD

**Issue by EallanW** [Snailclimb/JavaGuide#805]
“这里需要注意的是：与 SQL 标准不同的地方在于InnoDB 存储引擎在 **REPEATABLE-READ（可重读）事务隔离级别下使用的是Next-Key Lock 锁算法，因此可以避免幻读的产生，这与其他数据库系统(如 SQL Server)是不同的。所以说InnoDB 存储引擎的默认支持的隔离级别是 REPEATABLE-READ（可重读） 已经可以完全保证事务的隔离性要求，即达到了 SQL标准的SERIALIZABLE(可串行化)**隔离级别。

因为隔离级别越低，事务请求的锁越少，所以大部分数据库系统的隔离级别都是READ-COMMITTED(读取提交内容):，但是你要知道的是InnoDB 存储引擎默认使用 **REPEATABLE-READ（可重读）**并不会有任何性能损失。”

在以上这段内容中，InnoDB 存储引擎的默认支持的隔离级别REPEATABLE-READ（可重读） 并不能完全避免幻读的产生。原因详见请看以下链接，该文有引用MySQL的官方文档来解释。结论是：
“结论：MySQL InnoDB的可重复读并不保证避免幻读，需要应用使用加锁读来保证。而这个加锁度使用到的机制就是next-key locks。”

https://blog.csdn.net/Marvel__Dead/article/details/70209641

请问有关人士可以核实吗？

**Comment by LiWenGu** [comment]
1. https://medium.com/@chester.yw.chu/%E5%B0%8D%E6%96%BC-mysql-repeatable-read-isolation-%E5%B8%B8%E8%A6%8B%E7%9A%84%E4%B8%89%E5%80%8B%E8%AA%A4%E8%A7%A3-7a9afbac65af
2. http://mysql.taobao.org/monthly/2017/06/07/

结论：MySQL InnoDB的可重复读并不保证避免幻读，需要应用使用加锁读来保证。而这个加锁度使用到的机制就是next-key locks。例如应用语句：select * from table for update

**Comment by ClearLovePlus** [comment]
rr级别事务隔离 并不能完全保证不出现幻读，所以建议作者能修改一下啊

**Comment by EallanW** [comment]
> rr级别事务隔离 并不能完全保证不出现幻读，所以建议作者能修改一下啊

我也觉得改一下比较好

**Comment by miodawn** [comment]
https://github.com/Snailclimb/JavaGuide/blob/master/docs/database/%E4%BA%8B%E5%8A%A1%E9%9A%94%E7%A6%BB%E7%BA%A7%E5%88%AB(%E5%9B%BE%E6%96%87%E8%AF%A6%E8%A7%A3).md

https://github.com/Snailclimb/JavaGuide/blob/master/docs/database/MySQL.md

这两篇文章中对RR隔离级别，并不能完全保证不出现幻读的信息，并未同步修改
https://github.com/Snailclimb/JavaGuide/pull/806
