### ISSUE TITLE
Java 并发进阶常见面试题总结1.2小节volatile 关键字修饰的必要性

### ISSUE THREAD

**Issue by mojirml** [Snailclimb/JavaGuide#807]
我理解的是在这样的情形下volatile是有必要性的
`    public static Singleton3 getInstance() {
        if (sInstance == null) {
            synchronized (Singleton3.class) {
                if (sInstance == null) {
                    sInstance = new Singleton3(); //位置2
                }
            }
        }
        return sInstance;
    }`
但是1.2小节似乎不是这样，而是在静态方法上就已经加锁，没有造成这种情况的可能。望大佬解答

**Comment by ArvinDevel** [comment]
详见#293

**Comment by mojirml** [comment]
> 详见#293

回答中的确解释了我issue中的代码使用volatile的必要性，但是还是没有解释清为什么1.2小节出现的必要性吧

**Comment by hokage123** [comment]
Brother what do you want to know about volatile concept

**Comment by hokage123** [comment]
兄弟，您想了解易失性概念

**Comment by wx2700317** [comment]
同问啊，DCL里面get方法是syn锁住的，所以相当于单线程情况下，那怎么会有第二个线程可以获取未初始化的实例

**Comment by hokage123** [comment]
> 同问啊，DCL里面get方法是syn锁住的，所以相当于单线程情况下，那怎么会有第二个线程可以获取未初始化的实例

Two types of lock can be achieved
1-on instance
2-on class
It is second type of lock.
