### ISSUE TITLE
线程死锁发生的条件

### ISSUE THREAD

**Issue by IBXiaomi** [Snailclimb/JavaGuide#811]
线程发生死锁需要四个条件，其余三个都可以理解，但是第四个有点模糊。循环等待，说的是若干进程之间形成的头尾相接，等待资源的关系。
但是举例又是main方法中启动两个线程，感觉理解为线程之间的资源互相等待。所以想请教下大佬，这个条件理解为进程之间，还是线程之间？感谢

**Comment by Snailclimb** [comment]
> 线程发生死锁需要四个条件，其余三个都可以理解，但是第四个有点模糊。循环等待，说的是若干进程之间形成的头尾相接，等待资源的关系。
> 但是举例又是main方法中启动两个线程，感觉理解为线程之间的资源互相等待。所以想请教下大佬，这个条件理解为进程之间，还是线程之间？感谢

这个循环等待可以理解为一个线程的一个死循环。
