### ISSUE TITLE
ArrayList扩容1.5倍描述有误

### ISSUE THREAD

**Issue by myjunsi** [Snailclimb/JavaGuide#813]
/**
     * ArrayList扩容的核心方法。
     */
    private void grow(int minCapacity) {
       //elementData为保存ArrayList数据的数组
       ///elementData.length求数组长度elementData.size是求数组中的元素个数
        // oldCapacity为旧容量，newCapacity为新容量
        int oldCapacity = elementData.length;
        **//将oldCapacity 右移一位，其效果相当于oldCapacity /2，
        //我们知道位运算的速度远远快于整除运算，整句运算式的结果就是将新容量更新为旧容量的1.5倍，
        int newCapacity = oldCapacity + (oldCapacity >> 1);**
        //然后检查新容量是否大于最小需要容量，若还是小于最小需要容量，那么就把最小需要容量当作数组的新容量，
        if (newCapacity - minCapacity < 0)
            newCapacity = minCapacity;
        //再检查新容量是否超出了ArrayList所定义的最大容量，
        //若超出了，则调用hugeCapacity()来比较minCapacity和 MAX_ARRAY_SIZE，
        //如果minCapacity大于MAX_ARRAY_SIZE，则新容量则为Interger.MAX_VALUE，否则，新容量大小则为 MAX_ARRAY_SIZE。
        if (newCapacity - MAX_ARRAY_SIZE > 0)
            newCapacity = hugeCapacity(minCapacity);
        // minCapacity is usually close to size, so this is a win:
        elementData = Arrays.copyOf(elementData, newCapacity);
    }
理由：
int newCapacity = oldCapacity + (oldCapacity >> 1);
例如：假设旧容量oldCapacity=10，所以10的1.5倍为 10 + 10 * 1.5 = 25，
但是代码是 10 + 5 = 15，二进制位描述：1010 >> 1 = 101
当然这个是我的理解，我看过很多文章和视频，他们都说ArrayList扩容是原来的1.5倍，如果有什么不对的地方，希望得到你的指正，谢谢。

**Comment by myjunsi** [comment]
//将oldCapacity 右移一位，其效果相当于oldCapacity /2。
这句话也不是完全正确的因为当oldCapacity =33时，二进制描述11111 >> 1 = 1111，所以就是15
但是33/2不是15

**Comment by IBXiaomi** [comment]
33的二进制应该是0010 0001.不是11111.....

**Comment by myjunsi** [comment]
的确，我看错了 。。。@IBXiaomi

**Comment by hokage123** [comment]
Usually Array_Max_size only can go upto 10^6 or 10^7 in real it only looks like in theory that it can go to Integer_Max_value but not possible.

**Comment by hokage123** [comment]
> Usually Array_Max_size only can go upto 10^6 or 10^7 in real it only looks like in theory that it can go to Integer_Max_value but not possible.

This is the problem lead to segmented sieve type algorithm .
