### ISSUE TITLE
进程间的通讯方式

### ISSUE THREAD

**Issue by Zikai-Hao** [Snailclimb/JavaGuide#818]
前几天被面试官问到进程间和线程间的通讯方式，一脸懵逼，后来去查了查

1 管道通讯pipe/FIFO
  前者半双工 后者全双工
2 消息队列
3 信号量
 计数器 用于为多个进程提供对共享数据对象的访问
4 共享存储
5 socket套接字
  可用于不同机器间的进程通讯

-------------------------------------
线程间的通讯方式望大佬补充

**Comment by Snailclimb** [comment]
可以参考这篇文章：https://www.jianshu.com/p/9218692cb209
