### ISSUE TITLE
PWA支持

### ISSUE THREAD

**Issue by shelli-site** [Snailclimb/JavaGuide#821]
我在commit里看到【add pwa(离线模式)支持】，但访问[https://snailclimb.gitee.io/javaguide/](https://snailclimb.gitee.io/javaguide/)浏览器并没有出现
![image](https://user-images.githubusercontent.com/44458320/84637689-95807d80-af28-11ea-862e-90ac45adf202.png)可将网站添加到桌面的选项。原因是什么？我不是很了解。

**Comment by Snailclimb** [comment]
> 我在commit里看到【add pwa(离线模式)支持】，但访问https://snailclimb.gitee.io/javaguide/浏览器并没有出现
> ![image](https://user-images.githubusercontent.com/44458320/84637689-95807d80-af28-11ea-862e-90ac45adf202.png)可将网站添加到桌面的选项。原因是什么？我不是很了解。

或许是我的操作有问题。。pdf版本不知道能不能暂时帮助到你：https://github.com/Snailclimb/JavaGuide/blob/master/docs/javaguide%E9%9D%A2%E8%AF%95%E7%AA%81%E5%87%BB%E7%89%88.md
