### ISSUE TITLE
redis部分post的网站不存在，访问不了

### ISSUE THREAD

**Issue by JavaDeveloper53** [Snailclimb/JavaGuide#823]
如下网站https://www.jianshu.com/p/8bddd381de06 不能访问

**Comment by Snailclimb** [comment]
请问具体是哪一篇文章？(redis有好几篇文章)

**Comment by Snailclimb** [comment]
> 如下网站https://www.jianshu.com/p/8bddd381de06 不能访问

请问具体是哪一篇redis的文章呢？

**Comment by LiWenGu** [comment]
> > 如下网站https://www.jianshu.com/p/8bddd381de06 不能访问
> 
> 请问具体是哪一篇redis的文章呢？

https://github.com/Snailclimb/JavaGuide/blob/master/docs/database/Redis/Redis.md#%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3-redis-%E7%9A%84%E5%B9%B6%E5%8F%91%E7%AB%9E%E4%BA%89-key-%E9%97%AE%E9%A2%98

**Comment by Snailclimb** [comment]
这部分内容正在重构，预计周四前完成。
