### ISSUE TITLE
删除链表的倒数k算法

### ISSUE THREAD

**Issue by liwang123** [Snailclimb/JavaGuide#825]
一次遍历算法有问题

**Comment by LiWenGu** [comment]
你说的是哪篇文章？

**Comment by liwang123** [comment]
https://github.com/Snailclimb/JavaGuide/blob/master/docs/dataStructures-algorithms/%E5%87%A0%E9%81%93%E5%B8%B8%E8%A7%81%E7%9A%84%E9%93%BE%E8%A1%A8%E7%AE%97%E6%B3%95%E9%A2%98.md
