### ISSUE TITLE
Java集合框架常见面试题中Java 集合概览的图片中展示异常

### ISSUE THREAD

**Issue by qiaofenlin** [Snailclimb/JavaGuide#828]
![image](https://user-images.githubusercontent.com/30179423/85037056-751a2280-b1b7-11ea-952d-6e777055267c.png)
ArrayDeque实现了Deque，而非Dequeue。
The name <i>deque</i> is short for "double ended queue" and is usually pronounced "deck"

**Comment by LiWenGu** [comment]
哪篇文章，地址贴一下

**Comment by qiaofenlin** [comment]
> 哪篇文章，地址贴一下
https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.md#iterator-%E8%BF%AD%E4%BB%A3%E5%99%A8

![image](https://user-images.githubusercontent.com/30179423/85101047-1646be80-b234-11ea-90ee-f4be604b0183.png)

**Comment by Snailclimb** [comment]
在线阅读这块应该是没有问题的：https://snailclimb.gitee.io/javaguide/#/docs/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98?id=iterator-%e8%bf%ad%e4%bb%a3%e5%99%a8 。

**Comment by qiaofenlin** [comment]
ArrayDeque实现了Deque，而非Dequeue。 源码中是Deque，图片中显示的是Dequeue。可能我有点吹毛求疵了。

**Comment by qiaofenlin** [comment]
> 在线阅读这块应该是没有问题的：https://snailclimb.gitee.io/javaguide/#/docs/java/collection/Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98?id=iterator-%e8%bf%ad%e4%bb%a3%e5%99%a8 。

ArrayDeque实现了Deque，而非Dequeue。 源码中是Deque，图片中显示的是Dequeue。可能我有点吹毛求疵了。
