### ISSUE TITLE
内部网关协议应该是OSPF不是OPSF

### ISSUE THREAD

**Issue by bookjiang** [Snailclimb/JavaGuide#832]
在计算机网络常见面试题第五大点的图片中，内部网关协议应该是OSPF吧，如果说错请原谅。/笑哭

**Comment by Snailclimb** [comment]
> 在计算机网络常见面试题第五大点的图片中，内部网关协议应该是OSPF吧，如果说错请原谅。/笑哭

已经修改！感谢老哥。👍
