### ISSUE TITLE
为什么重写 `equals` 时必须重写 `hashCode` 方法？

### ISSUE THREAD

**Issue by sruby** [Snailclimb/JavaGuide#833]
以下是我的demo，没有重写hashcode两个对象也能判断相等。

`public class HashcodeDemo {
    private String fieldOne;
    private String fieldTwo;

    public boolean equal(HashcodeDemo hashcodeDemo){
        if (this.fieldOne.equals(hashcodeDemo.getFieldOne()) && this.fieldTwo.equals(hashcodeDemo.getFieldTwo())){
            return true;
        }

        return false;
    }
}

HashcodeDemo hashcodeDemo = new HashcodeDemo("1","2");
HashcodeDemo hashcodeDemo2 = new HashcodeDemo("1","2");
boolean equal = hashcodeDemo.equal(hashcodeDemo2); //true
`

**Comment by srepeat** [comment]
这个hashcode是在判断存的数据hash值是否相同，如果相同就不会存储，hash相同就会使用equals进行比较，先用hashcode计算哈希值，然后如果哈希相同才会使用equals比较，如果自定义排序的话还得实现一个排序接口

**Comment by wandada** [comment]
你可以试试将两个对象都加入到Hashset中，再看set.size()，另外不得不说你的equals方法写的也有问题，参数应该设置为object类型，判断空什么的都没写。

**Comment by hokage123** [comment]
In HashMap and HashSet equals() and hashcode() method both serve a purpose equals is used to check object and hashcode is basically used for bucketing. 
Firstly we check from hashcode it belongs to which bucket then use equals to check that that key is present or not. 
If we want our custom object HashMap then we need to override both equals and hashcode.

**Comment by hokage123** [comment]
In HashMap and HashSet equals() and hashcode() method both serve a purpose equals is used to check object and hashcode is basically used for bucketing. 
Firstly we check from hashcode it belongs to which bucket then use equals to check that that key is present or not. 
If we want our custom object HashMap then we need to override both equals and hashcode.

**Comment by kaelzh** [comment]
不重写hascode的话，你可以存入set集合试试看。或者用 == 判断一下两个对象

**Comment by sruby** [comment]
> 你可以试试将两个对象都加入到HashSet中，再看set.size()，另外不得不说你的equals方法写的也有问题，参数应该设置为object类型，判断空什么的都没写。
> java中有个原则：
> equals方法返回true,hashcode必相等；
> hashcode不相等，equals方法一定不返回true；
> hashcode相等，equals方法不一返回true;
> 这里题主的写法明显违背了第一条。

谢谢指正，看了下这篇文章明白了，如果不把对象作为hashmap的key在实际运行中不会存在问题（不推荐这么做）。
作为key的时候因为hashmap是用hashcode来寻找key，在只实现equals的情况下，使用equals为true的两个对象A和B，先用A作为key put，然后用B去get，return  null。

https://www.journaldev.com/21095/java-equals-hashcode#implementing-equals-and-hashcode-method
