### ISSUE TITLE
4.1.9小节， 对幻读的理解问题

### ISSUE THREAD

**Issue by WangXin3** [Snailclimb/JavaGuide#834]
原文：
幻读（Phantom read）: 幻读与不可重复读类似。它发生在一个事务（T1）读取了几行数据，接着另一个并发事务（T2）插入了一些数据时。在随后的查询中，第一个事务（T1）就会发现多了一些原本不存在的记录，就好像发生了幻觉一样，所以称为幻读。

问题：
在可重复读隔离级别下，是有幻读存在的，但不是查询时出现幻读。T1事务多次读取是不会读取到T2提交的数据的。原文描述的只是不可重复读问题的一种。在可重复读已经解决了这个问题。

我理解的幻读是：
根据查询出的结果去更新、删除、新增数据时，出现了意外情况。
比如我T1事务查询id小于5的数据，查询出有3条，T2事务插入一条id为4的数据并提交事务，T1事务去删除id小于5的数据，会发现删除了4条，这时就像产生了幻觉，我明明查询出只有3条，为什么会删除4条呢。

**Comment by LiWenGu** [comment]
# 参考地址

1. 幻读和不可重复读的区别：https://stackoverflow.com/questions/11043712/what-is-the-difference-between-non-repeatable-read-and-phantom-read
2. 什么是幻读：https://dev.mysql.com/doc/refman/8.0/en/innodb-next-key-locking.html

# 原文和问题

参考地址 1 中里面讨论的核心在于：幻读是和事务的删除与插入操作有关，而不可重复读是和事务的更新操作有关。

原文描述确实不够严谨，但是你说的
>在可重复读隔离级别下，是有幻读存在的，但不是查询时出现幻读

也是不对的。因为还有 `select … for update` 操作。
具体查看参考文档 2 中关于幻读的定义
>For example, if a SELECT is executed twice, but returns a row the second time that was not returned the first time, the row is a “phantom” row.

幻读 SQL 举例如下：

![image](https://user-images.githubusercontent.com/15909210/85948742-1312a780-b985-11ea-8c57-b34b880c4420.png)
---

# 我对幻读和不可重复读的理解

大前提，假设有两个**事务**操作：T1 和 T2，其中 T1 做了读取操作。而 T2 在 T1 在做读取操作过程中，有**数据修改**操作。

## 相同点

幻读和不可重复读都和不同**事务的修改操作**有关，这些事务（T2）是在事务（T1）开始之后提交的，并且在 T1 提交前提交。

## 不同点

不可重复读：T1 事务读到了 T2 事务已提交的 UPDATES 操作。即：同一行的值，在多次读取时是不一样的。
幻读：T1 事务读到了 T2 事务已提交的 INSERTS/DELETES 操作。即：某一行，可能没了或多了。**同一个范围，条数不一样了**

## 举例说明

![](http://assets.processon.com/chart_image/5ef88f296376891e81eb364e.png)

**Comment by LiWenGu** [comment]
这是几个 sql 案例，但是我觉得得单独拎出来，因为它和谈论的问题无关，但是可以加深理解

![image](https://user-images.githubusercontent.com/15909210/85951418-b7044f00-b995-11ea-8ee0-c87914cf3789.png)

**Comment by LiWenGu** [comment]
参考 SQL：
![](http://assets.processon.com/chart_image/5ef88f296376891e81eb364e.png#1)

**Comment by Snailclimb** [comment]
已经修复!感谢👍
