### ISSUE TITLE
Redis 常见问题汇总 链接失效 404

### ISSUE THREAD

**Issue by CreamBing** [Snailclimb/JavaGuide#835]
以下为链接地址
https://snailclimb.gitee.io/javaguide/#/docs/database/Redis/redis
![image](https://user-images.githubusercontent.com/16008373/85925539-97085900-b8cb-11ea-8fc2-310ecf298456.png)

**Comment by 94rain** [comment]
看来是没有大写， https://snailclimb.gitee.io/javaguide/#/docs/database/Redis/Redis 可以访问
README里应改为`* [Redis 常见问题总结](docs/database/Redis/Redis.md)`
