### ISSUE TITLE
运行时常量池问题

### ISSUE THREAD

**Issue by zhou-ning** [Snailclimb/JavaGuide#836]
在Java内存区域.md#26-运行时常量池讲解中，作者是说将jdk1.7只是将字符串常量池被从方法区拿到了堆中,但是在JVM垃圾回收.md#25-如何判断一个常量是废弃常量中，作者又 JDK1.7 及之后版本的 JVM 已经将运行时常量池从方法区中移了出来，在 Java 堆（Heap）中开辟了一块区域存放运行时常量池。有点迷糊了，诶诶希望能有正确的回答

**Comment by wangpeipei90** [comment]
没问题，字符串常量池只是常量池的一种，还有int的常量池对于数字0-255。运行时常量池还可以包括自定义的常量，比如 static的字段

**Comment by zhou-ning** [comment]
> 没问题，字符串常量池只是常量池的一种，还有int的常量池对于数字0-255。运行时常量池还可以包括自定义的常量，比如 static的字段

意思是1.7版本只是将字符串常量池从方法区中移除吗？

**Comment by Snailclimb** [comment]
HI，请看下面内容。垃圾回收这部分是没有同步修改的原因。
![image](https://user-images.githubusercontent.com/29880145/86133949-95cd6b00-bb1b-11ea-92c7-2fad4d784e02.png)


> 在Java内存区域.md#26-运行时常量池讲解中，作者是说将jdk1.7只是将字符串常量池被从方法区拿到了堆中,但是在JVM垃圾回收.md#25-如何判断一个常量是废弃常量中，作者又 JDK1.7 及之后版本的 JVM 已经将运行时常量池从方法区中移了出来，在 Java 堆（Heap）中开辟了一块区域存放运行时常量池。有点迷糊了，诶诶希望能有正确的回答

**Comment by zhou-ning** [comment]
好的，谢谢
