### ISSUE TITLE
《这几道Java集合框架面试题几乎必问》ConcurrentHashMap比Hashtable 效率提高16 倍的疑问

### ISSUE THREAD

**Issue by MiracleHe** [Snailclimb/JavaGuide#84]
《这几道Java集合框架面试题几乎必问》中“ConcurrentHashMap 和 Hashtable 的区别”关于“默认分配16个Segment，比Hashtable效率提高16倍。”的疑问。

ConcurrentHashMap默认将hash表分为16个桶，诸如get、put、remove等常用操作只锁住当前需要用到的桶。这样，原来只能一个线程进入，现在却能同时有16个写线程执行，并发性能的提升是显而易见的。但此处并不能说效率就是提高了16倍。
ConcurrentHashMap是由Segment数组结构和HashEntry数组结构组成。Segment是一个可重入锁（ReentrantLock），在ConcurrentHashMap里扮演锁的角色；HashEntry则用于存储键值对数据。一个ConcurrentHashMap里包含一个Segment数组。Segment的结构和HashMap类似，是一种数组和链表结构。一个Segment里包含一个HashEntry数组，每个HashEntry是一个链表结构的元素，每个Segment守护着一个HashEntry数组里的元素。当对HashEntry数组的数据进行修改时，必须首先获得与它对应的segment锁。
因为一个Segment里包含一个HashEntry数组，故锁住一个Segment时即锁住了该Segment下的HashEntry数组。

**Comment by mogongzi** [comment]
JDK 1.7和1.8的实现也不一样，1.8已经不用分段锁了

**Comment by Snailclimb** [comment]
嗯嗯 这样说确实欠妥！已经更改。感谢!
