### ISSUE TITLE
添加mysql8修改后的查看隔离级别命令

### ISSUE THREAD

**Issue by miodawn** [Snailclimb/JavaGuide#843]
"MySQL InnoDB 存储引擎的默认支持的隔离级别是 REPEATABLE-READ（可重读）。我们可以通过SELECT @@tx_isolation;命令来查看"
这里命令建议添加mysql8修改后的命令
tx_isolation在8.0版本更改为transaction_isolation
命令更改为：
select @@transaction_isolation;

**Comment by LiWenGu** [comment]
两篇已添加：
https://github.com/Snailclimb/JavaGuide/blob/master/docs/database/MySQL%E9%AB%98%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96%E8%A7%84%E8%8C%83%E5%BB%BA%E8%AE%AE.md  

https://github.com/Snailclimb/JavaGuide/blob/master/docs/system-design/framework/spring/spring-transaction.md

**Comment by miodawn** [comment]
> 添加的两篇地址为：
> https://github.com/Snailclimb/JavaGuide/blob/master/docs/database/MySQL%E9%AB%98%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96%E8%A7%84%E8%8C%83%E5%BB%BA%E8%AE%AE.md
> 
> https://github.com/Snailclimb/JavaGuide/blob/master/docs/system-design/framework/spring/spring-transaction.md

第一个地址写错了吧，应该是MySQL.md

另外，在https://github.com/Snailclimb/JavaGuide/issues/805中，我在下面提到文章并未同步修改的问题，麻烦跟踪一下
