### ISSUE TITLE
volatile-lru和volatile-lfu解释模糊

### ISSUE THREAD

**Issue by HaloCsidez** [Snailclimb/JavaGuide#847]
关于redis的文章中介绍 6 种数据淘汰策略：
文中描述的概念模糊：
- volatile-lru：从已设置过期时间的数据集（server.db[i].expires）中挑选最近最少使用的数据淘汰
- volatile-lfu：从已设置过期时间的数据集(server.db[i].expires)中挑选最不经常使用的数据淘汰

建议补充：
- least frequently used——lfu——使用频率最少的键
- least recently used——lru——最久没有使用的键

**Comment by Snailclimb** [comment]
> 关于redis的文章中介绍 6 种数据淘汰策略：
> 文中描述的概念模糊：
> 
> * volatile-lru：从已设置过期时间的数据集（server.db[i].expires）中挑选最近最少使用的数据淘汰
> * volatile-lfu：从已设置过期时间的数据集(server.db[i].expires)中挑选最不经常使用的数据淘汰
> 
> 建议补充：
> 
> * least frequently used——lfu——使用频率最少的键
> * least recently used——lru——最久没有使用的键

已经修改。这种问题的话最好可以提PR，感谢支持！爱你哦！
