### ISSUE TITLE
java 重写时返回类型疑惑

### ISSUE THREAD

**Issue by Zouxxyy** [Snailclimb/JavaGuide#848]
Java基础知识 1.4.3.2.重写 中指出重写时返回值类型相同；我觉得应改为返回类型小于等于父类方法返回类型。

我注意到 issue#723 改正了这一说法，能说说原因吗？感谢！

下面是我在JDK 1.8进行的测试

```java
public class A {

    public Number fun() {
        System.out.println("A");
        return null;
    }
}

class B extends A {

    @Override
    public Integer fun() {
        System.out.println("B");
        return null;
    }

    public static void main(String[] args) {
        A a = new B();
        a.fun();
    }
}

// 输出 B
```

**Comment by wangpeipei90** [comment]
你的例子应该是正确的。
Returns type can be different only if the parent class method return type is
a supertype of child class method return type.
See [StackOverflow post:](https://stackoverflow.com/questions/14694852/can-overridden-methods-differ-in-return-type#:~:text=Before%20Java%205.0%2C%20when%20you,subclass%20of%20the%20object%20returned.)

**Comment by Rorke76753** [comment]
为什么我用跟你相同的代码测试结果不一样呢，我也是jdk8但输出的是子类的内容

**Comment by Zouxxyy** [comment]
> 为什么我用跟你相同的代码测试结果不一样呢，我也是jdk8但输出的是子类的内容
> 
> ```java
> public class ChildrenClass extends SuperClass{
>     @Override
>     public Integer test() {
>         System.out.println("int");
>         return null;
>     }
> 
>     public static void main(String[] args) {
>         SuperClass clazz = new ChildrenClass();
>         clazz.test();
>     }
> }
> 
> class SuperClass {
>     public Number test(){
>         System.out.println("number");
>         return null;
>     }
> }
> ```
> 
> 每次输出的都是int

**Comment by Zouxxyy** [comment]
> 为什么我用跟你相同的代码测试结果不一样呢，我也是jdk8但输出的是子类的内容
> 
> ```java
> public class ChildrenClass extends SuperClass{
>     @Override
>     public Integer test() {
>         System.out.println("int");
>         return null;
>     }
> 
>     public static void main(String[] args) {
>         SuperClass clazz = new ChildrenClass();
>         clazz.test();
>     }
> }
> 
> class SuperClass {
>     public Number test(){
>         System.out.println("number");
>         return null;
>     }
> }
> ```
> 
> 每次输出的都是int

是的，就是输出子类的，表示重写成功， 我当时好像忘记改了，我怎么会写aaa。。。

**Comment by Zouxxyy** [comment]
> 为什么我用跟你相同的代码测试结果不一样呢，我也是jdk8但输出的是子类的内容
> 
> ```java
> public class ChildrenClass extends SuperClass{
>     @Override
>     public Integer test() {
>         System.out.println("int");
>         return null;
>     }
> 
>     public static void main(String[] args) {
>         SuperClass clazz = new ChildrenClass();
>         clazz.test();
>     }
> }
> 
> class SuperClass {
>     public Number test(){
>         System.out.println("number");
>         return null;
>     }
> }
> ```
> 
> 每次输出的都是int

是的，就是输出子类的，表示重写成功， 我当时好像忘记改了，我怎么会写aaa。。。
