### ISSUE TITLE
synchronized和ReenTrantLock对比还可以讲下两者对于异常的处理方式

### ISSUE THREAD

**Issue by fuyuaaa** [Snailclimb/JavaGuide#849]
https://github.com/SnailClimb/JavaGuide/blob/master/docs/java/Multithread/synchronized.md#
这篇文章，synchronized和ReenTrantLock对比还可以讲下两者对于异常的处理方式。
synchronized 异常就会释放锁
ReenTrantLock 异常需要在finally里unlock

**Comment by Snailclimb** [comment]
> synchronized 异常就会释放锁
> ReenTrantLock 异常需要在finally里unlock

感谢补充！
