### ISSUE TITLE
MySQL优化建议疑似误写

### ISSUE THREAD

**Issue by RosePuff** [Snailclimb/JavaGuide#856]
2. 数据库和表的字符集统一使用 UTF8
兼容性更好，统一字符集可以避免由于字符集转换产生的乱码，**不同的字符集进行比较前需要进行转换会造成索引失效**，如果数据库中有存储 emoji 表情的需要，字符集需要采用 utf8mb4 字符集。

这里的不同字符集进行转换比较前需要进行转换**否则**会造成索引失效

**Comment by LiWenGu** [comment]
不是误写，参考这篇博文：https://blog.csdn.net/horses/article/details/107243447

**Comment by LiWenGu** [comment]
如果没什么疑问的话，你可以关闭这个 issue 了 @RosePuff

**Comment by HiAscend** [comment]
guide哥是不是比较忙啊，好多问题都一直开着

**Comment by Snailclimb** [comment]
> guide哥是不是比较忙啊，好多问题都一直开着

哈哈哈，一般是一周处理两次或者一次，多点的话处理三次。见谅。

**Comment by Snailclimb** [comment]
我把真实案例的链接也添加到上面去了。
![image](https://user-images.githubusercontent.com/29880145/88446137-26b50f00-ce5a-11ea-965a-dbcba6fb9a5b.png)
