### ISSUE TITLE
1.1.1. Java 集合概览中的继承关系图有些问题

### ISSUE THREAD

**Issue by Coldzera126** [Snailclimb/JavaGuide#861]
1. 双向队列的接口名为Deque
2. Deque接口继承Queue接口
3. 由点2，LinkedList直接实现的是Deque接口，间接实现Queue接口
4. LinkedHashSet类继承HashSet类

**Comment by Snailclimb** [comment]
> 1. 双向队列的接口名为Deque
> 2. Deque接口继承Queue接口
> 3. 由点2，LinkedList直接实现的是Deque接口，间接实现Queue接口
> 4. LinkedHashSet类继承HashSet类

已经修复！感谢指出！👍
![image](https://user-images.githubusercontent.com/29880145/109117703-4e1be380-777d-11eb-9a0a-38b7fd0bb3f7.png)
