### ISSUE TITLE
JVM垃圾回收 应该是回收未标记对象 文档内容还未修改

### ISSUE THREAD

**Issue by zqcleo** [Snailclimb/JavaGuide#863]
JVM垃圾回收 应该是回收未标记对象 
参考链接：
https://github.com/Snailclimb/JavaGuide/pull/727
https://github.com/Snailclimb/JavaGuide/issues/82

目前下面这个链接中还是下图这样，还没有修改
https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/jvm/JVM%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6.md#31-%E6%A0%87%E8%AE%B0-%E6%B8%85%E9%99%A4%E7%AE%97%E6%B3%95
![image](https://user-images.githubusercontent.com/35221698/88264847-10df0700-ccff-11ea-8432-a8115f991df3.png)

**Comment by Rorke76753** [comment]
标记的都是可达的对象，这下全把可达对象回收了xd

**Comment by Snailclimb** [comment]
> JVM垃圾回收 应该是回收未标记对象
> 参考链接：
> #727
> #82
> 
> 目前下面这个链接中还是下图这样，还没有修改
> https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/jvm/JVM%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6.md#31-%E6%A0%87%E8%AE%B0-%E6%B8%85%E9%99%A4%E7%AE%97%E6%B3%95
> ![image](https://user-images.githubusercontent.com/35221698/88264847-10df0700-ccff-11ea-8432-a8115f991df3.png)



> JVM垃圾回收 应该是回收未标记对象
> 参考链接：
> #727
> #82
> 
> 目前下面这个链接中还是下图这样，还没有修改
> https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/jvm/JVM%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6.md#31-%E6%A0%87%E8%AE%B0-%E6%B8%85%E9%99%A4%E7%AE%97%E6%B3%95
> ![image](https://user-images.githubusercontent.com/35221698/88264847-10df0700-ccff-11ea-8432-a8115f991df3.png)

查阅了一些相关资料，以及参考你给的两个issue链接，确实是标记不需要回收的对象这个说法更加准确。[refer this commit](https://github.com/Snailclimb/JavaGuide/commit/a39a40448f3dda2670c1ccf501b0cf0ad76af7d6)

**Comment by debugjoker** [comment]
@Snailclimb 实际上是两种都可以，可以看下《深入理解Java虚拟机》第三版，文中是这样说的
> 最早出现也是最基础的垃圾收集算法是“标记-清除”（Mark-Sweep）算法，在1960年由Lisp之父
John McCarthy所提出。如它的名字一样，算法分为“标记”和“清除”两个阶段：首先标记出所有需要回
收的对象，在标记完成后，统一回收掉所有被标记的对象，也可以反过来，标记存活的对象，统一回
收所有未被标记的对象。标记过程就是对象是否属于垃圾的判定过程，这在前一节讲述垃圾对象标记
判定算法时其实已经介绍过了

**Comment by dxqlovestudy** [comment]
众说纷纭，有的是说标记需要回收的，有的是标记不需要回收的。ChatGPT给出的是需要回收的，而且我还问了好几遍，还是这个答案。
