### ISSUE TITLE
ArrayList-Grow.md 文档，JDK11 移除了 ensureCapacityInternal() 和 ensureExplicitCapacity() 方法

### ISSUE THREAD

**Issue by onemsg** [Snailclimb/JavaGuide#865]
JDK11 移除了 ensureCapacityInternal () 和 ensureExplicitCapacity ()方法
应该在文档中标注一下

**Comment by Snailclimb** [comment]
> ensureCapacityInternal

👍

**Comment by apprenticedyc** [comment]
对的,今天刚看,文档里没有标注弃用,但是找不到能调用ensureCapacityInternal的地方
