### ISSUE TITLE
单例模式的静态内部类的实现里的final关键字有啥作用

### ISSUE THREAD

**Issue by wandada** [Snailclimb/JavaGuide#873]
public class Singleton {

    private Singleton(){
    }
    public static Singleton getInstance(){  
             return SingletonHolder.sInstance;  
    }  
    private static class SingletonHolder {  
           private static final Singleton sInstance = new Singleton();  //final关键字
    }  
    }
为什么需要final关键字，不加的话有什么区别？

**Comment by Snailclimb** [comment]
![image](https://user-images.githubusercontent.com/29880145/89043148-a707d280-d37a-11ea-9857-0cd177e6a482.png)
