### ISSUE TITLE
说说线程的生命周期和状态

### ISSUE THREAD

**Issue by yujmh** [Snailclimb/JavaGuide#874]
操作系统隐藏 Java 虚拟机（JVM）中的 RUNNABLE 和 RUNNING 状态，它只能看到 RUNNABLE 状态

应该改为：
操作系统隐藏 Java 虚拟机（JVM）中的 READY 和 RUNNING 状态，它只能看到 RUNNABLE 状态

原文地址：
https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/Multithread/JavaConcurrencyBasicsCommonInterviewQuestionsSummary.md#6-%E8%AF%B4%E8%AF%B4%E7%BA%BF%E7%A8%8B%E7%9A%84%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F%E5%92%8C%E7%8A%B6%E6%80%81

**Comment by Snailclimb** [comment]
> 操作系统隐藏 Java 虚拟机（JVM）中的 READY 和 RUNNING 状态

感谢👍已经改正
