### ISSUE TITLE
1.4.2. 为什么 Java 中只有值传递？ 答非所问

### ISSUE THREAD

**Issue by CarterYang0** [Snailclimb/JavaGuide#876]
建议修改答案如下
为什么java中只有值传递：
1.选择值传递的原因：为了保护实参，牺牲空间做值拷贝
2.只保留的原因：统一只用值传递，简单方便安全易懂（这个想法和取消指针不谋而和）
注：其他语言保留引用传递的原因：方便修改实参，不用拷贝实参，节约空间时间
（才疏学浅，欢迎斧正）

**Comment by Snailclimb** [comment]
> 建议修改答案如下
> 为什么java中只有值传递：
> 1.选择值传递的原因：为了保护实参，牺牲空间做值拷贝
> 2.只保留的原因：统一只用值传递，简单方便安全易懂（这个想法和取消指针不谋而和）
> 注：其他语言保留引用传递的原因：方便修改实参，不用拷贝实参，节约空间时间
> （才疏学浅，欢迎斧正）

👍你好，我觉得你分享的挺有道理的！可以简单分享一下这个说法的依据不？比如相关的参考文献。

**Comment by CarterYang0** [comment]
没有依据,突发奇想,谨慎采纳,哈哈哈哈
