### ISSUE TITLE
1.2.9. 3)为什么重写 equals 时必须重写 hashCode 方法？不是必须

### ISSUE THREAD

**Issue by CarterYang0** [Snailclimb/JavaGuide#877]
建议修改答案如下：
重写 equals 时不必重写 hashCode 方法
只有当用到hashmap，hashtable，hashset时，才要重写
此时如果不重写的话，用object默认的，是把引用进行哈希，两个实际意义相同的对象可能无法正常去重
或者把问题改为：
为什么使用到hashmap，hashtable，hashset时，重写 equals 时必须重写 hashCode 方法

**Comment by LiWenGu** [comment]
还有 ConcurrentSkipListMap、ConcurrentHashMap 等等，你可以慢慢一个一个列出来，或者说只要是实现自 Map 的类，但是没有必要解释的这么复杂。
这是规范，重写  equals 建议也重写 hashCode。既然是规范，你可以也可以不用遵守。因为 JDK 没有强制每个 Bean 都要求必须重写这两个方法。
原答案没问题在于，在实际生产项目中，你必须要这么做，因为实际项目系统涉及复杂并且有迭代，你写的 Bean 可能被别人使用。
