### ISSUE TITLE
try-with-resources 的补充

### ISSUE THREAD

**Issue by simon-sou** [Snailclimb/JavaGuide#878]
1、适用范围（资源的定义）：任何实现 java.lang.AutoCloseable或者java.io.Closeable 的对象
2、关闭资源和final的执行顺序： 在try-with-resources语句中，任何catch或finally块在声明的资源关闭后运行

**Comment by Snailclimb** [comment]
> 1、适用范围（资源的定义）：任何实现 java.lang.AutoCloseable或者java.io.Closeable 的对象
> 2、关闭资源和final的执行顺序： 在try-with-resources语句中，任何catch或finally块在声明的资源关闭后运行

已经添加！👍

**Comment by zchazc** [comment]
这段话中 `final` 是指 `finally`语句块吗？如果是的话是不是可以明确写明为 `finally` ？

**Comment by Snailclimb** [comment]
> 这段话中 `final` 是指 `finally`语句块吗？如果是的话是不是可以明确写明为 `finally` ？

是的 已经写明了。

**Comment by zchazc** [comment]
> > 这段话中 `final` 是指 `finally`语句块吗？如果是的话是不是可以明确写明为 `finally` ？
> 
> 是的 已经写明了。

先感谢下 guide 哥百忙之中的答复，我只是读到这里看名词变了，以为有什么其他含义。可能有点儿抠字眼了。:sweat:

**Comment by Snailclimb** [comment]
> > > 这段话中 `final` 是指 `finally`语句块吗？如果是的话是不是可以明确写明为 `finally` ？
> > 
> > 
> > 是的 已经写明了。
> 
> 先感谢下 guide 哥百忙之中的答复，我只是读到这里看名词变了，以为有什么其他含义。可能有点儿抠字眼了。😓

哈哈哈 挺好的啊 我已经改过来了！感谢👍

**Comment by zchazc** [comment]
> > > > 这段话中 `final` 是指 `finally`语句块吗？如果是的话是不是可以明确写明为 `finally` ？
> > > 
> > > 
> > > 是的 已经写明了。
> > 
> > 
> > 先感谢下 guide 哥百忙之中的答复，我只是读到这里看名词变了，以为有什么其他含义。可能有点儿抠字眼了。😓
> 
> 哈哈哈 挺好的啊 我已经改过来了！感谢👍

错失PR~:sob:
