### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by lichengjie19** [Snailclimb/JavaGuide#891]
非常感谢 暖心的 Guide 哥 总结的 Java 知识，并开源出来。以下是阅读过程中感觉是错别字的内容：
```
1.4.3.2. 重写
...
暖心的 Guide 哥最后再来个图标总结一下！
```
图标？图表？

**Comment by Snailclimb** [comment]
> 非常感谢 暖心的 Guide 哥 总结的 Java 知识，并开源出来。以下是阅读过程中感觉是错别字的内容：
> 
> ```
> 1.4.3.2. 重写
> ...
> 暖心的 Guide 哥最后再来个图标总结一下！
> ```
> 
> 图标？图表？

赞！已修改。
