### ISSUE TITLE
1.4.3.2. 重写 返回值类型

### ISSUE THREAD

**Issue by lichengjie19** [Snailclimb/JavaGuide#892]
在 暖心的 Guide 哥 总结的图表中，**重写方法的返回类型一定不能修改** 这个不对吧
> 以下内容摘录自《疯狂 Java 讲义》
> 方法的重写要遵循“两同两小一大”：
> - “两同”即方法名相同、形参列表相同；
> - “两小”指的是子类方法返回值类型应比父类方法返回值类型更小或相等，子类方法声明抛出的异常类应比父类方法声明抛出的异常类更小或相等；
> - “一大”指的是子类方法的访问权限应比父类方法的访问权限更大或相等。

**Comment by sruby** [comment]
这里确实存在问题，《疯狂 Java 讲义》是正确的。

**Comment by Snailclimb** [comment]
> 在 暖心的 Guide 哥 总结的图表中，**重写方法的返回类型一定不能修改** 这个不对吧
> 
> > 以下内容摘录自《疯狂 Java 讲义》
> > 方法的重写要遵循“两同两小一大”：
> > 
> > * “两同”即方法名相同、形参列表相同；
> > * “两小”指的是子类方法返回值类型应比父类方法返回值类型更小或相等，子类方法声明抛出的异常类应比父类方法声明抛出的异常类更小或相等；
> > * “一大”指的是子类方法的访问权限应比父类方法的访问权限更大或相等。

赞赞赞！学到了。已经修改。
![image](https://user-images.githubusercontent.com/29880145/90258301-eb1acd00-de7a-11ea-9351-b1d61f99f2c4.png)

**Comment by liuyaofang996** [comment]
小： 指的是子类
