### ISSUE TITLE
"使用 == 比较枚举类型"一节中一处不理解的描述

### ISSUE THREAD

**Issue by wenpeng** [Snailclimb/JavaGuide#922]
> 我们看另一个示例，两个不同枚举类型进行比较，使用equal方法比较结果确定为true，因为getStatus方法的枚举值与另一个类型枚举值一致...

"两个不同枚举类型进行比较，使用equal方法比较结果确定为true" 这个结论是如何得来？怎么理解呢？

**Comment by guorong2705** [comment]
作者复制黏贴的

**Comment by Snailclimb** [comment]
参见：https://stackoverflow.com/questions/1750435/comparing-java-enum-members-or-equals
另外：
刚有个人才评论这段话是我直接复制粘贴的，就是这位 @guorong2706 ,因为过于评论过于脑残就给删除了。
请仔细看文章。
![image](https://user-images.githubusercontent.com/29880145/95315858-a2edb900-08c5-11eb-84bf-c8f42acd7b8d.png)
