### ISSUE TITLE
1.1.5. 什么是 Java 程序的主类 应用程序和小程序的主类有何不同? 中描述有问题

### ISSUE THREAD

**Issue by Reluxer** [Snailclimb/JavaGuide#935]
![image](https://user-images.githubusercontent.com/9294566/93465994-1d0dcc00-f91e-11ea-86b9-d9047e1fabd0.png)

这里的描述感觉有问题，我觉得应该是

小程序的主类不一定要求是 public 类，但应用程序的主类要求必须是 public 类。

**Comment by Snailclimb** [comment]
由于这个问题过于脑残，我已经将其移除。
