### ISSUE TITLE
寻找创业伙伴

### ISSUE THREAD

**Issue by polkm09** [Snailclimb/JavaGuide#944]
[](https://i.loli.net/2020/09/26/vKuOwkmxhcJCnRg.png)

**Comment by cn-Panzy** [comment]
Have any requirements?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snailclimb/JavaGuide"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月26日(星期六) 晚上7:10
收件人:&nbsp;"Snailclimb/JavaGuide"<JavaGuide@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Snailclimb/JavaGuide] 寻找创业伙伴 (#944)

**Comment by 00544wei** [comment]
the same question,hava any requirements?
