### ISSUE TITLE
ScheduledExecutorService表述错误

### ISSUE THREAD

**Issue by ZacBi** [Snailclimb/JavaGuide#951]
接口只能继承接口, 怎么实现?
[Java线程池](https://snailclimb.gitee.io/javaguide/#/./docs/java/Multithread/java%E7%BA%BF%E7%A8%8B%E6%B1%A0%E5%AD%A6%E4%B9%A0%E6%80%BB%E7%BB%93?id=_2-%e4%bb%bb%e5%8a%a1%e7%9a%84%e6%89%a7%e8%a1%8cexecutor)中的表述有问题
> 而 ScheduledExecutorService 又实现了 ExecutorService，正如我们下面给出的类关系图显示的一样。

ScheduledExecutorService 和 ExecutorService同为接口
源码:
```Java
public interface ScheduledExecutorService extends ExecutorService
```

**Comment by Snailclimb** [comment]
> 接口只能继承接口, 怎么实现?
> [Java线程池](https://snailclimb.gitee.io/javaguide/#/./docs/java/Multithread/java%E7%BA%BF%E7%A8%8B%E6%B1%A0%E5%AD%A6%E4%B9%A0%E6%80%BB%E7%BB%93?id=_2-%e4%bb%bb%e5%8a%a1%e7%9a%84%e6%89%a7%e8%a1%8cexecutor)中的表述有问题
> 
> > 而 ScheduledExecutorService 又实现了 ExecutorService，正如我们下面给出的类关系图显示的一样。
> 
> ScheduledExecutorService 和 ExecutorService同为接口
> 源码:
> 
> ```java
> public interface ScheduledExecutorService extends ExecutorService
> ```

已经修正！👍
