### ISSUE TITLE
Shell脚本移除数组元素指令误解

### ISSUE THREAD

**Issue by aihw** [Snailclimb/JavaGuide#970]
![image](https://user-images.githubusercontent.com/66098065/97413503-d27c6800-193d-11eb-9a08-ec540f6a3033.png)

**Comment by Snailclimb** [comment]
感谢！已经修改：

![image](https://user-images.githubusercontent.com/29880145/97767561-d08df100-1b57-11eb-9dc2-4ee48d4d2490.png)

在 Shell 中，使用 unset 关键字来删除数组元素，具体格式如下：
```shell
unset array_name[index]
```
其中，array_name 表示数组名，index 表示数组下标。

如果不写下标，而是写成下面的形式：
```shell
unset array_name
```
