### ISSUE TITLE
ThreadLocal 表述错误

### ISSUE THREAD

**Issue by ZacBi** [Snailclimb/JavaGuide#975]
ref: [万字详解ThreadLocal关键字](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/multi-thread/%E4%B8%87%E5%AD%97%E8%AF%A6%E8%A7%A3ThreadLocal%E5%85%B3%E9%94%AE%E5%AD%97.md)

> `Thread`类有一个类型为``ThreadLocal`.`ThreadLocalMap``的实例变量`threadLocals`，也就是说每个线程有一个自己的`ThreadLocalMap`。
`ThreadLocalMap`有自己的独立实现，可以简单地将它的`key`视作`ThreadLocal`，`value`为代码中放入的值（实际上`key`并不是`ThreadLocal`本身，而是它的一个**弱引用**）。
每个线程在往`ThreadLocal`里放值的时候，都会往自己的`ThreadLocalMap`里存，读也是以`ThreadLocal`作为引用，在自己的`map`里找对应的`key`，从而实现了**线程隔离**。
`ThreadLocalMap`有点类似`HashMap`的结构，只是`HashMap`是由**数组+链表**实现的，而`ThreadLocalMap`中并没有**链表**结构。
我们还要注意`Entry`， 它的`key`是``ThreadLocal`<?> k` ，继承自`WeakReference， 也就是我们常说的弱引用类型。

[source code]:(https://github.com/zxiaofan/JDK/blob/e9bc5747d76f92fe183232800cc53d3fcd3e09f8/JDK1.8/src/java/lang/ThreadLocal.java#L298-L316)
```java
    static class ThreadLocalMap {


        /**
         * The entries in this hash map extend WeakReference, using
         * its main ref field as the key (which is always a
         * ThreadLocal object).  Note that null keys (i.e. entry.get()
         * == null) mean that the key is no longer referenced, so the
         * entry can be expunged from table.  Such entries are referred to
         * as "stale entries" in the code that follows.
         */
        static class Entry extends WeakReference<ThreadLocal<?>> {
            /** The value associated with this ThreadLocal. */
            Object value;


            Entry(ThreadLocal<?> k, Object v) {
                super(k);
                value = v;
            }
        }
```

key本身就是`ThreadLocal`对象的引用, 是一个**强引用**, `ThreadLocal`并不继承自`WeakReference`, 而是`ThreadLcoalMap.Entry`继承自`WeakReference`.下面GC关于key的内容也需要改改.

还有能把`类`和`对象`的后缀加上么, 看的有点难受.

**Comment by Snailclimb** [comment]
> ref: [万字详解ThreadLocal关键字](https://github.com/Snailclimb/JavaGuide/blob/master/docs/java/multi-thread/%E4%B8%87%E5%AD%97%E8%AF%A6%E8%A7%A3ThreadLocal%E5%85%B3%E9%94%AE%E5%AD%97.md)
> 
> > `Thread`类有一个类型为`` ThreadLocal`.`ThreadLocalMap ``的实例变量`threadLocals`，也就是说每个线程有一个自己的`ThreadLocalMap`。
> > `ThreadLocalMap`有自己的独立实现，可以简单地将它的`key`视作`ThreadLocal`，`value`为代码中放入的值（实际上`key`并不是`ThreadLocal`本身，而是它的一个**弱引用**）。
> > 每个线程在往`ThreadLocal`里放值的时候，都会往自己的`ThreadLocalMap`里存，读也是以`ThreadLocal`作为引用，在自己的`map`里找对应的`key`，从而实现了**线程隔离**。
> > `ThreadLocalMap`有点类似`HashMap`的结构，只是`HashMap`是由**数组+链表**实现的，而`ThreadLocalMap`中并没有**链表**结构。
> > 我们还要注意`Entry`， 它的`key`是``ThreadLocal`<?> k` ，继承自`WeakReference， 也就是我们常说的弱引用类型。
> 
> ```java
>     static class ThreadLocalMap {
> 
> 
>         /**
>          * The entries in this hash map extend WeakReference, using
>          * its main ref field as the key (which is always a
>          * ThreadLocal object).  Note that null keys (i.e. entry.get()
>          * == null) mean that the key is no longer referenced, so the
>          * entry can be expunged from table.  Such entries are referred to
>          * as "stale entries" in the code that follows.
>          */
>         static class Entry extends WeakReference<ThreadLocal<?>> {
>             /** The value associated with this ThreadLocal. */
>             Object value;
> 
> 
>             Entry(ThreadLocal<?> k, Object v) {
>                 super(k);
>                 value = v;
>             }
>         }
> ```
> 
> key本身就是`ThreadLocal`对象的引用, 是一个**强引用**, `ThreadLocal`并不继承自`WeakReference`, 而是`ThreadLcoalMap.Entry`继承自`WeakReference`.下面GC关于key的内容也需要改改.
> 
> 还有能把`类`和`对象`的后缀加上么, 看的有点难受.

感谢👍可以提交一下PR不？

**Comment by LiWenGu** [comment]
你可以能理解有问题，Entry是将key作为被弱引用的对象，value作为强引用，因此key是会被回收的，但是value不会被回收。如下例子：
```java
public static void main(String[] args) {
        // baseWeak();
        Car car = new Car(22000, "sliver");
        Entry entry = new Entry(car, new Object());
        int i = 0;
        
        new Thread(() -> {
            while (true) {
                System.gc();
            }
        }).start();

        while (true) {
            if (entry.get() != null) {
                i++;
                System.out.println("Object is alive for " + i + " loops - " + entry);
            } else {
                // Object is alive for 61441 loops - Entry@490d6c15
                // null,java.lang.Object@7d4793a8
                // Object has been collected.
                System.out.println(entry.get() + "," + entry.getValue());
                System.out.println("Object has been collected.");
                break;
            }
        }
    }

class Car {
    private double price;
    private String colour;

    public Car(double price, String colour) {
        this.price = price;
        this.colour = colour;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public String getColour() {
        return colour;
    }

    public void setColour(String colour) {
        this.colour = colour;
    }
}

class Entry extends WeakReference<Car> {
    /**
     * The value associated with this ThreadLocal.
     */
    Object value;

    Entry(Car k, Object v) {
        super(k);
        value = v;
    }

    public Object getValue() {
        return value;
    }
}
```
我的机器稳定在第6W次轮询就会出现null

**Comment by ZacBi** [comment]
@LiWenGu 感谢回复. 

> key本身就是ThreadLocal对象的引用, 是一个强引用,

我的意思是, 当外部方法调用`threadLocalObjRef.set()`时, 必然存在一个强引用, 这个强引用就是`key`. `key`所指向的对象是一个`ThreadLocal`对象, 进入`set()`方法内部时, 这个`ThreadLocal`对象会被增加一个弱引用. 至于你代码中的垃圾回收造返回null值, 我是有点奇怪. 这时`car`的强引用应该仍然存在于本地变量表啊?

![image](https://user-images.githubusercontent.com/22130631/98752144-867cf900-23fc-11eb-8b95-62d349882f42.png)

**Comment by LiWenGu** [comment]
@ZacBi 
>值得注意的一点 , 即使有 car 引用指向对象, 且 car 是一个strong reference, weak reference weakCar指向的对象仍然被回收了. 这是因为java的编译器在发现进入while循环之后, car 已经没有被使用了, 所以进行了优化(将其置空?)
>来源：https://blog.csdn.net/zmx729618/article/details/54093532
你最后贴的图有点不懂，"强引用仍然存在于本地变量表"这句话的意思是该对象是栈上分配吗？

**Comment by ZacBi** [comment]
@LiWenGu `强引用`-> `Strong reference`(ref: [Wikipedia](https://en.wikipedia.org/wiki/Reference_(computer_science))).  
GC 得看本地栈帧啊, 不能章口就来啊, 那篇blog也没咋说对啊. 

[GC roots](https://help.eclipse.org/2020-09/index.jsp?topic=%2Forg.eclipse.mat.ui.help%2Fconcepts%2Fgcroots.html&cp=37_2_3):
![image](https://user-images.githubusercontent.com/22130631/98789187-edba9d80-243c-11eb-9dc7-1770eebe8b4a.png)

**Comment by LiWenGu** [comment]
您这话说的就有点火箭味十足，说话确实得要依据，但是我跟你说的也是根据我的经验结论。要证明只能要搞JVM的人给你解释清楚，你可以去知乎找R大这种大牛。ps：我还没战术后仰呢，你就说我章口就来。既然你觉得我是胡诌乱造没有依据，那你可以关注下这个问题：https://stackoverflow.com/questions/64783413/why-this-object-with-strong-reference-will-be-recycled#comment114542031_64783413

按目前的阶段的讨论可能是JIT的优化越过了可达性分析的判断。

**Comment by ZacBi** [comment]
@LiWenGu 感谢您的答复, 讨论是有点冲动了, 向您道歉.

**Comment by wecgwm** [comment]
还是觉得这句话可能不太准确。这句话中的 `key` 应该指的是 `ThreadLocalMap` 中的 `key`，即 `ThreadLocal` 或者说它的哈希码。而所指的弱引用应该是被 `Entry` (继承了 `WeakReference` ) 包装的 `ThreadLocal` ，而 `Entry` 本身就只是 `ThreadLocalMap` 中的 `value` ，他们显然都不是 `ThreadLocalMap` 的 `key` 。感觉有点把 `ThreadLocalMap` 的 `key` 和 `Entry` 的 `key` 混为一谈了。
>ThreadLocalMap有自己的独立实现，可以简单地将它的key视作ThreadLocal，value为代码中放入的值（实际上key并不是ThreadLocal本身，而是它的一个弱引用）
