### ISSUE TITLE
类文件结构.md 中 2.7 方法表集合 配图有误

### ISSUE THREAD

**Issue by Greenbeen5** [Snailclimb/JavaGuide#976]
此处access_flag配图误用了上一节 2.6 字段表集合 中的配图，需要更换。

**Comment by Snailclimb** [comment]
> 此处access_flag配图误用了上一节 2.6 字段表集合 中的配图，需要更换。

老哥，很细节！👍非常感谢！

**Comment by Snailclimb** [comment]
![image](https://user-images.githubusercontent.com/29880145/97767214-c0751200-1b55-11eb-9220-fd7124fd950d.png)
![image](https://user-images.githubusercontent.com/29880145/97767221-c7038980-1b55-11eb-9634-006720e387a0.png)

**Comment by Greenbeen5** [comment]
谢谢！
