### ISSUE TITLE
1.8

### ISSUE THREAD

**Issue by weihubeats** [Snailclimb/JavaGuide#979]
![image](https://user-images.githubusercontent.com/42484192/97936128-8f931800-1db5-11eb-894e-0fcc7a29571b.png)
1.8当链表长度大于阈值（默认为8）时就会将链表转化为红黑树？为什么我看源码不是如此呢？我看源码 treeifyBin()方法还是有个条件
![image](https://user-images.githubusercontent.com/42484192/97936350-34155a00-1db6-11eb-950e-2241b0c1c8a4.png) 
这么明显的问题没人指出吗？还是说我的理解有问题？

**Comment by 397772414** [comment]
你好，你是点进去源码看的吗？？
