### ISSUE TITLE
如何设计一个高可用系统要考虑哪些地方.md （表述）

### ISSUE THREAD

**Issue by calibura** [Snailclimb/JavaGuide#980]
JavaGuide/docs/system-design/high-availability/如何设计一个高可用系统要考虑哪些地方.md

哪些情况会导致系统不可用？
...
代码中的坏``味道``导致内存泄漏或者其他问题导致程序挂掉。
...

看不太懂

**Comment by LiWenGu** [comment]
例如看如下sonar扫描的两个规则，一个是就根本没用线程如果在里面做了IO那不是得堵死？一个是可能会死锁程序挂掉：
![image](https://user-images.githubusercontent.com/15909210/98623203-2e83bb00-2346-11eb-8544-54117ba0161d.png)
![image](https://user-images.githubusercontent.com/15909210/98623305-596e0f00-2346-11eb-9f1e-030960c24f8a.png)

**Comment by calibura** [comment]
感谢解答
