### ISSUE TITLE
2.3.3. 常见关键字总结:static,final,this,super 链接404

### ISSUE THREAD

**Issue by abdyou000** [Snailclimb/JavaGuide#987]

**Comment by Snailclimb** [comment]
> _No description provided._

https://snailclimb.gitee.io/javaguide/#/docs/java/basis/Java%E5%B8%B8%E8%A7%81%E5%85%B3%E9%94%AE%E5%AD%97%E6%80%BB%E7%BB%93 

![image](https://user-images.githubusercontent.com/29880145/98818332-5ec27b00-2466-11eb-965c-803350c18e01.png)
