### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [Snailclimb/JavaGuide#988]
The README file in this repo has a bad link - [404:NotFound]

The markup version of the readme that is displayed for the main page in this repo contains the following link:

消息队列总结 (/Snailclimb/JavaGuide/blob/master/docs/system-design/data-communication/message-queue.md)

Status code [404:NotFound] - Link: https://github.com/Snailclimb/JavaGuide/blob/master/docs/system-design/data-communication/message-queue.md

(The link in the readme’s raw markdown may appear in a different format to the link above)

--

This bad link was found by a tool I very recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback.

**Comment by Snailclimb** [comment]
> 此仓库中的自述文件链接错误-[404：NotFound]
> 
> 此仓库中为主页显示的自述文件的标记版本包含以下链接：
> 
> 消息形式总结（/Snailclimb/JavaGuide/blob/master/docs/system-design/data-communication/message-queue.md）
> 
> 状态码[404：NotFound]-链接：[https](https://github.com/Snailclimb/JavaGuide/blob/master/docs/system-design/data-communication/message-queue.md) : [//github.com/Snailclimb/JavaGuide/blob/master/docs/system-design/data-communication/message-queue.md](https://github.com/Snailclimb/JavaGuide/blob/master/docs/system-design/data-communication/message-queue.md)
> 
> （自述文件的原始markdown中的链接可能以与上面的链接不同的格式显示）
> 
> -
> 
> 我最近在一个新的实验性业余项目中创建了一个工具，发现了这个错误的链接：[https](https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder) : [//github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder](https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder)
> 我（人类）验证了这一点链接已断开，并已手动记录了此问题（即，该问题尚未由漫游器创建）。
> 如果这对您有帮助，请考虑为上述Repo加上星号。
> 
> 如果您对此处提供的信息或工具本身有任何反馈，请随时分享您的想法并传递反馈。

👍
