### ISSUE TITLE
doc/database

### ISSUE THREAD

**Issue by freeman-zmy** [Snailclimb/JavaGuide#991]
database的description是不是错了，不应该是计算机网络的总结吧而是数据库的？

**Comment by Snailclimb** [comment]
> database的description是不是错了，不应该是计算机网络的总结吧而是数据库的？

你好，问题可以描述的具体一点不？

**Comment by freeman-zmy** [comment]
![图片](https://user-images.githubusercontent.com/59650407/99739389-9df86800-2b07-11eb-81e2-6a38067c8672.png)

**Comment by freeman-zmy** [comment]
> 
> 
> > database的description是不是错了，不应该是计算机网络的总结吧而是数据库的？
> 
> 你好，问题可以描述的具体一点不？

https://github.com/Snailclimb/JavaGuide/issues/991#issuecomment-730372621

**Comment by Snailclimb** [comment]
> > > database的description是不是错了，不应该是计算机网络的总结吧而是数据库的？
> > 
> > 
> > 你好，问题可以描述的具体一点不？
> 
> [#991 (comment)](https://github.com/Snailclimb/JavaGuide/issues/991#issuecomment-730372621)

这个不是描述，这个只是提交记录。
