### ISSUE TITLE
关于Mybatis中 Mapper接口中方法重载

### ISSUE THREAD

**Issue by mengxiangcxy** [Snailclimb/JavaGuide#995]
Mapper中方法是可以重载的。 重载后的方法在MapperProxy中是两个，只是用全限定名+方法名定位到同一个MappedStatement。

**Comment by Snailclimb** [comment]
> Mapper中方法是可以重载的。 重载后的方法在MapperProxy中是两个，只是用全限定名+方法名定位到同一个MappedStatement。

你好 可以提交一个PR么？
